### ISSUE TITLE
ValueError: [WriteGear:ERROR] :: All frames must have same size! -- what is the root cause?

### ISSUE THREAD

**Issue by michaelhku2002** [abhiTronix/vidgear#102]
Dear all,

I am now trying to use VideoGear for capturing live video from webcam plugged in a raspberry pi, and then streaming it to the Ubuntu server for storage. However, when I tried to save the streaming video to the file and then store in server, it always shows
`Traceback (most recent call last):
  File "webstreaming_server_storage.py", line 31, in <module>
    writer.write(jpeg)
  File "/usr/local/lib/python3.6/dist-packages/vidgear/gears/writegear.py", line 213, in write
    raise ValueError('[WriteGear:ERROR] :: All frames must have same size!')
ValueError: [WriteGear:ERROR] :: All frames must have same size!
`

The followings are my client and server scripts respectively:
client.py
`import time
import socket
import cv2
import logging
from vidgear.gears import VideoGear, NetGear

options_cam={"CAP_PROP_FRAME_WIDTH":640,"CAP_PROP_FRAME_HEIGHT":480,"CAP_PROP_FPS":30}
options_client={'compression_format':'.jpg','compression_param':[cv2.IMWRITE_JPEG_QUALITY,80],'flag':0,'copy':False,'track':False}
stream=VideoGear(enablePiCamera=False,logging=False,**options_cam).start()
client=NetGear(address=[IP_ADDRESS], port='20001', protocol='tcp', pattern=2, receive_mode=False, logging=False, **options_client)
keep_running=True
try:
        while keep_running:
                try:
                        frame= stream.read()
                        client.send(frame)
                        print("frame sent")
                except KeyboardInterrupt:
                        keep_running=False
                        cv2.destroyAllWindows()
                        break
        stream.stop()
        client.close()

except Exception as e:
        print("Error: {}".format(e))
        logging.exception('Caught of error')
`

server.py
`from flask import Response
from flask import Flask
from flask import render_template
from vidgear.gears import WriteGear,NetGear
import threading
import argparse
import datetime
import cv2
import zmq
import numpy as np
import traceback
import keyboard

options_server={'compression_param':cv2.IMREAD_UNCHANGED,'flag':0,'copy':False,'track':False}
server = NetGear(address='206.189.144.234', port='20001', protocol='tcp', pattern=2, receive_mode=True, logging=False, **options_server)
options_writer = {"-output_dimensions": (640,480),"-vcodec":"libx264", "-crf": 0, "-preset": "fast", "tune": "zerolatency"}
writer=WriteGear(output_filename='Output.mp4',logging=True,**options_writer)

frame = None
try:
        while True:
                image = server.recv()
                ret, jpeg = cv2.imencode('.jpg', image)
                if ret==True:
                        writer.write(jpeg)
                        if keyboard.is_pressed('q'):
                                break
                else:
                        break

        cv2.destroyAllWindows()

        stream.stop()
        writer.close()
        server.close()

except Exception as e:
        print("Server error: {}".format(traceback.format_exc()))`

The config of the server is as follows:
Ubuntu 18.04
python 3.6.9
FFmpeg 3.4.6
opencv-contrib-python 4.1.2.30

Thanks!

**Comment by abhiTronix** [comment]
@michaelhku2002 `ret, jpeg = cv2.imencode('.jpg', image)` no need for converting frame to jpeg, just give raw frame to WriteGear writer.

**Comment by michaelhku2002** [comment]
Hi Abhishek,
Thanks for your reply. But when I just modified the row "ret, jpeg = cv2.imencode('.jpg', image)" i.e.
image = server.recv()ret, jpeg = cv2.imencode('.jpg', image)if ret==True:       writer.write(jpeg)
to
frame=server.recv()writer.write(frame)
It shows
Input #0, rawvideo, from 'pipe:':  Duration: N/A, start: 0.000000, bitrate: 184320 kb/s    Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 640x480, 184320 kb/s, 25 tbr, 25 tbn, 25 tbc[NULL @ 0x55f054554160] Unable to find a suitable output format for 'tune'tune: Invalid argumentWriteGear :: ERROR :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!Server error: Traceback (most recent call last):  File "/usr/local/lib/python3.6/dist-packages/vidgear/gears/writegear.py", line 230, in write    self.__process.stdin.write(frame.tostring())BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  File "webstreaming_server_storage.py", line 39, in <module>    writer.write(frame)  File "/usr/local/lib/python3.6/dist-packages/vidgear/gears/writegear.py", line 235, in write    raise ValueError #for testing purpose onlyValueError
What is the root cause then? Thanks again!
Cheers,Michael
    Abhishek Thakur (<notifications@github.com>) 在 2020年1月27日星期一 下午07:37:18 [GMT+8] 寫道：  
 
 
@michaelhku2002 ret, jpeg = cv2.imencode('.jpg', image) no need for converting frame to jpeg, just give raw frame to WriteGear writer.

**Comment by abhiTronix** [comment]
> options_writer = {"-output_dimensions": (640,480),"-vcodec":"libx264", "-crf": 0, "-preset": "fast", "tune": "zerolatency"}

@michaelhku2002 This is wrong as there's no `"tune"` option, kindly change it to `"-tune"` as follows:

```python
options_writer = {"-output_dimensions": (640,480),"-vcodec":"libx264", "-crf": 0, "-preset": "fast", "-tune": "zerolatency"}
```
Also kindly comprehend [WriteGear: Compression Mode](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#compression-mode-built-upon-ffmpeg) Wiki before using it using it your own code.
