### ISSUE TITLE
HLS and HSS video streaming support in StreamGear

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#106]
### [HTTP Smooth Streaming (HSS)](https://www.microsoft.com/silverlight/smoothstreaming)

HTTP Smooth Streaming is Microsoft’s foray into adaptive HTTP streaming that runs on their IIS web server and Silverlight player. The Silverlight player detects local bandwidth and CPU conditions and dynamically switches bitrates to offer uninterrupted streaming. HSS supports multiple audio and video codecs, and is highly customizable. It is often used for very large-scale streams, such as NBC’s online stream of the Olympic Games, and is part of Netflix’s streaming stack.

### [HTTP Live Streaming (HLS)](https://developer.apple.com/streaming/)
It is an HTTP-based adaptive bitrate streaming communications protocol developed by Apple Inc. and released in 2009. Support for the protocol is widespread in media players, web browsers, mobile devices, and streaming media servers.

HLS resembles MPEG-DASH in that it works by breaking the overall stream into a sequence of small HTTP-based file downloads, each download loading one short chunk of an overall potentially unbounded transport stream. A list of available streams, encoded at different bit rates, is sent to the client using an extended M3U playlist.

Based on standard HTTP transactions, HTTP Live Streaming can traverse any firewall or proxy server that lets through standard HTTP traffic, unlike UDP-based protocols such as RTP. This also allows content to be offered from conventional HTTP servers and delivered over widely available HTTP-based content delivery networks.

### Context

Our goal through this proposal is to implement HLS and HSS streaming server within vidgear's [StreamGear](https://abhitronix.github.io/vidgear/gears/streamgear/overview/) streaming API.

### Your Environment

* VidGear version: 0.2.2-dev
* Branch:  Development
* Python version: 3.6+
* pip version: all
* Operating System and version: all

### Any Other Important Information

https://ffmpeg.org/ffmpeg-formats.html#smoothstreaming
https://ffmpeg.org/ffmpeg-formats.html#hls-1
https://ffmpeg.org/ffmpeg-formats.html#hls-2

**Comment by Odianosen25** [comment]
Hello @abhiTronix,

I just came across this framework, and thanks for this great framework you have developed. This feature is actually the exact reason I having been searching the internet for the good part of a month to find (I know, me not finding it shows how poor I am at searching 😆).

Anyway if I understand what you wrote here, this should be in dev? My use case is as follows:

I have my code capturing video from my cameras and processing them using opencv. The post frames I then want to stream using HLS. I was reading abt it, and found out I could use FFMPEG to create segments, which I can then transmit. Then the issue I had was how to write my frames to ffmpeg without first writing to disk and how I came across your framework.

I can still use vidgear to like create segments from frames right? Also with this feature you want to add, does it mean vidgear will be able to take in the frame and just do the streaming over HLS or HSS itself? Even without much input from the developer? 

Thanks and regards

**Comment by abhiTronix** [comment]
@Odianosen25 Thanks for your kind words, but this feature is not in priority list right now and thereby I haven't started worked on it due to busy schedule. For now, It is opened for community to contribute with PR.

> Also with this feature you want to add, does it mean vidgear will be able to take in the frame and just do the streaming over HLS or HSS itself? Even without much input from the developer?

Yup, exactly. Just like rest of Gears within vidgear. You just has feed live frames, rest will be done automatically at its multi-threaded backend. And thats what make vidgear different, it is simple, fast and flexible.

**Comment by Odianosen25** [comment]
@abhiTronix Oh thanks for responding, and quite quickly. 

>Yup, exactly. Just like rest of Gears within vidgear. 

Oh that's cool. Sad its not being developed now anyway, but in the mean time will use the WriteGear() to see if I can use it to create the segments, and try setting up the HLS server.

if there is any pointers you can give me to develop it, will be very nice. Kudos with the development anyway, its really one of the best video framework I have come across; actually haven't come across a lot, as I am not a developer ;)

Regards

**Comment by golyalpha** [comment]
So, what's the plan? Implement a new web server for HLS/HSS video streaming (maybe even adding DASH into the mix?), or extend the existing web server to allow for streaming those formats alongside MJPEG?

Implementing a pipeline using VidGear APIs for transcoding arbitrary A/V source (or transmuxing for applicable source formats) into HLS/HSS/DASH streams shouldn't be too hard, so the only real question is how we want to get there.

**Comment by golyalpha** [comment]
I personally am up to the task, since I am already working on a streaming pipeline where I'm using VidGear for the multi-res transcode part of the pipeline, though I'm using Nginx for both the ingest (RTMP) and TV (HLS/DASH) parts of the stream pipeline, but having this all integrated into VidGear, with VidGear potentially also working as the ingest server, would actually simplify the architecture of the system immensely.

**Comment by golyalpha** [comment]
It also might be worth, since transcoding certain formats will be required for any Dynamic HTTP streaming format, including a benchmark suite that would run encode+scale benchmarks, to see what resolutions and framerates can a given computer comfortably transcode in real time.

**Comment by abhiTronix** [comment]
@golyalpha Apologizes for the delay, I'm really busy with a job project. 

> So, what's the plan? Implement a new web server for HLS/HSS video streaming (maybe even adding DASH into the mix?), or extend the existing web server to allow for streaming those formats alongside MJPEG?
Implementing a pipeline using VidGear APIs for transcoding arbitrary A/V source (or transmuxing for applicable source formats) into HLS/HSS/DASH streams shouldn't be too hard, so the only real question is how we want to get there.

**I'm in favor of implementing a new webserver for HLS/HSS video streaming. Since WriteGear _(that utilizes FFmpeg for its core)_  is already overcrowded and also reserved as writing tool. I'm thinking of a new Network API that utilizes on WriteGear's robust mechanism to detect FFmpeg executables automatically to implement a independent webserver for video streaming.**

> I personally am up to the task, since I am already working on a streaming pipeline where I'm using VidGear for the multi-res transcode part of the pipeline, though I'm using Nginx for both the ingest (RTMP) and TV (HLS/DASH) parts of the stream pipeline, but having this all integrated into VidGear, with VidGear potentially also working as the ingest server, would actually simplify the architecture of the system immensely.

That would be great. And yes, This will be the next biggest feature for VidGear, but unfortunately, I'm not getting enough time to start working on it. **If you could [help us on this feature with a Pull Request](https://abhitronix.github.io/vidgear/contribution/PR/), that would be awesome. Also, I can guide you along the way and we can implement this feature for VidGear even faster.**

> It also might be worth, since transcoding certain formats will be required for any Dynamic HTTP streaming format, including a benchmark suite that would run encode+scale benchmarks, to see what resolutions and framerates can a given computer comfortably transcode in real time.

**That will be awesome. Please if let me know if you need my help anywhere in implementing these new features, and I'm really looking forward to it. Thanks.**

**Comment by abhiTronix** [comment]
**APPLE HLS support successfully implemented and merged in commit  https://github.com/abhiTronix/vidgear/commit/11f7dadc67874bf38808853b0c69821eddb2fd64**

**Comment by golyalpha** [comment]
Hey @abhiTronix, great work on the HLS/DASH support. The StreamGear docs seem to imply that StreamGear will create a multires output, and generate a master playlist not just for the individual resolutions, but for the entire multires stream. Is that correct?

**Comment by abhiTronix** [comment]
> The StreamGear docs seem to imply that StreamGear will create a multires output, and generate a master playlist not just for the individual resolutions, but for the entire multires stream. Is that correct?

@golyalpha Multiple-bitrates of all indivisual streams defined within a master playlist.

**Comment by golyalpha** [comment]
I just found the configuration documentation for that in the docs, however, this concerns me:
```
If you define both -video_bitrate and -framerate values at the same time, StreamGear will discard the -framerate value automatically.
```

This is not a great idea - if I'm defining both b:v and r, it should be assumed I "know what I'm doing" and want both to be respected. In other words, I feel like VidGear should defer to ffmpeg on this front.

**Comment by abhiTronix** [comment]
> I just found the configuration documentation for that in the docs, however, this concerns me:
> 
> ```
> If you define both -video_bitrate and -framerate values at the same time, StreamGear will discard the -framerate value automatically.
> ```
> 
> This is not a great idea - if I'm defining both b:v and r, it should be assumed I "know what I'm doing" and want both to be respected. In other words, I feel like VidGear should defer to ffmpeg on this front.

@golyalpha Yeah, but only if you read above it:
```
You only need either of -video_bitrate or -framerate for defining a valid stream. Since with -framerate value defined, video-bitrate is calculated automatically using -bpps and -resolution values.
```

**Comment by golyalpha** [comment]
I know. However, manually specifying both should override that logic.

**Comment by abhiTronix** [comment]
> It also seems that bpp is not documented in ffmpeg - is that something that VidGear itself calculates?

@golyalpha It's Bits-Per-Pixel(BPP) and you should know how video framerate, BPP and bitrate are correlated.

**Comment by golyalpha** [comment]
> > It also seems that bpp is not documented in ffmpeg - is that something that VidGear itself calculates?
> 
> @golyalpha It's Bits-Per-Pixel(BPP) and you should know how video framerate, BPP and bitrate are correlated.

Well, that's the thing, bpp usually refers to color depth of the "raw" image data, and doesn't directly relate to the bitrate of an encoded file.

Quite frankly, having bitrate be a function of frame size and rate is not a good idea in general. The necessary bitrate changes not just according to those two values, but also based on the inter- and intra-frame content of the video stream in question. A 1080p60 video stream of an aquarium with a fish will need less bits to provide the same level of quality, than a 1080p60 video stream of high-motion action movie fight with cuts all over the place.

**Comment by abhiTronix** [comment]
> This logic is essentially forcing someone, who wants to control over both framerate and bitrate, to do a reverse calculation just so they can set that specific bitrate, instead of just being able to specify said bitrate directly.

@golyalpha That's utter nonsense. You can't directly specify output framerate for individual stream. If you can then, encode one yourself.

**Comment by abhiTronix** [comment]
> Quite frankly, having bitrate be a function of frame size and rate is not a good idea in general. The necessary bitrate changes not just according to those two values, but also based on the inter- and intra-frame content of the video stream in question. A 1080p60 video stream of an aquarium with a fish will need less bits to provide the same level of quality, than a 1080p60 video stream of high-motion action movie fight with cuts all over the place.

I've done both 1080p60fps and 1080p30fps and they did just fine, you can try yourself. I don't see the point, it like creating issue out of nothing less.

**Comment by golyalpha** [comment]
Since you seem adamant, that I know nothing about video encoding, here's some actual encoding work.

Here's the source image sequence (250 1920x1080 PNG frames) I used for this:  https://www.filehosting.org/file/details/959380/render.zip

Here's ffmpeg encoding that image sequence into a single 1080p60 file (treating the image sequence as 60FPS)
```
$ ffmpeg -hide_banner -r 60 -i %04d.png -c:v h264 -b:v 10M -r 60 1080p60-from-seq.mp4
Input #0, image2, from '%04d.png':
  Duration: 00:00:10.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc), 1920x1080 [SAR 2835:2835 DAR 16:9], 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x560b7c3a9dc0] using SAR=1/1
[libx264 @ 0x560b7c3a9dc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x560b7c3a9dc0] profile High 4:4:4 Predictive, level 4.2, 4:4:4, 8-bit
[libx264 @ 0x560b7c3a9dc0] 264 - core 161 r3049 55d517b - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=10000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '1080p60-from-seq.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv444p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 10000 kb/s, 60 fps, 15360 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/10000000 buffer size: 0 vbv_delay: N/A
frame=  251 fps= 44 q=-1.0 Lsize=    4683kB time=00:00:04.13 bitrate=9282.0kbits/s dup=1 drop=0 speed=0.717x    
video:4680kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.082098%
[libx264 @ 0x560b7c3a9dc0] frame I:2     Avg QP: 5.25  size:211491
[libx264 @ 0x560b7c3a9dc0] frame P:63    Avg QP: 2.90  size: 38593
[libx264 @ 0x560b7c3a9dc0] frame B:186   Avg QP: 7.66  size: 10413
[libx264 @ 0x560b7c3a9dc0] consecutive B-frames:  0.8%  0.0%  3.6% 95.6%
[libx264 @ 0x560b7c3a9dc0] mb I  I16..4: 37.3% 51.7% 11.0%
[libx264 @ 0x560b7c3a9dc0] mb P  I16..4:  2.3%  3.9%  0.6%  P16..4:  8.3%  1.8%  2.2%  0.0%  0.0%    skip:80.9%
[libx264 @ 0x560b7c3a9dc0] mb B  I16..4:  0.3%  0.5%  0.0%  B16..8:  7.1%  2.0%  0.8%  direct: 1.3%  skip:88.0%  L0:40.0% L1:46.9% BI:13.0%
[libx264 @ 0x560b7c3a9dc0] final ratefactor: 4.27
[libx264 @ 0x560b7c3a9dc0] 8x8 transform intra:56.7% inter:39.2%
[libx264 @ 0x560b7c3a9dc0] coded y,u,v intra: 83.2% 0.0% 0.0% inter: 5.2% 0.0% 0.0%
[libx264 @ 0x560b7c3a9dc0] i16 v,h,dc,p: 28%  8% 34% 30%
[libx264 @ 0x560b7c3a9dc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu:  9%  9% 72%  2%  2%  1%  2%  1%  2%
[libx264 @ 0x560b7c3a9dc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 16% 50%  4%  3%  2%  3%  2%  2%
[libx264 @ 0x560b7c3a9dc0] Weighted P-Frames: Y:6.3% UV:0.0%
[libx264 @ 0x560b7c3a9dc0] ref P L0: 81.4%  1.6% 12.8%  3.8%  0.3%
[libx264 @ 0x560b7c3a9dc0] ref B L0: 89.0%  9.5%  1.5%
[libx264 @ 0x560b7c3a9dc0] ref B L1: 96.0%  4.0%
[libx264 @ 0x560b7c3a9dc0] kb/s:9162.37
```
As you can see, I have *explicitly* set both the bitrate (-b:v) and the output framerate (-r). 
Now, you may say "but your input stream is 60 FPS!", and you would be right. It is, if I omited the output framerate, the output would be exactly the same. 
So, now, we shall take this mp4 video file, and transcode it into a 5Mbps 30FPS file:
```
$ ffmpeg -hide_banner -i 1080p60-from-seq.mp4 -c:v h264 -b:v 5M -r 30 1080p30-from-60.mp4  
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1080p60-from-seq.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:04.18, start: 0.000000, bitrate: 9169 kb/s
  Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1920x1080 [SAR 1:1 DAR 16:9], 9163 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x560d4bed9e80] using SAR=1/1
[libx264 @ 0x560d4bed9e80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x560d4bed9e80] profile High 4:4:4 Predictive, level 4.0, 4:4:4, 8-bit
[libx264 @ 0x560d4bed9e80] 264 - core 161 r3049 55d517b - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=5000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '1080p30-from-60.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv444p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 5000 kb/s, 30 fps, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/5000000 buffer size: 0 vbv_delay: N/A
frame=  127 fps= 41 q=-1.0 Lsize=    2025kB time=00:00:04.13 bitrate=4013.1kbits/s dup=0 drop=124 speed=1.32x    
video:2023kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.116366%
[libx264 @ 0x560d4bed9e80] frame I:1     Avg QP: 9.17  size: 15216
[libx264 @ 0x560d4bed9e80] frame P:33    Avg QP: 4.47  size: 38280
[libx264 @ 0x560d4bed9e80] frame B:93    Avg QP:10.34  size:  8515
[libx264 @ 0x560d4bed9e80] consecutive B-frames:  1.6%  1.6%  2.4% 94.5%
[libx264 @ 0x560d4bed9e80] mb I  I16..4: 49.3% 47.4%  3.3%
[libx264 @ 0x560d4bed9e80] mb P  I16..4:  2.7%  6.1%  0.9%  P16..4:  9.8%  1.8%  2.0%  0.0%  0.0%    skip:76.6%
[libx264 @ 0x560d4bed9e80] mb B  I16..4:  0.5%  0.7%  0.1%  B16..8:  8.6%  1.9%  0.6%  direct: 1.0%  skip:86.7%  L0:41.1% L1:48.8% BI:10.1%
[libx264 @ 0x560d4bed9e80] final ratefactor: 8.63
[libx264 @ 0x560d4bed9e80] 8x8 transform intra:58.2% inter:51.3%
[libx264 @ 0x560d4bed9e80] coded y,u,v intra: 70.2% 0.0% 0.0% inter: 4.5% 0.0% 0.0%
[libx264 @ 0x560d4bed9e80] i16 v,h,dc,p: 36%  9% 33% 22%
[libx264 @ 0x560d4bed9e80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12%  9% 72%  2%  1%  1%  1%  1%  2%
[libx264 @ 0x560d4bed9e80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 21% 40%  4%  3%  2%  3%  2%  3%
[libx264 @ 0x560d4bed9e80] Weighted P-Frames: Y:3.0% UV:0.0%
[libx264 @ 0x560d4bed9e80] ref P L0: 80.6%  2.2% 12.5%  4.6%  0.1%
[libx264 @ 0x560d4bed9e80] ref B L0: 90.2%  8.4%  1.4%
[libx264 @ 0x560d4bed9e80] ref B L1: 96.0%  4.0%
[libx264 @ 0x560d4bed9e80] kb/s:3912.47
```
As you can see from the console output, the input file is a 1080p60 file, with a bitrate of 9163 kb/s slight difference, but that's okay. But look at the output, it's a 1080p file at... 30 FPS, with a bitrate of... 5Mbps. Well, would you look at that, ffmpeg did in fact let me specify both the framerate and the bitrate of a video file.

Now, just like with the first file, where the bitrate was slightly below 10Mbps, even with this file, the bitrate will differ. Here's the output of ffprobe on that file:
```
$ ffprobe -hide_banner 1080p30-from-60.mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1080p30-from-60.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:04.23, start: 0.000000, bitrate: 3917 kb/s
  Stream #0:0(und): Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p, 1920x1080 [SAR 1:1 DAR 16:9], 3913 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```
As we can see, the bitrate is actually 3913 kb/s, just like with the 60FPS 10Mbps file, a slight difference, and that's okay.

In case you're curious about what the files actually look like, here they are: https://www.filehosting.org/file/details/959382/encode.zip

So, here's your quote:
> @golyalpha That's utter nonsense. You can't even directly specify output framerate for individual stream. If you can then, encode one yourself.

I call BS on that.

Now, time to turn to that fabled bpp of yours.

Here's a quote from Wikipedia's introductory parahraph on Color depth (emphasis my own):
> Color depth or colour depth (see spelling differences), also known as bit depth, is either the number of bits used to indicate the color of a single pixel, in a bitmapped image or video framebuffer, or the number of bits used for each color component of a single pixel. For consumer video standards, the bit depth specifies the number of bits used for each color component. When referring to a pixel, **the concept can be defined as bits per pixel (bpp)**. When referring to a color component, the concept can be defined as bits per component, bits per channel, bits per color (all three abbreviated bpc), and also bits per pixel component, bits per color channel or bits per sample (bps).

So, let *me* quote *you* back on that:
> Frankly speaking you have no idea about it. FYI.

Even so, I admit that having bps as a rudimentary form of bitrate control for video is an interesting concept, though from the point of view of video streaming over network, it would actually be more useful to have bps, along with a target framerate & bitrate, calculate the appropriate resolution. Either way, let's see what ffmpeg does with it:
```
$ ffmpeg -hide_banner -i 1080p60-from-seq.mp4 -c:v h264 -bpp 0.1 -r 30 1080p30-from-60.mp4
Unrecognized option 'bpp'.
Error splitting the argument list: Option not found
```
WHOOPS!
Well, not all hope is lost, vidgear docs occasionally mention -bpps instead of -bpp, let's try that:
```
$ ffmpeg -hide_banner -i 1080p60-from-seq.mp4 -c:v h264 -bpps 0.1 -r 30 1080p30-from-60.mp4
Unrecognized option 'bpps'.
Error splitting the argument list: Option not found
```
No bueno. 
I'mma go ahead and quote you again:
> Frankly speaking you have no idea about it. FYI.
