### ISSUE TITLE
Screen recording and stream to server

### ISSUE THREAD

**Issue by SaddamBInSyed** [abhiTronix/vidgear#108]
Thank you for work.

I want to capture a desktop screen ( e.g) from 10 pc) and post to the server pc and after annotation of the received images then the server will push images again to the same client pc.

is it possible with this vidgear library?

**Comment by abhiTronix** [comment]
@SaddamBInSyed, yup absolutely possible. 

> I want to capture a desktop screen ( e.g) from 10 pc)

See [Screengear API](https://github.com/abhiTronix/vidgear/wiki/screengear) 

> post to the server pc and after annotation of the received images then the server will push images again to the same client pc.

See [NetGear API](https://github.com/abhiTronix/vidgear/wiki/netgear) and its [Bidirectional Mode](https://github.com/abhiTronix/vidgear/wiki/Bidirectional-Mode:-Bidirectional-Data-Transfer-in-NetGear-API)
