### ISSUE TITLE
Fix simple typo: accidently -> accidentally

### ISSUE THREAD

**Issue by timgates42** [abhiTronix/vidgear#109]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine README.md.
2. Search for `accidently`.

# Expected Behaviour

1. Should read `accidentally`.

**Comment by abhiTronix** [comment]
@timgates42 Kindly make changes as requested in the PR. Also make sure to read our [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/testing/contributing.md#how-to-contribute-with-pull-request-pr) before making any contribution.

**Comment by abhiTronix** [comment]
**Fixed in commit https://github.com/abhiTronix/vidgear/commit/33d0a1abe9f70733fdbf16ce50b5fe13168283a2**
