### ISSUE TITLE
Sample code of sending Opencv Frame via WebGear, please?

### ISSUE THREAD

**Issue by cesarandreslopez** [abhiTronix/vidgear#111]
## Question

The amount of effort and quality code you've put into this project is quite impressive, thank you for your hard work!

I've taken a look into WebGear and am wondering if you can provide sample code of how it would be possible to use Opencv Frames as WebGear source (as opposed to a file or rtsp stream).

Thank you!

### Acknowledgment

- [x] A brief but descriptive Title of your issue.
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [ ] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [ ] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Your Environment

* VidGear version:
* Branch: 
* Python version:
* pip version:
* Operating System and version:

**Comment by abhiTronix** [comment]
@cesarandreslopez 

> how it would be possible to use Opencv Frames as WebGear source (as opposed to a file or rtsp stream).

There's no direct way of doing this yet but it's not difficult. Here's the trick to do it:

**Step-1:** First run any WebGear example to trigger the [auto-generation process](https://github.com/abhiTronix/vidgear/wiki/WebGear#auto-generation-process). The default generated will be saved at `$HOME/.vidgear` directory of your machine.

**Step-2: Build your own Frame Producer Route:** create script code which must look something like this:
```python
#import necessary libs
import uvicorn, asyncio, cv2
from starlette.routing import Route
from vidgear.gears import WebGear
from vidgear.gears.helper import reducer
from starlette.responses import StreamingResponse

#initialize WebGear app with a valid source you want to use
web = WebGear(source = "/home/abhishek/stmarc_video.avi", logging = True) #also enable `logging` for debugging 

#create your own frame producer
async def my_frame_producer():
	# loop over frames
	while True:
		#read frame from
		frame = web.stream.read()
		#break if NoneType
		if frame is None: break


		#do something with frame here


		#reducer frames size if you want more performance otherwise comment this line
		frame = reducer(frame, percentage = 50) #reduce frame by 50%
		#handle JPEG encoding
		encodedImage = cv2.imencode('.jpg', frame)[1].tobytes()
		#yield frame in byte format
		yield  (b'--frame\r\nContent-Type:image/jpeg\r\n\r\n'+encodedImage+b'\r\n')
		await asyncio.sleep(0.01)


#now create your own streaming response server
async def video_server(scope):
	assert scope['type'] == 'http'
	return StreamingResponse(my_frame_producer(), media_type='multipart/x-mixed-replace; boundary=frame') #add your frame producer



#append new route to point your own streaming response server created above
web.routes.append(Route('/my_frames', endpoint=video_server)) #new route for your frames producer will be `{address}/my_frames`

#run this app on Uvicorn server at address http://0.0.0.0:8000/
uvicorn.run(web(), host='0.0.0.0', port=8000)

#close app safely
web.shutdown()
```

**Step-3: Change Webpage address in your own HTML file:** Go to `$HOME/.vidgear/templates` directory of your machine and **change the line - `25` on `index.html` file**:

**From:**
`<p class="lead"><img src="/video" class="img-fluid" alt="Feed"></p>`
**To:**
`<p class="lead"><img src="/my_frames" class="img-fluid" alt="Feed"></p>`


**Final Step:** Run the above script and see output at address http://0.0.0.0:8000/ on your browser. 

It's a dirty fix but will do the job intended :smiley:

**Comment by mosesmmoisebidth** [comment]
hey @abhiTronix    is there anyway that i can use WebGear with react
