### ISSUE TITLE
Colorspace conversion even if no colorspace was defined

### ISSUE THREAD

**Issue by witling** [abhiTronix/vidgear#113]
## Description

There is a logic bug in the `PiGear` color conversion, that makes vidgear try to perform said operation even though no colorspace was defined.

``` python
gear = PiGear((800, 600), framerate=24)
```

vidgear throws an exception because opencv's `cvtColor` does not accept `None` as colorspace.

### Acknowledgment

- [X] A brief but descriptive Title of your issue
- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [X] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).
- [X] I have read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md).

There is an [issue](https://github.com/abhiTronix/vidgear/issues/78) that seems to have tackled the same problem, yet I wonder why this change has not reached master.

### Environment

* VidGear version: 0.1.6
* Branch: PyPi
* Python version: 3.5.2
* pip version: 9.0.1-2+rpt2
* Operating System and version: Raspbian for Robots 9.11

### Expected Behavior
No conversion of colorspace happens.

### Actual Behavior
```
PiGear :: WARNING :: Input camera_num value `{}` is invalid, Defaulting to index 0!
PiGear :: ERROR :: an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/vidgear/gears/pigear.py", line 147, in __init__
    if not(self.frame is None and self.color_space is None): self.frame = cv2.cvtColor(self.frame, self.color_space)
TypeError: an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/vidgear/gears/pigear.py", line 147, in __init__
    if not(self.frame is None and self.color_space is None): self.frame = cv2.cvtColor(self.frame, self.color_space)
TypeError: an integer is required (got type NoneType)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/witling/dev/botlib/botlib/bot.py", line 58, in camera
    self._camera = Camera(self)
  File "/home/witling/dev/botlib/botlib/camera.py", line 12, in __init__
    self._stream = PiGear(self._resolution, framerate=self._framerate)
  File "/usr/local/lib/python3.5/dist-packages/vidgear/gears/pigear.py", line 150, in __init__
    raise RuntimeError('[PiGear:ERROR] :: Camera Module failed to initialize!')
RuntimeError: [PiGear:ERROR] :: Camera Module failed to initialize!
```

### Possible Fix
The colorspace conversion **can** only happen if `frame` and `colorspace` are defined so,
I believe that this line https://github.com/abhiTronix/vidgear/blob/8357aa5d6df59df45bd21a7c23c0950c6b152f59/vidgear/gears/pigear.py#L147 should rather be
``` python
if not (self.frame is None or self.color_space is None): ...
```

This way, the conversion will only happen if `self.frame` and `self.color_space` are not `None`. (See [DeMorgan's law](https://en.wikipedia.org/wiki/Negation#Distributivity))

**Comment by abhiTronix** [comment]
**@witling Thanks for finding this bug, much appreciated.** I wonder how a small logic error snicked passed without making any error for so long. 

**Bug:** The current logic: `if not(self.frame is None and self.color_space is None)` is completely incorrect in this context. 

Please wait, I'm pushing related PR in the `development` branch shortly.

**Comment by abhiTronix** [comment]
**@witling Kindly install development branch as follows:**

```sh
git clone git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout development
sudo pip install .
cd
```

**Then check if the problem is gone?** 


> if not (self.frame is None or self.color_space is None): ...

Yes, a simple OR will also be correct.

**Comment by abhiTronix** [comment]
**@witling Closed and marked solved for now. Kindly share your results when you're ready. Good luck!**

**Comment by witling** [comment]
The code works now. Thanks for your effort!

**Comment by fahrettine** [comment]
> **@witling Kindly install development branch as follows:**
> 
> ```shell
> git clone git clone https://github.com/abhiTronix/vidgear.git
> cd vidgear
> git checkout development
> sudo pip install .
> cd
> ```
> 
> **Then check if the problem is gone?**
> 
> > if not (self.frame is None or self.color_space is None): ...
> 
> Yes, a simple OR will also be correct.

Hi guys,
I tried the commands above but didnt work?
Any solution?
Thanks...

**Comment by witling** [comment]
@fahrettine the first line of the install script has an error. try to adapt your setup script like:
```
git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout development
sudo pip install .
```

Please note that 'didnt work' is not a very helpful problem description for a software engineer.

**Comment by abhiTronix** [comment]
> Hi guys,
> I tried the commands above but didnt work?
> Any solution?
> Thanks...

@fahrettine **Either you're not installing vidgear for your python3-pip version**, OR **calling your script with python2 instead or python3**, OR **there are multiple python versions are installed on your system**, Anyways, Try these commands and revert here:

```sh
git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout testing
sudo python3 -m pip install .
cd
```

**Comment by abhiTronix** [comment]
@fahrettine After installing vidgear as shown above, call your script with `python3 {your script name}.py`

**Comment by fahrettine** [comment]
Thank you very much for your quick response guys...
This helped...

git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout testing
sudo python3 -m pip install .
cd
