### ISSUE TITLE
WebGear + WriteGear simultaneously

### ISSUE THREAD

**Issue by jpzomer** [abhiTronix/vidgear#115]
## Question

Is it possible to use WebGear and WriteGear simultaneously?

### Acknowledgment

- [x] A brief but descriptive Title of your issue.
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Context
I want to stream the webcam to a website and saves the video on drive at the same time.
I haven't succeeded, because the WriteGear seems to need the frames individually inside a loop.

### Your Environment

* VidGear version: 0.1.6
* Branch: Testing
* Python version: 3.6+
* pip version:
* Operating System and version:

**Comment by abhiTronix** [comment]
**@jpzomer Yep, absolutely possible. See my comment: https://github.com/abhiTronix/vidgear/issues/111#issuecomment-593053564**. If you still run into any issue, comment here. Goodluck.
