### ISSUE TITLE
Catch youtube livestream 

### ISSUE THREAD

**Issue by PranavPuranik** [abhiTronix/vidgear#116]
When vidgear is used on a youtube live stream that has been running for 20 mins, it starts reading frames from the beginning of the video (20 mins ago).

Can it catch a live stream, read the current frames...?

**Comment by abhiTronix** [comment]
@PranavPuranik VidGear depends on [`pafy`](https://github.com/mps-youtube/mps-youtube) and [`youtube-dl`](https://github.com/ytdl-org/youtube-dl) libraries as backend for providing Youtube streaming within its CamGear API. **I've looked into both these libraries and found these links:**

-  **youtube-dl:** 
   - https://unix.stackexchange.com/questions/230481/how-to-download-portion-of-video-with-youtube-dl-command
   - https://github.com/ytdl-org/youtube-dl/issues/622
- **pafy:** https://github.com/mps-youtube/mps-youtube/issues/989 

and it seems you can post-process video after downloading with FFmpeg and `youtube-dl` but you cannot specify timestamp directly and that's a bummer for now. Thereby for now, You can raise this issue in-either or both these library to add this feature but until then it's not possible to add or work this enhancements. 
pafy:
