### ISSUE TITLE
__address and __port are not set in async mode

### ISSUE THREAD

**Issue by otter-in-a-suit** [abhiTronix/vidgear#117]
## Description

The following issue arises when switching from legacy to async when using `address` and `port` as kwargs:
```
NetGear_Async :: ERROR :: 'NetGear_Async' object has no attribute '_NetGear_Async__address'
Traceback (most recent call last):
  File "/home/christian/workspace/scarecrow/env/lib/python3.7/site-packages/vidgear/gears/asyncio/netgear_async.py", line 304, in __server_handler
    self.__protocol + "://" + str(self.__address) + ":" + str(self.__port)
```

### Acknowledgment

- [X] A brief but descriptive Title of your issue
- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [X] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).
- [X] I have read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md).

### Environment

* VidGear version: 0.1.7.dev1 
* Branch: testing
* Python version: 3.7.5
* pip version: 18.1
* Operating System and version: `Linux pop-os 5.3.0-7629-generic #31~1581628825~19.10~f90b7d5-Ubuntu SMP Fri Feb 14 19:56:45 UTC  x86_64 x86_64 x86_64 GNU/Linux`

### Expected Behavior

The `NetGear_Async` class should accept `address`, `port`

### Actual Behavior

The code checks for whether the kwargs are `None` and defaults them, but never sets the passed arguments

### Possible Fix

https://github.com/abhiTronix/vidgear/pull/118

### Steps to reproduce

**Client**:
```
# import libraries
from vidgear.gears.asyncio import NetGear_Async
import cv2, asyncio

#define and launch Client with `receive_mode = True`
client = NetGear_Async(receive_mode = True, framerate=25, address='127.0.0.1', port=5544, protocol='tcp',
                       pattern=0, logging=True).launch()


#Create a async function where you want to show/manipulate your received frames
async def main():
    # loop over Client's Asynchronous Frame Generator
    async for frame in client.recv_generator():

        
        # do something with received frames here

        
        # Show output window
        cv2.imshow("Output Frame", frame)
        key = cv2.waitKey(1) & 0xFF

        #await before continuing
        await asyncio.sleep(0.00001)


if __name__ == '__main__':
    #Set event loop to client's
    asyncio.set_event_loop(client.loop)
    try:
        #run your main function task until it is complete
        client.loop.run_until_complete(main())
    except KeyboardInterrupt:
        #wait for keyboard interrupt
        pass
        
    # close all output window
    cv2.destroyAllWindows()
    # safely close client
    client.close()
```

**Server**:
```
# import libraries
from vidgear.gears.asyncio import NetGear_Async
import asyncio

#initialize Server with suitable source
server = NetGear_Async(source='/home/christian/workspace/scarecrow/resources/videos/test.mp4', 
    framerate=25, address='127.0.0.1', port=5544, protocol='tcp',
                       pattern=0, receive_mode=False, logging=True).launch()

if __name__ == '__main__':
  #set event loop
  asyncio.set_event_loop(server.loop)
  try:
    #run your main function task until it is complete
    server.loop.run_until_complete(server.task)
  except KeyboardInterrupt:
    #wait for keyboard interrupt
    pass
  finally:
    # finally close the server
    server.close()
```

### Optional

Before:
![Screenshot from 2020-03-15 08-24-43](https://user-images.githubusercontent.com/6397962/76705669-9f040a80-66d9-11ea-8cc7-29c0389eb8a7.png)

After:
![Screenshot from 2020-03-15 08-25-07](https://user-images.githubusercontent.com/6397962/76705672-9f9ca100-66d9-11ea-8e74-d1e582b97619.png)

**Comment by abhiTronix** [comment]
@otter-in-a-suit That's why it is necessary to test PR as soon as possible. Yes this is bug. I've asked you to make some changes, kindly see and apply them.

**Comment by otter-in-a-suit** [comment]
As you are normally assuming int, I've changed that to remove the cast to int.

**Comment by abhiTronix** [comment]
@otter-in-a-suit can you run some memory test as pervious with new NetGear_Async API too and report results here?

**Comment by abhiTronix** [comment]
**Successfully resolved in commit fb17287**

**Comment by abhiTronix** [comment]
**@otter-in-a-suit Kindly share memory benchmarking results when ready.**

**Comment by otter-in-a-suit** [comment]
It will take me a while to update my own code besides the generic testing I did. 

I'd be happy to take any PRs that can integrate asyncio into https://github.com/otter-in-a-suit/scarecrow/blob/development/scarecrow_server/server/receiver.py and https://github.com/otter-in-a-suit/scarecrow/blob/development/scarecrow_client/client/sender.py.

Once that is done, I will update you.

**Comment by abhiTronix** [comment]
@otter-in-a-suit surely i'll look into it. But I'm curious what memory footprints are getting of basic examples given in NetGear_Async wiki?
