### ISSUE TITLE
How to connect a IP cammera

### ISSUE THREAD

**Issue by TomasTrnkaPLC** [abhiTronix/vidgear#120]
Hi. 
I want to connect a IP camera via vidgear. How I can do it?
I want to modify this
import urllib.request
import cv2
import numpy as np
import time
URL = "http://192.168.43.1:8080"
while True:
    img_arr = np.array(bytearray(urllib.request.urlopen(URL).read()),dtype=np.uint8)
    img = cv2.imdecode(img_arr,-1)
    cv2.imshow('IPWebcam',img)
    
    if cv2.waitKey(1):
        break

but 
cap= CamGear(source=URL, time_delay=1 return me Source is invalid, CamGear failed to intitialize stream on this source!

what I do wrong?

**Comment by abhiTronix** [comment]
@TomasTrnkaPLC **What IP camera are you using? Also complete following tasks and share your result here:**

1. Kindly turn logging on by setting `logging=True` in **CamGear** API and paste your terminal output here.
2. Try `URL = "http://192.168.43.1:8080/video"` instead along with  `logging=True` and see if it works?

**Comment by abhiTronix** [comment]
**Closed. Kindly provide proper evidence related to your issue and also related log data for further investigation and follow proper template for filing issue next time.**
