### ISSUE TITLE
reconnecting to server_end after disconnecting by the client

### ISSUE THREAD

**Issue by rubar-tech** [abhiTronix/vidgear#121]
## Description

hi, everything works fine with me, i have only a small problam; server_end, for exp a rashberri pi is away from me, after first connection, every things fine i get frames as a client; but if the client quit, it can't reconnect to the server. for reconnection code at the server_end must be restarted. i would be great if after ending each successful connection, the code be restarted at server_end automatically. thank you

### Acknowledgment

- [x] A brief but descriptive Title of your issue
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).
- [x] I have read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md).

### Environment

* VidGear version: 0.1.7
* Branch:  Testing
* Python version: all
* pip version: latest
* Operating System and version: all

**Comment by abhiTronix** [comment]
**@rubar-tech I've updated your issue with proper description, Kindly make sure you do the same next time.**

**Comment by rubar-tech** [comment]
sorry friend, actually it was my mistake, i was re editing it now , anyway thx
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Apr 1, 2020, 13:36 by notifications@github.com:

**Comment by abhiTronix** [comment]
**@rubar-tech Kindly wait, I'll push related PR in the development branch in upcoming days. So stay tuned.**

**Comment by rubar-tech** [comment]
thanks for every thing

**Comment by abhiTronix** [comment]
@rubar-tech **This is not a feature request, but the solution is already present in vidgear API.**

### Solution:

**You can easily tackle this problem by setting `pattern=2` in NetGear API on bother Server-end  and Client-end in NetGear API during its initialization** . Thereby on setting `pattern=2` _(ie[.`zmq.PUB/zmq.SUB`](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html) (ZMQ Publish/Subscribe Pattern))_, and if you exit Client-end, then Server-end need not to be started as this is asynchronous mode specially designed to stream live camera stream on the network, where both Server and Client end works independent of each other.

**Comment by abhiTronix** [comment]
**@rubar-tech Kindly set `pattern=2` in your code and revert if it works for you as expected or not?**

**Comment by abhiTronix** [comment]
**Answered on Gitter community channel.**

**Comment by abhiTronix** [comment]
@rubar-tech **This feature is currently being worked on. Please wait for next PR.**

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit 8f8d951**
