### ISSUE TITLE
Streaming to Google Cloud Compute engine machine

### ISSUE THREAD

**Issue by OctaM** [abhiTronix/vidgear#122]
I am trying to send a live stream to a Google Cloud Compute engine machine.

## Question

It is possible to send the video stream from my computer to an external IP, like the one from the gcp platform?

### Acknowledgment

- [x] A brief but descriptive Title of your issue.
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Context

I am trying to send live images from my computer to gcp in order to perform object detection online and I'm trying to figure if this would be a good option for video streaming

### Your Environment

* VidGear version:0.1.6
* Branch: PyPi 
* Python version:3.7
* pip version:19.03
* Operating System and version:macOS Catalina 10.15

**Comment by abhiTronix** [comment]
> It is possible to send the video stream from my computer to an external IP, like the one from the gcp platform?

@OctaM This is nothing to do with external IP or even with Video-processing. You need to implement a script to access [`google.cloud` API in order interface with any Google Cloud Platform services to be able to send any file to its server](https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-python). 

> I am trying to send live images from my computer to gcp in order to perform object detection online and I'm trying to figure if this would be a good option for video streaming

> live images

Moreover, I'm not aware of any python library or API that can stream live data/image to GCP cloud servers in realtime, but you surely can [send images to GCP servers with python](https://stackoverflow.com/questions/46078088/how-to-upload-a-bytes-image-on-google-cloud-storage-from-a-python-script) but it is really very slow. Nor, vidgear yet support Google cloud APIs, but If you really want this feature in vidgear then I can add this to TODO list to work on it in future, but still real-time performance is not guaranteed.

**Comment by abhiTronix** [comment]
Closed. Kindly respond to above queries to continue discussion further on this issue. I'll work on this feature if possible in the future.
