### ISSUE TITLE
Output video drops frames and then pads by duplicating the final frame many times

### ISSUE THREAD

**Issue by PolarBean** [abhiTronix/vidgear#123]
### Acknowledgment

- [x ] A brief but descriptive Title of your issue
- [ x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x ] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x ] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).
- [x ] I have read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md).

### Environment

* VidGear version: 0.1.6
* Branch: 
* Python version: 3.7.4
* pip version: 19.2.2
* Operating System and version: Windows 10

### Expected Behavior

When writing frames from a USB vision camera, I have vsync set to zero to prevent dropped or replicated frames, however whenever the framerate of ffmpegs encoding drops below the capture rate of my camera vidgear/ffmpeg does not cache the frame into memory but instead drops it and compensates by replicating the final frame for each dropped frame. 
Is there anyway to prevent writer.write from sending the next frame to ffmpeg until the previous has been written? or to ensure that frames are cached into system memory until written.

### Actual Behavior

Frames are dropped and the final frame is duplicated for each dropped frame

### Steps to reproduce

I am writing frames to a thread queue from the camera, then taking the frames from the queue in a separate thread and writing them to a video using vidgear.
the options im using are:

output_params = {"-vcodec":"h264","-bufsize":"1M","-crf": 5, "-preset": "ultrafast","-profile:v":"high","-input_framerate":90} #define (Codec,CRF,preset)
### Screenshot

![vidgear issue](https://user-images.githubusercontent.com/38996929/78745279-fb8bda00-79a6-11ea-8e73-f87f31a66a59.jpg)

**Comment by PolarBean** [comment]
just a note the behaviour is present regardless of vsync, -r and adjusting crf affects it when it causes more frames to be dropped thus worsening it, indicating its a symptom not a cause.
Any help is greatly appreciated!

**Comment by abhiTronix** [comment]
@PolarBean **Can you paste here the terminal log by setting `logging = True` for your WriteGear class in your python script?**

### Answer the following question:

> whenever the framerate of ffmpegs encoding drops below the capture rate of my camera vidgear/ffmpeg

**How does that happen? Are you changing some parameter in WriteGear class?**

> vidgear writer is pulling them out as fast as they are coming in before discarding them

VidGear doesn't discard anything nor it is using any multi-threading, rather it send frame directly to ffmpeg pipeline through its `subprocess` module API. Your actual problem lies in parameters passed to FFmpeg. **Only If its possible, can  you share part of code where you using this class and share the resultant video if possible through (youtube, gdrive etc.)?**

### Also, Try this Solution:

**Remove `"-input_framerate":90` and set framerate at using `-r`  FFmpeg parameter as follows:**

```python
output_params = {"-r":90, "-vcodec":"h264","-bufsize":"1M","-crf": 5, "-preset": "ultrafast","-profile:v":"high"} #define (Codec,CRF,preset)
``` 
**and revert if it works.** _(**Note:** you must set value of `-r` higher than input video framerate.)_

**Comment by PolarBean** [comment]
When I refer to the encoding rate of ffmpeg I mean the rate at which my CPU encodes frames, when this dips I see dropped and duplicated frames. 

Thank you greatly for your help. 
here is the requested screenshot of the log
![vidgear response](https://user-images.githubusercontent.com/38996929/78749122-f6338d00-79b0-11ea-88da-3534d396b210.jpg)

Here is the code used to record

output_params = {"-vcodec":"h264","-bufsize":"1M","-crf": 5, "-preset": "ultrafast","-profile:v":"high","-input_framerate":90} #define (Codec,CRF,preset) FFmpeg tweak parameters for writer
writer = WriteGear(output_filename = 'camera_1_recordng_at_{0}.mp4'.format(time.strftime('%y-%m-%d-%H-%M')), compression_mode = True, logging = True, **output_params) # loop over frames from the video stream
# loop over frames from the video stream

now = datetime.datetime.now()
framequeue=queue.Queue()

def vid_cap(Camera,oldimage=0,count=0):
    while True:
## grab image from camera
            image = Camera.GetImageEx()
           ##while frame is equal to the previous frame update until the camera gives us a new frame
            while (image==oldimage).all():
                image = Camera.GetImageEx() 

                count+=1
               ##if the camera has not given us a new frame within the given timeframe then break
                if count>270:
                    break
            if count>270:
                    break
            oldimage=image       
            framequeue.put(image)
            count=0



def vid_write(writer):
    while True:
        try:
            image_grab=framequeue.get(block=True,timeout=3)
        except queue.Empty:
            break
        image_grab = image_grab*(np.array(255)/image_grab.max())
        image_grab=image_grab.astype(np.uint8)
        writer.write(image_grab)
        
    print(datetime.datetime.now()-now)
    writer.close()


heres the video, I have clipped the final seconds where the error happens
[output2.zip](https://github.com/abhiTronix/vidgear/files/4448506/output2.zip)


I had assumed this was an error to do with VidGear as issue https://github.com/abhiTronix/vidgear/issues/70
mentions a frozen frame at the end of their encoded video. If this is not a case and it is a problem elsewhere then no worries!

Thank you for your time

**Comment by abhiTronix** [comment]
> I had assumed this was an error to do with VidGear as issue #70

@PolarBean Are you sure you're using [NetGear API](https://github.com/abhiTronix/vidgear/wiki/NetGear#netgear-api) as source, because #70 is related to it not WriteGear API?

### Also, Try this Solution:

@PolarBean Also did you tried the following solution, does it changes thing?

**Set framerate at using `-r`  FFmpeg parameter along with `"-input_framerate":90` as follows:**

```python
output_params = {-input_framerate":90, "-r":90, "-vcodec":"h264","-crf": 5, "-preset": "ultrafast","-profile:v":"high"} #define (Codec,CRF,preset)
writer = WriteGear(output_filename="out.mp4", compression_mode = True, logging =True, **output_params)
``` 
**and revert if it works.** _(**Note:** you must set value of `-r` equal or higher than input video framerate.)_

**Comment by PolarBean** [comment]
Ah I see no im not using NetGear, I forgot to mention I was using -r originally and it made no difference, i just tried setting it again and still no change. 
![issue2](https://user-images.githubusercontent.com/38996929/78767636-348b7500-79ce-11ea-87a7-1fc8f1fb93c3.jpg)
![issue3](https://user-images.githubusercontent.com/38996929/78767816-6e5c7b80-79ce-11ea-96d6-bdde3e9b0c6e.jpg)

also to note, RAM usage never increases so I believe no frames are being stored in memory while ffmpeg encodes new frames. Im going to reinstall ffmpeg unless you have any other suggestions. 

All the best, 

Harry

**Comment by abhiTronix** [comment]
> Im going to reinstall ffmpeg unless you have any other suggestions.

@PolarBean Nope, it will not make any difference, you're already using the latest one.

**Comment by PolarBean** [comment]
Ah dang, what do you think could be causing this?

**Comment by abhiTronix** [comment]
@PolarBean Why are you doing this?
```python
##while frame is equal to the previous frame update until the camera gives us a new frame
            while (image==oldimage).all():
                image = Camera.GetImageEx() 
```

This why you are getting duplicate frame. You're feeding same frame again and again to WriteGear's FFmpeg writer until camera gives a new frame. The queue at `vid_cap` function is continuing to feed same frame to your queue.

**Comment by abhiTronix** [comment]
**Kindly use following code instead of yours and this problem should go away:**

```python
output_params = {"-vcodec":"h264","-bufsize":"1M","-crf": 5, "-preset": "ultrafast","-profile:v":"high","-input_framerate":90} #define (Codec,CRF,preset) FFmpeg tweak parameters for writer
writer = WriteGear(output_filename = 'camera_1_recordng_at_{0}.mp4'.format(time.strftime('%y-%m-%d-%H-%M')), compression_mode = True, logging = True, **output_params) # loop over frames from the video stream
# loop over frames from the video stream

now = datetime.datetime.now()
framequeue=queue.Queue()

def vid_cap(Camera,oldimage=0,count=0):
    while True:
## grab image from camera
            image = Camera.GetImageEx()
           ##while frame is equal to the previous frame update until the camera gives us a new frame
            while (image==oldimage).all():
                image = None

                count+=1
               ##if the camera has not given us a new frame within the given timeframe then break
                if count>270:
                    break
            if count>270:
                    break
            oldimage=image       
            framequeue.put(image)
            count=0



def vid_write(writer):
    while True:
        try:
            image_grab=framequeue.get(block=True,timeout=3)
        except queue.Empty:
            break
        if image_grab is None: continue
        image_grab = image_grab*(np.array(255)/image_grab.max())
        image_grab=image_grab.astype(np.uint8)
        writer.write(image_grab)
        
    print(datetime.datetime.now()-now)
    writer.close()
```

**Comment by abhiTronix** [comment]
@PolarBean I've updated the code just now, Kindly try again and revert if it works or problem still persist?

**Comment by PolarBean** [comment]
I appreciate you doing that, however even with this new code the issue persists.  With every dropped frame resulting in a duplicate. I will continue to investigate on my end and update you if I find a solution.

**Comment by PolarBean** [comment]
> a new frame. The queue at `vid_cap` function is continuing to feed same frame to your queue regardless of any new frame

Ah here it doesnt actually pass anything to the frame writer until the frame changes, the framequeue line is outside of the while statement. Your code is more interpretable though so thank you :) 

I believe it must be some issue with ffmpeg so I'll run some experiments.

**Comment by abhiTronix** [comment]
> I believe it must be some issue with ffmpeg so I'll run some experiments.

@PolarBean I don't think its FFmpeg as I've searched through internet and not found if FFmpeg does that of its own. OK, I've change `vid_write` to this, so that you can see each frame by your eyes:

```python
 def vid_write(writer):
    while True:
        try:
            image_grab=framequeue.get(block=True,timeout=3)
        except queue.Empty:
            break
        if image_grab is None or not(image_grab): continue
        image_grab = image_grab*(np.array(255)/image_grab.max())
        image_grab=image_grab.astype(np.uint8)
        cv2.imshow("Output Frame", image_grab)
        key = cv2.waitKey(1) & 0xFF
        writer.write(image_grab)
        
    print(datetime.datetime.now()-now)
    writer.close()
```

**Comment by abhiTronix** [comment]
@PolarBean If that doesn't works than remove `output_params` and set `compression_mode=False` to activate [Non-Compression Mode in WiteGear ](https://github.com/abhiTronix/vidgear/wiki/Non-Compression-Mode:-OpenCV#non-compression-mode-built-upon-opencv-videowriter-class) that uses OpenCV's writer instead of FFmpeg and see if that works. 

@PolarBean Also, try setting low `-input_framerate"` and `"-r"`  value smaller than 90 to somwhere 
 between `30~60` and see if that solves this problem.

**Comment by PolarBean** [comment]
Yes!! this was the problem, the feeder was 88fps while the consumer was 90fps, this caused the weird behaviour, ill set it to 60 fps and compensate for this in my analysis of the videos. 
Thank you for all of your help
