### ISSUE TITLE
CamGear :: WARNING :: Threaded Queue Mode is disabled for the current video source!

### ISSUE THREAD

**Issue by fahrettine** [abhiTronix/vidgear#131]
Hi everyone,

- I am testing the new 64bit Raspberry Pi OS on Raspberry Pi 4 4GB.
- Python 3.7.3  / GCC 8.3.0 on Linux,
- OpenCV 3.2.0 (sudo apt install python3-opencv)
- Installed picamera and vidgear by pip3, 18.1-5+rpt1,
- Also there is a USB camera connected, index=1,
- I use Thonny as IDE,
The codes are working but, I get this  WARNING:
CamGear :: WARNING :: Threaded Queue Mode is disabled for the current video source!

What I am doing wrong?
Is still Multithreading active?
Thanks!!!

MyCodes:

import cv2
stream = CamGear(source=1, logging=True).start()  #USB cam
while True:
    frame = stream.read()
    if frame is None:
        break
    cv2.imshow("Output Frame", frame)
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break
cv2.destroyAllWindows()
stream.stop()

**Comment by abhiTronix** [comment]
@fahrettine That's a normal behaviour. Please read about [Threaded Queue Mode](https://github.com/abhiTronix/vidgear/wiki/Threaded-Queue-Mode#threaded-queue-mode).

**Comment by muhammad-faizan-122** [comment]
Hi @abhiTronix, Is it possible to use **THREADED_QUEUE_MODE**  for webcam or live streaming? I doesn't want to skip any   frame of live stream. The following code give warning "CamGear    :: WARNING  :: Threaded Queue Mode is disabled for the current video source!". Please help to resolve this issue.
```
from vidgear.gears import CamGear
import cv2

options = {"THREADED_QUEUE_MODE": True}
stream1 = CamGear(source=0, logging=True, **options).start() 

while True:

    frameA = stream1.read()
    if frameA is None:         
        break    
    cv2.imshow("Output Frame1", frameA)
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):        
        break    

cv2.destroyAllWindows()
stream1.stop()
```

**Comment by abhiTronix** [comment]
> I doesn't want to skip any frame of live stream.

Skipping frame doesn't happen in case of Live source as it is controlled by your machine's IO.

**Comment by muhammad-faizan-122** [comment]
@abhiTronix, I forgot to mention before that I also want apply object detection model on each frame of live stream data which will take ~2s. During this 2s live stream frame will be dropped. How to tackle this issue.
