### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [abhiTronix/vidgear#132]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by abhiTronix** [comment]
Hey, @thomasrockhu Thanks for reporting this issue. I've just installed and configured Codecov from market place successfully for vidgear. **Is there anything else I need to change? if yes, then please let me know.**

**Comment by thomasrockhu** [comment]
Hi @abhiTronix , thanks for getting back to me so quickly. I'm actually not seeing it activated for `vidgear`. 

You can do this by going [here](https://github.com/apps/codecov/installations/new), clicking on the `abhiTronix` button, and selecting

![image](https://user-images.githubusercontent.com/4213028/83536368-1ec39900-a4c1-11ea-8aae-90a4044104b8.png)

either all repositories, or specifically this repository. Let me know if that doesn't makes sense.

**Comment by abhiTronix** [comment]
@thomasrockhu, Done :+1:  Please check again.

**Comment by thomasrockhu** [comment]
Awesome, looks great! Thanks @abhiTronix
