### ISSUE TITLE
NetGear_Async API Server Usage Example throws error

### ISSUE THREAD

**Issue by whogben** [abhiTronix/vidgear#136]
## Description

Running the example "Using NetGear_Async with Variable Parameters - Server's End" results in:
`ValueError: [NetGear_Async:ERROR] :: Invalid configuration. Assigned generator must be a asynchronous generator function/method only!`

Example with the issue is ([here](https://abhitronix.github.io/vidgear/bonus/reference/netgear_async/)):

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/contribution/issue/).

### Environment

Raspberry Pi 4 on current Raspbian
Python 3.8
vidgear freshly installed with "pip3 install vidgear[asyncio]"

### Expected Behavior
Server would start

### Actual Behavior

```
NetGear_Async :: DEBUG :: Creating NetGear asynchronous server handler!
NetGear_Async :: DEBUG :: Terminating various Send Mode Processes.
Traceback (most recent call last):
  File "/home/pi/Desktop/netgear_example.py", line 13, in <module>
    server.loop.run_until_complete(server.task)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/pi/.local/lib/python3.7/site-packages/vidgear/gears/asyncio/netgear_async.py", line 238, in __server_handler
    "[NetGear_Async:ERROR] :: Invalid configuration. Assigned generator must be a asynchronous generator function/method only!"
ValueError: [NetGear_Async:ERROR] :: Invalid configuration. Assigned generator must be a asynchronous generator function/method only!
```
### Steps to reproduce

Download the example code, modify with your IP address and run it via python3 examplecode.py

Here is the code I am using:

```
# import libraries
from vidgear.gears.asyncio import NetGear_Async
import asyncio

#initialize Server with suitable source
server=NetGear_Async(source=0, address='192.168.1.14', port='5454', protocol='tcp',  pattern=3, logging=True).launch()

if __name__ == '__main__':
    #set event loop
    asyncio.set_event_loop(server.loop)
    try:
        #run your main function task until it is complete
        server.loop.run_until_complete(server.task)
    except KeyboardInterrupt:
        #wait for keyboard interrupt
        pass
    finally:
        # finally close the server
        server.close()
```

**Comment by abhiTronix** [comment]
@whogben Thanks for finding this critical bug in NetGear_Async API. Fortunately, **I've fixed it in commit https://github.com/abhiTronix/vidgear/commit/09eec5d18c123bf925cf343b0c37568bb9a97e95 on  `testing` branch, and you can easily re-install it by following [these instructions](https://abhitronix.github.io/vidgear/installation/source_install/#installation).** Also, Kindly revert if this solved your problem, I'm waiting for your response. Goodluck.

**Comment by whogben** [comment]
Thanks very much! Confirming that the testing branch resolves the error - running the same code I now get this output:

```
CamGear :: WARNING :: Threaded Queue Mode is disabled for the current video source!
NetGear_Async :: DEBUG :: Creating NetGear asynchronous server handler!
NetGear_Async :: DEBUG :: Successfully connected to address: tcp://192.168.1.14:5454 with pattern: 3.
NetGear_Async :: DEBUG :: Send Mode is successfully activated and ready to send data!
```

**Comment by abhiTronix** [comment]
> Also, I apologize, but I don't know what "kindly revert if this solves your problem" means - what should I do?

**@whogben It means respond back to me that if this fix works correctly for you or not?**

**Comment by abhiTronix** [comment]
**Successfully resolved in commit https://github.com/abhiTronix/vidgear/commit/09eec5d18c123bf925cf343b0c37568bb9a97e95**
