### ISSUE TITLE
CamGear :: ERROR :: 'thumbnails' in youtube mode

### ISSUE THREAD

**Issue by varneyraney** [abhiTronix/vidgear#138]
## Description

I get a , thumbnails, error when I use camgear to play youtube videos. I also got the same error when I tried it with older vidgear versions

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/contribution/issue/).

### Environment

* VidGear version:  0.1.8
* Branch: 
* Python version: 3.6
* pip version: 9.0.1
* Operating System and version: Ubuntu 18.04

### Expected Behavior
Opencv to play youtube video stream

### Actual Behavior
CamGear :: ERROR :: 'thumbnails'
Traceback (most recent call last):
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/vidgear/gears/camgear.py", line 92, in __init__
    source_object = pafy.new(url)
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 57, in _fetch_basic
    self._bestthumb = self._ydl_info['thumbnails'][0]['url']
KeyError: 'thumbnails'
Traceback (most recent call last):
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/vidgear/gears/camgear.py", line 92, in __init__
    source_object = pafy.new(url)
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 57, in _fetch_basic
    self._bestthumb = self._ydl_info['thumbnails'][0]['url']
KeyError: 'thumbnails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testvidgear.py", line 6, in <module>
    stream = CamGear(source='https://youtu.be/dQw4w9WgXcQ', y_tube=True, logging=True).start() 
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/vidgear/gears/camgear.py", line 116, in __init__
    "[CamGear:ERROR] :: YouTube Mode is enabled and the input YouTube URL is invalid!"
ValueError: [CamGear:ERROR] :: YouTube Mode is enabled and the input YouTube URL is invalid!

### Steps to reproduce
```python
 from vidgear.gears import CamGear
 import cv2
 stream = CamGear(source='https://youtu.be/dQw4w9WgXcQ', y_tube=True, logging=True).start() 
 while True:

    frame = stream.read()
    if frame is None:
        break

    cv2.imshow("Output Frame", frame)
    key = cv2.waitKey(1) & 0xFF

    if key == ord("q"):
        break
cv2.destroyAllWindows()
stream.stop()
```

**Comment by danlapko** [comment]
Seems they have changed something important in youtube-dl, so consider to update youtube-dl https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl

**Comment by varneyraney** [comment]
@danlapko  thank you it works now

**Comment by abhiTronix** [comment]
@danlapko Thanks.

**Comment by abhiTronix** [comment]
Running tests in CI for confirmation. This issue will be closed once all tests completed successfully.

**Comment by fspider** [comment]
I am getting the same error on Ubuntu 18.04 while it's working on windows as you shared above. 

![image](https://user-images.githubusercontent.com/53686427/84734033-2d6d7e00-afa0-11ea-8463-1f38fd9308a4.png)
```
from vidgear.gears import CamGear
import cv2 as cv
        cap = CamGear(source=videoUrl, y_tube = True, logging=True).start() # YouTube Video URL as input
        fps = cap.framerate
```

**Comment by fspider** [comment]
Ohh. Sorry. I have solved.
Acutally the code was this.
`        cap = CamGear(source=videoUrl, y_tube = True, time_delay=1, logging=True).start() # YouTube Video URL as input
`
And I removed time_delay=1 and this is working now!!!

**Comment by fspider** [comment]
Let me ask you one question.
Is it possible to receive youtube live stream video with Vidgear?
From this sample live stream.
https://www.youtube.com/watch?v=1EiC9bvVGnk

**Comment by abhiTronix** [comment]
>  Is it possible to receive youtube live stream video with Vidgear?

@fspider Absolutely yes.

Try installing vidgear from testing branch as follows:
```sh
pip install git+git://github.com/abhiTronix/vidgear@testing#egg=vidgear
```

Then run this example:
```python
# import required libraries
from vidgear.gears import CamGear
import cv2


# Add YouTube Video URL as input source (for e.g https://youtu.be/dQw4w9WgXcQ) and enable `y_Tube`
stream = CamGear(source='https://www.youtube.com/watch?v=1EiC9bvVGnk', y_tube=True, logging=True).start() 

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break


    # {do something with the frame here}


    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()
```

**Comment by fspider** [comment]
Thanks. It is running but after 2 seconds, it stuck.
Do you know why this happens?
As I know, When the network loos one frame, this happens.
How can I solve this?

**Comment by abhiTronix** [comment]
@fspider It is a [bug in FFmpeg](https://github.com/abhiTronix/vidgear/issues/133#issuecomment-638263225) provided by OpenCV. And only possible workaround for this bug is: https://github.com/abhiTronix/vidgear/issues/133#issuecomment-638567443

**Comment by fspider** [comment]
Thanks for your response every time.
My opencv was build with CMAKE and gstreamer was enabled.
![image](https://user-images.githubusercontent.com/53686427/84805743-04330900-b005-11ea-85ac-f689f1d9ae59.png)

But getting this error. Please help me. I was wrong with Gstreamer?

```
(venv) root@iZ8ps1o9x7u4ik765voxefZ:/var/www# python vidtest.py
CamGear :: DEBUG :: YouTube source ID: `Y_TLxje5Qw4`, Title: `Downtown Telluride Live Camera`
CamGear :: DEBUG :: Enabling Threaded Queue Mode for the current video source!
[ WARN:0] global /var/opc/opencv-4.1.1/modules/videoio/src/cap_gstreamer.cpp (1741) handleMessage OpenCV | GStreamer warning: your GStreamer installation is missing a required plugin
[ WARN:0] global /var/opc/opencv-4.1.1/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module uridecodebin0 reported: No URI handler implemented for "https".
[ WARN:0] global /var/opc/opencv-4.1.1/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /var/opc/opencv-4.1.1/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
CamGear :: DEBUG :: Setting backend `1800` for this source.
Traceback (most recent call last):
  File "vidtest.py", line 7, in <module>
    stream = CamGear(source='https://www.youtube.com/watch?v=Y_TLxje5Qw4', y_tube=True, logging=True, backend=cv2.CAP_GSTREAMER).start()
  File "/var/www/venv/lib/python3.6/site-packages/vidgear/gears/camgear.py", line 214, in __init__
    "[CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!"
RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!
```

**Comment by fspider** [comment]
Wow. I solved that problem by installing Gstreamer Plugins..
It's great!!! Thank you very much. @abhiTronix

**Comment by fspider** [comment]
Can I ask you more questions?
Does this only work with test branch?
How set read stream frame_rate? if I need only 5 fps.

**Comment by fspider** [comment]
Could you help me how to solve this?
It seems blocked from youtube ... I can see this is not error related to vidgear... but want to ask you.

```
2|backend1_0  | ERROR: Unable to download webpage: HTTP Error 429: Too Many Requ                                                               ests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue                                                                on https://yt-dl.org/bug . Make sure you are using the latest version; see  http                                                               s://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --ve                                                               rbose flag and include its complete output.
2|backend1_0  | CamGear :: ERROR :: ERROR: Unable to download webpage: HTTP Erro                                                               r 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); pleas                                                               e report this issue on https://yt-dl.org/bug . Make sure you are using the lates                                                               t version; see  https://yt-dl.org/update  on how to update. Be sure to call yout                                                               ube-dl with the --verbose flag and include its complete output.
2|backend1_0  | Traceback (most recent call last):
2|backend1_0  |   File "/var/www/venv/lib/python3.6/site-packages/youtube_dl/ext                                                               ractor/common.py", line 627, in _request_webpage
2|backend1_0  |     return self._downloader.urlopen(url_or_request)
2|backend1_0  |   File "/var/www/venv/lib/python3.6/site-packages/youtube_dl/You                                                               tubeDL.py", line 2238, in urlopen
2|backend1_0  |     return self._opener.open(req, timeout=self._socket_timeout)
2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
2|backend1_0  |     response = meth(req, response)
2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 642, in http                                                               _response
2|backend1_0  |     'http', request, response, code, msg, hdrs)
2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 570, in erro                                                               r
2|backend1_0  |     return self._call_chain(*args)
2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 504, in _cal                                                               l_chain
2|backend1_0  |     result = func(*args)
2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 650, in http                                                               _error_default
2|backend1_0  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2|backend1_0  | urllib.error.HTTPError: HTTP Error 429: Too Many Requests
2|backend1_0  | During handling of the above exception, another exception occurr                                                               ed:

```

**Comment by abhiTronix** [comment]
> Does this only work with test branch?

No, master branch and pypi install also works too. But I recently added few performance improvements for `testing` branch, so it works the best.

>  How set read stream frame_rate when if I need only 5 fps.

You cannot change framerate of source directly as it is not possible in OpenCV or pafy or youtube-dl. But you can add small delay to your code to make it slow like `time.sleep(2)` inside the loop. Or if you're saving it with WriteGear API then set [`-input_framerate`](https://abhitronix.github.io/vidgear/gears/writegear/compression/usage/#using-compression-mode-with-controlled-framerate) parameter to 5fps.

**Comment by abhiTronix** [comment]
> It seems blocked from youtube ... I can see this is not error related to vidgear... but want to ask you.
> 
> 
> 2|backend1_0  | CamGear :: ERROR :: ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> 2|backend1_0  | Traceback (most recent call last):
> 2|backend1_0  |   File "/var/www/venv/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
> 2|backend1_0  |     return self._downloader.urlopen(url_or_request)
> 2|backend1_0  |   File "/var/www/venv/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
> 2|backend1_0  |     return self._opener.open(req, timeout=self._socket_timeout)
> 2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
> 2|backend1_0  |     response = meth(req, response)
> 2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
> 2|backend1_0  |     'http', request, response, code, msg, hdrs)
> 2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
> 2|backend1_0  |     return self._call_chain(*args)
> 2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
> 2|backend1_0  |     result = func(*args)
> 2|backend1_0  |   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
> 2|backend1_0  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> 2|backend1_0  | urllib.error.HTTPError: HTTP Error 429: Too Many Requests
> 2|backend1_0  | During handling of the above exception, another exception occurred:

@fspider **It may be bad news for you, As YouTube ban IP's with "HTTP ERROR 429: Too Many Requests" and it can last for few days to forever.** I thinks you tried to download or stream too much data out of YouTube, and they noticed it. See following links for more info:

https://www.reddit.com/r/youtubedl/comments/ejgy2l/yt_banning_ips_with_http_error_429_too_many/
https://github.com/ytdl-org/youtube-dl/issues/22839
https://github.com/ytdl-org/youtube-dl/issues/21729
https://github.com/ytdl-org/youtube-dl/issues/23028

**Comment by fspider** [comment]
So isn't there any solution to solve this issue?
There may be any api from youtube?

**Comment by abhiTronix** [comment]
Use VPN.

**Comment by fspider** [comment]
Thanks for your fast help.
Do you know any paid proxy IP providing services for ubuntu?

**Comment by fspider** [comment]
Thank you very much @abhiTronix 
It is working again!!
