### ISSUE TITLE
Can't run vidgear, getting same error in windows10 and ubuntu 18.04 # ModuleNotFoundError: No module named 'vidgear.gears'; 'vidgear' is not a package

### ISSUE THREAD

**Issue by kushu9999** [abhiTronix/vidgear#140]
## Question
Can't run vidgear, getting same error in windows10 and ubuntu 18.04 # ModuleNotFoundError: No module named 'vidgear.gears'; 'vidgear' is not a package

### Acknowledgment

- [ok ] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [ok ] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [ok ] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Your Environment
 
* VidGear version: 0.1.8 & 0.1.7 both tried
* Branch: 
* Python version:3.7.6 , 3.7.7 , 3.8 all tried
* pip version: 20.1.1
* Operating System and version: Windows10 and Ubuntu 18.04

### Optional

![Command Prompt 6_21_2020 5_41_03 AM](https://user-images.githubusercontent.com/38341722/85217574-07851680-b3b0-11ea-8989-9e0b430b7023.png)

**Comment by abhiTronix** [comment]
@kushu9999 How are you installing vidgear on your machine?

**Comment by kushu9999** [comment]
> @kushu9999 How are you installing vidgear on your machine? Can you share/paste the installation terminal log here?

I installed from all sources are mentioned in this [Link](https://abhitronix.github.io/vidgear/installation/source_install/), but I'm getting
Same error

**Comment by abhiTronix** [comment]
> I installed from all sources are mentioned in this Link, but I'm getting

@kushu9999 Are you new to GitHub? I know that you followed the instructions given here. But, I want the actual log from the terminal to debug if something went wrong with the installation, and see if vidgear is installed correctly on your machine or not? Kindly provide it or otherwise this issue will be closed.

**Comment by abhiTronix** [comment]
**Closed. Kindly provide proper evidence related to your issue and also related log data for further investigation.**

**Comment by kushu9999** [comment]
![Screenshot from 2020-06-22 09-49-12](https://user-images.githubusercontent.com/38341722/85248181-b6d3f300-b46d-11ea-8660-1717e7cd2b21.png)

**Comment by abhiTronix** [comment]
@kushu9999 Also Share the complete screenshot from Windows machine by running command `python -m pip install vidgear[asyncio]`  on the Windows's Command Prompt.

**Comment by abhiTronix** [comment]
@kushu9999 Are you aware that you're installing vidgear inside a [virtual environment](https://docs.python.org/3/library/venv.html) named as `(base)`?  And you cannot access package/library installed in virtual environment outside it, or in another virtual environment. This is why you cannot call vidgear in your script.

**Comment by kushu9999** [comment]
i know i'm installing on base and trying to run on base , same as i'm installed on windows cmd python 3.7 and i'm getting same error as above screenshot of windows , i'm uploading installation screenshot of windows in few minutes

**Comment by abhiTronix** [comment]
@kushu9999 You can also copy-paste output directly here instead of screenshot.

**Comment by abhiTronix** [comment]
@kushu9999 Also, you're using anaconda, which is not officially supported by vidgear yet.

**Comment by kushu9999** [comment]
@abhiTronix on windows i'm not using anaconda

**Comment by abhiTronix** [comment]
@kushu9999 Make sure to run command `python -m pip install -U --user vidgear[asyncio]` on the Windows's Command Prompt.

**Comment by kushu9999** [comment]
![Command Prompt 6_22_2020 6_52_07 AM](https://user-images.githubusercontent.com/38341722/85257260-2dc7b680-b483-11ea-957c-b9707e0da825.png)
![Command Prompt 6_22_2020 6_52_57 AM](https://user-images.githubusercontent.com/38341722/85257256-2c968980-b483-11ea-9875-736e87ec556f.png)

**Comment by abhiTronix** [comment]
@kushu9999 Python Paths are not correct on your machine. Please paste the output of `python -v -c "from vidgear.gears import CamGear"` command by running it on your Windows's Command Prompt. Do not screenshot this time, as output will be huge.

**Comment by abhiTronix** [comment]
@kushu9999 **Also, I think since you've named your python script `vidgear.py`,  which maybe interfering with vidgear library, and causing this error.** Kindly change it to something else like `test.py` and then run it, and see if works this time without any error.
