### ISSUE TITLE
Non-File FFMPEG output (rtmp etc)

### ISSUE THREAD

**Issue by esologic** [abhiTronix/vidgear#144]
### Context

Hi Abhishek! Your library is absolutely amazing, however, there is a feature that I think would be easy for you to implement that could make it even more powerful. This came up on stackoverflow a few days ago [here](https://stackoverflow.com/questions/34167691/pipe-opencv-images-to-ffmpeg-using-python/55937094#comment110888597_55937094). This person is pointing out that when one is trying to stream to an RTMP server using ffmpeg, the location of the server is put in the command where the name of the output file normally goes. Example:

```
ffmpeg -re -i file.flv -c copy -f flv rtmp://live.twitch.tv/app/<stream key>
```

I got this example from [here](https://trac.ffmpeg.org/wiki/EncodingForStreamingSites).

It would be amazing if we could provide rtmp addresses instead of output file paths with `WriteGear`, like so:

```
writer = WriteGear(output_filename="rtmp://live.twitch.tv/app/<stream key>")
```

### Your Environment

* VidGear version: Latest PyPi
* Branch: Master
* Python version: 3
* pip version: latest
* Operating System and version: Ubuntu

### Any Other Important Information
N/A

**Comment by abhiTronix** [comment]
@esologic   Try #145 PR by installing `development` branch as follows:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout development

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```

**and check if it works as you expected or not? also share your result here.**

**Comment by abhiTronix** [comment]
**@esologic Try following complete python example with WriteGear API instead:**

```python
# import required libraries
from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import cv2

# Open live webcam video stream on first index(i.e. 0) device
stream = CamGear(source=0, logging=True).start() 

# define required FFmpeg parameters for your writer
output_params = {"-vcodec":"libx264","-profile:v":"main","-preset:v":"medium","-r":30,"-g":60,"-keyint_min":60,"-sc_threshold":0,"-b:v":"2500k","-maxrate":"2500k","-bufsize":"2500k","-filter:v":"scale='trunc(oha/2)2:720'","-sws_flags":"lanczos+accurate_rnd","-acodec":"libfdk_aac","-b:a":"96k","-ar":"48000","-ac":2,"-f":"flv"}

# Define writer with defined parameters and change your STREAM_KEY below
writer = WriteGear(output_filename = 'rtmp://live.twitch.tv/app/STREAM_KEY', logging =True, **output_params)

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break


    # {do something with the frame here}


    # write frame to writer
    writer.write(frame)

    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()

# safely close writer
writer.close()
```

**and revert results here. Goodluck!**

**Comment by abhiTronix** [comment]
@esologic Did you got the chance to test above example? Please let us know.

**Comment by abhiTronix** [comment]
Successfully resolved and merged in commit d76c8be.

**Comment by abhiTronix** [comment]
@esologic Closed and marked solved for now. Kindly share your results when you're ready. Good luck!

**Comment by abhiTronix** [comment]
You must not copy the exact example, i meant to take ideas from it for building a RTMP stream pipeline. Btw you need to replace `output_params` with suitable FFmpeg parameters, in case if you wonder what's wrong, such as follows:

```python 
# define required FFmpeg parameters for your writer output_params = {"-profile:v":"main","-preset:v":"medium","-input_framerate":stream.framerate,"-r":stream.framerate,"-g":60,"-keyint_min":60,"-sc_threshold":0,"-b:v":"2500k","-maxrate":"2500k","-bufsize":"2500k","-f":"flv"} 
```
