### ISSUE TITLE
Using webgear & netgear together

### ISSUE THREAD

**Issue by KhalidS1** [abhiTronix/vidgear#146]
Hello , first i'd like to thank toy for this AMAZING library.

I am in a situation where i have a raspberry connected to camera , that raspberry should send the video stream to a pc with local lan connection, i am using NetGear for that , then the pc will send the stream to another python app for image processing via another NetGear , at the same time , the pc will stream the video to a browser .
i can achieve the NetGear to NeatGear stream with something like
```
while True:

    # receive frames from network
    frame = client.recv()

    # check for received frame if Nonetype
    if frame is None:
        break
    server.send(frame)
```
but i can't find a way to tell WebGear that the source is NetGear 

thank you

**Comment by abhiTronix** [comment]
@KhalidS1 This question is answered multiple times and also available in [WebGear's FAQ](https://abhitronix.github.io/vidgear/help/webgear_faqs/#how-to-send-opencv-frames-directly-to-webgear-server). Kindly refer it.

**Comment by gembancud** [comment]
Hi, this library is WONDERFUL and is a LIFESAVER!
I am having a similar case with op. I have an edge device running a client(netgear_async, receive_mode=false) that
pushes frames to a server (neatgear_async, receive_mode=true & webgear) on my computer. Unfortunately, I haven't found a way to mix a netgear_async and webgear together. I would highly appreciate your help! 😅
