### ISSUE TITLE
can't import the vidgear as a package

### ISSUE THREAD

**Issue by cyber-hoax** [abhiTronix/vidgear#150]
## Description

when trying to import from vidgear.gears import CamGear its showing error 
 
    ModuleNotFoundError: No module named 'vidgear.gears'; 'vidgear' is not a package

**Comment by abhiTronix** [comment]
**Duplicate of #140.** You either have a file named `vidgear.py` in your python path or you've named your python script `vidgear.py`. Remove replace `vidgear` name with anything else to fix this error.
