### ISSUE TITLE
why to used vidgear?do u give me a simple examples instead of opencv?

### ISSUE THREAD

**Issue by tms2003** [abhiTronix/vidgear#151]
I already read the introducation of vidgear. and I noticed multi-thread and something in it.but ,I can't understand the differents with opencv lib.

If I have two cameras,how to use vidgear?anything like opencv ?

could u give me some multi threads simple?

**Comment by abhiTronix** [comment]
> I can't understand the differents with opencv lib.

Read this: https://abhitronix.github.io/vidgear/help/general_faqs/#vidgear-is-using-multi-threading-but-python-is-notorious-for-its-poor-performance-in-multithreading  and https://abhitronix.github.io/vidgear/bonus/TQM/

> could u give me some multi threads simple?

Multi-Threading is used internally  for its videocapture APIs. You just have to run any given example of respective API and rest is done automatically. If you're already familiar with OpenCV see this https://abhitronix.github.io/vidgear/switch_from_cv/#switching-videocapture-apis
