### ISSUE TITLE
"[CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!" RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!. When using opencv version 3.3.0 and above

### ISSUE THREAD

**Issue by varneyraney** [abhiTronix/vidgear#152]
## Description

I am getting a, RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source, when I use opencv version 3.3.0 and above on an ubuntu 18.04 VM. Camgear works when I use opencv version 3.2.0

### Acknowledgment

- [x ] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x ] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [ x] I have read the [Issue Guidelines](https://abhitronix.github.io/contribution/issue/).

### Environment

* VidGear version: 0.1.8
* Python version: 3.6
* pip version: 20.2
* Operating System and version: Ubuntu 18.04
 *OpenCV version: 3.3.0 and after

### Expected Behavior
VidGear and OpenCV must be able to play pafy video streams.

### Actual Behavior
  "[CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!"
RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!

### Steps to reproduce
```python
from vidgear.gears import CamGear
import cv2
stream = CamGear(source='https://www.youtube.com/watch?v=9y0yyt0edXI', y_tube=True, logging=True).start() 
while True:
    frame = stream.read()
    if frame is None:
        break
    cv2.imshow("Output Frame", frame)
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break
cv2.destroyAllWindows()
stream.stop() 
```

**Comment by abhiTronix** [comment]
> Actual Behavior
> "[CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!"
> RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!

This is incomplete. Kindly paste full log to debug the error.

**Comment by varneyraney** [comment]
My bad I put the wrong url. here is the one that I meant to put: 
https://www.youtube.com/watch?v=atzIb1gYOGQ
```python
/io/opencv/modules/videoio/src/cap_images.cpp:235: error: (-5:Bad argument) CAP_IMAGES: error, expected '0?[1-9][du]' pattern, got: https://manifest.googlevideo.com/api/manifest/dash/expire/1596188287/ei/HpIjX6T7N8TYDajejpgM/ip/34.67.54.19/id/6adcc86f58183864/source/youtube/requiressl/yes/playback_host/r4---sn-qxoedn7k.googlevideo.com/mh/Mi/mm/31%2C26/mn/sn-qxoedn7k%2Csn-5go7yner/ms/au%2Conr/mv/m/mvi/4/pl/23/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2663750/vprv/1/mt/1596166590/fvip/4/keepalive/yes/fexp/23883098/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgQoeFfHwYtfgd2BjSWi7uj10uJs8-HH85RhCuBXTyev4CIQDzSpAB8TsczID9GZOPRSaDKZ_cAgvfZviHpPGQAmcDQg%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAK3iuuewpMFqp7eW2WSOlMAWj7l_aey9o4HxA3iCuhneAiEAsz9xqLMwtkQ_ser09YZt0hIsBxHB5voyMxRztmO-lTE%3D in function 'icvExtractPattern'


Traceback (most recent call last):
  File "testvidgear.py", line 24, in <module>
    stream = CamGear(source=inputs, y_tube=True, logging=True).start()
  File "/home/gdfutbos/.local/lib/python3.6/site-packages/vidgear/gears/camgear.py", line 214, in __init__
    "[CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!"
RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!
```

**Comment by abhiTronix** [comment]
> /io/opencv/modules/videoio/src/cap_images.cpp:235: error: (-5:Bad argument) CAP_IMAGES: error, expected '0?[1-9][du]' pattern, got: https://manifest.googlevideo.com/api/manifest/dash/expire/1596188287/ei/HpIjX6T7N8TYDajejpgM/ip/34.67.54.19/id/6adcc86f58183864/source/youtube/requiressl/yes/playback_host/r4---sn-qxoedn7k.googlevideo.com/mh/Mi/mm/31%2C26/mn/sn-qxoedn7k%2Csn-5go7yner/ms/au%2Conr/mv/m/mvi/4/pl/23/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2663750/vprv/1/mt/1596166590/fvip/4/keepalive/yes/fexp/23883098/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgQoeFfHwYtfgd2BjSWi7uj10uJs8-HH85RhCuBXTyev4CIQDzSpAB8TsczID9GZOPRSaDKZ_cAgvfZviHpPGQAmcDQg%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAK3iuuewpMFqp7eW2WSOlMAWj7l_aey9o4HxA3iCuhneAiEAsz9xqLMwtkQ_ser09YZt0hIsBxHB5voyMxRztmO-lTE%3D in function 'icvExtractPattern'

@varneyraney  It is a [bug in FFmpeg](https://github.com/abhiTronix/vidgear/issues/133#issuecomment-638263225) provided by OpenCV. **And only possible workaround for this bug is: https://github.com/abhiTronix/vidgear/issues/133#issuecomment-638567443**

**Comment by abhiTronix** [comment]
> Camgear works when I use opencv version 3.2.0

That's interesting. I wonder if OpenCV devs changed something critical with FFmpeg backend.

**Comment by abhiTronix** [comment]
@varneyraney  I think #274 resolves this issue too. 

Clone and Install `development` branch:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout development

  # install normally
  pip install .[core]

  # OR install with asyncio support
  pip install .[asyncio]
```
Test your code:
```python
# import required libraries
from vidgear.gears import CamGear
import cv2

options = {"STREAM_RESOLUTION": "720p"}

# Add YouTube Video URL as input source (for e.g https://youtu.be/bvetuLwJIkA)
# and enable Stream Mode (`stream_mode = True`)
stream = CamGear(
    source="https://youtu.be/j1GLs_fMn1s", stream_mode=True, logging=True, **options
).start()

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # Show output window
    cv2.imshow("Output", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()
```

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit: https://github.com/abhiTronix/vidgear/commit/dc26c00bcb4ec6e40645b4ad1aa1aedf4f0c6b43**

### Usage docs are available at: https://abhitronix.github.io/vidgear/v0.2.4-dev/gears/camgear/usage/#using-camgear-with-youtube-videos
