### ISSUE TITLE
Unable to merge audio and video with WriteGear on window system

### ISSUE THREAD

**Issue by vishram2997** [abhiTronix/vidgear#158]
## Description

```sh
Getting error when trying to merge audio and video from microphone and webcam on window system using writegear

Duration: N/A, start: 0.000000, bitrate: 90316 kb/s
    Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 448x336, 90316 kb/s, 25 tbr, 25 tbn, 25 tbc
[dshow @ 00000231858dee40] Could not find audio only device with name ["Microphone (Realtek(R) Audio)"] among source devices of type audio.
[dshow @ 00000231858dee40] Searching for audio device within video devices for "Microphone (Realtek(R) Audio)"
[dshow @ 00000231858dee40] Could not find audio only device with name ["Microphone (Realtek(R) Audio)"] among source devices of type video.
```

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/contribution/issue/).

### Environment

* VidGear version: 
* Branch: 
* Python version:
* pip version:
* Operating System and version:

### Steps to reproduce

```python
options = {'bidirectional_mode': True} 

output_params = {'-f': 'dshow', '-i': 'audio="Microphone (Realtek(R) Audio)"','-acodec':'aac', '-ac':'2', '-ab':'32k', '-ar':'44100' }  

stream = VideoGear(source=0).start()

writer = WriteGear(output_filename = 'Output.mp4',compression_mode=True, logging = True, **output_params)
client = NetGear(address = '192.168.0.12', port = '5454', protocol = 'tcp',receive_mode = True, pattern = 1, logging = True, **options)

while True:

    frame = stream.read()

    if frame is None:
        break

    frame = reducer(frame, percentage = 30) #reduce frame by 30%
    writer.write(frame)
```

![image](https://user-images.githubusercontent.com/5601084/91673223-f2331380-eae7-11ea-82d5-f452317e7bd4.png)

![image](https://user-images.githubusercontent.com/5601084/91673235-fe1ed580-eae7-11ea-92c4-3f3fe73ff4b6.png)

**Comment by abhiTronix** [comment]
@vishram2997 try using `'audio=Microphone (Realtek(R) Audio)'` instead of `'audio="Microphone (Realtek(R) Audio)"'`

**Comment by vishram2997** [comment]
@abhiTronix  Thanks ,Now I don't get error but I am not getting voice on server side using bidirectional.

**Comment by abhiTronix** [comment]
@vishram2997 you cannot send audio data with NetGear.

**Comment by abhiTronix** [comment]
@vishram2997 Please example what you're trying to achieve and what is your setup?

**Comment by vishram2997** [comment]
@abhiTronix I am trying to build video chat system.

**Comment by abhiTronix** [comment]
@vishram2997 with audio?

**Comment by vishram2997** [comment]
@abhiTronix yes like normal video call.

**Comment by abhiTronix** [comment]
Try this example: https://gist.github.com/lmNt/68994a58b022f2217571, does it works?

**Comment by vishram2997** [comment]
@abhiTronix  I want to send video + audio. this one is only to send audio.

**Comment by abhiTronix** [comment]
@vishram2997 I know, but If this example works, then you can modify NetGear to work like this,

**Comment by abhiTronix** [comment]
**@vishram2997 This issue is no longer related to problem you described in Title, so I'm closing it.** Please continue discussion on our [Gitter community channel](https://gitter.im/vidgear/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge), you can join there.
