### ISSUE TITLE
processed frames web streaming

### ISSUE THREAD

**Issue by idanmosh** [abhiTronix/vidgear#159]
Hey,
First of all thank for great repo.
I am connecting to an IP camera via VidGear, grab frame by frame, processed them on my local computer(e.g object detection) and want to stream that frames in real-time to AWS EC2 computer in order that my clients(react's app) will can see the processed frame's(e.g frame with bounding box).
I followed the whole documentation and see that there is module's for some specific task in my pipeline like WebGear but nothing that combine the whole pipeline toghter.
can you please guide me?

the pipeline:
grab frame -> perform object detection  -> stream the frame to html file on AWS server

**Comment by abhiTronix** [comment]
> the pipeline:
> grab frame -> perform object detection -> stream the frame to html file on AWS server

> grab frame

**Use any [VideoCapture Gears](https://abhitronix.github.io/vidgear/gears/#a-videocapture-gears).**

> -> perform object detection

VideoGear is a video-processing library, so **you need to use third-party ML/DL library for object detection.**


> -> stream the frame to html file on AWS server

**You don't need WebGear for this task, but [WriteGear API](https://abhitronix.github.io/vidgear/gears/writegear/introduction/) _(that supports Streaming URLs with its [Compression Mode: FFmpeg Backend](https://abhitronix.github.io/vidgear/gears/writegear/compression/overview/))_ is what you're looking for. Just [initiate a RTP/RTMP stream with WriteGear API](https://github.com/abhiTronix/vidgear/issues/144#issuecomment-657985607) and [Connect this RTMP/RTP stream to AWS Media Services in the Cloud](https://aws.amazon.com/blogs/media/connecting-ffmpeg-using-rtmp-to-aws-media-services-in-the-cloud/).** Goodluck and drop a ⭐ if it helps.

**Comment by abhiTronix** [comment]
**@idanmosh Marked Solved for now. Kindly share if it works when you ready. Goodluck!**

**Comment by idanmosh** [comment]
Hey, thnak's for your response. i try your ffmpeg command and it's not work. i get this error:
Error initializing filter 'scale' with args 'trunc(oha/2)2:720:flags=bicubic:sws_flags=lanczos+accurate_rnd'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Conversion failed!
WriteGear :: ERROR :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!
Traceback (most recent call last):
  File "/home/idan/.local/lib/python3.8/site-packages/vidgear/gears/writegear.py", line 304, in write
    self.__process.stdin.write(frame.tostring())
BrokenPipeError: [Errno 32] Broken pipe

**Comment by abhiTronix** [comment]
You must not copy the exact example, i meant to take ideas from it for building a RTMP stream pipeline. Btw you need to replace `output_params` with suitable FFmpeg parameters, in case if you wonder what's wrong, such as follows:

```python
# define required FFmpeg parameters for your writer output_params = {"-profile:v":"main","-preset:v":"medium","-input_framerate":stream.framerate,"-r":stream.framerate,"-g":60,"-keyint_min":60,"-sc_threshold":0,"-b:v":"2500k","-maxrate":"2500k","-bufsize":"2500k","-f":"flv"} 
```
