### ISSUE TITLE
Error With YouTube Live

### ISSUE THREAD

**Issue by jbwps** [abhiTronix/vidgear#16]
I'm running the example code to use a live YouTube stream as a video source, but am receiving an error:

"YouTube Mode is enabled and the input YouTube Url is invalid!"

I'm using the sample code verbatim, and only changed the YouTube URL to a live stream (https://youtu.be/Nk4HAS-HOr4) instead of the Rick Roll video.

I'm pretty sure all of my packages are up to date, including youtube-dl

**Comment by abhiTronix** [comment]
@jbwps Thanks for pointing this out, A bug is discovered as follows:

### Bug Summary: 
`https://youtu.be/Nk4HAS-HOr4` is a live stream video which do not support video only streams therefore resulted in NoneType video object and finally "YouTube Mode is enabled and the input YouTube Url is invalid!" returned in vidgear.

I'm working on a fix, Kindly wait!

**Comment by abhiTronix** [comment]
@jbwps Fixed! Kindly test testing branch by strictly following steps: 

1. **Firstly, Kindly clone and install `testing` branch as follows:**
```sh
git clone git clone https://github.com/abhiTronix/vidgear.git
cd testing
git checkout testing
sudo pip install .
cd
```

then rerun the same algorithm with your URL `(https://youtu.be/Nk4HAS-HOr4` as follows:
```python
# import libraries
from vidgear.gears import CamGear
import cv2

stream = CamGear(source='https://youtu.be/Nk4HAS-HOr4', y_tube =True,  time_delay=1, logging=True).start() # YouTube Video URL as input

# infinite loop
while True:
	
	frame = stream.read()
	# read frames

	# check if frame is None
	if frame is None:
		#if True break the infinite loop
		break
	
	# do something with frame here
	
	cv2.imshow("Output Frame", frame)
	# Show output window

	key = cv2.waitKey(1) & 0xFF
	# check for 'q' key-press
	if key == ord("q"):
		#if 'q' key-pressed break out
		break

cv2.destroyAllWindows()
# close output window

stream.stop()
# safely close video stream.
```

**Comment by abhiTronix** [comment]
Resolved in 03ec55487855a76c9faee464e11b39492896179e . Feel free to reopen, if something doesn't works for you.

**Comment by imranilyas** [comment]
I'm using CamGear and the following live youtube url: https://www.youtube.com/watch?v=ZWcV3g23c8Y&ab_channel=CNN-News18 

After about 40 seconds, the livestream terminates and I get the following errors:
[tls @ 000001835c367600] Unable to read from socket
[tls @ 000001835c398580] Failed to send close message
[tls @ 000001835c394e40] Unable to read from socket
[tls @ 000001835c394ac0] Failed to send close message

**Comment by abhiTronix** [comment]
@imranilyas Bug in FFmpeg, see Issue https://github.com/abhiTronix/vidgear/issues/133. Being worked on in issue #160

**Comment by imranilyas** [comment]
This is what comes up when I run print(cv2.getBuildInformation())
Since GStreamer isn't available, what can I use as a substitute for the
backend parameter in the CamGear function?

Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.54.100)
      avformat:                  YES (58.29.100)
      avutil:                    YES (56.31.100)
      swscale:                   YES (5.5.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      NO

**Comment by abhiTronix** [comment]
> Since GStreamer isn't available, what can I use as a substitute for the
backend parameter in the CamGear function?

@imranilyas Nothing else works for now, you have to wait for #160 to be resolved.
