### ISSUE TITLE
its not working with OpenCV 4.3.0

### ISSUE THREAD

**Issue by masterchop** [abhiTronix/vidgear#163]
I get this error:

   "[Vidgear:ERROR] :: Installed OpenCV API version(< 3.0) is not supported!"
ImportError: [Vidgear:ERROR] :: Installed OpenCV API version(< 3.0) is not supported!

but i am working with OpenCV 4.3.0

**Comment by abhiTronix** [comment]
> I get this error:
> 
> "[Vidgear:ERROR] :: Installed OpenCV API version(< 3.0) is not supported!"
> ImportError: [Vidgear:ERROR] :: Installed OpenCV API version(< 3.0) is not supported!

@masterchop **Not enough information**,  I need the complete terminal log from from machine. Also, I need to know the OS,  vidgear and python version you're working on.


> but i am working with OpenCV 4.3.0

@masterchop **No, It means it is using old copies of OpenCV binaries on your system. It is certainly not v4.3.0,and to confirm that, add following lines to your python script:**

```python
import cv2
print( print(cv2.__version__)
```

**run it, and then paste the terminal output here.**

**Comment by abhiTronix** [comment]
Also it is working fine on CI tests https://travis-ci.com/github/abhiTronix/vidgear/jobs/379911391#L5339 and https://ci.appveyor.com/project/abhiTronix/vidgear/build/job/803n5a5qwci8bm9v?fullLog=true#L48, so problem is obiously on your end only.
