### ISSUE TITLE
vidgear on a headless jupyter notebook - saving output with writegear

### ISSUE THREAD

**Issue by timoburmeister** [abhiTronix/vidgear#167]
Hi guys,

thanks for this amazing library.

I have two issues which I can't get figured out.

Since I'm working on a IBM Watson jupyter notebook environment it's necessary to use openvc in headless mode so I can avoid a libgl ImportError due to the missing GUI.
Furtermore, I cannot use cv2.imShow due to that headless env.
That's why I use matplotlib to show the frame. My issues here are first that the imshow does not stop (due to the fact that I cannot push any button due to the missing GUI), and second that I can't get the writegear to save the output. While I'm in a notebook env I guess I have to save the file to my local desktop or something?

Any help or hint would be appreciated!

```python
from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import matplotlib.pyplot as plt
import cv2

stream = CamGear(source='https://www.youtube.com/watch?v=tFq6Q_muwG0', y_tube=True, logging=True).start() 


output_params = {"-input_framerate":stream.framerate}

writer = WriteGear(output_filename = 'Output.mp4', **output_params, compression_mode=True)


while True:


    frame = stream.read()

    if frame is None:
        break
    
    start_point = (30, 25) 
    end_point = (400, 400) 
    color = (255, 0, 0) 
    thickness = 10
    img = cv2.rectangle(frame, start_point, end_point, color, thickness) 
    
    plt.imshow(img) 
    plt.show()
    
    

    writer.write(img)


cv2.destroyAllWindows()


stream.stop()


writer.close()
```

**Comment by abhiTronix** [comment]
> Furtermore, I cannot use cv2.imShow due to that headless env.
> That's why I use matplotlib to show the frame. My issues here are first that the imshow does not stop (due to the fact that I cannot push any button due to the missing GUI),

@timoburmeister Is it necessary to `imshow()` for your application? If not, just drop it.

> second that I can't get the writegear to save the output. While I'm in a notebook env I guess I have to save the file to my local desktop or something?

Path with not work in an notebook environment. You have to provide full-path to the directory you want to save your output to. So it you want to store it to home directory, then you have to do as follows:

```python
from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import cv2

stream = CamGear(source='https://www.youtube.com/watch?v=tFq6Q_muwG0', y_tube=True, logging=True).start() 
writer = WriteGear(output_filename = '/home/<your username>/Output.mp4', logging=True) # change <your username> with yours

while True:
    frame = stream.read()
    if frame is None:
        break
    start_point = (30, 25) 
    end_point = (400, 400) 
    color = (255, 0, 0) 
    thickness = 10
    img = cv2.rectangle(frame, start_point, end_point, color, thickness) 
    writer.write(img)

stream.stop()
writer.close()
```
This is a bare-minimum python example you need write. Goodluck and Share your result here.

**Comment by abhiTronix** [comment]
@timoburmeister Also, YouTube Mode (`y_tube=True`) will not work as the dependency `youtube-dl` is now removed due to a DMCA. **See issue #166** . Therefore use a video source (file or webcam) instead of this.
