### ISSUE TITLE
still got ModuleNotFoundError

### ISSUE THREAD

**Issue by kamarisoim** [abhiTronix/vidgear#174]
File "D:\workspace\ripcio.prj\testarea\vidgear.py", line 6, in <module>
    from vidgear.gears import CamGear
ModuleNotFoundError: No module named 'vidgear.gears'; 'vidgear' is not a package

I've tried everything........

**Comment by kamarisoim** [comment]
Sorry...settled...I used vidgear.py for my filename
change to vdg.py ....then everything OK
Thank you

**Comment by abhiTronix** [comment]
**@kamarisoim There's already similar issue #140 & #150 that are resolved. Kindly search previous issues before opening a new one.**
