### ISSUE TITLE
Utilizing Cuda cores for frame stabilization

### ISSUE THREAD

**Issue by Nizcik** [abhiTronix/vidgear#175]
As the frame size is increased  - Stabilization starts to experience delay.  This possibly could be improved by utilizing Cuda cores of Nvidia GPUs

## Detailed Description
I have performed stabilization tests on live-feed with different resolutions and noticed that low resolution frames get processed smoothly even if the CPU (Ryzen 3600) has high utilization. When the resolution is increased to 720p Stabilized image starts to lag behind causing audio sync issues and the video skips frames as the delay grows too large.  Even when CPU load is reduced the stabilized feed might lag. 

### Context
Ability to handle 720p live-content with stabilizer would be great as current software in most mobile phones does not allow to use built-in stabilization. Many live streamers would benefit if a moderate gaming system would be capable of stabilizing at least 720p video feed smoothly.

### Your Current Environment

* VidGear version:  0.1.9
* Branch: Development
* Python version:  3.9.0
* Operating System and version: Windows 10 2004
CPU: Ryzen 3600
GPU: Geforce 1070TI

### Any Other Important Information

Video demonstrating the behavior with time stamps.

https://youtu.be/ysvaSvLdjLE

**Comment by abhiTronix** [comment]
@Nizcik Can you provide raw un-stablized 720p footage here directly _(GitHub comments now support video attachments)_ or YouTube or else way. I need to run some tests.

**Comment by Nizcik** [comment]
@abhiTronix Here you go. There was limit of 10mb uploading directly to github

https://mega.nz/folder/GARTySKI#i1Vm6HKB92AlLSzWJW-T0g

1080p footage was also 5 minutes, but it got very laggy at the end so I cut that to 1 minute. Let me know if you need more footage or if this is not good enough.

Happy new year!

**Comment by abhiTronix** [comment]
@Nizcik Could perform same test as before .i.e.  [Video demonstrating the behavior with time stamps](https://youtu.be/ysvaSvLdjLE) by installing latest vidgear that uses experimental `Queue` instead of `deques`, and see if this made any difference. You can install latest vidgear development branch as follows:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest development branch
  git checkout development

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```

After installation run those test with `720p` video input. Thanks in Advance.

**Comment by abhiTronix** [comment]
@Nizcik Any updates on this?

**Comment by Nizcik** [comment]
Sorry, I noticed your message only now. I made a quick test and it seemed that there is slight improvement. Still now when I loaded the cpu a bit more I experienced a lag. However with light CPU usage 720p 30fps seemed to stabilize in real time. 

I will try to do a longer field test tomorrow and let you know.

Just a note, I experimented with lower resolutions also earlier and I got lag even with lowest resolutions then after maybe 10 minutes or so, and suddenly stabilization processing slowed down.

Anyways - Ill test this more.

**Comment by abhiTronix** [comment]
> Still now when I loaded the cpu a bit more I experienced a lag.

@Nizcik CamGear now utilizes all CPU cores with this queue approach. That's why it is hanging a bit. I'll advise to remove 
```python 
    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break
```

from your code to improve performance significantly.

> Just a note, I experimented with lower resolutions also earlier and I got lag even with lowest resolutions then after maybe 10 minutes or so, and suddenly stabilization processing slowed down.

Did you checked the CPU utilization? Add a [CPU widget if on Windows 10](https://www.microsoft.com/en-in/p/widget-launcher/9wzdncrdqfbt?activetab=pivot:overviewtab), and a [GPU monitor](https://blogs.windows.com/windowsexperience/2013/08/01/monitor-your-gpu-on-windows-with-gpu-z-by-techpowerup/) to see both CPU an GPU usage in real-time.

**Comment by abhiTronix** [comment]
@Nizcik Any updates on this?

**Comment by abhiTronix** [comment]
@Nizcik I'll just call it a day till my college is over, I just tested [cupy](https://github.com/cupy/cupy) and it sorta works on my AMD setup but I need a proper NVIDIA hardware to test it performance which I'll be purchasing at sometime in 2022. So stay tuned for any future updates.
