### ISSUE TITLE
vidgear write mjpeg insted of hevc

### ISSUE THREAD

**Issue by hfmsite** [abhiTronix/vidgear#176]
I replace my opencv videoWriter with vidgear.
a lot of time it realy encode with hevc but few time it encode as mjpeg (70mb for 5 sec of video - 720P)

version 0.1.9

why it happend?

the code I used:
```
from vidgear.gears import WriteGear

output_params = {'-vcodec': 'h264_nvenc', "-b": "2500k","-input_framerate": 24.0} 

out = WriteGear(output_filename =  files_dict[file_point]["output_filename"] + ".mp4", compression_mode = True, logging = True, **output_params)

out.write(image)

out.close()

```

**Comment by abhiTronix** [comment]
> I replace my opencv videoWriter with vidgear.
> a lot of time it realy encode with hevc but few time it encode as mjpeg (70mb for 5 sec of video - 720P)
> 
> version 0.1.9
> 
> why it happend?

@hfmsite This is incomplete. I need one terminal log from each situation when "it encode as mjpeg" and "it worked normally". Only then anyone can see what is happening.

> from vidgear.gears import WriteGear
> 
> output_params = {'-vcodec': 'h264_nvenc', "-b": "2500k","-input_framerate": 24.0} 
> 
> out = WriteGear(output_filename =  files_dict[file_point]["output_filename"] + ".mp4", compression_mode = True, logging = True, **output_params)
> 
> out.write(image)
> 
> out.close()

This also incomplete, I at least need to what source your using for frames, and why `"-b": "2500k"` why you choose that. Also,  what's the value of `file_dict` and other values in  `files_dict[file_point]["output_filename"] + ".mp4"`. To make any assumption.

Finally, It is always advised to atleast run a bare minimum example (with `h264_nvenc` in your case) given in the docs to be sure, that this isn't Coding Fault before opening any issue.

**Comment by hfmsite** [comment]
first thank's for the answer.
(as you understand English isnt my native language).

> Finally, It is always advised to atleast run a bare minimum example (with h264_nvenc in your case) given in the docs to be sure, that this isn't Coding Fault before opening any issue.

I try the h264_nvenc - with vidgear - for same task in bare minimum - it work - (give me around 2-2.5 MB file.)

for the input I use FHD video file that I get from other source - open it with regular opencv VideoCapture 

the: "files_dict[file_point]["output_filename"] + ".mp4"" isn't very importent it just give a filename.

my wanted result is - file with smaller size with close quality 
(the opencv FOURCC - H264 give me 9MB for 170 frames - 5-7 sec)

I ask and open an issue becouse the resualt of the vidgear WriteGear wasn't consistency - 80% I get my wanted resault(2-3mb file) - for 15-20% I get an 70mb~ file. - when i open the 70mb file in vlc - and open "media info" it show that it was encode as MJPEG.

**Comment by abhiTronix** [comment]
>  (as you understand English isnt my native language).

@hfmsite Same here buddy., English is not my native language too. But as a programmer, I can understand what other is saying by looking at the code or if adequate information is provided. Being said that you can use Google translator to interpret what I'm saying anytime.

> @hfmsite This is incomplete. I need one terminal log(logging = True) from each situation, i.e. when "it encode as mjpeg" and "it worked normally". Only then anyone(including me) can debug what is happening/wrong.

**I asked for this above, but you didn't provided it in your comment, so it difficult to debug the problem. I need terminal log to see what is causing it. Kindly provide one terminal log (i.e. set `logging = True` in WriteGear) from each situation, i.e. when "it encode as mjpeg" and "it worked normally" and paste it here in comment .**


> I ask and open an issue becouse the resualt of the vidgear WriteGear wasn't consistency - 80% I get my wanted resault(2-3mb file) - for 15-20% I get an 70mb~ file. - when i open the 70mb file in vlc - and open "media info" it show that it was encode as MJPEG.

Yes, you can open the issue for this behaviour. But I pretty sure it is a coding error. **If you can provide compete code, I can solve it in second.**

**Comment by hfmsite** [comment]
hello again.
first  - the full code - is very complicated and very long - this file only have more then 1500 lines - and it include other file
with lot of dependencies.
so - the full code, isnt relevant.
the logging is on - but because it have flask turn on - all the std-out doesnt show.
can the vidgear write the log to a file? - so i can add here the full vidgear logs.

**Comment by abhiTronix** [comment]
> first - the full code - is very complicated and very long - this file only have more then 1500 lines - and it include other file
> with lot of dependencies.
> so - the full code, isnt relevant.

This is the most riduclous thing i ever hear. What do you mean by complex code? I have 10000+ lines of code in this repo. This is utter non-sense.

>  the logging is on - but because it have flask turn on - all the std-out doesnt show.

@hfmsite You can easily enable logging inside flask. You're just being ignorant.


 I'm closing this issue now. Provide any relevant data/log to prove this issue.
