### ISSUE TITLE
Is writing video clips with variable frame rate possible with vidgear?

### ISSUE THREAD

**Issue by bml1g12** [abhiTronix/vidgear#177]
Just wondering if it is possible to write video clips with variable frame rate if one knows the time interval between each frame when the input is numpy arrays? 

Thanks!

**Comment by abhiTronix** [comment]
> Just wondering if it is possible to write video clips with variable frame rate if one knows the time interval between each frame when the input is numpy arrays?

@bml1g12 If you can do that with `FFmpeg`. Then answer is yes otherwise no.
