### ISSUE TITLE
VidGear with v4l2loopback

### ISSUE THREAD

**Issue by wpcasarin** [abhiTronix/vidgear#178]
Is possible to use the module with `v4l2loopback`? I've working for a while without success, I'm trying to send the `NetGear` output trough `ffmpeg` with the `tcp` protocol but without success. Would be nice if the somehow the module had the capability to write strait to the `v4l2loopback` devices. Anyway the `vidgear` is simplifying thing a lot, thank you for the hard work.

**Comment by abhiTronix** [comment]
> Is possible to use the module with v4l2loopback?

@wpcasarin Yes, you can easily with [WriteGear API's Compression Mode](https://abhitronix.github.io/vidgear/gears/writegear/compression/overview/) with `FFmpeg` backend, that supports URLs. See an twitch example [here](https://github.com/abhiTronix/vidgear/issues/144#issuecomment-657985607) and convert it according to your need for `v4l2loopback`.
