### ISSUE TITLE
How use vidgear django and build docker image?

### ISSUE THREAD

**Issue by esmaily** [abhiTronix/vidgear#185]
# I'm using django with docker for project but when add vidgear and opencv-python in requirments.txt file when
build image occer this error 

![opencv-python erorr](https://www.mediafire.com/convkey/e23c/iihrkfnus4dkf1ozg.jpg)
 ![vidgear error ](https://www.mediafire.com/convkey/0009/vdz5b53iqg59ficzg.jpg)

### My Environment
* VidGear version: 0.1.9
* django:3.1.4
* pytz:2020.4
* Python version: 3.9.1 or 3.8.3
* PiP version: 20.3
* Operating System and version: python:3.9.1-alpine or python:3.8.3-alpine

**note: testing with python3.7,3.8 and 3.9 but again this error occering**

**Comment by abhiTronix** [comment]
@esmaily Alpine is not manylinux1-compatible, so any package containing C extensions must be built from source. This means you have to install the build tools first. Also use alpine image instead of  `python:3.9.1-alpine` or `python:3.8.3-alpine`:

```sh
FROM alpine:edge

RUN apk update && apk add build-base libzmq musl-dev python3 python3-dev zeromq-dev

RUN pip3 install vidgear

CMD ["/bin/sh"]
```

**Comment by esmaily** [comment]
thank you solved
