### ISSUE TITLE
conflict between opencv3 and opencv4? no attribute 'y_tube'

### ISSUE THREAD

**Issue by rapierbit** [abhiTronix/vidgear#189]
Not sure this is a bug, hence filing as a question.

I'm very new to vidgear but I have gotten it to work in a very specific circumstance for a root user, but not for a non-root user. I'm trying to use your [baseline example](https://stackoverflow.com/questions/37555195/is-it-possible-to-stream-video-from-https-e-g-youtube-into-python-with-ope/55937170#55937170) to stream from youtube using Raspberry Pi.

If I am logged on as pi (the root user), and install opencv and vidgear as follows, the baseline example **just works**:
sudo apt-get install python3-opencv (installs opencv-3.2.0+dfsg-6)
pip3 install vidgear (installs vidgear-0.2.0) 

Issue: I want to get this working for a non-root user on the RPi. For this circumstance, I'm trying to use pip3 alone to install opencv and vidgear; however, **pip3 install opencv-python** installs opencv-4.4.0.46 (in contrast to what I get with **apt-get install**). under this circumstance, I get this error:

`01:34:30 :: Helper :: ERROR :: module 'cv2.cv2' has no attribute 'y_tube'
Traceback (most recent call last):
  File "/home/3user1/.local/lib/python3.7/site-packages/vidgear/gears/helper.py", line 450, in capPropId
    integer_value = getattr(cv2, property)
AttributeError: module 'cv2.cv2' has no attribute 'y_tube'
01:34:30 :: Helper :: CRITICAL :: `y_tube` is not a valid OpenCV property!
Traceback (most recent call last):
  File "./stream.py", line 8, in <module>
    stream = CamGear(source='https://youtu.be/dQw4w9WgXcQ', y_tube =True).start() # YouTube Video URL as input
  File "/home/3user1/.local/lib/python3.7/site-packages/vidgear/gears/camgear.py", line 311, in __init__
    "[CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!"
RuntimeError: [CamGear:ERROR] :: Source is invalid, CamGear failed to intitialize stream on this source!`

Is this an opencv issue, or does it have something to do with vidgear? If it's not vidgear, why does vidgear appear to work under root with opencv3 and not under root with opencv4? I admit I'm a little new to the differences between pip3 and sudo apt-get install. I usually work as root only on RPi but I have a need to run this as an unprivileged user. I tried forcing the install of opencv v3 with pip 3, but the earliest version I could find is 3.4.2.16.

Any tips would be appreciated. 

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [ ] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Your Environment

* VidGear version: 0.2.0
* Branch: ?
* Python version: 3.7.3
* PiP version: 18.1
* Operating System and version: 8-20 Buster

**Comment by abhiTronix** [comment]
`y_tube` has been changed to `stream_mode` in latest `v0.2.0`, see [CamGear Docs Example](https://abhitronix.github.io/vidgear/latest/gears/camgear/usage/#using-camgear-with-youtube-videos).

**Comment by abhiTronix** [comment]
@rapierbit Thanks, Stackoverflow example updated too.
