### ISSUE TITLE
Writegear - use hardware encoder

### ISSUE THREAD

**Issue by mj43** [abhiTronix/vidgear#19]
Writegear uses libx264 or libx265 encoders. Is it possible to make use of existing hardware encoders - for example on an Intel CPU the h264_vaapi encoder. I ask as using libx264 my CPU is saturating and the output video is dropping frames. In tests I have done outside of Writegear, using the h264_vaapi encoder significantly reduces the CPU load.

**Comment by abhiTronix** [comment]
@mj43 

>  Writegear uses libx264 or libx265 encoders.

**No you are wrong, WriteGear is just a wrapper around FFmpeg library. It DOES NOT exclusively use any libx264 or libx265 encoders, but use them only as fallback encoders when no `-vcodec` parameter is passed in [output_param](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#1-usage) dict.**

> Is it possible to make use of existing hardware encoders - for example on an Intel CPU the h264_vaapi encoder.

**The solution is right there in [docs](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#output-parameterscompression-mode-only), kindly go through it.** _Changing codec is a piece of cake in VidGear, just pass the encoder `-vcodec:h264_vaapi` in [output_param](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#1-usage) dict in WriteGear class. Also you can specify the device/harware to be used with `'-vaapi_device':'/dev/dri/renderD128'`or other features such as `'-vf':'format=nv12,hwupload'` in output_param dict. You can easily find such options in [FFmpeg docs](https://trac.ffmpeg.org/wiki/Hardware/VAAPI) easily._ **But first remember to check if your FFmpeg supports VAAPI encoders as below.**

### Important :warning:
Kindly first confirm that your FFmpeg support VAAPI encoders, with command as follows:
```sh
ffmpeg  -hide_banner -encoders | grep vaapi 

 V..... h264_vaapi           H.264/AVC (VAAPI) (codec h264)
 V..... hevc_vaapi           H.265/HEVC (VAAPI) (codec hevc)
 V..... mjpeg_vaapi          MJPEG (VAAPI) (codec mjpeg)
 V..... mpeg2_vaapi          MPEG-2 (VAAPI) (codec mpeg2video)
 V..... vp8_vaapi            VP8 (VAAPI) (codec vp8)
```

**Finally, Remember You can alter almost any parameter that is supported by FFmpeg itself with vidgear library!**

**Comment by mj43** [comment]
Many thanks for this guidance.
