### ISSUE TITLE
Small error in documentation of NetGear

### ISSUE THREAD

**Issue by orpinchasov** [abhiTronix/vidgear#190]
In NetGear's documentation page in the primary modes of operations section:
https://abhitronix.github.io/vidgear/latest/gears/netgear/overview/#primary-modes

it says that the user should set receive_mode to True in both sections. I guess it should be False for send mode.

**Comment by abhiTronix** [comment]
Thanks, but for next time please reach us through our [Gitter Community channel](https://gitter.im/vidgear/community) for submitting any typos. More information can be found in [Submission Contexts](https://abhitronix.github.io/vidgear/contribution/#submission-contexts)

**Comment by orpinchasov** [comment]
Right, sorry.

**Comment by abhiTronix** [comment]
**Successfully resolved in commit https://github.com/abhiTronix/vidgear/commit/a35c5a6d77bd2d1b12733e135c9b6127f8e880a1**
