### ISSUE TITLE
How can i ues it in deeplearning?

### ISSUE THREAD

**Issue by morestart** [abhiTronix/vidgear#193]
when i use this project in my dl project, the rtsp strame tape casting time is high... And it also jumps frames.

**Comment by abhiTronix** [comment]
> when i use this project in my dl project, the rtsp strame tape casting time is high... And it also jumps frames.

@morestart No proper context, no example code, or understandable argument provided. Kindly reedit this issue and provide relevant information, or else this issue will be closed and marked invalid.

**Comment by abhiTronix** [comment]
**I'm closing this issue now. Provide any relevant data/log to prove this issue.**

**Comment by morestart** [comment]
thanks, i write a video process program by myself
