### ISSUE TITLE
StreamGear Keeps Buffering

### ISSUE THREAD

**Issue by arcphysx** [abhiTronix/vidgear#200]
I have a problem with the StreamGear API, when I access the stream output using Clappr and dash-shaka-playback plugin, at first the stream goes fine, but after a few minutes the player (Clappr) buffers indefinitely unless I refresh the page, but after a few minutes it'll happen again

Here's the screenshot
![1614240936816](https://user-images.githubusercontent.com/39365378/109244685-b4524600-7811-11eb-8892-9a634775befd.jpg)

And here's my console output
![Screenshot from 2021-02-25 15-20-19](https://user-images.githubusercontent.com/39365378/109244783-e8c60200-7811-11eb-8a5d-53dadd4505c0.png)

**Comment by abhiTronix** [comment]
@arcphysx No related to StreamGear, See Clappr configurations like [`rebufferingGoal`](https://shaka-player-demo.appspot.com/docs/api/tutorial-network-and-buffering-config.html) and also, verify you're using it correctly: https://github.com/clappr/clappr/issues/1239
