### ISSUE TITLE
Multiple "-f" formats not working

### ISSUE THREAD

**Issue by albertfaromatics** [abhiTronix/vidgear#201]
## Description
I'm trying to create a program that reads from another program that retrieves frames from a ML application and from a USB microphone, merge frames+audio, and stream it using mpeg1video and mpegts output format to a local http server to display.

I can do it from the command line directly from the webcam using ffmpeg:

`ffmpeg -f alsa -ac 1 -ar 48000 -i plug:dsnoopUSB -f v4l2 -i /dev/video8 -f mpegts -vcodec mpeg1video http://address:port/id`

I'm trying to reproduce it using vidgear and frame by frame, but I'm not able to achieve it. As I need 2 "-f" parameters, I'm trying to use the "-clones" param but it simply fails.

### Acknowledgment

- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [X] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version: 0.2.0
* Branch: PyPi
* Python version: 3.7.3
* PiP version: 18.1
* Operating System and version: Raspberry Pi 4 Raspbian OS 

### Expected Behavior

I expect for the audio and frames to be merged in one stream

### Actual Behavior

If I set all the parameters  with "-clones" as: 
```
output_params = {
            "-clones": ["-f", "mpegts", "-f", "alsa"],
            "-ac": "1",
            "-ar": "48000",
            "-i": "plug:dsnoopUSB",
            "-vcodec": "mpeg1video"
        }
```

The input microphone is not found, as "alsa" is not parsed. If I use:
```
output_params = {
            "-f": "alsa",
            "-ac": "1",
            "-ar": "48000",
            "-i": "plug:dsnoopUSB",
            "-vcodec": "mpeg1video"
        }
```

I'm getting this error

`ffmpeg unable to find suitable output format`

As the output format is not being set.

And if I add two "-f", one of them is overwritter as it is a dictionary.

### Possible Fix

Maybe "-f" is not differentiated between input and output?

### Steps to reproduce

A bit tricky, as the output needs to point to an HTTP server running ffmpeg to receive the data. I cannot change this, at least not for now as it's not something I've created.

**Comment by abhiTronix** [comment]
@albertfaromatics Ok your command is little complicated, so you need to be little creative to use it. Try this:

```python3
output_params = {
    "-i": "plug:dsnoopUSB",
    "-f": "alsa",
    "-ac": "1",
    "-ar": "48000",
    "-clones": ["-vcodec", "mpeg1video", "-f", "mpegts"],
}
```
and see if this work. Goodluck.

**Comment by abhiTronix** [comment]
**Closed. Please reopen if issue still persists or provided solution doesn't works.**
