### ISSUE TITLE
Creating segments (separate files) with WriteGear

### ISSUE THREAD

**Issue by FraBle** [abhiTronix/vidgear#205]
## Question

FFmpeg has the concept of [segments](https://ffmpeg.org/ffmpeg-formats.html#segment_002c-stream_005fsegment_002c-ssegment) to create separate files from a video stream. The following code, for example, records a `mjpeg` stream, converts it to `H.264` using `libx264`, and saves it as files with ~5sec length named `output000.mp4`, `output001.mp4`,...

```bash
ffmpeg \
-f mjpeg \
-r 24 \
-i "http://someurl/stream" \
-c:v libx264 \
-segment_time 5 \
-reset_timestamps 1 \
-r 24 \
-f segment output%03d.mp4
```

How would I achieve something similar with `WriteGear`?
(I've got the stream receiving pieces in place using VideoGear based on the excellent documentation)

Current `WriteGear` initialization code:

```python
ffmpeg_options = {
    '-vcodec': 'libx264',
    '-preset': 'fast',
    '-tune': 'zerolatency',
    '-input_framerate': 24,
    '-r': 24,
    '-pix_fmt': 'yuv420p',
}
writer = WriteGear(
    output_filename='output.mp4',
    logging=True,
    **ffmpeg_options,
)
```

### Acknowledgment
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Context

I'm trying to reproduce the FFmpeg snippet from above, but want to add some extra content to the frames using OpenCV (hence trying it with `VideoGear` + `WriteGear`)

### Your Environment

* VidGear version: `0.2.0`
* Branch: `Master`
* Python version: `3.7.10`
* PiP version: `21.0.1`
* Operating System and version: `MacBook Pro (13-inch, 2017) with macOS Big Sur 11.2.3`

**Comment by abhiTronix** [comment]
Hey @FraBle, Actually it is actually quite simple. But i'll advise that you first install latest testing branch that include some critical  latest patches for WriteGear API as follows:
```sh 
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout testing

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```

and than use this python code:

```python
# import required libraries
from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import cv2

# Open any video source `foo.mp4`
stream = CamGear(
    source="foo.mp4", logging=True
).start()

# define required FFmpeg optimizing parameters for your writer
output_params = {
    "-c:v": "libx264",
    "-crf": 22,
    "-map": 0,
    "-segment_time": 9,
    "-g": 9,
    "-sc_threshold": 0,
    "-force_key_frames": "expr:gte(t,n_forced*9)",
    "-clones": ["-f", "segment"],
}

# Define writer with defined parameters and
writer = WriteGear(output_filename="output%03d.mp4", logging=True, **output_params)

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # write frame to writer
    writer.write(frame)

    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()

# safely close writer
writer.close()
```

Also,  next time please reach us through our [Gitter Community channel](https://gitter.im/vidgear/community) for asking any usage questions. Have a nice day.

**Comment by FraBle** [comment]
@abhiTronix You're a lifesaver! That was exactly what I was looking for! Next coffee is on me!

**Comment by abhiTronix** [comment]
@FraBle Thank you for the donation. Much appreciated.
