### ISSUE TITLE
Live passthrough with audio

### ISSUE THREAD

**Issue by LosTigeros** [abhiTronix/vidgear#209]
## Question

Would it be possible in future to process live streams with the help of VideoGear to stabilize it and output a stream with WriteGear which would have the audio from incoming source?

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Context

I just want to process the incoming stream and output a stabilized video with synced audio from same source.

Here is the code I have now
```py
# Import libraries
from vidgear.gears import VideoGear
from vidgear.gears import WriteGear
import cv2
import signal

# Formatting / additional parameters
options = {
  "SMOOTHING_RADIUS": 20, # Smooth by 20 pixels
  "BORDER_SIZE": 0, # Set the border for cropping
  "CROP_N_ZOOM": False, # Crop and zoom
  "CAP_PROP_FRAME_WIDTH": 1280, # Width of the frames
  "CAP_PROP_FRAME_HEIGHT": 720, # Height of the frames
  "CAP_PROP_FPS": 30, # 30 FPS
  "THREADED_QUEUE_MODE": True # Threaded queue mode
}

# Open video source
stream = VideoGear(
  source="rtmp://xyz.abc/def/ghi",
  backend=cv2.CAP_FFMPEG,
  stabilize=True,
  logging=True,
  **options
).start()

# Set the output params for local rtmp stream
output_params = {
  "-listen": "1",
  "-vcodec": "libx264",
  "-tune": "zerolatency",
  "-profile:v": "main",
  "-pix_fmt": "yuv420p",
  "-preset:v": "veryfast",
  "-g": 30,
  "-b:v": "4000k",
  "-maxrate": "10000k",
  "-bufsize": "10000k",
  "-f": "flv"
}

writer = WriteGear("rtmp://localhost:1935", logging=True, **output_params)

# Set signal handler because KeyboardInterrupt doesn't fire in every situation it should.
signal.signal(signal.SIGINT, signal.default_int_handler)

while True:
  try:
    # Read frame from the stream
    frame = stream.read()

    # Skip if there's no frame
    if frame is None:
      break

    # Write frame to local stream
    writer.write(frame)
  except KeyboardInterrupt:
    # Gracefully shutdown when CTRL+C
    break

# Stop everything and clear resources
stream.stop()
writer.close()
```

### Your Environment

* VidGear version: 0.2.1
* Branch: PyPi
* Python version: 3.9.4
* PiP version: 21.1
* Operating System and version: Windows 10 20H2

**Comment by abhiTronix** [comment]
@LosTigeros This Feature needs #148 to be resolved first to have full control over media stream, which will probably happen in the next version. Please subscribe/watch the repository to receive updated related to it. Also any PR related to #148 is welcomed.

**Comment by abhiTronix** [comment]
@LosTigeros This is solved. 

#### Example is provided in docs: https://abhitronix.github.io/vidgear/latest/help/stabilizer_ex/#saving-stabilizer-class-output-with-live-audio-input

**Comment by LosTigeros** [comment]
Woah, that's really nice! Will it work with live streams though?
In the example I can see you've used another input with audio device coming from the webcam, in a live stream it'd be ideal to have only one input. Should it be split up in some way?

**Comment by abhiTronix** [comment]
ill it work with live streams though?
In the example I can see you've used another input with audio device coming from the webcam, in a live stream it'd be ideal to have only one input. Should it be split up in some way?

@LosTigeros Yes you can use video itself as audio source in FFmpeg. So it is definitely possible.

**Comment by abhiTronix** [comment]
@LosTigeros Here's your example: https://abhitronix.github.io/vidgear/v0.2.4-dev/help/videogear_ex/#using-videogear-for-real-time-stabilization-with-audio-encoding .Good luck!

**Comment by LosTigeros** [comment]
Hey.

Yeah this example will work with files but with live streams there are problems either with audio being cut/silent for some time, video/audio not synced, stabilization not being smooth.

I've checked the output encoding speed because I thought maybe it's because encoding is too slow but the speed is 1x on it.
`frame=  610 fps= 25 q=20.0 Lsize=   16183kB time=00:00:24.40 bitrate=5432.0kbits/s speed=   1x`

It could be because the stream is being downloaded twice (once by VideoGear and once by WriteGear) but I can't prove it.

Nevertheless thanks for the help.

**Comment by abhiTronix** [comment]
@LosTigeros Oh ok, you need to stabilize livestream, and yeah that isn't possible in current scenario since, audio is been streamed at must faster pace then video frames itself. If you need consistent results then you need to download video locally before using it in this example. Being said that, Livestreams can only be possible if we have #148 resolved.

**Comment by abhiTronix** [comment]
@LosTigeros Also, Can I see the complete terminal logs? I think something is off with your log.

**Comment by LosTigeros** [comment]
Script:
```python
# import required libraries
from vidgear.gears import WriteGear
from vidgear.gears import VideoGear
import cv2

# Give suitable video file path to be stabilized
unstablized_videofile = "rtmp://localhost:1935/publish/live"

# Formatting / additional parameters
options = {
  "SMOOTHING_RADIUS": 20, # Smooth by 20 pixels
}

# open any valid video path with stabilization enabled(`stabilize = True`)
stream_stab = VideoGear(
  source=unstablized_videofile,
	stabilize=True,
	logging=True,
	**options,
).start()

# define required FFmpeg optimizing parameters for your writer
output_params = {
  "-i": unstablized_videofile,
  "-c:a": "aac",
  "-input_framerate": stream_stab.framerate,
  "-clones": ["-shortest"],
  "-preset": "veryfast",
  # !!! Uncomment following line if video duration is too short(<60sec). !!!
  #"-disable_force_termination": True,
}

# Define writer with defined parameters and suitable output filename for e.g. `Output.mp4
writer = WriteGear(output_filename="Output.flv", logging=True, **output_params)

# loop over
while True:
  try:
    # read frames from stream
    frame_stab = stream_stab.read()

    # check for frame if not grabbed
    if frame_stab is None:
      break

    # {do something with the stabilized frame here}

    # write stabilized frame to writer
    writer.write(frame_stab)	
  except KeyboardInterrupt:
    # Gracefully shutdown when CTRL+C
    break

# safely close streams
stream_stab.stop()

# safely close writer
writer.close()
```

[logs.txt](https://github.com/abhiTronix/vidgear/files/7454016/logs.txt)

**Comment by LosTigeros** [comment]
Sure, here are 3 files:

- [AT-cm_1240377008.mp4](https://s.lostigeros.dev/vidgear/AT-cm_1240377008.mp4) - this file is streamed in loop with obs to local rtmp with NVENC and 4000Kbps bitrate (it's a little stabilized but still has small amount of shake)
- [Output-without-change.flv](https://s.lostigeros.dev/vidgear/Output-without-change.flv) - output of the script I posted in previous comment
- [Output-uncommented-force-commended-clones.flv](https://s.lostigeros.dev/vidgear/Output-uncommented-force-commended-clones.flv) - output with uncommented `"-disable_force_termination": True,` and commented `"-clones": ["-shortest"],`

**Comment by abhiTronix** [comment]
> output_filename="Output.flv",

@LosTigeros Why are you using flv? Also, default WriteGear's encoder(H.264 encoder) is not suitable for flv formats.

> # Formatting / additional parameters
options = {
  "SMOOTHING_RADIUS": 20, # Smooth by 20 pixels
}

Why lowering value? It worsen the stabilization performance. If it is to reduce latency then it won't make much difference as compared to 30.

**Comment by abhiTronix** [comment]
@LosTigeros I tested this code on Windows and it worked fine:

```python
# import required libraries
from vidgear.gears import WriteGear
from vidgear.gears import VideoGear
import cv2

# Give suitable video file path to be stabilized
unstablized_videofile = "http://www.liushuaicheng.org/CVPR2014/data/limitation3.avi"

# open any valid video path with stabilization enabled(`stabilize = True`)
stream_stab = VideoGear(
    source=unstablized_videofile,
    stabilize=True,
    logging=True,
).start()

# define required FFmpeg optimizing parameters for your writer
output_params = {
    "-i": unstablized_videofile,
    "-c:a": "aac",
    "-input_framerate": stream_stab.framerate,
    "-clones": ["-shortest"],
    # !!! Uncomment following line if video duration is too short(<60sec). !!!
    "-disable_force_termination": True,
}

# Define writer with defined parameters and suitable output filename for e.g. `Output.mp4
writer = WriteGear(output_filename="Output.mp4", logging=True, **output_params)

# loop over
while True:
    try:
        # read frames from stream
        frame_stab = stream_stab.read()

        # check for frame if not grabbed
        if frame_stab is None:
            break

        # {do something with the stabilized frame here}

        # write stabilized frame to writer
        writer.write(frame_stab)
    except KeyboardInterrupt:
        # Gracefully shutdown when CTRL+C
        break

# safely close streams
stream_stab.stop()

# safely close writer
writer.close()
```

### Input:

Here is input:
http://www.liushuaicheng.org/CVPR2014/data/limitation3.avi

### Output:

And here is output:

https://user-images.githubusercontent.com/34266896/139700329-b143bae4-6235-4f18-ace2-16154ba91f95.mp4

**Comment by LosTigeros** [comment]
`Why are you using flv?` so I can preview the file while it's being generated, on .mp4 container it just doesn't play until I stop the processing.

`Why lowering value?` Because once I zoom into the image to hide black bars I still want to have some fov (this isn't final decision).

**Comment by abhiTronix** [comment]
> so I can preview the file while it's being generated, on .mp4 container it just doesn't play until I stop the processing.

Ohk.

> Because once I zoom into the image to hide black bars I still want to have some fov (this isn't final decision).

@LosTigeros No `SMOOTHING_RADIUS` is not used for that, it only affects latency at expense of stabilization. Instead, You need use `crop_n_zoom` parameter with `border_size` parameter for this purpose as:

```python
options = {'BORDER_SIZE': 10, 'CROP_N_ZOOM' : True}
```

**Comment by abhiTronix** [comment]
Also, it [my example](https://github.com/abhiTronix/vidgear/issues/209#issuecomment-956350656) worked for you?

**Comment by LosTigeros** [comment]
I tested your example with just replacing
`unstablized_videofile = "http://www.liushuaicheng.org/CVPR2014/data/limitation3.avi"`
to
`unstablized_videofile = "rtmp://localhost:1935/publish/live"`
and streaming that file on OBS.

This is the result (audio out of sync):
[Output.mp4](https://s.lostigeros.dev/vidgear/Output.mp4)

**Comment by abhiTronix** [comment]
@LosTigeros I'm out of ideas why its lagging will looping, Maybe looping is causing this or RTMP stream itself. If by any means you can make this work with just FFmpeg, then it will also work with WriteGear or any other gear involved. Until then, it's a no.

**Comment by LosTigeros** [comment]
Does output frames have some timestamps so ffmpeg could resync the audio?

Audio may be shifted because it's a stream so timestamps may differ between VidGear and ffmpeg.
I also saw that terminating VideoGear kills the ffmpeg process which makes .mp4 container corrupted (that was also the reason why I used .flv), I have to stop the stream instead for it to complete.

**Comment by abhiTronix** [comment]
> Does output frames have some timestamps so ffmpeg could resync the audio?

@LosTigeros Nope. OpenCV is useless, that's why #148 is so important.

> I also saw that terminating VideoGear kills the ffmpeg process which makes .mp4 container corrupted (that was also the reason why I used .flv), I have to stop the stream instead for it to complete.

Yup, and that's why you need `"-disable_force_termination": True,` in your code.

**Comment by abhiTronix** [comment]
@LosTigeros Like I said, make just audio syncing work with FFmpeg, and this problem will be solved automatically,

**Comment by LosTigeros** [comment]
I would but without timestamps on both sides It's currently not possible. I'll wait until #148 is solved then.
Thanks for the help!

**Comment by abhiTronix** [comment]
> VideoGear kills the ffmpeg process which makes .mp4 container corrupted

Nope, VideoGear have no effect on frames number as it never exit untill last frame is outputted, It's WriteGear which kills FFmpeg process.
