### ISSUE TITLE
Decoding multiple rtsp streams with/without GPU

### ISSUE THREAD

**Issue by chandu1263** [abhiTronix/vidgear#211]
## Question
Does Vidgear provide GPU-based encoding and decoding? If so, is it using GStreamer?

I am currently working on a computer vision project which needs multiple video stream decoding.
Using OpenCV takes a huge toll on the CPU, then I came across FFMPEG GPU-based decoding and encoding, but was not able to make it work. How to use vidgear for my use-case (which is decoding multiple rtsp streams at the same time using GPU)?

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [ ] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [ ] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Context

Decoding multiple RTSP streams using GPU.

### Your Environment

* VidGear version: 
* Branch: 
* Python version: 
* PiP version: 
* Operating System and version:

**Comment by abhiTronix** [comment]
> Vidgear provide GPU-based encoding and decoding?

@chandu1263 
GPU Encoding: YES (See this [doc](https://abhitronix.github.io/vidgear/v0.2.1-stable/gears/writegear/compression/usage/#using-compression-mode-with-hardware-encoders))
GPU Decoding: NO (But there's a [hack](https://github.com/abhiTronix/vidgear/issues/69#issuecomment-551112764))

> If so, is it using GStreamer?

VidGear can work on both FFmpeg and GStreamer backend for decoding. But for encoding only FFmpeg is used.

> multiple video stream decoding.

Yes, you can use Gstreamer both inside VidGear for Multi-Stream Decoding but it will require significant amount of GPU power to decode, so what machine are you using? 

### Example Code: _(Tested on jetson nano)_

Btw **Here's a example code for decoding multiple RTSP streams on Jetson Nano with VidGear's [CamGear](https://abhitronix.github.io/vidgear/v0.2.1-stable/gears/camgear/overview/#camgear-api) API running on GStreamer Pipeline and Backend:**

---
:warning: But first check your OpenCV to be built with GStreamer support. You can easily check it by running `print(cv2.getBuildInformation())` python command and see if output contains something similar as follows:
```sh
Video I/O:
  ...
     GStreamer:                   YES (ver 1.8.3)
  ...
```

### See [this FAQ](https://abhitronix.github.io/vidgear/latest/help/camgear_faqs/#how-to-compile-opencv-with-gstreamer-support) to compile OpenCV with GStreamer support.

---

```python
# import required libraries
from vidgear.gears import CamGear
import cv2

# add rstp source
RSTP_source_location = "rtsp://some.server/url"

# define gstreamer pipeline
gstreamer_source = (
        'rtspsrc location={} latency=300 !'.format(RSTP_source_location)
        'rtph264depay !'
        'h264parse !' 
        'omxh264dec enable-max-performance=1 !'
        'nvvidconv ! video/x-raw, format=(string)BGRx!'
        'videoconvert !'
        'appsink')

# Add gstreamer source and enable backend
stream = CamGear(source=gstreamer_source , logging=True, backend=cv2.CAP_GSTREAMER).start() 

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break


    # {do something with the frame here}


    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()
# safely close video stream.
```
