### ISSUE TITLE
webrtc Retrying source if enable live stream

### ISSUE THREAD

**Issue by haviduck** [abhiTronix/vidgear#212]
i dont know if this applies to enough others but it certainly fits here. i use webrtc to stream from various ip cams to operators with handhelds. its outside in a rough environment and at times cams can boot, loose connection etc. 

i solve this by Retrying the source if videocapture.read() returns none. in gears when live stream is enabled you default to infinite blank frames which is awesome, but id love to be able to apply a retry function if live stream enabled and  inf frames true. so after f_stream = blank_frame i suggest another conditional using:

```python
 # display blank if NoneType
        if f_stream is None:
            if self.blank_frame is None or not self.is_running:
                return None
            else:
                f_stream = self.blank_frame[:]


                self.__stream.start()
                f_stream = self.__stream.read()
                print("#ended")
            if not self.__enable_inf:
                self.terminate()
```
 applicable if a new param "retry" is true.

i wrote it in and it works, but i dont know enough about gears to see if theres any big red flags by doing this.

**Comment by abhiTronix** [comment]
@haviduck This feature/flag is way complex to handle/implement in comparison to its very limited use, and thereby not worth the effort. So I will advise you to create your own [WebGearRTC custom server](https://abhitronix.github.io/vidgear/v0.2.1-stable/gears/webgear_rtc/advanced/#using-webgear_rtc-with-a-custom-sourceopencv) and implement this functionality there.

**Comment by haviduck** [comment]
> @haviduck This feature/flag is way complex to handle/implement in comparison to its very limited use, and thereby not worth the effort. So I will advise you to follow much easier approach and create your own [WebGearRTC custom server](https://abhitronix.github.io/vidgear/v0.2.1-stable/gears/webgear_rtc/advanced/#using-webgear_rtc-with-a-custom-sourceopencv) and implement this functionality there.

i understand :) will try custom server again, it did not like my opencv processing last time. thanks for reply!

**Comment by abhiTronix** [comment]
@haviduck Btw, You can replace [OpenCV with CamGear or any other videocapture gear](https://abhitronix.github.io/vidgear/v0.2.1-stable/switch_from_cv/#switching-the-videocapture-apis) easily. 😉

**Comment by haviduck** [comment]
> @haviduck Btw, You can replace [OpenCV with CamGear or any other videocapture gear](https://abhitronix.github.io/vidgear/v0.2.1-stable/switch_from_cv/#switching-the-videocapture-apis) easily. 😉

hehe yeah im slowly changing out stuff. should have found this sooner as ive reinvented the wheel a couple of times by now😅.

**Comment by abhiTronix** [comment]
@haviduck No, I like solving coding problems in my free time and that's why vidgear exists. But I could guide you with your project if possible. 😃

**Comment by haviduck** [comment]
> @haviduck No, I like solving coding problems in my free time and that's why vidgear exists. But I could guide you with your project if possible. 😃

completely understand. got custom server running and it works great. chopped a bunch of memory by doing so and ip cams can disconnect and reconnect and continue spewing out frames to connected clients. thank you :) 

now to see if i can switch out my own zmq implementation with yours.

**Comment by abhiTronix** [comment]
> completely understand. got custom server running and it works great. chopped a bunch of memory by doing so and ip cams can disconnect and reconnect and continue spewing out frames to connected clients. thank you :)
> now to see if i can switch out my own zmq implementation with yours.

@haviduck Reach me out through gitter private chat and also share a rough diagram of setup you're trying to achieve.

**Comment by haviduck** [comment]
> > completely understand. got custom server running and it works great. chopped a bunch of memory by doing so and ip cams can disconnect and reconnect and continue spewing out frames to connected clients. thank you :)
> > now to see if i can switch out my own zmq implementation with yours.
> 
> @haviduck Reach me out through gitter private chat and also share a rough diagram of setup you're trying to achieve there.
> @haviduck texted you.

sorry for late reply, holiday etc.
Awesome, ill jump right on it :)
