### ISSUE TITLE
Tunneling with ssh in NetGear

### ISSUE THREAD

**Issue by marcosar** [abhiTronix/vidgear#213]
## Detailed Description

The facility to start an ssh tunnel with a remote server 

### Context

I have an opencv application that works standalone. I need to place it on the server so that the server would do the processing, the client would only provide the input stream (no need to display the input stream) and receive  the processed frames from the server (only the processed images would be displayed on the browser).

I would think that it is only including the facility to do it over an ssh tunnel. 

I would think that this may be a common usage for apps running on the server, acquiring images from a remote device, processing it, and returning to the device's browser for display.

### Your Current Environment

Mac OS Catalina, Python 3.9

* VidGear version:  0.2.0
* Branch:  latest
* Python version:  Python 3.9.1
* Operating System and version: MacOs Catalina Version 10.15.7

**Comment by abhiTronix** [comment]
**Related:** https://pyzmq.readthedocs.io/en/latest/ssh.html

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit: https://github.com/abhiTronix/vidgear/commit/6ddc9ffa729e6485dc71a174ed6fb1ddf42824f8**

**Comment by abhiTronix** [comment]
### Usage Examples can be found here: https://abhitronix.github.io/vidgear/v0.2.2-dev/gears/netgear/advanced/ssh_tunnel/#ssh-tunneling-mode-for-netgear-api
