### ISSUE TITLE
Not able to save the stream video as output

### ISSUE THREAD

**Issue by uditrawat23** [abhiTronix/vidgear#214]
### import required libraries
    from vidgear.gears import CamGear
    from vidgear.gears import WriteGear
    import cv2
    import os
    from vidgear.gears import WriteGear
    import ffmpeg
    import time

    _media_path = "C:/Users/erawudi/Downloads/Vidgear"
    output_params = {"-vcodec": "libx264", "-crf": "28", "-preset": "ultrafast", "-filter:v":"fps=20", "-loglevel": "fatal"}

    m_filename = time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime()) + ".mp4"
    download_path = os.path.join(_media_path, m_filename)

    writer = WriteGear(output_filename=download_path, logging=True, **output_params)

    URL = "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
    ### Open suitable video stream, such as webcam on first index(i.e. 0)
    stream = cv2.VideoCapture(URL, cv2.CAP_FFMPEG)

    ### loop over
    while True:

        ### read frames from stream
        frame = stream.read()

        ### check for frame if None-type
        if frame is None:
            break

        ### {do something with the frame here}

        ### write frame to writer
        writer.write(frame)

        ### Show output window
        cv2.imshow("Output Frame", frame)

        ### check for 'q' key if pressed
        key = cv2.waitKey(1) & 0xFF
        if key == ord("q"):
            break

    ### close output window
    cv2.destroyAllWindows()

    ### safely close video stream
    stream.stop()

    # safely close writer
    writer.close()

### Acknowledgment

- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Your Environment

* VidGear version: 2.1
* Python version: 3.8
* Operating System and version: Windows 10

**Comment by abhiTronix** [comment]
@uditrawat23 Please provide the following information:

- Are you able to see output while running this code?
- Paste the terminal log with `logging=True` here, so that the problem can be debugged.

**Comment by abhiTronix** [comment]
**I'm closing this issue now. Provide any relevant data/log to support this issue.**
