### ISSUE TITLE
ScreeGear: sourced pixel straight from video card or not?

### ISSUE THREAD

**Issue by axlgit** [abhiTronix/vidgear#217]
Hi,

the project looks amazing, great job!
I just would like to know if ScreenGear gets the pixels from the OS video buffers or if sources them from the graphic card.
Some programs write directly to the video card and hence when I tried other (non necessarily Python) tools like vidgear I got just a black image, I hope I can overcome this with ScreenGear :-)

Thanks!

Axl

## Question

_Kindly describe the issue here._

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [ ] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [ ] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Your Environment

* VidGear version: 
* Branch: 
* Python version: 
* PiP version: 
* Operating System and version:

**Comment by axlgit** [comment]
Ok,

using this code

```
from mss.windows import MSS as mss
with mss() as sct:
    filename = sct.shot(mon=-1, output='fullscreen.png')
...

```
doesn't seem so.

So I guess there is no way, isn't it?

Axl

**Comment by axlgit** [comment]
Thanks @abhiTronix .
I will my questions there.

Thx!

**Comment by abhiTronix** [comment]
> using this code
> 
> from mss.windows import MSS as mss
> with mss() as sct:
>     filename = sct.shot(mon=-1, output='fullscreen.png')
> ...
> 
> doesn't seem so.
> 
> So I guess there is no way, isn't it?

@axlgit ScreenGear also uses `pyscreenshot` in addition to `python-mss`. So you may check that too.
