### ISSUE TITLE
Hardware encoding fails on v0.2.1

### ISSUE THREAD

**Issue by teaglin** [abhiTronix/vidgear#218]
Using version 0.2.1 I am unable to use hardware encoding via h264_nvenc on NVIDIA GPUs. FFMPEG is correctly installed. Hardware encoding works in other applications using ffmpeg and is visible from cli.

I tried setting the custom path of FFMPEG, but that fails as well. Downgrading to any earlier version seems to resolve the issue.

## Description

Error from vidgear
`WriteGear :: CRITICAL :: Provided FFmpeg does not support `h264_nvenc` video-encoder. Switching to default supported `libx264` encoder!`

## FFMPEG
ffmpeg is accessible from path, and is correctly compiled and working in other applications. Looking through available codecs it also contains h264_nvenc.

ffmpeg -codecs | grep h264
ffmpeg version N-102049-gcc7943e803 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --extra-libs='-lpthread -lm' --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-cuda --enable-cuvid --enable-nvenc --enable-pic --enable-shared --enable-libnpp
  libavutil      56. 74.100 / 56. 74.100
  libavcodec     58.137.100 / 58.137.100
  libavformat    58. 79.100 / 58. 79.100
  libavdevice    58. 14.100 / 58. 14.100
  libavfilter     7.111.100 /  7.111.100
  libswscale      5. 10.100 /  5. 10.100
  libswresample   3. 10.100 /  3. 10.100
  libpostproc    55. 10.100 / 55. 10.100
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2mh264_cuvid ) (encoders: libx264 libx264rgb h264_nvenc h264_v4l2m2m h264_vaapi nvenc nvenc_h264 )

### Environment

* VidGear version: 0.2.1
* Branch: PyPi
* Python version:3.8
* PiP version: 20.0.2
* Operating System and version: Ubuntu 20.04

### Expected Behavior
Encoding with FFMPEG via NVIDIA h264 hw encoder should work.

### Actual Behavior
Says it can't find ffmpeg codec when clearly it exists.

**Comment by abhiTronix** [comment]
@teaglin Thanks for raising this issue. I just tested and can confirm that regex is broken exclusively for this encode. But nothing to worry about as I'll fix this in not time. Please stay tuned, I'll notify you here when it is done.

> I tried setting the custom path of FFMPEG, but that fails as well. Downgrading to any earlier version seems to resolve the issue.

@teaglin Yeah, That's because encoder check was added recently in v0.2.1.

**Comment by teaglin** [comment]
@abhiTronix Not a problem and thanks for the quick update.

**Comment by abhiTronix** [comment]
@teaglin Thanks for your patience. I've patched the regex expression in `development`, and you can install vidgear from source as follow:

```sh
 # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest development branch
  git checkout development

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```
and test if issue is fixed or not? Goodluck.

**Comment by abhiTronix** [comment]
**Solved as working as intending.** Kindly test it whenever possible.

**Comment by chouex** [comment]
facing the same problem @0.2.1, not detect libx264 and hevc_nvenc
fixed after install develop branch.

just report the fix is working

**Comment by abhiTronix** [comment]
@chouex It's solved. Kindly use steps given [above comment](https://github.com/abhiTronix/vidgear/issues/218#issuecomment-853471558) to update vidgear to latest until `v0.2.2` is released with patch.
