### ISSUE TITLE
Vidgear ROS compatibility 

### ISSUE THREAD

**Issue by guiaugustoga987** [abhiTronix/vidgear#225]
I have a drone with a camera attached and I use opencv with ROS (Robot Operating System
) to visualize the camera frames. Can I use vidgear for video stabilization in this case ?

In the line code : 
`stream = VideoGear(source=0, stabilize = True).start() # To open any valid video stream(for e.g device at 0 index)
`
I'm not sure how do I set up my video stream obtained with ROS. Any recommendation ?

**Comment by abhiTronix** [comment]
@guiaugustoga987 Actually, It's pretty easy . Just use [`cv_bridge`](http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython) to convert OpenCV frames to ROS image messages. You can use following code for reference:

```python
#!/usr/bin/env python
from __future__ import print_function

import roslib

roslib.load_manifest("my_package")

# import required libraries
import sys
import rospy
import cv2
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
from vidgear.gears import VideoGear
import numpy as np


class image_converter:
    def __init__(self, source=0, stabilize=True, logging=False):
        self.image_pub = rospy.Publisher("image_topic_2", Image)
        self.bridge = CvBridge()
        # stabilization enabled(`stabilize = True`)
        self.stream_stab = VideoGear(
            source=source, stabilize=stabilize, logging=logging
        ).start()

    def callback(self, data):
        # read stabilized frames
        frame_stab = self.stream_stab.read()
        # check for stabilized frame if None-type
        if frame_stab is None:
            # {do something with the frame here}
            try:
                self.image_pub.publish(self.bridge.cv2_to_imgmsg(cv_image, "bgr8"))
            except CvBridgeError as e:
                print(e)

    def close(self):
        self.stream_stab.stop()


def main(args):
    # open any valid video stream (for e.d foo.mp4)
    ic = image_converter(source="foo.mp4", logging=True)
    rospy.init_node("image_converter", anonymous=True)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")
    ic.close()


if __name__ == "__main__":
    main(sys.argv)
```

**Comment by abhiTronix** [comment]
@guiaugustoga987 Kindly test this solution and report back here with result. Goodluck!

**Comment by abhiTronix** [comment]
Marked solved, as working as intended. Feel free to test it and provide valuable feedback when possible.

**Comment by guiaugustoga987** [comment]
Hello, sorry for the late response.

My issue is that I need to stabilize the frames from the camera that is simulated on gazebo.

I use this command to subscribe to the camera stream : `self.image_sub = rospy.Subscriber('camera/rgb/image_raw',Image, self.image_callback,queue_size=1, buff_size=2**30)`

When I call Videogear function I'm not sure which 'source' parameter I should use (0 opens my notebook webcam device)  

Here is a simplified sample of my code : 


`def __init__(self):`

     `self.image_sub = rospy.Subscriber('camera/rgb/image_raw',Image, self.image_callback,queue_size=1, buff_size=2**30)`

 `def get_distance(self,img):`
                
       self.bridge = cv_bridge.CvBridge()
       cv_image = self.bridge.imgmsg_to_cv2(img,'32FC1')
       cv_image = np.array(cv_image, dtype=np.float32)
       return cv_image

`def image_callback(self, msg):`

      ` frame = self.bridge.imgmsg_to_cv2(msg,desired_encoding='bgr8')`


So my task is to take the frames from frame variable and stabilize them. What is the best approach for that ?

Thanks in advance.

**Comment by abhiTronix** [comment]
@guiaugustoga987 You shall use `cv_bridge` to convert the Gazebo Image topics into OpenCV friendly numpy frames and then feed those frames to Vidgear's Stabilizer class(instead of Videogear API) directly for real-time stabilization. I am almost sure, OpenCV by itself won't detect Gazebo Topics as a streaming source.

You can find out more [here](http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython)
