### ISSUE TITLE
I want to get the live stream from youtube, and for that, I have used opencv along with the package vidgear. But while running the code, I am getting the following error. I am sure that there is no problem with the URL.  I have tried with pafy and streamlink. Even though both have given the result but after few frames, it was getting stuck and I want sequential frames without any pause.

### ISSUE THREAD

**Issue by adithya6aj** [abhiTronix/vidgear#23]
import cv2
from vidgear.gears import CamGear
stream = CamGear(source="https://www.youtube.com/watch?v=VIk_6OuYkSo", y_tube =True,  time_delay=1, logging=True).start() # YouTube Video URL as input

while True:

    frame = stream.read()
    if frame is None:
        break

    cv2.imshow("Output Frame", frame)

    key = cv2.waitKey(30) 

    if key == ord("q"):

        break

cv2.destroyAllWindows()
stream.stop()

'NoneType' object has no attribute 'extension'
Traceback (most recent call last):
  File "C:\Users\CamfyVision\AppData\Local\Programs\Python\Python36\lib\site-packages\vidgear\gears\camgear.py", line 120, in __init__
    print('Extension: {}'.format(_source.extension))
AttributeError: 'NoneType' object has no attribute 'extension'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DronrStream.py", line 4, in <module>
    stream = CamGear(source="https://www.youtube.com/watch?v=VIk_6OuYkSo", y_tube =True,  time_delay=1, logging=True).start() # YouTube Video URL as input
  File "C:\Users\CamfyVision\AppData\Local\Programs\Python\Python36\lib\site-packages\vidgear\gears\camgear.py", line 125, in __init__
    raise ValueError('YouTube Mode is enabled and the input YouTube Url is invalid!')

**Comment by abhiTronix** [comment]
@adithya6aj **See issue #16 and its solution is in my [comment](https://github.com/abhiTronix/vidgear/issues/16#issuecomment-495456217).**

**Comment by abhiTronix** [comment]
**Closed. Feel free to reopen if something related doesn't work for you.**

**Comment by abhiTronix** [comment]
@adithya6aj  I think #274 resolves this issue too. 

Clone and Install `development` branch:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout development

  # install normally
  pip install .[core]

  # OR install with asyncio support
  pip install .[asyncio]
```
Test your code:
```python
# import required libraries
from vidgear.gears import CamGear
import cv2

options = {"STREAM_RESOLUTION": "720p"}

# Add YouTube Video URL as input source (for e.g https://youtu.be/bvetuLwJIkA)
# and enable Stream Mode (`stream_mode = True`)
stream = CamGear(
    source="https://youtu.be/j1GLs_fMn1s", stream_mode=True, logging=True, **options
).start()

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # Show output window
    cv2.imshow("Output", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()
```
