### ISSUE TITLE
Audio input from device in StreamGear

### ISSUE THREAD

**Issue by tgentry1986** [abhiTronix/vidgear#236]
## Question

Hey! Im loving vidgear! I've managed to get an NDI stream in to it using a python implementation of the NDI libraries, then frames in to open CV and then out to an rtmp server using vidgear - Very, very cool (i work in VFX and more and more packages are supporting NDI i.e. avid, premiere, flame etc. and streaming NDI to an RTMP server is a very hot topic). However, audio doesnt work with the NDI library im using - ive reached out to the dev but had no response. 

One way i could get around this is by taking the system audio in to ffmpeg, which would usually be a -i <device name>, but it doesnt look like this option is available in vidgear. Is this possible and im doing something wrong? Or is this unimplemented at this time?

Thank again, vidgear is great!   

Cheers!
### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Context

See above! Would love to get system audio in to an ffmpeg stream using vidgear!

### Your Environment

* VidGear version: 0.2.1
* Branch: PyPi
* Python version: Python 3.9.6
* PiP version: 21.1.3
* Operating System and version: Windows 10

**Comment by abhiTronix** [comment]
> One way i could get around this is by taking the system audio in to ffmpeg, which would usually be a -i , but it doesnt look like this option is available in vidgear.

@tgentry1986 Nope. It is available, please go through docs. See this: https://abhitronix.github.io/vidgear/v0.2.2-dev/gears/writegear/compression/usage/#using-compression-mode-with-live-audio-input

**Comment by tgentry1986** [comment]
hey @abhiTronix 

Im using StreamGear rather than WriteGear and getting the following error;

Option vf (set video filters) cannot be applied to input url Stereo Mix (Realtek Audio) -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file Stereo Mix (Realtek Audio).

these are my current params;

stream_params = {
                    "-vsync":0,
                    "-threads:v":2,
                    "-threads:a:":8,
                    "-filter_threads":2,
                    "-video_size":"1920x1080", 
                    "-f":"gdigrab",
                    "-b:v":"5120k",
                    "-minrate:v":"5120k",
                    "-maxrate:v":"5120k",
                    "-bufsize:v":"2560k",
                    "-zerolatency":1,
                    "-qp:v":25,
                    "-profile:v":"main",
                    "-color_primaries":"bt709", 
                    "-color_trc":"bt709", 
                    "-colorspace":"bt709", 
                    "-color_range": "pc",
                    "-r:v": 30,
                    "-g:v": 60,
                    "-rc:v": "cbr_ld_hq",
                    "-bf:v": 0,
                    "-refs:v": 16,
                    "-f":"flv",
                    "-f": "dshow",
                    "-ac": "1",
                    "-ar": "48000",
                    "-i": "Stereo Mix (Realtek Audio)"}

streamer = StreamGear(output="rtmp://192.168.0.1/live/test", logging=True, **stream_params)

Am i doing this wrong here or does StreamGear not support audio input?

Apologies if my initial post wasnt clear enough about the usage of streamgear.

Thanks!

**Comment by abhiTronix** [comment]
> Im using StreamGear rather than WriteGear and getting the following error;

@tgentry1986 StreamGear doesn't support live input yet. It only allows file input as if now: https://abhitronix.github.io/vidgear/latest/gears/streamgear/usage/#b7-usage-with-audio-input

**Comment by abhiTronix** [comment]
Due to limited time right now, this can't be done in current `v0.2.2` release. I'll work on it in the future releases.

**Comment by tgentry1986** [comment]
@abhiTronix thank you so much! The ability to do this would certainly help me finish my current project easily without a lot of re-writing. Please let me know if youre able to achieve this!

**Comment by abhiTronix** [comment]
> streamer = StreamGear(output="rtmp://192.168.0.1/live/test", logging=True, **stream_params)

@tgentry1986 This is wrong. StreamGear doesn't support RMTP streaming format but only support **DASH** or **HLS** streaming. If you want to use RMTP then use WriteGear.

**Comment by abhiTronix** [comment]
**Successfully added and merged audio device input support in StreamGear in commit https://github.com/abhiTronix/vidgear/commit/11f7dadc67874bf38808853b0c69821eddb2fd64.**
