### ISSUE TITLE
name 'VideoStreamTrack' is not defined

### ISSUE THREAD

**Issue by zlg9folira** [abhiTronix/vidgear#246]
I am trying to use WebGear on Ubuntu 18.04. I installed `vidgear[asyncio]` from `pip3`. I am now running the following example:

```
import uvicorn
from vidgear.gears.asyncio import WebGear

#various performance tweaks
options = {"frame_size_reduction": 40, "frame_jpeg_quality": 80, "frame_jpeg_optimize": True, "frame_jpeg_progressive": False}

#initialize WebGear app with suitable video file (for e.g `foo.mp4`) 
web = WebGear(source = "foo.mp4", logging = True, **options)

#run this app on Uvicorn server at address http://0.0.0.0:8000/
uvicorn.run(web(), host='0.0.0.0', port=8000)

#close app safely
web.shutdown()
```

And it throws the following error:
```
in .../webgear_rtc.py" line 77 in module
NameError: name 'VideoStreamTrack' is not defined
corrupted size vs. prev-size
Aborted (core dumped)
```

What causes this? and How can I fix this?

**Comment by abhiTronix** [comment]
> in .../webgear_rtc.py" line 77 in module
NameError: name 'VideoStreamTrack' is not defined
corrupted size vs. prev-size
Aborted (core dumped)

@zlg9folira This is half error, i need complete log from your terminal to debug anything at all. Are you running old version of vidgear? What's output of `python3 -c "import vidgear; print(vidgear.__version__)"` 

>  I am now running the following example:

> import uvicorn
> from vidgear.gears.asyncio import WebGear
> 
> #various performance tweaks
> options = {"frame_size_reduction": 40, "frame_jpeg_quality": 80, "frame_jpeg_optimize": True, "frame_jpeg_progressive": False}
> 
> #initialize WebGear app with suitable video file (for e.g `foo.mp4`) 
> web = WebGear(source = "foo.mp4", logging = True, **options)
> 
> #run this app on Uvicorn server at address http://0.0.0.0:8000/
> uvicorn.run(web(), host='0.0.0.0', port=8000)
> 
> #close app safely
> web.shutdown()

I don't think so, Webgear errors don't propgate like this. Where's error handler values in your log? Did you modified code by yourself?
