### ISSUE TITLE
Audio Source anullsrc

### ISSUE THREAD

**Issue by nebriv** [abhiTronix/vidgear#247]
Hello,

I'm trying to live stream video frames generated from cv2 to YouTube. I was able to successfully do this through a straight ffmpeg solution by setting the audio input to 'anullsrc' however I can't find any option to do this within vidgear's implementation. Is this possible at all?

I was hoping to use either StreamGear to stream via DASH or HLS, or just WriteGear to stream via RTMP which what I'm currently doing. My current solution is buffering quite a bit and seems a bit cumbersome and VidGear seems like a cleaner solution.

For example this is what I'm using to run ffmpeg:
```python
command = ['ffmpeg',
            '-i', '-', #input from pipe
            '-f', 'lavfi',
            '-i','anullsrc', #Youtube Live needs some audio, so create fake audio src
            '-acodec', 'libmp3lame',
            '-ar', '44100',
            '-deinterlace',
            '-vcodec', 'libx264', #Use libx264 if no nvidia GPU available
            '-pix_fmt', 'yuv420p',
            '-s', '%sx%s' % (image_w, image_h),
            '-preset', 'veryfast',
            '-tune', 'fastdecode',
            '-r', '30', #Frame rate
            '-g', '65',
            '-b:v', '1500k',
            '-threads:6',
            '-qscale:3',
            '-b:a:712000',
            '-buffsize:1024k',
            '-f', 'flv',
            url]

p = subprocess.Popen(command, stdin=subprocess.PIPE)

while True:
    # Get frames and do stuff.
    p.stdin.write(frame)
```

When trying to replicate this with WriteGear (see example below) - I found I cannot provide the -f flag more than once as the parameters are passed via a dictionary. I tried adding a '.mp4' to the end of the YouTube stream URL however that causes it to fail with `rtmp://a.rtmp.youtube.com/live2/xxxx-xxxx-xxxx-xxxx-xxxx/test.mp4: I/O error
WriteGear :: ERROR :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!`
When I don't supply the first format flag I get the below error:
`anullsrc: No such file or directory
WriteGear :: ERROR :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!`

```python
output_params = {
    '-i': 'anullsrc',  # Youtube Live needs some audio, so create fake audio src
    '-acodec': 'libmp3lame',
    "-ar": 44100,
    "-b:a": 712000,
    "-vcodec": "libx264",
    "-preset": "medium",
    "-b:v": "4500k",
    "-bufsize": "512k",
    "-pix_fmt": "yuv420p",
    "-f": 'flv'
}
writer = WriteGear(
    output_filename=url,
    logging=True,
    **output_params
)
```

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Your Environment

* VidGear version: 0.2.2
* Branch: pypi
* Python version: 3.8
* PiP version: 
* Operating System and version:
Windows 10

Thanks for any input/feedback/help you can provide!!

**Comment by nebriv** [comment]
My apologies - this issue seems to be very similar but didn't come up in my initial searches.
https://github.com/abhiTronix/vidgear/issues/201

I've landed on these output parameters so far but the buffering is quite terrible, I'll have to keep experimenting! I think this can probably be closed unless there is a more elegant solution built-in.

```python
output_params = {
    '-f': 'lavfi',
    '-i': 'anullsrc',  # Youtube Live needs some audio, so create fake audio src
    '-acodec': 'libmp3lame',
    "-ar": 44100,
    "-b:a": 712000,
    "-vcodec": "libx264",
    "-preset": "veryfast",
    "-b:v": "4500k",
    "-pix_fmt": "yuv420p",
    "-clones": ["-f", "flv"],
}```

**Comment by abhiTronix** [comment]
> I'm trying to live stream video frames generated from cv2 to YouTube. I was able to successfully do this through a straight ffmpeg solution by setting the audio input to 'anullsrc' however I can't find any option to do this within vidgear's implementation. Is this possible at all?

@nebriv Have you checked the vidgear docs yet? **Solution is right there:** https://abhitronix.github.io/vidgear/v0.2.2-dev/help/writegear_ex/#using-writegears-compression-mode-for-youtube-live-streaming
