### ISSUE TITLE
StreamGear Malformed URI with Segments

### ISSUE THREAD

**Issue by Vboivin** [abhiTronix/vidgear#248]
## Description

- I am using StreamGear Real-Time Frames mode to transmit a live feed from a webcam to a client.
- I am using StreamGear to generate the playlist file (m3u8) and the segments (.ts files).
- When using the StreamGear Real-Time Frames mode, the segment files contain a '%' character in their name which causes an error when I am serving this static content through Nginx.
- The playlist file is served without an issue.

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version:   0.2.2
* Branch:  Master
* Python version:  3.6.9
* PiP version:  21.2.4
* Operating System and version: Ubuntu 18.04.6 LTS (Arm64)

### Expected Behavior

The segment files should be served without an issue by a server such as Nginx.

### Actual Behavior

The segment files are not served by Nginx and they result in a malformed URI error

### Possible Fix

Removing the extra '%' character from the naming convention for segment files

### Steps to reproduce

(Write your steps here:)

1. Create a StreamGear object with the following parameters:
- format="hls"
- stream_params: {"-livstream": True and "-input_framerate": 25}
- output="/test/folder"
2. Serve the folder /test/folder as static content with Nginx
3. Try to access the live stream through a javascript video player such as video.js and look at the network tab in your browser

### Example of the Bug:
![Screenshot-20210930011311-1747x487](https://user-images.githubusercontent.com/28627982/135478350-99f7f3d1-cf89-433f-a31e-2b645bbcdba8.png)
![Screenshot-20210930011436-644x36](https://user-images.githubusercontent.com/28627982/135478443-561f6496-cfdd-4003-a07b-66b645e569ff.png)

**Comment by abhiTronix** [comment]
@Vboivin Thank you for your contribution but I'm getting this error:

```sh
More than 1 variant streams are present, %v is expected either in the filename or in the sub-directory name of file /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temp_m3u8/chunk-stream-%03d.ts
```

**`%v` is related to multi-variant stream and it should not appear if single variant video is present(as seen in your case). This definitely a bug.** 

But simply changing `chunk-stream-%03d` would not work, but instead we need a logic to check if more than one stream is defined by user or not. If it defined than old `chunk-stream%v-%03d` is needed else `chunk-stream-%03d` is required.

**Comment by Vboivin** [comment]
@abhiTronix Thank you for the comment!

It makes much more sense now, I'll take a look around the code to figure out how to implement the if check.
Great library btw!

**Comment by abhiTronix** [comment]
> It makes much more sense now, I'll take a look around the code to figure out how to implement the if check.

@Vboivin I'm looking into this too, will update you  shortly. 

Also, Well done with well-formatted PR and issue. Good going. 👍🏽

**Comment by abhiTronix** [comment]
@Vboivin You can use `output_params["stream_count"]` key to determine the exact stream count. Default is `0`(Single variant stream) btw. 

https://github.com/abhiTronix/vidgear/blob/38a7f54eb911218e1fd6a95e243da2fba51a6991/vidgear/gears/streamgear.py#L643

I'm sending you fix in review please wait.

**Comment by abhiTronix** [comment]
@Vboivin Please make required changes.

**Comment by Vboivin** [comment]
@abhiTronix I modified #249 with the changes you've suggested.

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/dc9c60a54f3c843358e94707cfa43fe28bc65f14**

Thanks @Vboivin for the PR! 💯
