### ISSUE TITLE
video transfer with multiple servers and multiple clients

### ISSUE THREAD

**Issue by elaademiir** [abhiTronix/vidgear#252]
Hi, vidGear is very creative solution but I can not understand how to implement my problem with multiple servers and multiple clients.

My Question

I have 4 modules in my software architecture.
First one aims to send videos to 2nd modules only. And 1st module's work is done.
After 2nd modules receive videos from 1st one, it does some transactions with frames and sends videos to 3rd module. And its work is done.
After 3rd modules receive videos from 2nd one, it does some transactions with frames and sends videos to 4th module. And its work is done.
Every module has unique .py file. In my code, I can transfer videos between 2 modules and make transactions inside 2nd module using VidGear but can not transfer frames to 3rd module. Because in VidGear cant support me to make 2nd module both server and client. for example 2nd module send video after receive and transform frames.

I have read the https://abhitronix.github.io/vidgear/v0.2.1-stable/gears/netgear/advanced/multi_server/
I have read the https://abhitronix.github.io/vidgear/latest

**Comment by abhiTronix** [comment]
> I have 4 modules in my software architecture.
> First one aims to send videos to 2nd modules only. And 1st module's work is done.
> After 2nd modules receive videos from 1st one, it does some transactions with frames and sends videos to 3rd module. And its work is done.
> After 3rd modules receive videos from 2nd one, it does some transactions with frames and sends videos to 4th module. And its work is done.

@elanurozlem This isn't multiple servers and multiple clients problem but instead you're looking for a linked(chaining) setup where each module is receiving frames from later and forwarding it to next module after processing.

From what I understand you wanted this setup:

```sh
Module 1 ==Frames==> Module 2[Processing] ==Frames==> Module 3[Processing] ==Frames==> Module 4
``` 

Can you try following code:

### 0. Configurations:  `address` and `port` parameter values:
- Module - 1: 
  - **Server:** IP Address: {Use Module - 2 IP address} |  port Address = 5454
- Module - 2: 
   - **Client:** IP Address: {Use its own local  IP Address} |  port Address = 5454
   - **Server:** IP Address: {Use Module - 3 IP address} |  port Address = 3333
 - Module - 3: 
   - **Client:** IP Address: {Use its own local  IP Address} |  port Address = 3333
   - **Server:** IP Address: {Use Module - 4 IP address} |  port Address = 4545
 - Module - 4: 
   - **Client:** IP Address: {Use its own local IP Address} |  port Address = 4545

## 1. Module 1 Python Code (Acts as server):

```python
# import required libraries
from vidgear.gears import VideoGear
from vidgear.gears import NetGear

# define various tweak flags
options = {"flag": 0, "copy": False, "track": False}

# Open live video stream on webcam at first index(i.e. 0) device
stream = VideoGear(source=0).start()

# Define Netgear server at given IP address and define parameters 
# !!! change following IP address '192.168.x.xxx' with client's IP address !!!
server = NetGear(
    address="192.168.x.xxx", # Use Module-2 IP address here,
    port="5454",
    protocol="tcp",
    pattern=2, # Use `pattern=2` always
    logging=True,
    **options
)

# loop over until KeyBoard Interrupted
while True:

    try:
        # read frames from stream
        frame = stream.read()

        # check for frame if Nonetype
        if frame is None:
            break

        # {do something with the frame here}

        # send frame to server
        server.send(frame)

    except KeyboardInterrupt:
        break

# safely close video stream
stream.stop()

# safely close server
server.close()
```

### 2. Module 2 and 3 Python Code: (Act as Client as well as Server) _(⚠️ Make sure to replace values from above)_

```python
# import required libraries
from vidgear.gears import NetGear
import cv2

# define various tweak flags
options = {"flag": 0, "copy": False, "track": False}

# Define Netgear Client at given IP address and define parameters 
client = NetGear(
    address="192.168.x.xxx",  # !!! change following IP address '192.168.x.xxx' with yours from above !!!
    port="XXXX",   # !!! change following port address 'XXXX' with yours from above !!!
    protocol="tcp",
    pattern=2, # Use `pattern=2` always
    receive_mode=True,
    logging=True,
    **options
)

# define various tweak flags
options = {"flag": 0, "copy": False, "track": False}

# Define Netgear server at given IP address and define parameters 
# !!! change following IP address '192.168.x.xxx' with client's IP address !!!
server = NetGear(
    address="192.168.x.xxx", # !!! change following IP address '192.168.x.xxx' with yours from above !!!
    port="4545",  # !!! change following port address 'XXXX' with yours from above !!!
    protocol="tcp",
    pattern=2, # Use `pattern=2` always
    logging=True,
    **options
)

# loop over
while True:

    # receive frames from network
    frame = client.recv()

    # check for received frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

     # send frame to server
     server.send(frame)

    # Show output window
    # cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close client
client.close()

# safely close server
server.close()
```

## 3. Module 4 code (Acts as Client):

```python
# import required libraries
from vidgear.gears import NetGear
import cv2

# define various tweak flags
options = {"flag": 0, "copy": False, "track": False}

# Define Netgear Client at given IP address and define parameters 
client = NetGear(
    address="192.168.x.xxx", # !!! change following IP address '192.168.x.xxx' with yours !!!
    port="4545", 
    protocol="tcp",
    pattern=2, # Use `pattern=2` always
    receive_mode=True,
    logging=True,
    **options
)

# loop over
while True:

    # receive frames from network
    frame = client.recv()

    # check for received frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close client
client.close()
```
