### ISSUE TITLE
WebGear_RTC: Once the camera stream on the browser is closed, it cannot be reloaded again on a new tab until the app is closed and restarted.

### ISSUE THREAD

**Issue by megha-seventhsense** [abhiTronix/vidgear#258]
## Description

WebGear_RTC: Once the camera stream on the browser is closed, it cannot be reloaded again on a new tab until the app is closed and restarted.

### Acknowledgment

- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [X] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version: 0.2.2
* Branch: v0.2.2
* Python version: Python 3.7.9
* PiP version: 21.3
* Operating System and version: Ubuntu 18.04.3 LTS

### Expected Behavior
Once the browser tab with camera stream is closed, it should be possible to reopen it in a new browser/tab successfully without the need to close and restart the application.

### Actual Behavior
Once we close the first browser tab with camera stream and we try to reopen it again in a new tab, camera stream cannot be loaded at all. 

### Steps to reproduce
Tested with the below sample code from
https://abhitronix.github.io/vidgear/latest/gears/webgear_rtc/advanced/

1) Run the following sample code to view the camera stream on a browser-
```
#import necessary libs
import uvicorn, asyncio, cv2
from av import VideoFrame
from aiortc import VideoStreamTrack
from aiortc.mediastreams import MediaStreamError
from vidgear.gears.asyncio import WebGear_RTC
from vidgear.gears.asyncio.helper import reducer

#initialize WebGear_RTC app without any source
web = WebGear_RTC(logging=True)

#create your own Bare-Minimum Custom Media Server
class Custom_RTCServer(VideoStreamTrack):
    """
    Custom Media Server using OpenCV, an inherit-class
    to aiortc's VideoStreamTrack.
    """

    def __init__(self, source=None):

        # don't forget this line!
        super().__init__()

        # initialize global params
        self.stream = cv2.VideoCapture(source)

    async def recv(self):
        """
        A coroutine function that yields `av.frame.Frame`.
        """
        # don't forget this function!!!

        # get next timestamp
        pts, time_base = await self.next_timestamp()

        # read video frame
        (grabbed, frame) = self.stream.read()

        # if NoneType
        if not grabbed:
            return MediaStreamError

        # reducer frames size if you want more performance otherwise comment this line
        frame = await reducer(frame, percentage=30)  # reduce frame by 30%

        # contruct `av.frame.Frame` from `numpy.nd.array`
        av_frame = VideoFrame.from_ndarray(frame, format="bgr24")
        av_frame.pts = pts
        av_frame.time_base = time_base

        # return `av.frame.Frame`
        return av_frame

    def terminate(self):
        """
        Gracefully terminates VideoGear stream
        """
        # don't forget this function!!!

        # terminate
        if not (self.stream is None):
            self.stream.release()
            self.stream = None


#assign your custom media server to config with adequate source (for e.g. foo.mp4)
web.config["server"] = Custom_RTCServer(source=0)

#run this app on Uvicorn server at address http://localhost:8000/
uvicorn.run(web(), host="localhost", port=8000)

#close app safely
web.shutdown()
```
2. Open a browser (tested with Chrome and Firefox) and navigate to http://localhost:8000/. It should show the camera stream on the browser successfully.
3. Now close the above browser tab and open a new tab. Try to navigate to the URL http://localhost:8000/ again. Camera stream cannot be loaded at all.

### Optional
![Screenshot from 2021-10-22 12-03-59](https://user-images.githubusercontent.com/92971254/138404722-bf298b9b-7d73-4f74-93fd-5aa00d56d941.png)
![Screenshot from 2021-10-22 12-15-42](https://user-images.githubusercontent.com/92971254/138406151-72c86476-d5d8-42d9-a5a5-4db94c85a800.png)

**Comment by abhiTronix** [comment]
@megha-seventhsense This issue is being worked on and will be resolved soon. Please stay tuned.

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit: https://github.com/abhiTronix/vidgear/commit/cd481c142519b7973822179bc754435b68ce1ca2**

**Comment by abhiTronix** [comment]
### Docs for defining custom streaming class can be found here: https://abhitronix.github.io/vidgear/v0.2.4-dev/gears/webgear_rtc/advanced/#using-webgear_rtc-with-a-custom-sourceopencv
