### ISSUE TITLE
How to Receive audio stream and Send combined audio stream with VidGear

### ISSUE THREAD

**Issue by thusinh1969** [abhiTronix/vidgear#265]
I found that majority of VidGear functions focus on video frame and very little to do with audio if at all. 

## Question
Can VidGear, in combination with PyAudio (for example) give out functionality to combine (receiving) audio and then write/stream audio with sync together with video as H264 for example?

- Can we can use audio source from video files, or from microphone or from MediaPlayer.audio from WebRTC (aiortc) peerconnection as audio source ? How do we capture it and then write / stream it out in-sync with frame ?
- Can we then send/yield audio in-sync with video frame the same way VidStream do with WebStream, NetGear and so on ?

### Acknowledgment
I have read through most of pages, example of VidGear, great package for video-frame streaming bidirectionally but too little mention about audio.

### Your Environment
Same as recommended, Ubuntu 18, CPU/RAM/GPU adequate.

Thank you.
Steve

**Comment by abhiTronix** [comment]
> I found that majority of VidGear functions focus on video frame and very little to do with audio if at all.



> Can we can use audio source from video files, or from microphone or from MediaPlayer.audio from WebRTC (aiortc) peerconnection as audio source ? How do we capture it and then write / stream it out in-sync with frame ?

Nope, WebGear_RTC doesn't support audio yet. Maybe in future but not right now. You can use `aiortc` library directly.

**Comment by abhiTronix** [comment]
@thusinh1969 I'm closing this as I currently got not time to work on audio support. I'll work on this on future versions. Being said that any related PR is welcomed anytime.
