### ISSUE TITLE
Built-in logging module don't show log after importing CamGear

### ISSUE THREAD

**Issue by alanko0511** [abhiTronix/vidgear#266]
## Description

After importing CamGear, I found that all the log messages from the built-in logging module are gone, even changing the logging level still doesn't work.
```python
import logging
from vidgear.gears import CamGear

logging.basicConfig(level=logging.INFO)

logging.info('hello from logging!')
print('hello from print!')
```

### Environment

* VidGear version: 0.2.3
* Branch: PyPi
* Python version: 3.8.12
* PiP version: 21.0.1
* Operating System and version: Windows 11

### Expected Behavior
'hello from logging!' and 'hello from print!' should appear in the terminal when using the code in the "Description".
![image](https://user-images.githubusercontent.com/34646302/141727499-42dc95f2-2383-40f2-8815-0bdb429be93b.png)

### Actual Behavior
Only 'hello from print!' printed.
![image](https://user-images.githubusercontent.com/34646302/141727539-83ee938c-a8e0-4d58-a47a-b9459b0adf70.png)

### Possible Fix
I found that if I put the `logging.basicConfig` after importing CamGear, the log disappears, but it back to normal when I put it before importing CamGear.

This fixes the problem:
```python
import logging
logging.basicConfig(level=logging.INFO)
from vidgear.gears import CamGear

logging.info('I can see this message')
```

**Comment by abhiTronix** [comment]
@alanko0511 good find 👍🏽. This is indeed a bug. This is due to some redundant code left accidently in library, I'll fix it in no time.

**Comment by abhiTronix** [comment]
@alanko0511 Thank you for reporting this issue. It is now fixed in testing branch and you can test it as follows:

```
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout testing

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```

and logging module in your code should work now. Good luck.

**Comment by abhiTronix** [comment]
**Successfully fixed in commit https://github.com/abhiTronix/vidgear/commit/6e8bc6ce4b39540fc16fd1572faed3ff8ffa8f0c** 

@alanko0511 Please test it when ready.
