### ISSUE TITLE
How to initialize multiple filters to execute in `execute_ffmpeg_command`

### ISSUE THREAD

**Issue by Adib234** [abhiTronix/vidgear#269]
## Question

So I have this snippet of code which horizontally/vertically stacks 2 videos
```python
def stack(video_path, second_video_path, output_path, use_second_audio,stack):
    writer = WriteGear(output_filename = video_path,logging=True)
    ffmpeg_command = ["-y", "-i", video_path , "-i", second_video_path, "-filter_complex", "\'[1:v]scale=1020:720[1v];" + f"[0:v][1v]{stack}=inputs=2[v]\'", "-map" , " \'[v]\'" , "-map", f"{int(not use_second_audio)}:a" , "-vsync", "0" , "-preset", "ultrafast", output_path]
    writer.execute_ffmpeg_cmd(ffmpeg_command)
    writer.close()
```

However I get this error 
```
[AVFilterGraph @ 0x7fef6fc09280] No such filter: '[1:v]scale=1020:720[1v];[0:v][1v]hstack=inputs=2[v]'
Error initializing complex filters.
Invalid argument
```

So I decided to copy the command to be executed shown in VidGear logs
```
22:12:57 ::   WriteGear    ::  DEBUG  :: Executing FFmpeg command: `ffmpeg -y -i /tmp/test-video-1.mp4 -i /tmp/test-video.mp4 -filter_complex '[1:v]scale=1020:720[1v];[0:v][1v]hstack=inputs=2[v]' -map  '[v]' -map 0:a -vsync 0 -preset ultrafast res.mp4`
```

And this worked when I ran this as a command in my terminal

### Acknowledgment

- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Your Environment

* VidGear version:  0.2.3
* Branch:  Master
* Python version:  3.9.7
* PiP version:  21.2.4
* Operating System and version: MacOS

**Comment by abhiTronix** [comment]
@Adib234 Remove all quotes(single or double) and you're good to go.
