### ISSUE TITLE
How to get live feed from any remotely located device?

### ISSUE THREAD

**Issue by Ashish-U21** [abhiTronix/vidgear#276]
Hey, First of all, thank-you for providing such impressive repo.I am working on a project where I am using opencv and I need to get the source (video feed, in any format or url) to achieve my objective. Here I am using cam gear, but it required some source as well, do you have any suggestion regarding this like how I can get the feed from client device using vidgear?

Additionally, I have an IP address of the client's camera.

Environment

* VidGear version:  0.2.4
* Python version:  3.7
* PiP version: 21.1.2
* Operating System and version: ubuntu 20.04

**Comment by abhiTronix** [comment]
Hi @Ashish-U21, Everything is in docs, See https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/ssh_tunnel/#ssh-tunneling-mode-for-netgear-api

**Comment by abhiTronix** [comment]
@Ashish-U21 Another way is to [live-stream to YouTube or Twitch](https://abhitronix.github.io/vidgear/latest/gears/writegear/compression/usage/#using-compression-mode-for-streaming-urls) and [download it frame-by-frame](https://abhitronix.github.io/vidgear/latest/gears/camgear/usage/#using-camgear-with-streaming-websites) on remote machine.

**Comment by Ashish-U21** [comment]
> Hi @Ashish-U21, Everything is in docs, See https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/ssh_tunnel/#ssh-tunneling-mode-for-netgear-api for connecting two remote machines(present in two different networks) over SSH tunnel for sending frames.

I have been trying to solve this but I am not able to, I do not understand how to integrate or install in the frontend, I asked my frontend engineer to do same, he was asking the steps or key points to keep in mind, can you please help me with that, it will be a great help our project is stucked on this.

**Comment by abhiTronix** [comment]
> I have been trying to solve this but I am not able to, I do not understand how to integrate or install in the frontend, I asked my frontend engineer to do same, he was asking the steps or key points to keep in mind, can you please help me with that, it will be a great help our project is stucked on this.

@Ashish-U21 OK I've updated the instructions in our doc: https://abhitronix.github.io/vidgear/v0.2.5-dev/gears/netgear/advanced/ssh_tunnel/ .

**Basically you need this configuration for implementing [SSH tunneling](https://www.ssh.com/academy/ssh/tunneling/example):**

### A. Server End(A system for sending video-frames to remote Client): [Located on your Home Network]
- VideoGear to capture video frames from video source.
- Do suitable processing on frames.
- Implement  NetGear Server(for sending frames) with [**SSH Tunneling Mode**](https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/ssh_tunnel/#ssh-tunneling-mode-for-netgear-api) enabled for remotely connecting it to Client End at `<ssh-username>@<client-public-ip>:22` SSH address. 

### B. Client End(A system for receiving frames from server): [Located on Remote Network outside your Home Network]
- Implement NetGear Client(for receiving frames from Server) . 
- Here, ⚠️ You need to [forward TCP port `22`](https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/) at your Client's router to be able to connect Server remotely to it via SSH Tunneling. Other instruction you can find in [SSH tunneling mode docs](https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/ssh_tunnel/#ssh-tunneling-mode-for-netgear-api)
