### ISSUE TITLE
CamGears THREAD_TIMEOUT parameter

### ISSUE THREAD

**Issue by Input-BDF** [abhiTronix/vidgear#277]
Hey there, first of all, thanks for vidGear. It saves me alot of headache^^

Currently I'm moving from plain OpenCVs VideoCapture to vidGear, cause of alot of reasons. I was a little bit forced to implement a timeout on millisecond basis on frame reading before using vidGear cause timing was essential. Trying now to figure out what I still need.

Your implementation of timeout parameter casts the provided parameter value as int which does not allow something like timeout after 1.5 frames and causes no frame to be read anyway. E.g. int(0.025) returns 0 and therefore always times out on read(). Cf.. [camGears init function](https://github.com/abhiTronix/vidgear/blob/9e24af6d723a802d934a0d0494ee457fd055d068/vidgear/gears/camgear.py#L323)

Since threadings condition.wait() supports fractions of seconds shouldn't be float the better choice? Or is there any kind of dependency/ relation to camGears queue?

**Comment by abhiTronix** [comment]
> Since threadings condition.wait() supports fractions of seconds shouldn't be float the better choice? Or is there any kind of dependency/ relation to camGears queue?

@Input-BDF I don't really know exactly why I kept this integer value, this may be somewhat related to something I read way back that python's queue `timeout` parameter behavior is inconsistent on different platforms: https://bugs.python.org/issue34535, so maybe I thought assuming absolute integer value is way to go. 

But I think float value is more suitable for this job. No worries I'll change it.

**Comment by abhiTronix** [comment]
@Input-BDF A fix has been added to latest testing branch, you can test by installing vidgear as follows:

```sh
# clone the repository and get inside
git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

# checkout the latest testing branch
git checkout testing

# Install latest stable release with all Core dependencies
pip install -U .[core]

# Or Install latest stable release with all Core & Asyncio dependencies
pip install -U .[asyncio]

```

Then use float as input value `THREAD_TIMEOUT` attribute. Goodluck!

**Comment by Input-BDF** [comment]
Tested and works for me. Think this one can be closed. At least from my side^^

**Comment by abhiTronix** [comment]
Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/de2e8a9cc8e0fd29eaf636d487e7a22f2c038505
