### ISSUE TITLE
How to Send a Message with Frame in MultiClient Mode

### ISSUE THREAD

**Issue by elanurozlem** [abhiTronix/vidgear#278]
cannot send message with frame!

## Question

Hi,
  I have multiple clients and 1 server. I aim to send my message with frame from my server to all clients but there is no option to do that in multi-client mode. How to do that with multi-client mode or with bidirectional mode without creating any new server port?

**Comment by abhiTronix** [comment]
> I have multiple clients and 1 server. I aim to send my message with frame from my server to all clients but there is no option to do that in multi-client mode. How to do that with multi-client mode or with bidirectional mode without creating any new server port?

@elanurozlem You can't currently as NetGear only support unidirectional data transfer in both Multi-clients and Multi-Server Exclusive modes. It could be possible to implement bidirectional data transfer in these modes, but I'll not going to work on it right now, may be in the near future. Being said that any related PRs are always welcome.

**Comment by elanurozlem** [comment]
I just wonder that is there any way to send a message with frame from 1 server to multiple clients in VidGear?

**Comment by abhiTronix** [comment]
I explained already above. No not yet.

**Comment by abhiTronix** [comment]
@elanurozlem This feature is being worked on now. Please stay tuned.

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/9006f7ca41a6a40df0c76473ef898daf6b685ffa**

**Comment by abhiTronix** [comment]
Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/de2e8a9cc8e0fd29eaf636d487e7a22f2c038505
