### ISSUE TITLE
Missing UDP stream support in NetGear

### ISSUE THREAD

**Issue by stampycode** [abhiTronix/vidgear#281]
TCP stream is supported but UDP stream is not.

## Detailed Description
Add support to send/receive video via UDP.

### Context
It's quite common to stream video in UDP on local networks.

**Comment by abhiTronix** [comment]
> TCP stream is supported but UDP stream is not.

@stampycode Supported by what? What is Gear/API in question?

**Comment by stampycode** [comment]
@abhiTronix  NetGear 👍

**Comment by abhiTronix** [comment]
@stampycode Is there any clear advantage of UDP over TCP connection? FYI, TCP transmissions are highly optimized in terms of speed in NetGear API.

**Comment by abhiTronix** [comment]
Unless, UDP targets some specific application or provides significant edge over TCP connections in your case, It couldn't be added as alternative.

**Comment by stampycode** [comment]
UDP is fully supported by ffmpeg.
Its ideal for broadcasting video in a connectionless environment, such as satellite video.

Suggest you also have a look at SRT, which is UDP based. 👍

-------- Original Message --------

**Comment by abhiTronix** [comment]
@stampycode Ohk, looks convincing, I'll work on this later. Any related PRs are always welcome.
