### ISSUE TITLE
[Bug]: Zero(`0`) index device bug in StreamGear

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#289]
## Brief Description

There's a hidden bug in StreamGear which incorrectly infers `-video_source` attribute  of `stream_params` dictionary parameter as empty when a Zero(`0`) index camera device is used as input, and thereby even if `logging=False` StreamGear API outputs debug logs.

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version:  v0.2.6
* Branch:  testing
* Python version:  3.7+
* PiP version:  latest
* Operating System and version: all

### Actual Behavior

If we use `-video_source` attribute in `stream_params` dictionary parameter `0`(or use zero index camera device), it makes `self.__video_source` in StreamGear `True`, since _string("0")  is not false_ or `"0"!=False`  in python language. 

### Expected Behavior

Must able to handle `-video_source` attribute value properly.

### Steps to reproduce

```python
# import required libraries
from vidgear.gears import CamGear
from vidgear.gears import StreamGear
import cv2

# open any valid video stream
stream = CamGear(source="foo.mp4").start() 
# define `-video_source` value to `0`
stream_params = {"-video_source": 0}
# describe a suitable master playlist location/name and assign params
streamer = StreamGear(output="./New folder/hls_out.m3u8", format = "hls", **stream_params)
# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break


    # {do something with the frame here}


    # send frame to streamer
    streamer.stream(frame)

    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()

# safely close streamer
streamer.terminate()
```

### Credits

This bug was discovered by @enarche-ahn

**Comment by abhiTronix** [comment]
Hi @enarche-ahn, can you test if logging problem is fixed in StreamGear by installing `development` branch as follows:

```sh
 # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest development branch
  git checkout development

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```
After installing, run your test example again. **Kindly test it as soon as possible and share your results here. Goodluck!**

**Comment by enarche-ahn** [comment]
Just now I finished testing with the development branch, and it worked fine in both case, 'logging=True' and 'logging=False' option.

    streamer = StreamGear(
	output="./New folder/hls_out.m3u8",
	format="hls",
	logging=False,
	**stream_params)

    streamer = StreamGear(
	output="./New folder/hls_out.m3u8",
	format="hls",
	logging=True,
	**stream_params)

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/1b9b413e11b58def2b3e130303b29ba776fe30c8**
