### ISSUE TITLE
[Bug]: zmq.error.ZMQError: Can't assign requested address error trying NetGear+WebGear example

### ISSUE THREAD

**Issue by iandol** [abhiTronix/vidgear#291]
## Brief Description

I have a Raspberry Pi400 (using latest 64bit Bullseye release) with a UVC USB3 camera attached. On the same local network I have a Macbook Pro that I want to use to connect to the RPi and display the camera output. Speaking to @abhiTronix on chat, he recommended the following code: https://abhitronix.github.io/vidgear/latest/help/netgear_ex/#using-netgear-with-webgear

However, the client code crashes when trying to set up ZMQ connection:

```
zmq.error.ZMQError: Can't assign requested address
RuntimeError: [NetGear:ERROR] :: Receive Mode failed to bind address: tcp://192.168.1.44:5454 and pattern: 1! Kindly recheck all parameters.
```

I've tested the ZMQ hello world test code and it works fine on the same machines. I also tested `uvicorn` to run a simple server and it works. I have reinstalled zmq (`brew reinstall zmq`) on the client machine, and using `venv` have reinstalled all pip packages from scratch. Python is V3.10.2 on the client and V3.9.2 on the server.

The code (slightly modified to fix a couple of errors I got from Python (no self, cannot return a value in async) and error logs are found at this gist:

https://gist.github.com/iandol/ebf722f75251bb9f5bc57ba967fd12ba

### Acknowledgment

- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [X] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version: 0.25* Branch: 
* Python version: 3.10.2
* PiP version: 22.0.3
* Operating System and version: macOS 12.2.1

### Expected Behavior
See the video from RPi in the Macbook browser.

### Actual Behavior
client.py crashes

### Steps to reproduce

(Write your steps here:)

1. Clean 64bit bullseye OS, create a new venv on the RPi, install vidgear[core] and deps to run Netgear and CamGear. Add server.py taken from example code. Use IP taken from RPi.
2. Create venv on macOS, install vidgear[asyncio] and any other Netgear and Webgear deps.
3. Add client.py on macOS set up to correct IP of RPi.
4. Run server.py on RPi and cleint.py on macOS.

**Comment by abhiTronix** [comment]
@iandol what's the IP address on both mac and Rpi? Follow following instructions and paste the results here:
- Open a Terminal app on each machine.
- Type and run `/sbin/ifconfig` this will list your IP address as well your MAC address.
- You can use cmd+a to select all, cmd+c to copy and it can be pasted to whatever you want.

**Comment by iandol** [comment]
My RPi is assigned `192.168.1.44` and my macbook is `192.168.1.38`. I can ping `192.168.1.44` from the macbook OK, and as I said I tried to run the `zmq` hello world server/client, and I've also tried lazy pirate from the zmq docs using the same `192.168.1.44:5454` and it works fine; code here: https://gist.github.com/iandol/a0cd594d790230435d4f3d343830da9f 

RPi:
```
 ifconfig              
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether dc:a6:32:fd:fb:d1  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 50634  bytes 2534509 (2.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 50634  bytes 2534509 (2.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.44  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::6929:d8dd:27f8:3367  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:fd:fb:d5  txqueuelen 1000  (Ethernet)
        RX packets 85726  bytes 27307320 (26.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 67060  bytes 37502674 (35.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

macbook:
```
gears on  main [!?⇡] via 🐍 v3.10.2 (vidgear) took 5s
❯ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether ac:bc:32:8c:08:39
	inet6 fe80::1cd9:3c9c:20ff:6cc2%en0 prefixlen 64 secured scopeid 0x4
	inet 192.168.1.38 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:17:03:a6:48:00
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:17:03:a6:48:01
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 82:17:03:a6:48:00
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	options=400<CHANNEL_IO>
	ether 0e:bc:32:8c:08:39
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 3e:47:26:cc:db:ba
	inet6 fe80::3c47:26ff:fecc:dbba%awdl0 prefixlen 64 scopeid 0x9
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 3e:47:26:cc:db:ba
	inet6 fe80::3c47:26ff:fecc:dbba%llw0 prefixlen 64 scopeid 0xa
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
feth6702: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 2800
	ether 66:65:74:68:1a:2e
	peer: feth1702
	media: autoselect
	status: active
feth1702: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800
	ether de:6c:d8:46:89:a2
	inet 172.22.22.2 netmask 0xffff0000 broadcast 172.22.255.255
	inet6 fe80::dc6c:d8ff:fe46:89a2%feth1702 prefixlen 64 scopeid 0xc
	inet6 fda0:9acf:233:27ef:de99:9383:ff75:8b6d prefixlen 88
	peer: feth6702
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::1261:2fb:2ba2:d54f%utun0 prefixlen 64 scopeid 0xd
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::6ff3:ef9:a481:9c4f%utun1 prefixlen 64 scopeid 0xe
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 fe80::ce81:b1c:bd2c:69e%utun2 prefixlen 64 scopeid 0xf
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::9383:904d:c951:598e%utun3 prefixlen 64 scopeid 0x10
	nd6 options=201<PERFORMNUD,DAD>
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::3cd1:8cff:700d:52ef%utun4 prefixlen 64 scopeid 0x12
	nd6 options=201<PERFORMNUD,DAD>
```

On the RPi and macbook I also checked that nothing was holding onto port 5454, here is the result for the RPi:

```
❯ sudo lsof -i TCP -P              
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
cupsd      623 root    6u  IPv6  13676      0t0  TCP localhost:631 (LISTEN)
cupsd      623 root    7u  IPv4  13677      0t0  TCP localhost:631 (LISTEN)
vncserver  645 root   11u  IPv6  14636      0t0  TCP *:5900 (LISTEN)
vncserver  645 root   12u  IPv4  14637      0t0  TCP *:5900 (LISTEN)
vncserver  645 root   16u  IPv4  15003      0t0  TCP localhost:43434->localhost:39405 (ESTABLISHED)
vncserver  645 root   17u  IPv4  86119      0t0  TCP 192.168.1.44:5900->192.168.1.38:49564 (ESTABLISHED)
sshd       662 root    3u  IPv4  14515      0t0  TCP *:22 (LISTEN)
sshd       662 root    4u  IPv6  14517      0t0  TCP *:22 (LISTEN)
vncserver 1009   pi    8u  IPv4  15004      0t0  TCP localhost:39405->localhost:43434 (ESTABLISHED)
chromium- 1734   pi   31u  IPv4  20776      0t0  TCP 192.168.1.44:59132->stackoverflow.com:443 (ESTABLISHED)
```

**Comment by abhiTronix** [comment]
> Add client.py on macOS set up to correct IP of RPi.
> My RPi is assigned 192.168.1.44 and my macbook is 192.168.1.38

@iandol This pretty obvious that you're doing it wrong. It mentioned everywhere in NetGear docs(see any example) as well in example links I provided you for reference, that you need to ***"Replace the IP addresses in the code with Client's IP address, i.e. `192.168.1.38` in your case."***. Kindly read docs properly before raising an issue here.

**Comment by iandol** [comment]
Yikes, you are completely correct of course. I'm very sorry. My brain made a strong assumption in a client + server system it was the server address that must be used... 

As a slight emphasis for others who may make such an misguided assumption, perhaps the first comment on the example page could be slightly modified:

> Note down the local IP-address of the ***client system***; it is important to understand that the IP address of the client must be used on client and server. Replace this IP in the following code.

There were 3 problems I encountered with the client code. There is a missing import for Netgear, a wrong `self`, and apparently return cannot return any value inside an async:

![Screenshot 2022-02-19 at 21 37 49](https://user-images.githubusercontent.com/153905/154820022-d6ffdfa7-c323-46ba-8696-a265259bf03a.png)

**Comment by abhiTronix** [comment]
@iandol I think all the instructions are already self-explanatory, no need to emphasis on (client) keyword in example. However, You can surely make a new FAQ for NetGear https://abhitronix.github.io/vidgear/latest/help/netgear_faqs/ explaining the error and what one must do to avoid it. **A PR would be great, but read the guidelines carefully: https://abhitronix.github.io/vidgear/latest/contribution/PR/**
