### ISSUE TITLE
[Question]: Small issues with Netgear example

### ISSUE THREAD

**Issue by iandol** [abhiTronix/vidgear#294]
When going through https://abhitronix.github.io/vidgear/latest/help/netgear_ex/#using-netgear-with-webgear I came on some small issues with the code, @abhiTronix recommended they should be fixed; well he only mentioned the `self.` typo but I assume the missing import and the return value are also OK?

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Context

See closed issue #291. I opened a pull request fixing this here: #295

**Comment by abhiTronix** [comment]
@iandol Thanks, but make sure next time not open to multiple PRs rather combine commits under one PR. Also, I asked to one changes.

**Comment by iandol** [comment]
OK, I'll roll changes into one in the future (other repos often prefer separate pulls to make a more explanatory commit log). I'm sorry but I can't see what change you've asked for in the pull request?

**Comment by abhiTronix** [comment]
@iandol see review on PR, you newd to revert missing `None`.

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/53ca17bf61d9c6ff8adadc978fe4036c3fd93ba4**
