### ISSUE TITLE
After Video Processing Save Video with Audio as Well

### ISSUE THREAD

**Issue by DanielOX** [abhiTronix/vidgear#296]
## Question

Hello, first for all thanks for the awesome library. I am using vidgear for downloading video streams from twitter and youtube. The video is downloaded perfectly but on the other hand, the audio is not being downloaded, i am using CamGear which supports youtube platform. Can u please help me out with this issue? I will happy to share my code. Can u help me with this? I want to download audio of the video as well after processing.

### Acknowledgment

- [ x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [ x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [ x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Context

I am trying to perform object detection on incoming frame but i also want the audio to be stored along the video

Doing object detection for research purposes by using vidgear CamGear api

### Your Environment

* VidGear version: 0.2.5
* Branch: Master
* Python version: 3.8.10
* PiP version: 21.3 
* Operating System and version: Ubuntu 18.00

### Code 
```

import cv2
from vidgear.gears import VideoGear
from vidgear.gears import WriteGear
from vidgear.gears import CamGear

# Open input video stream
options = {"STREAM_RESOLUTION": "480p"}

try:
    stream = CamGear(source='https://youtu.be/M8kcjRrroOE',stream_mode=True,**options).start()
except:
    stream = CamGear(source='https://youtu.be/M8kcjRrroOE',stream_mode=True).start()
    

output_params = {
    "-input_framerate": stream.framerate,
    "-thread_queue_size": "512",
    "-ac": "2",
    "-ar": "48000",
    "-f": "alsa", 
    "-i": "hw:1" # i don't know what to insert here audio
}

writer = WriteGear(output_filename='/home/Downloads/vidgear_try/downloads/temp.mp4', logging=True,**output_params, )

# infinite loop
while True:

    frame = stream.read()
    # read frames

    # check if frame is None
    if frame is None:
        # if True break the infinite loop
        break

    # write frame to writer
    writer.write(frame)

cv2.destroyAllWindows()


stream.stop()
# safely close video stream
writer.close()
cv2.destroyAllWindows()


stream.stop()
# safely close video stream
writer.close()
```

**Comment by abhiTronix** [comment]
@DanielOX audio is not supported in CamGear yet. Follow #148 that will resolve this issue.
