### ISSUE TITLE
WebCam Source: data is not aligned!

### ISSUE THREAD

**Issue by sweetngx** [abhiTronix/vidgear#298]
Warning: data is not aligned! This can lead to a speed loss.
Does it matter if I get this warning? Everything is fine, but I was just nervous.

**Comment by abhiTronix** [comment]
@sweetngx No context regarding which gear you used or what python code you used or where in output you getting this is provided. Please fill the template properly or this issue will be closed soon.

**Comment by sweetngx** [comment]
@abhiTronix Ah Sorry... I am using Python 3.8 version and I get this warning when I use it with OBS Virtual Cam.

options = {
    "CAP_PROP_FRAME_WIDTH": 1920, # resolution 320x240
    "CAP_PROP_FRAME_HEIGHT": 1080,
    "CAP_PROP_FPS": 30, # framerate 60fps
}


stream = VideoGear(source=1, logging=True, **options).start()

**Comment by abhiTronix** [comment]
@sweetngx This warning is related to unusual frame size that your source `1` is outputting. This warning is generated by OpenCV's FFmpeg backend, it is a common FFmpeg warning and causes no harm. So you're good.

**Comment by sweetngx** [comment]
Thank you very much for your interest and information...
