### ISSUE TITLE
[Question]: urllib3 Error

### ISSUE THREAD

**Issue by sweetngx** [abhiTronix/vidgear#299]
When everything was fine and working healthy, I just took a tea break and when I returned, I started getting this error. I reinstalled python and even recompiled opencv but still the same error, I'm going crazy please help.
OS: Windows 10
Python: 3.8.3

  File "C:\Program Files\Python38\lib\site-packages\vidgear\gears\helper.py", line 44, in <module>
    from requests.packages.urllib3.util.retry import Retry
ModuleNotFoundError: No module named 'requests.packages.urllib3.util.retry'; 'requests.packages.urllib3.util' is not a package

**Comment by abhiTronix** [comment]
@sweetngx Thanks for finding this bug. I'll work on this in my free time. For the time being, downgrade your `requests` dependency.

**Comment by abhiTronix** [comment]
OK, it wasn't a bug but `requests` package installed incorrectly. More info can be found here: https://github.com/certbot/certbot/issues/5104
