### ISSUE TITLE
[Question]: Starting a video (`.mp4`) at a given frame

### ISSUE THREAD

**Issue by connor-john** [abhiTronix/vidgear#300]
## Question

Using `VideoGear` I wish to start a video (`.mp4`) at a given frame say 100, I could not find if this is possible, is this not intended functionality?

Similar to opencv's functionality of 
```python
video_capture.set(cv2.CAP_PROP_POS_FRAMES, 100)
```

And below is async locked
```python
stream = VideoGear(source='video.mp4').start()

stream.stream.stream.set(cv2.CAP_PROP_POS_FRAMES, 100)
```

Thanks in advance.

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Your Environment

* VidGear version: `0.2.5`
* Branch: `master`
* Python version: `3.7.9`
* PiP version: `20.1.1`
* Operating System and version: Windows 11

**Comment by connor-john** [comment]
Seems #53 mentioned this in 2019, is this still the case?

**Comment by abhiTronix** [comment]
@connor-john not at all, you lucky since can now use my new library DeFFcode which is designed exactly to tackle this problem, and will soon replace OpenCV in CamGear or some other Gear. Here's example for accurate seeking:
https://abhitronix.github.io/deffcode/latest/examples/basic/#saving-keyframes-as-image

You need to make some changes according to your application, but I'll leave that to you,as it's pretty easy. Anyways if you get stuck anywhere, let me know. Also, drop a 🌟 if you like it.

**Comment by connor-john** [comment]
This looks like exactly what I am after, thank you @abhiTronix

**Comment by edu010101** [comment]
> @connor-john not at all, you lucky since now you can use my new [**DeFFcode library**](https://abhitronix.github.io/deffcode/latest) which is designed exactly to tackle this problem, and will soon replace OpenCV in CamGear or some other Gear in #148. Here's example for accurate seeking: https://abhitronix.github.io/deffcode/latest/examples/basic/#saving-keyframes-as-image
> 
> You need to make some changes according to your application, but I'll leave that to you,as it's pretty easy. Anyways if you get stuck anywhere, let me know. Also, drop a star2 if you like it.

Hello, is there any way to apply the "ffparams" after starting the video?, in short, I would like to use the equivalent of the function "cap.set(cv2.CAP_PROP_POS_FRAMES, 100)" in your library, several times, in the same video open only once
