### ISSUE TITLE
Netgear API multiple listening error on same port

### ISSUE THREAD

**Issue by zeynepkoyun** [abhiTronix/vidgear#301]
When I try to listen to the same port multiple times with the Netgear API, I get the error that the port is already listening.

Would you help me with this topic?

**Comment by abhiTronix** [comment]
@zeynepkoyun seems like you're not closing NetGear properly. Can you fill the template properly as need to know what machine/OS are you running? Or version of vidgear you're using, and so on. Plus, I need terminal debug logs to be able to solve this issue, so kimdly set `logging=True` in NetGear and then, paste the output from terminal here, whenever this issue happens.

**Comment by abhiTronix** [comment]
Also @zeynepkoyun If you're okay with providing code here, then I'll able to resolve it more quickly.

**Comment by zeynepkoyun** [comment]
Hi @abhiTronix 
Actually, I want different clients to listen to the same port and show the video image simultaneously, so I should be able to reconnect to the same port without closing it.

**Comment by zeynepkoyun** [comment]
> Also @zeynepkoyun If you're okay with providing code here, then I'll able to resolve it more quickly.
client = NetGear(
            address="127.0.0.1",
            port="1025",
            protocol="tcp",
            pattern=2,
            receive_mode=True,
            logging=True,
            **options
        )

I want to enable connection by more than one client via Netgear API as in the above line of code.

**Comment by abhiTronix** [comment]
> Hi @abhiTronix
Actually, I want different clients to listen to the same port and show the video image simultaneously, so I should be able to reconnect to the same port without closing it.

Nope, that's not how NetGear API or its backend ZMQ works. A port once bind cannot be called again with a new connection until it closed properly. If you want multiple clients with one server, why don't you use its Multi-Clients mode: https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/multi_client/#multi-clients-mode-for-netgear-api

**Comment by abhiTronix** [comment]
@zeynepkoyun also, if you're comfortable with showing image/video on browser to multiple users at same time then see our [Webgear](https://abhitronix.github.io/vidgear/v0.2.5-stable/gears/webgear/overview/#webgear-api) and [Webgear_RTC](https://abhitronix.github.io/vidgear/v0.2.5-stable/gears/webgear_rtc/overview/) APIs.

**Comment by zeynepkoyun** [comment]
@abhiTronix Thank you for your answers, but here is: With Netgear, I broadcast multiple cameras over different ports, then I receive all the frames sent by the server on the client side.

However, when a different person wants to listen to the same port, I get the error that the port is already in use.

**Comment by abhiTronix** [comment]
@zeynepkoyun i think you're looking for UDP, but NetGear API only supports TCP, that's why it's impossible to do so. However good news is that you use either [Webgear](https://abhitronix.github.io/vidgear/v0.2.5-stable/gears/webgear/overview/#webgear-api) or [Webgear_RTC](https://abhitronix.github.io/vidgear/v0.2.5-stable/gears/webgear_rtc/overview/) API instead which both supports multiple clients on same port in the network. Check advanced examples to get started.
