### ISSUE TITLE
[Proposal]: Fix deprecation warning for tostring() for numpy 1.19+

### ISSUE THREAD

**Issue by Lucas-Steinmann** [abhiTronix/vidgear#302]
## Brief Description

numpy deprecated the `numpy.ndarray.tostring()` function since 1.19. See: https://numpy.org/devdocs/reference/generated/numpy.ndarray.tostring.html
The replacement  `numpy.ndarray.tobytes()` was implemented since 1.9, which was release Sep 7, 2014. See: https://numpy.org/devdocs/reference/generated/numpy.ndarray.tobytes.html.

`tostring()` is called during every call `write()` of WriteGear, if `compression_mode==True`.
This triggers a deprecation warning, which spams the console.
Surely, the user could filter out the warning, but I think the cleaner solution would be to use the replacement, since it has been supported for a long time (way longer than this project exists).

### Context
Why is this change important to you? How would you use it?: DeprecationWarning annoys me and floods terminal → hides other warnings/messages
Will this change the existing VidGear APIs? How?: Will require `numpy>=1.9.0`
How can it benefit other users?: Benefits all users who use compression mode with WriteGear

### Your Current Environment

* VidGear version: 0.2.4,  but I checked that the [function is still called in current master](https://github.com/abhiTronix/vidgear/blob/6af7aef2b924b5b9b9923a527f7d844c82991b7f/vidgear/gears/writegear.py#L354)
* Branch: PyPi
* Python version: Python 3.8.10
* Operating System and version: GNU/Linux Ubuntu 16.04

**Comment by abhiTronix** [comment]
Hi @Lucas-Steinmann, this issue is already fixed in commit https://github.com/abhiTronix/vidgear/commit/e53d94f5ce1b152e1584d4649779b05ebbaf47f8 on `testing` branch.
