### ISSUE TITLE
[Bug]:NetGear is not OPENCV 4.5.5 Compatible  

### ISSUE THREAD

**Issue by rubar-tech** [abhiTronix/vidgear#303]

**Comment by abhiTronix** [comment]
@rubar-tech kindly explain your issue by filling the template.

**Comment by rubar-tech** [comment]
I will post more info on error but for now, all I can say is that I think due to some changes in open cv 4.5.5, may be a few more new versions too, Netgear can't run
I think you can reproduce the problem if you try bare minimum example of netgear
Deep 📝,  I use vidgear 0.2.0 and due to existence of simplejpeg in recent versions, I can not upgrade

**Comment by abhiTronix** [comment]
> I use vidgear 0.2.0

That itself is the problem. We don't maintain or even provide support for old versions of vidgear. Upgrade to latest versions to make sure everything works on your end. If you experience the same problem with latest version too then reopen this issue anytime.
