### ISSUE TITLE
[Question]: How do I set cv2.CAP_PROP_FOURCC with VideoGear?

### ISSUE THREAD

**Issue by zorrobyte** [abhiTronix/vidgear#304]
## Question

I'd like to use CAP_PROP_FOURCC to use my webcam in MJPG mode but I'm struggling with the options syntax. It looks like this is an option in WriteGear but not VidGear.

```"CAP_PROP_FOURCC": ('M', 'J', 'P', 'G'),```

```Traceback (most recent call last):
  File "/home/ross/Documents/GitHub/opencv-playground/main.py", line 18, in <module>
    stream1 = VideoGear(source=0, logging=True, **options).start()
  File "/home/ross/Documents/GitHub/opencv-playground/venv/lib/python3.8/site-packages/vidgear/gears/videogear.py", line 142, in __init__
    self.stream = CamGear(
  File "/home/ross/Documents/GitHub/opencv-playground/venv/lib/python3.8/site-packages/vidgear/gears/camgear.py", line 373, in __init__
    self.stream.set(property, value)
TypeError: Argument 'value' can not be treated as a double
```

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Context
I'm trying to use a Logitech Brio 4k webcam at 4k, it only supports MJPG for this use case. I want to use it with OpenPilot to drive my car.

### Your Environment

* VidGear version: ?
* Branch: PIP
* Python version: 3.8.10
* PiP version: ?
* Operating System and version: Ubuntu 20.04

**Comment by zorrobyte** [comment]
I was able to figure it out!

`"CAP_PROP_FOURCC": 0x47504A4D,  # MJPG`

**Comment by 3togo** [comment]
According toe the https://abhitronix.github.io/vidgear/latest/gears/writegear/non_compression/params/#supported-fourcc-codecs

```
# format codec as dictionary attribute
output_params = {"-fourcc":"MJPG"} 
# and then, assign it
WriteGear(output = 'output.mp4', **output_params)
```

but it never works, 

@zorrobyte  's suggestion is the only workaround that I know

```
output_params = {"CAP_PROP_FOURCC": 0x47504A4D}
self.writer = WriteGear(output=out_video_name, **output_params)
```

**Comment by abhiTronix** [comment]
@3togo can you show terminal logs by adding  `logging = True` in WriteGear API instance in your python script, then paste output from your terminal here?

**Comment by 3togo** [comment]
I guess the generated ffmpeg command line is incorrect.

```
16:01:26 ::    Helper     ::   INFO   :: Running VidGear Version: 0.3.1
16:01:26 ::   WriteGear   ::  DEBUG   :: Output Parameters: `{'-fourcc': 'MJPG', '-fps': 30}`
16:01:26 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.
16:01:26 ::    Helper     ::  DEBUG   :: Final FFmpeg Path: ffmpeg
16:01:26 ::    Helper     ::  DEBUG   :: FFmpeg validity Test Passed!
16:01:26 ::    Helper     ::  DEBUG   :: Found valid FFmpeg Version: `b'N-111794-gaea2d269db'` installed on this system
16:01:26 ::   WriteGear   ::  DEBUG   :: Found valid FFmpeg executable: `ffmpeg`.
16:01:26 ::   WriteGear   ::  DEBUG   :: Compression Mode with FFmpeg backend is configured properly.
16:01:28 ::   WriteGear   ::  DEBUG   :: InputFrame => Height:480 Width:853 Channels:3 Datatype:uint8
16:01:28 ::   WriteGear   ::  DEBUG   :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 853x480 -pix_fmt bgr24 -i - -fourcc MJPG -fps 30 -vcodec libx264 -crf 18 -preset fast /home/joe/gitee/j_misc/j_vd/python/eg01/abc.avi`
```

**Comment by 3togo** [comment]
For posterity's sake, here's at least one working example,

` output_params = {"logging": True, "-vcodec": "libvpx-vp9", "-r": 30}   `

**Comment by abhiTronix** [comment]
> 16:01:26 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.

@3togo You can clearly see you're using compression mode which basically means you're using FFmpeg instead of OpenCV Writer Class, so `{'-fourcc': 'MJPG', '-fps': 30}` will never work as it is meant only for OpenCV Writer Class. Kindly see docs, you need compression mode turned off by using `compression=False` in WriteGear API to make it work.

**Comment by abhiTronix** [comment]
> According toe the https://abhitronix.github.io/vidgear/latest/gears/writegear/non_compression/params/#supported-fourcc-codecs

For this, I agree there should be `compression_mode=False` in the example. I'll correct it.

**Comment by 3togo** [comment]
many thanks
