### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by haimat** [abhiTronix/vidgear#305]
## Question

Hey guys, I have a stream of images from my webcam, with roughly 20 fps - sometimes a bit more, sometimes a bit less, I cannot rely on that fps count. Now I want to save the stream of frames as video file, using WriteGear. That works, however, the video becomes way to fast when played - it looks as if viewed in fast-forward. And the whole minute of camera frames leads to a ~10 secs video. I played with various `-input_framerate` and/or `-r` parameters, but they did not really help.

All I want is that a real-time minute from the camera stream becomes also one minute in the output video, regardless of how many frames I receive from the camera in that minute. How can I achive that?

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Your Environment

* VidGear version: 0.2.5
* Branch: PyPi 
* Python version: 3.8.10
* PiP version: 22.0.4
* Operating System and version: Ubuntu 20.04

**Comment by abhiTronix** [comment]
@haimat You can only combine frames into video at fps that you used to extract frames to get a accurate time precise video. If you increase fps ot will result in fast forwarded short video and if you decrease fps you'll get a stretched very long video. But with a variable framerate during decoding frames can never be encoded into a video which is time accurate, you'll always going to have some inconsistencies in the output no matter how hard you try, and it is not specific to WriteGear or FFMPEG, you'll find same results with other libraries too.

**Comment by abhiTronix** [comment]
@haimat right now you cannot control framerate precisely with OpenCV but my deffcode library is able to just that using FFMPEG. But unfortunately it doesn't support Webcams yet, you'll have to wait for it.

**Comment by haimat** [comment]
> @haimat right now you cannot control framerate precisely with OpenCV while decoding but my deffcode library is able to just that using FFMPEG. But unfortunately it doesn't support Webcams yet, you'll have to wait for it.

Well, I get the webcam images via as CV2 images - would that work with your library?

**Comment by abhiTronix** [comment]
CV2 images?

**Comment by haimat** [comment]
So - in a loop I get one OpenCV (CV2) image after the other. I have now set my webcam to send only 5 FPS. Now I want to save those frames in the correct speed of 5 FPS into a video. I am using these parameters:

```python
cam_fps = 5  # this variable is also used when initializing the webcam
video_params = {
    "-vcodec": "libx265",
    "-crf": 25,
    "-input_framerate": cam_fps,
    "-r": cam_fps,
}
video_writer = WriteGear(output_filename=video_file, logging=True, **video_params)
```

However, all frames from one minute still end up in a ~10 seconds video.
What am I doing wrong?

**Comment by abhiTronix** [comment]
> OpenCV (CV2) image after the other. I have now set my webcam to send only 5 FPS

Those aren't images but numpy frames. There's a big difference. And no you cannot use Webcam frames directly with DeFFcode, you need to save them on disk as images or video file and then deffcode can read them. 

> However, all frames from one minute still end up in a ~10 seconds video.
What am I doing wrong?

I already told you what's wrong in above comment https://github.com/abhiTronix/vidgear/issues/305#issuecomment-1121929740

**Comment by haimat** [comment]
> I already told you what's wrong in above comment [#305 (comment)](https://github.com/abhiTronix/vidgear/issues/305#issuecomment-1121929740)

Yes, and as response to your comment I told you that I changed my webcam to provide 5 FPS now, but even with setting both `-input_framerate` and `-r` to a a value of 5 as well I still don't end up with a video in correct speed - one minute of frames end up in ~10 seconds of video.

For the records: I switched to `cv2.VideoWriter()` now, also with a setting of 5 FPS, and there it works - the 5 FPS stream of one minute from the webcam leads to a 1-minute video as well.
