### ISSUE TITLE
[Bug]: WriteGear: ```-input_framerate``` less than 5 does not get used ?

### ISSUE THREAD

**Issue by freol35241** [abhiTronix/vidgear#306]
## Brief Description

I am trying to to use WriteGear to output a (semi) live stream to an rtsp server (as already detailed in #228)(yes, I have an rtsp server running). The input (using Camgear) is also an rtsp live stream and I am doing quite som heavy processing in between. This means:
* I am not using Threaded Queue Mode on the input (CamGear) since I will not be able to process all frames and its fine to drop any frames I dont manage to process
* I manage to process frames at about 1 fps
* I want to output the processed frames to an rtsp stream with fps 15, in effect duplicating the frames (or 25 or 30, this doesnt matter much but has to be larger than 1 since this does not work nicely with other rtsp clients such as VLC or another ffmpeg instance)

My attempt was this:

```python
sink = WriteGear(
    output_filename="rtsp://localhost:8554/cam/processed",
    logging=True,
    **{
        "-f": "rtsp",
        "-rtsp_transport": "tcp",
        "-tune": "zerolatency",
        "-preset": "ultrafast",
        "-stimeout": "1000000",
        "-input_framerate": 1,
        "-r": 15,
    }
```

But WriteGear does not use the `"-input_framerate": 1` and the resulting rtsp stream becomes unusable it seems. 

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version: 0.2.5
* Branch: PyPi
* Python version: 3.8.5
* PiP version: 20.0.2
* Operating System and version: WSL2 (Ubuntu 20.04) on Windows 10

### Expected Behavior
WriteGear honors ```"-input_framerate": 1``` so that the output stream behaves as expected.
### Actual Behavior
WriteGear disregards ```"-input_framerate": 1``` making the rtsp stream unusable by other rtsp clients

### Possible Fix

Change https://github.com/abhiTronix/vidgear/blob/master/vidgear/gears/writegear.py#L414
```python
if self.__inputframerate > 5:
    ...
```
 to:
```python
if self.__inputframerate > 0:
    ...
```
This seems to fix the issue as far as I can tell. What is the reason for this threshold anyway?

### Steps to reproduce

(Write your steps here:)

1. `docker run --rm -it -e RTSP_PROTOCOLS=tcp -p 8554:8554 aler9/rtsp-simple-server`
2. Generate a fake 1 fps stream and output via WriteGear
```python
import time
import numpy as np
from vidgear.gears import WriteGear


sink = WriteGear(
    output_filename="rtsp://localhost:8554/fake",
    logging=True,
    **{
        "-f": "rtsp",
        "-rtsp_transport": "tcp",
        "-tune": "zerolatency",
        "-preset": "ultrafast",
        "-stimeout": "1000000",
        "-input_framerate": 1,
        "-r": 15,
    }
)

while True:
    # Generate fake frame
    frame = np.random.randint(0, 255, size=(1080, 1920, 3))

    # Write to sink
    sink.write(frame)

    # Emulate fps 1
    time.sleep(1)
```
3. Try to record this rtsp using another ffmpeg instance
```
ffmpeg -rtsp_transport tcp -i rtsp://localhost:8554/fake fake_output.mp4

**Comment by abhiTronix** [comment]
@freol35241 nice catch. This piece of code ia not supposed to be there at all. This should've removed long ago as I did in Streamgear API. Could you send PR for the same to our `testing` branch? I'll merge it.

⚠ Make sure you push all commits against testing branch only.

**Comment by freol35241** [comment]
The threshold seems to be identical in the StreamGear API? 
https://github.com/abhiTronix/vidgear/blob/master/vidgear/gears/streamgear.py#L484-L490

**Comment by abhiTronix** [comment]
> The threshold seems to be identical in the StreamGear API?
https://github.com/abhiTronix/vidgear/blob/master/vidgear/gears/streamgear.py#L484-L490

@freol35241 wow, I thought I removed it. Could you change that too?, would be really helpful.

**Comment by abhiTronix** [comment]
@freol35241 Thank you again. But you've changed `pytest.xfail` in wrong line(i.e. line-229). Kindly revert commit https://github.com/abhiTronix/vidgear/pull/307/commits/1378332c2b72bb2192eaebaaaaedd64f71263e7b and make the same change at correct line(i.e. line-232).

 https://github.com/abhiTronix/vidgear/blob/a9a84e68a04f4f8380082fbc20ce12e219991109/vidgear/tests/videocapture_tests/test_camgear.py#L232

**Comment by abhiTronix** [comment]
@freol35241 Thank you and apologies for the delay. I've merged the fix successfully and will prepare the next release soon. Stay tuned.
