### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Sherensberk** [abhiTronix/vidgear#308]
## Question
How to Stream more than one camera individually (without joining more than one frame into one) with the least possible delay..
this example is almost what i want, but uses another server and join the frames: https://abhitronix.github.io/vidgear/v0.2.5-stable/help/webgear_rtc_ex/#display-two-sources-simultaneously-in-webgear_rtc

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Context
I already have an application configured and running with Startlette.
The ideal would be that the routes were mounted in this application, to avoid opening another "server".

```
# Another things...
app = Starlette(debug=True, routes=routes,)
# Other app settings...
# ...

cam0 = cv2.VideoCapture(0)
cam1 = cv2.VideoCapture(1)


cam_store = {'default': cam0, 'cam0': cam0, 'cam1':cam1}

class MultipleCameras():
    """
    Using 'set_read' actually modifies the "source" when WebRTC gear tries to "read()",
    but that sometimes this fail (connection closes, and some wesocket raise errors),
    and the delay increases sometimes when set_read()' is called.
    """
    def __init__(self, store):
        self.store = store
        self.read_id = 'default'

    def set_read(self, id):
        self.read_id = id

    def read(self):
        return (self.store.get(self.read_id, self.store['default'])).read()[1]

Source = MultipleCameras(cam_store)


options = {
    "custom_stream": Source
    "custom_data_location": "./",
    "frame_size_reduction": 50,
    "jpeg_compression_quality": 21,
}

Managers_Import(mangers)
Steramer= WebGear_RTC(logging=True, **options)

uvicorn.run(app, host="localhost", port=7000)
uvicorn.run(Steramer(), host="localhost", port=8000) # How to avoid this, and use the "Steramer" on app.

# How to :
# localhost:7000/videos/'cam1' (steram over WebRTC cam1).
# localhost:7000/videos/'cam2' (steram over WebRTC cam2).

```

### Your Environment

* VidGear version: 0.2.5
* Branch: PyPi
* Python version: 0.2.5
* PiP version: 22.0.4
* Operating System and version: (Tested in docker running at Ubuntu).

**Comment by abhiTronix** [comment]
> How to :
> localhost:7000/videos/'cam1' (steram over WebRTC cam1).
> localhost:7000/videos/'cam2' (steram over WebRTC cam2).

@Sherensberk Actually it's quit easy then you think: See my comment https://github.com/abhiTronix/vidgear/issues/224#issuecomment-865969481
