### ISSUE TITLE
[Question]: Stereo-Camera Synchronized Frame Capture

### ISSUE THREAD

**Issue by vinkaga** [abhiTronix/vidgear#311]
## Question

_Kindly describe the issue here._

In your Stackoverflow answer (https://stackoverflow.com/a/68342818), you mention that the camera streams are synchronized. The `read` API document states
> read(self) [⚓](https://abhitronix.github.io/vidgear/latest/bonus/reference/camgear/#vidgear.gears.camgear.CamGear.read)
Extracts frames synchronously from monitored queue, while maintaining a fixed-length frame buffer in the memory, and blocks the thread if the queue is full.

Assuming the videos are running at 60fps, with the Stackoverflow code example, is it able to capture frames with offset of 1/60 sec or less?

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Your Environment

* VidGear version:  Latest
* Branch: 
* Python version:  3.9
* PiP version: 
* Operating System and version: Windows 11

**Comment by abhiTronix** [comment]
> Assuming the videos are running at 60fps, with the Stackoverflow code example, is it able to capture frames with offset of 1/60 sec or less?

@vinkaga  **By offset you meant pull frame at every 1/60 second?** Sorry, I don't understand the question. But If you meant he same, then OpenCV [do not lets you time accurately pull frames](https://stackoverflow.com/a/22706622/10158117), and so as vidgear which works on OpenCV backend. It just let you delay frames by using higher delay value in `cv2.waitKey(value)`.

However, you can checkout my new library [DeFFcode ](https://github.com/abhiTronix/deffcode) library that can do whatever FFmpeg able to do. You can get frame every 1/60th of second just by doing this: 

```python
# import the necessary packages
from deffcode import FFdecoder
import cv2

# define suitable FFmpeg parameter
extraparams = {
    "-vf": "fps=1/60",
}

# initialize and formulate the decode with suitable source and params
decoder = FFdecoder(
    "foo.mp4", frame_format="bgr24", **extraparams
).formulate()

# grab the RGB24(default) frame from the decoder
for frame in decoder.generateFrame():

    # check if frame is None
    if frame is None:
        break

    # Show output window
    cv2.imshow("Output", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()
# terminate the decoder
decoder.terminate()
```
Checkout docs here: https://abhitronix.github.io/deffcode/latest/

**Comment by ykk648** [comment]
@vinkaga 
you may need to adjust offset by yourself:
https://github.com/ykk648/cv2box/blob/e915ea72adc1106345f358c3fe78355ece01ae71/cv_gears/cv_multi_video_thread.py#L60
