### ISSUE TITLE
[Bug]: Facing Issue In Some Youtube Link due to HTTP Dash Segment

### ISSUE THREAD

**Issue by DynamiteC** [abhiTronix/vidgear#314]
## Brief Description

_Kindly briefly explain the issue here._

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version: 0.2.5"` -->
* Branch: Master -->
* Python version: 3.9.13 -->
* PiP version: 22.1.2 -->
* Operating System and version: Ubuntu 18.04

### Expected Behavior

Streams should be readable by videoCapture when fetched using youtube dl

### Actual Behavior

Streams are fetched but when considering either the best stream resolution or 720p the extracted streams give the result of dash segment video

### Possible Fix

I have created a pull request to resolve this.

### Steps to reproduce

(Write your steps here:)

1. Take any youtube URL, for example [Live Match](https://www.youtube.com/watch?v=t9MkJWxj3M0l)
2. Enable Stream Mode and Logging 
3. Start Reading the frames.

```
from vidgear.gears import CamGear

stream = CamGear(
    source='https://www.youtube.com/watch?v=t9MkJWxj3M0',
    stream_mode=True,
    logging=True,
).start()
test = stream.read()


def start_stream():
    while (1):
        frame = stream.read()
        if frame is None:
            break

if __name__ == '__main__':
    start_stream()
```

### Optional

![Screenshot from 2022-06-16 12-14-03](https://user-images.githubusercontent.com/19831283/174070359-1c5dde00-d25c-4540-a33c-c6e03a10af82.png)

**Comment by abhiTronix** [comment]
Related #16 #133

**Comment by abhiTronix** [comment]
@DynamiteC Ok I tested it and your PR fixes this issue. But I need you to make some changes before accepting it, please go through **Review comments**.

**Comment by DynamiteC** [comment]
Where can i find the review comments?

**Comment by abhiTronix** [comment]
@DynamiteC Check your PR. I've left some review. Apply them as soon as possible.

**Comment by DynamiteC** [comment]
Sorry to bother you, I checked PR didn't find anything mentioned apart from conversation 6hrs earlier regard ing LF.

**Comment by abhiTronix** [comment]
@DynamiteC Apologies I failed to submit the finalized reviews. Can you see those now?

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/f0d2dad5149bcaebf31c2e4a028cfdb531e5bd21**
