### ISSUE TITLE
[Question]: How to read resolution from VideoGear?

### ISSUE THREAD

**Issue by 3togo** [abhiTronix/vidgear#317]
After setting up a stream object from VideoGear, how can I get the height and width of a frame?
self.stream = VideoGear(source="xxx.mp4").start()

**Comment by abhiTronix** [comment]
@3togo It is same as in OpenCV

### A. Through `stream` global parameter:

```python
# import required libraries
from vidgear.gears import CamGear
import cv2

# open any valid video stream(for e.g `myvideo.avi` file)
stream = CamGear(source="myvideo.avi").start()

# get whatever you want similar to as in OpenCV
width = stream.stream.get(cv2.CAP_PROP_FRAME_WIDTH )
height = stream.stream.get(cv2.CAP_PROP_FRAME_HEIGHT )
fps =  stream.stream.get(cv2.CAP_PROP_FPS)

# safely close video stream
stream.stop()
```

### B. Through `frame` dimensions:

```python
# import required libraries
from vidgear.gears import CamGear
import cv2


# open any valid video stream(for e.g `myvideo.avi` file)
stream = CamGear(source="myvideo.avi").start()

# read frames from stream
frame = stream.read()

# get resolution
(height, width) = frame.shape[:2]

# safely close video stream
stream.stop()

```

**Comment by 3togo** [comment]
many thanks

**Comment by 3togo** [comment]
width = stream.stream.get(cv2.CAP_PROP_FRAME_WIDTH ) <--- won't work
I can't find "get" in dir(stream.stream)

vidgear.__version__ =  0.3.1
dir(stream.stream) =  ['_CamGear__logging', '_CamGear__queue', '_CamGear__stream_read', '_CamGear__terminate', '_CamGear__thread', '_CamGear__thread_timeout', '_CamGear__threaded_queue_mode', '_CamGear__update', '_CamGear__youtube_mode', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'color_space', 'frame', 'framerate', 'read', 'start', 'stop', 'stream', 'ytv_metadata']
type(cap_.stream) =  <class 'vidgear.gears.camgear.CamGear'>

**Comment by 3togo** [comment]
the following shall work
height, width = stream.stream.frame.shape

**Comment by abhiTronix** [comment]
> width = stream.stream.get(cv2.CAP_PROP_FRAME_WIDTH ) <--- won't work

@3togo Yes for VideoGear API you need to access stream attribute within class as follows:

```py
stream.stream.stream.get(cv2.CAP_PROP_FRAME_WIDTH)
```

**Comment by 3togo** [comment]
many thanks
