### ISSUE TITLE
[Bug]: NetGear_Async never raises connection error

### ISSUE THREAD

**Issue by stantonius** [abhiTronix/vidgear#324]
### Description

First of all, awesome repo. Many thanks for your hard work.

I am running the NetGear_Async server on one Raspberry Pi with a Camera, sending the frames to a second RPi which is my mini home server. Currently I am trying to set up a program that continues to try to connect the NetGear_Async server to the NetGear_Async client (and isn't constrained by just a timeout parameter, as I want to log missed connections and retries).

The issue: the NetGear server always says the connection to the client is successful even when I have purposely disabled the connection. No error is raised that the connection doesn't exist - the only error message that is returned is a TimeoutError.

Note I followed the NetGear_Async + WebGear example [here](https://abhitronix.github.io/vidgear/latest/help/netgear_async_ex/)

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

When the NetGear_Async client attempts to connect to the client and no connection is made, we should get a `ValueError` (as seen around line 400 in `netgear_async.py`) and not a `TimeoutError`.

### Actual behaviour

The NetGear_Async client indicates that every connection is successful. The `ValueError` mentioned above can never be triggered. We end up with a `TimeoutError` which is misleading and bypasses the code that already exists that better diagnoses the issue.

### Steps to reproduce

The steps are the same as in the [documentation](https://abhitronix.github.io/vidgear/latest/help/netgear_async_ex/) for NetGear_Async + WebGear.

### Terminal log output

```shell
# Below messages are shown regardless of the connection state
# The appear immediately as if the connection was made instantaneously, even when I have a
# connection that will never work

03:14:11 :: NetGear_Async ::  DEBUG   :: Successfully connected to address: tcp://192.168.0.226:5454 with pattern: 1.

03:14:11 :: NetGear_Async :: CRITICAL :: Send Mode is successfully activated and ready to send data!
```

### Python Code

```python
# lines 368-c.400 of netgear_async.py

        # try connecting socket to assigned protocol, address and port
        try:
            self.__msg_socket.connect(
                self.__protocol + "://" + str(self.__address) + ":" + str(self.__port)
            )
            print("ISSUE: Connect method above is always 'successful' even when I intentionally make connection impossible")
            # finally log if successful
            if self.__logging:
                logger.debug(
                    "Successfully connected to address: {} with pattern: {}.".format(
                        (
                            self.__protocol
                            + "://"
                            + str(self.__address)
                            + ":"
                            + str(self.__port)
                        ),
                        self.__msg_pattern,
                    )
                )
            logger.critical(
                "Send Mode is successfully activated and ready to send data!"
            )
        except Exception as e:
            print("ISSUE: Exception here is never triggered")
```

### VidGear Version

0.2.6

### Python version

3.9.2

### OpenCV version

4.6.0

### Operating System version

Raspberry Pi OS (Bullseye)

### Any other Relevant Information?

I spent some time trying to solution this for an eventual PR. It seems to me that the `zmq.socket.connect` method doesn't actually return anything useful, regardless of the connection state (it always returns a `_SocketContext` object with no reference to state).

There is however a `_state` property on the `self.__msg_socket` attribute of the `NetGear_Async` class. This state changes from `0` to a unique `<PollEvent.0: 0>` object when a true socket connection is made. Perhaps awaiting for this `_state` property to change as a proxy for whether a socket connection exists and is successful?

Finally, this does look like a bug since I can never trigger the ValueError when a connection is not made. However I will jump on the Gitter community to ask a broader question around how to manage connection retries between NetGear_Async server and client.

**Comment by abhiTronix** [comment]
Hi @stantonius, thanks for opening issue here. What the `pattern` parameter value you're using?

**Comment by abhiTronix** [comment]
> The issue: the NetGear server always says the connection to the client is successful even when I have purposely disabled the connection.

Disabled? How?

**Comment by stantonius** [comment]
> Hi @stantonius, thanks for opening issue here. What's the `pattern` parameter value you're using?

Ive tried with both 0 and 1. Same behaviour.

**Comment by stantonius** [comment]
> > The issue: the NetGear server always says the connection to the client is successful even when I have purposely disabled the connection.
> 
> Disabled? How? 

Apologies. Misleading language. What I meant is I either never opened the client, or used a different ip address that was incorrect, both as tests.

**Comment by abhiTronix** [comment]
@stantonius Thanks for the clarification. While I test this on system, Could you check if you can reproduce this error with NetGear+WebGear using this example: https://abhitronix.github.io/vidgear/latest/help/netgear_ex/#using-netgear-with-webgear

**Comment by abhiTronix** [comment]
@stantonius OK I've found the reason and it is working as it should be. An advantage of ZeroMQ is that you do not have to `connect` only after the client was started(i.e when `bind()` is called on client), also meaning that it is ok to `connect` even if the connection to the client is temporarily down. ZeroMQ will keep the connection (request) and try again.

The docs for [`zmq_connect()`](http://api.zeromq.org/3-2%3azmq-connect) states that:

> For most transports and socket types the connection is not performed immediately but as needed by ØMQ. Thus a successful call to zmq_connect() does not mean that the connection was or could actually be established. Because of this, for most transports and socket types the order in which a server socket is bound and a client socket is connected to it does not matter.

As seen in the docs, **there is no error code for non-responding/existing endpoint**. 

### So what's the Solution?

The docs for [`zmq_connect()`](http://api.zeromq.org/3-2%3azmq-connect) further states that:

> The first exception is when using the inproc:// transport: you must call `zmq_bind()` before calling zmq_connect(). The second exception are ZMQ_PAIR sockets, which do not automatically reconnect to endpoints.

So in your case, you should use protocol value as `protocol="inproc"` to make Server(running `connect()`) throw error if called before Client(running `bind()`). But the problem is both NetGear and NetGear_Async donot support `inproc` protocol as if now.

**Comment by abhiTronix** [comment]
@stantonius Never mind this problem is unsolvable. 

As the name implies, `inproc` sockets can only be used within the same process. That means if you have two threads in the same process with only one Context define(you will only call `zmq.Context()` once in your program), you could use inproc, otherwise you cannot.

The [documentation](http://api.zeromq.org/2-1:zmq-inproc) is very clear on this point:

> The in-process transport passes messages via memory directly between threads sharing a single ØMQ context.

So using ZMQ on two different machines with inproc is impossible.

**Comment by stantonius** [comment]
Wow thanks so much for the quick and hard work @abhiTronix .

I get the above - certainly the limitations regarding ZeroMQ and how it works to wait for connections. However that still means there is code that is never reachable in the `NetGear_Async` class - shown below.

```python
try:
            self.__msg_socket.connect(
                self.__protocol + "://" + str(self.__address) + ":" + str(self.__port)
            )

```

Based on your research re ZeroMQ, this isn't so much as a breaking change as it is slightly misleading config and error/stacktrace. What I mean is that the *exception* from the `try` loop above can never be triggered if the `connect` never returns an error code as you mention. Therefore we always get a TimeoutError when it was actually a connection *issue* (not an error as you rightfully have validated from the ZeroMQ docs)

As you mentioned, I tried the sync NetGear + WebGear setup and didn't encounter this issue, but it then dawned on me that it wouldn't because those Gears dont use. However I did correctly see the right exception here - not a TimeoutError but rather a `[NetGear:ERROR] :: Failed to connect address` error)

**Comment by abhiTronix** [comment]
> However that still means there is code that is never reachable in the NetGear_Async class - shown below.
> 
> try:
>             self.__msg_socket.connect(
>                 self.__protocol + "://" + str(self.__address) + ":" + str(self.__port)
>             )
> Based on your research re ZeroMQ, this isn't so much as a breaking change as it is slightly misleading config and error/stacktrace. What I mean is that the exception from the try loop above can never be triggered if the connect never returns an error code as you mention. Therefore we always get a TimeoutError when it was actually a connection issue (not an error as you rightfully have validated from the ZeroMQ docs)

@stantonius Yeah you're right. But It can fail if someone put wrong IP that is unreachable or even malformed. I'll change the docs and let users know that we'll get a `TimeoutError` in NetGear Async for connection errors.

> As you mentioned, I tried the sync NetGear + WebGear setup and didn't encounter this issue, but it then dawned on me that it wouldn't because those Gears dont use ZeroMQ protocol. However I did correctly see the right exception here - not a TimeoutError but rather a [NetGear:ERROR] :: Failed to connect address error)

@stantonius NetGear worked maybe because we are using polling here or may be because we aren't using `AsyncIO` package of ZMQ here. You have to ask ZMQ developers for this inconsistent behavior across its API. Or It might be mention somewhere in docs we aren't aware of. But since NetGear worked for you, and NetGear_Async is just experimental extension of NetGear, I'll say this issue is resolved for now.

**Comment by stantonius** [comment]
OK cool. Thanks again for all your hard work.
