### ISSUE TITLE
[Question]: Why youtube stream does not start with writegear?

### ISSUE THREAD

**Issue by pentadotddot** [abhiTronix/vidgear#328]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

I have tried basically everything I found on the internet, but nothing works for me to start a youtube livestream using opencv pipeing into ffmpeg.

I have an rtsp stream, which I would like to post process via opencv and other python libs, and then stream it to youtube.

I stumbled upon write gears youtube streaming solution: 
```python
# import required libraries
from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import cv2

# define video source
VIDEO_SOURCE = "/home/foo/foo.mp4"

# Open stream
stream = CamGear(source=VIDEO_SOURCE, logging=True).start()

# define required FFmpeg optimizing parameters for your writer
# [NOTE]: Added VIDEO_SOURCE as audio-source, since YouTube rejects audioless streams!
output_params = {
    "-i": VIDEO_SOURCE,
    "-acodec": "aac",
    "-ar": 44100,
    "-b:a": 712000,
    "-vcodec": "libx264",
    "-preset": "medium",
    "-b:v": "4500k",
    "-bufsize": "512k",
    "-pix_fmt": "yuv420p",
    "-f": "flv",
}

# [WARNING] Change your YouTube-Live Stream Key here:
YOUTUBE_STREAM_KEY = "xxxx-xxxx-xxxx-xxxx-xxxx"

# Define writer with defined parameters and
writer = WriteGear(
    output_filename="rtmp://a.rtmp.youtube.com/live2/{}".format(YOUTUBE_STREAM_KEY),
    logging=True,
    **output_params
)

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # write frame to writer
    writer.write(frame)

# safely close video stream
stream.stop()

# safely close writer
writer.close()
```

and it runs properly, but then my youtube live does not start.

I inputed the correct stream api key (Ive tested it in other ways and it started livestream properly),
I have a conda environment, all of my libs are up to date...

please help:S

### VidGear Version

newest

### Python version

Python 3.9.12

### Operating System version

ubuntu 18.04

**Comment by abhiTronix** [comment]
@pentadotddot Where are the terminal logs? I atleast need those to say anything.

**Comment by abhiTronix** [comment]
> VidGear Version
newest

Also, what is this "latest" ?

**Comment by pentadotddot** [comment]
This is what I can read on my terminal when running:

03:03:50 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6
03:03:50 ::    CamGear    ::  DEBUG   :: Enabling Threaded Queue Mode for the current video source!
03:03:51 ::    Helper     :: WARNING  :: Specified directory `/home/mobilrouter/rtmp_YT/rtmp:/a.rtmp.youtube.com/live2` doesn't exists or valid.
03:03:51 ::   WriteGear   :: WARNING  :: `rtmp://a.rtmp.youtube.com/live2/9a7p-647j-2k7y-5677-3v0c` isn't a valid system path or directory. Skipped!
03:03:51 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.
03:03:51 ::   WriteGear   ::  DEBUG   :: Output Parameters: {'-i': 'rtsp://admin:Arviz987@10.113.166.83:554/stream1', '-f': 'flv', '-rtsp_transport': 'tcp', '-force_key_frames': 'expr:gte(t,n_forced*2)', '-reorder_queue_size': '4000', '-max_delay': '10000000', '-acodec': 'aac', '-ar': 44100, '-b:a': 712000, '-vcodec': 'libx264', '-preset': 'medium', '-b:v': '4500k', '-bufsize': '2048k', '-pix_fmt': 'yuvj420p'}
03:03:51 ::    Helper     ::  DEBUG   :: Final FFmpeg Path: ffmpeg
03:03:51 ::    Helper     ::  DEBUG   :: FFmpeg validity Test Passed!
03:03:51 ::    Helper     ::  DEBUG   :: Found valid FFmpeg Version: `b'9c33b2f'` installed on this system
03:03:51 ::   WriteGear   ::  DEBUG   :: Found valid FFmpeg executable: `ffmpeg`.
03:03:51 ::   WriteGear   ::  DEBUG   :: Checking whether output_filename is a valid URL..
03:03:51 ::    Helper     ::  DEBUG   :: URL scheme `rtmp` is supported by FFmpeg.
03:03:51 ::   WriteGear   ::  DEBUG   :: URL:`rtmp://a.rtmp.youtube.com/live2/9a7p-647j-2k7y-5677-3v0c` is successfully configured for streaming.
03:03:51 ::   WriteGear   ::  DEBUG   :: Forced termination is enabled for this FFmpeg process.
03:03:51 ::   WriteGear   ::  DEBUG   :: Compression Mode with FFmpeg backend is configured properly.
03:03:52 ::   WriteGear   ::  DEBUG   :: InputFrame => Height:1520 Width:2688 Channels:3
03:03:52 ::   WriteGear   ::  DEBUG   :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 2688x1520 -pix_fmt bgr24 -i - -i rtsp://admin:Arviz987@10.113.166.83:554/stream1 -f flv -rtsp_transport tcp -force_key_frames expr:gte(t,n_forced*2) -reorder_queue_size 4000 -max_delay 10000000 -acodec aac -ar 44100 -b:a 712000 -vcodec libx264 -preset medium -b:v 4500k -bufsize 2048k -pix_fmt yuvj420p -crf 18 rtmp://a.rtmp.youtube.com/live2/9a7p-647j-2k7y-5677-3v0c`
ffmpeg version 9c33b2f Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3.0 (crosstool-NG 1.24.0.133_b0863d8_dirty)
  configuration: --prefix=/home/mobilrouter/anaconda3/envs/ppe_env --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1627813612080/_build_env/bin/x86_64-conda-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame --pkg-config=/home/conda/feedstock_root/build_artifacts/ffmpeg_1627813612080/_build_env/bin/pkg-config
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 2451456 kb/s
    Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 2688x1520, 2451456 kb/s, 25 tbr, 25 tbn, 25 tbc
[rtsp @ 0x564b5167ad40] max delay reached. need to consume packet
[rtsp @ 0x564b5167ad40] RTP: missed 51 packets
[h264 @ 0x564b5167e180] error while decoding MB 48 36, bytestream -5
[h264 @ 0x564b5167e180] concealing 9913 DC, 9913 AC, 9913 MV errors in P frame
Input #1, rtsp, from 'rtsp://admin:Arviz987@10.113.166.83:554/stream1':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.280000, bitrate: N/A
    Stream #1:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1520 [SAR 95:98 DAR 12:7], 25 fps, 25 tbr, 90k tbn, 50 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[swscaler @ 0x564b51809900] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x564b516c33c0] VBV bufsize set but maxrate unspecified, ignored
[libx264 @ 0x564b516c33c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x564b516c33c0] profile High, level 5.0, 4:2:0, 8-bit
[libx264 @ 0x564b516c33c0] 264 - core 161 r3030M 8bd6d28 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, flv, to 'rtmp://a.rtmp.youtube.com/live2/9a7p-647j-2k7y-5677-3v0c':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264) ([7][0][0][0] / 0x0007), yuvj420p(pc), 2688x1520, q=-1--1, 4500 kb/s, 25 fps, 1k tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/4500000 buffer size: 2048000 vbv_delay: N/A
frame=    5 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   [rawvideo @ 0x564b516771c0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
frame=   14 fps= 13 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   frame=   26 fps= 17 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   frame=   40 fps= 19 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   frame=   47 fps= 16 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   frame=   58 fps= 16 q=23.0 size=     495kB time=-00:00:00.03 bitrate=N/A speed=Nframe=   63 fps= 15 q=23.0 size=     774kB time=00:00:00.16 bitrate=39379.0kbitsframe=   69 fps= 14 q=23.0 size=    1013kB time=00:00:00.40 bitrate=20686.2kbitsframe=   75 fps= 14 q=23.0 size=    1398kB time=00:00:00.64 bitrate=17870.3kbitsframe=   81 fps= 13 q=23.0 size=    1641kB time=00:00:00.88 bitrate=15260.8kbitsframe=   87 fps= 13 q=23.0 size=    2015kB time=00:00:01.12 bitrate=14728.5kbitsframe=   92 fps= 13 q=23.0 size=    2239kB time=00:00:01.32 bitrate=13887.9kbitsframe=   99 fps= 13 q=23.0 size=    2620kB time=00:00:01.60 bitrate=13408.0kbits^Xframe=  103 fps= 13 q=23.0 size=    2806kB time=00:00:01.76 bitrate=13055.0kbiframe=  111 fps= 13 q=23.0 size=    3542kB time=00:00:02.08 bitrate=13945.0kbitsf

**Comment by pentadotddot** [comment]
> > VidGear Version
> > newest
> 
> Also, what is this "latest" ?

newest -> latest

**Comment by abhiTronix** [comment]
@pentadotddot Edit your comment you should never paste your YouTube Key on a public forum.

**Comment by abhiTronix** [comment]
> -i rtsp://admin:Arviz987@10.113.166.83:554/stream1

@pentadotddot Does this source contains any audio? I'm not seeing it in logs.

**Comment by pentadotddot** [comment]
> > -i rtsp://admin:Arviz987@10.113.166.83:554/stream1
> 
> @pentadotddot Does this source contains any audio? I'm not seeing it in logs.

no it does not include audio

**Comment by abhiTronix** [comment]
@pentadotddot Then use this code instead and you'll able to stream to YouTube Live:

```python
# import required libraries
from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import cv2

# define and open video source
stream = CamGear(source="/home/foo/foo.mp4", logging=True).start()

# define required FFmpeg parameters for your writer
output_params = {
    "-clones": ["-f", "lavfi", "-i", "anullsrc"],
    "-vcodec": "libx264",
    "-preset": "medium",
    "-b:v": "4500k",
    "-bufsize": "512k",
    "-pix_fmt": "yuv420p",
    "-f": "flv",
}

# [WARNING] Change your YouTube-Live Stream Key here:
YOUTUBE_STREAM_KEY = "xxxx-xxxx-xxxx-xxxx-xxxx"

# Define writer with defined parameters
writer = WriteGear(
    output_filename="rtmp://a.rtmp.youtube.com/live2/{}".format(YOUTUBE_STREAM_KEY),
    logging=True,
    **output_params
)

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # write frame to writer
    writer.write(frame)

# safely close video stream
stream.stop()

# safely close writer
writer.close()
```

If you get stuck anywhere, let me know. Also, drop a 🌟 if you like it.

**Comment by abhiTronix** [comment]
Updated Example is Here: https://abhitronix.github.io/vidgear/v0.3.0-dev/help/writegear_ex/#using-writegears-compression-mode-for-youtube-live-streaming
