### ISSUE TITLE
[Bug]: When playing a live stream using opencv after several hours the program stops.

### ISSUE THREAD

**Issue by salar-dev** [abhiTronix/vidgear#334]
### Description

When playing a live stream using opencv after several hours the program stops.
and this is shown in the terminal

tls @ 0x7f866699c300] Error in the pull function.
[tls @ 0x7f866699ba40] Error in the pull function.
[tls @ 0x7f866bf40880] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf4db40] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866be61940] Error in the pull function.
[tls @ 0x7f866bf53e00] Error in the pull function.
[tls @ 0x7f866699c840] Error in the pull function.
[tls @ 0x7f866699c840] Error in the pull function.
[tls @ 0x7f866699bc00] Error in the pull function.
[tls @ 0x7f866699c840] Error in the pull function.
[tls @ 0x7f866bf60c80] Error in the pull function.
[tls @ 0x7f866699be80] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf53e00] Error in the pull function.
[tls @ 0x7f86669cbe40] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f866bf53e00] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f8655055d00] Error in the pull function.
[tls @ 0x7f866bfdef40] Error in the pull function.
[tls @ 0x7f8655f70340] Error in the pull function.
[tls @ 0x7f8655f80ec0] Error in the pull function.
[tls @ 0x7f8655f6d040] Error in the pull function.
[tls @ 0x7f8655f81880] Error in the pull function.
[tls @ 0x7f8655fa0900] Error in the pull function.
[tls @ 0x7f8655f81880] Error in the pull function.
[tls @ 0x7f8655fbcd00] Error in the pull function.
[tls @ 0x7f8655fb3780] Error in the pull function.
[tls @ 0x7f865509a9c0] Error in the pull function.
[tls @ 0x7f8655f81880] Error in the pull function.
[tls @ 0x7f8655ffdb80] Error in the pull function.
[tls @ 0x7f8655ff8fc0] Error in the pull function.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

run code
No problems
4 to 6 hours later
video stops

### Actual behaviour

run code
No problems
4 to 6 hours later
video stops

### Steps to reproduce

run code
No problems
4 to 6 hours later
video stops

### Terminal log output

```shell
08:25:19 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6
08:25:19 ::    Helper     :: WARNING  :: GStreamer not found!
08:25:19 ::    CamGear    ::   INFO   :: Verifying Streaming URL using yt-dlp backend. Please wait...
08:25:23 ::    CamGear    ::   INFO   :: [Backend] :: Streaming URL is fully supported. Available Streams are: [144p, 240p, 360p, 480p, 720p, 1080p, best, worst]
08:25:23 ::    CamGear    :: WARNING  :: Livestream URL detected. It is advised to use GStreamer backend(`cv2.CAP_GSTREAMER`) with it.
[tls @ 0x7f866699c300] Error in the pull function.
[tls @ 0x7f866699ba40] Error in the pull function.
[tls @ 0x7f866bf40880] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf4db40] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866be61940] Error in the pull function.
[tls @ 0x7f866bf53e00] Error in the pull function.
[tls @ 0x7f866699c840] Error in the pull function.
[tls @ 0x7f866699c840] Error in the pull function.
[tls @ 0x7f866699bc00] Error in the pull function.
[tls @ 0x7f866699c840] Error in the pull function.
[tls @ 0x7f866bf60c80] Error in the pull function.
[tls @ 0x7f866699be80] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf53e00] Error in the pull function.
[tls @ 0x7f86669cbe40] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f866bf53e00] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f866be487c0] Error in the pull function.
[tls @ 0x7f866bf59440] Error in the pull function.
[tls @ 0x7f8655055d00] Error in the pull function.
[tls @ 0x7f866bfdef40] Error in the pull function.
[tls @ 0x7f8655f70340] Error in the pull function.
[tls @ 0x7f8655f80ec0] Error in the pull function.
[tls @ 0x7f8655f6d040] Error in the pull function.
[tls @ 0x7f8655f81880] Error in the pull function.
[tls @ 0x7f8655fa0900] Error in the pull function.
[tls @ 0x7f8655f81880] Error in the pull function.
[tls @ 0x7f8655fbcd00] Error in the pull function.
[tls @ 0x7f8655fb3780] Error in the pull function.
[tls @ 0x7f865509a9c0] Error in the pull function.
[tls @ 0x7f8655f81880] Error in the pull function.
[tls @ 0x7f8655ffdb80] Error in the pull function.
[tls @ 0x7f8655ff8fc0] Error in the pull function.
```

### Python Code

```python
from vidgear.gears import CamGear
import cv2

stream = CamGear(source='live-video-url', stream_mode = True, logging=False).start() # YouTube Video URL as input

while True:
    frame = stream.read()
    cv2.imshow("Output Frame", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
```

### VidGear Version

0.2.6

### Python version

3.9.6

### OpenCV version

4.6.0

### Operating System version

mac, windows 10

**Comment by abhiTronix** [comment]
This not a Vidgear related bug but the FFmpeg backend your installed OpenCV binaries are using. As mentioned clearly in docs, you need to Install OpenCV with Gstreamer Backend to solve this error: https://abhitronix.github.io/vidgear/latest/help/camgear_faqs/#how-to-compile-opencv-with-gstreamer-support
