### ISSUE TITLE
[Proposal]: Allow configuration of input parameters

### ISSUE THREAD

**Issue by HeeebsInc** [abhiTronix/vidgear#335]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) and found nothing related to my idea.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and it doesn't mention anything about my idea.
- [X] To my best knowledge, my idea wouldn't break something for other users.

### Describe your Idea

Like output params, allow configuration of input parameters when using WriteGear.  I recently faced an issue where I needed to have 
-framerate 1 
in the input parameters and the only way to get that working with vidgear was to modify the source code and replace
input_parameters ={}   --> input_parameters= {'framerate': 1}
inside of writegear.py

### Use Cases

when creating a video that you instead of be encoded at 1 fps.  Using h265, trying to do this without having the additional input parameter created a video that is not actually 1 fps.

**Comment by abhiTronix** [comment]
> Like output params, allow configuration of input parameters when using WriteGear. I recently faced an issue where I needed to have
> -framerate 1
> in the input parameters and the only way to get that working with vidgear was to modify the source code and replace
> input_parameters ={} --> input_parameters= {'framerate': 1}
> inside of writegear.py

@HeeebsInc That's what [`-ffpreheaders`](https://abhitronix.github.io/vidgear/latest/gears/writegear/compression/params/#supported-parameters) exclusive attribute is for in WriteGear API's `output_params` dictionary parameter. Kindly go through docs properly before opening issue here.

**Comment by abhiTronix** [comment]
@HeeebsInc Also, `'framerate': 1` can be assigned by putting `output_params = {"-input_framerate": 1.0}`.

**Comment by HeeebsInc** [comment]
good afternoon @abhiTronix - I got the pipeline working only by modifying the source code.  Before modifying and pulling the most recent release I see the parsing logic for ffpreheaders is not working.  When passing
```
output_params = {
            '-ffpreheaders': ['-framerate', 1],
            '-c:v': 'libx265',
            '-x265-params': '"crf=0:lossless=1:qp=0:keyint=1:ref=1:no-open-gop=1:weightp=0:weightb=0:cutree=0:rc-lookahead=0:bframes=0:scenecut=0:b-adapt=0:repeat-headers=1"',
            '-pix_fmt': 'yuv420p',
            '-r': 1
}
out = WriteGear(output_filename=video_file, logging = True, **output_params)
```

I get the following output 
```
18:20:12 :: WriteGear :: DEBUG :: Compression Mode is enabled therefore checking for valid FFmpeg executables.
18:20:12 :: WriteGear :: DEBUG :: Output Parameters: {'-ffpreheaders': ['-framerate', 1], '-c:v': 'libx265', '-x265-params': '"crf=0:lossless=1:qp=0:keyint=1:ref=1:no-open-gop=1:weightp=0:weightb=0:cu
tree=0:rc-lookahead=0:bframes=0:scenecut=0:b-adapt=0:repeat-headers=1"', '-pix_fmt': 'yuv420p', '-r': 1}
18:20:12 :: Helper :: DEBUG :: Final FFmpeg Path: ffmpeg
18:20:12 :: Helper :: DEBUG :: FFmpeg validity Test Passed!
18:20:12 :: Helper :: DEBUG :: Found valid FFmpeg Version: `b'3.4.11-0ubuntu0.1'` installed on this system
18:20:12 :: WriteGear :: DEBUG :: Found valid FFmpeg executables: `ffmpeg`.
18:20:12 :: WriteGear :: DEBUG :: Compression Mode is configured properly!
[DEEPSTREAM] (TE--2) Creating Video /ze/data/Experiments/DAB/D_2/Vid_960_540.mp4..:   0%|                                                                                      | 0/1000 [00:00<?, ?it/s]
18:20:12 :: WriteGear :: DEBUG :: InputFrame => Height:540 Width:960 Channels:3
18:20:12 :: WriteGear :: DEBUG :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 960x540 -pix_fmt bgr24 -i - -ffpreheaders ['-framerate', 1] -x265-params "crf=0:lossless=1:qp=0:k
eyint=1:ref=1:no-open-gop=1:weightp=0:weightb=0:cutree=0:rc-lookahead=0:bframes=0:scenecut=0:b-adapt=0:repeat-headers=1" -pix_fmt yuv420p -r 1 -vcodec libx265 -crf 18 -preset fast /ze/data/Experiments
/DAB/D_2/Vid_960_540.mp4`
```

Vid gear is passing pre-headers as a list in the ffmpeg argument when it should be parsing it and passing in each argument of the list.   so should be the following

ffmpeg -y -f rawvideo -vcodec rawvideo -s 960x540 -pix_fmt bgr24 -i - -framerate 1 -x265-params "crf=0:lossless=1:qp=0:k

**Comment by HeeebsInc** [comment]
`ffmpeg -y -f rawvideo -vcodec rawvideo -framerate 1 -s 960x540 -pix_fmt bgr24 -i - -framerate 1 -x265-params "crf=0:lossless=1:qp=0:keyint=1:ref=1:no-open-gop=1:weightp=0:weightb=0:cutree=0:rc-lookahead=0:bframes=0:scenecut=0:b-adapt=0:repeat-headers=1" -pix_fmt yuv420p -r 1 -vcodec libx265 -crf 18 -preset fast /Vid.mp4`

this is the command I was hoping for.  In order to get -framerate to the left you need to modify the vidgear.py file and add 
input_parameters={'-framerate': 1}

or am I missing something?  -ffpreheaders: ['-framerate', 1] does not work

**Comment by HeeebsInc** [comment]
following up on this again - 

in order to allow for input_framerate less than 5, we need to modify this

![image](https://user-images.githubusercontent.com/60490377/218168983-a535043a-6474-46ed-96c8-dff4041becb4.png)
