### ISSUE TITLE
[Question]: I am trying to upscale a rtsp stream and convert it back to rtsp stream but getting error

### ISSUE THREAD

**Issue by SawantMyelin** [abhiTronix/vidgear#336]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

So, i am doing a project in which i am taking in a rtsp stream and upscaling it using my own trained ML model and then converting back the live frames into an rtsp stream but after processing 45 frames, the code throws an error saying "av_interleaved_write_frame(): Broken pipe
frame=   47 fps=2.5 q=23.0 size=N/A time=-00:00:00.07 bitrate=N/A speed=N/A  " and also "WriteGear   ::  ERROR   :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs! ".  Can someone please tell me what am i doing wrong here. I am reading the frames using opencv and then doing the upscaling on the frames and then writing them back to the vidgear.write.

### VidGear Version

0.2.6

### Python version

3.10.6

### Operating System version

Ubuntu

**Comment by abhiTronix** [comment]
@SawantMyelin You need to share code or terminal output with `logging=True`, so that we will be able to debug the problem.

**Comment by SawantMyelin** [comment]
Thanks for the quick reply, I am pasting my code below .

from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import cv2
import datetime
import time
import tensorflow as tf
# import matplotlib.pyplot as plt
import numpy as np
import os
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)



height=480
width=640

model = tf.keras.models.load_model('/home/sawant/dashnet_v1/saved_model_2x_e92_dashnet_v1')


class Reconnecting_CamGear:
    def __init__(self, cam_address, reset_attempts=50, reset_delay=5):
        self.cam_address = cam_address
        self.reset_attempts = reset_attempts
        self.reset_delay = reset_delay
        self.source = CamGear(source=self.cam_address).start()
        self.running = True

    def read(self):
        if self.source is None:
            return None
        if self.running and self.reset_attempts > 0:
            frame = self.source.read()
            if frame is None:
                self.source.stop()
                self.reset_attempts -= 1
                print(
                    "Re-connection Attempt-{} occured at time:{}".format(
                        str(self.reset_attempts),
                        datetime.datetime.now().strftime("%m-%d-%Y %I:%M:%S%p"),
                    )
                )
                time.sleep(self.reset_delay)
                self.source = CamGear(source=self.cam_address).start()
                # return previous frame
                return self.frame
            else:
                self.frame = frame
                return frame
        else:
            return None

    def stop(self):
        self.running = False
        self.reset_attempts = 0
        self.frame = None
        if not self.source is None:
            self.source.stop()

output_params = {"-f": "rtsp", "-rtsp_transport": "tcp"}
writer = WriteGear(
    output_filename="rtsp://localhost:8554/mystream", logging=True, **output_params
)

if __name__ == "__main__":
    # open any valid video stream
    stream = Reconnecting_CamGear(
        cam_address="rtsp://192.168.1.193:5540/ch0",
        reset_attempts=20,
        reset_delay=5,
    )


    # loop over
    while True:

        # read frames from stream
        frame = stream.read()

        # check for frame if None-type
        if frame is None:
            break

        cv2.imwrite('img.png',frame)

        # Show output window
        cv2.imshow("Output", frame)

        im = cv2.imread('img.png')
        yuv = cv2.cvtColor(im, cv2.COLOR_RGB2YUV)
        y = yuv[:,:,0] / 255.
        uv = yuv[:,:,1:]
        y = y[tf.newaxis,..., tf.newaxis]
        mat = model.predict(y)

        mat = np.reshape(mat, (2*height, 2*width, 1))
        mat = np.clip(mat, 0, 1)
        mat = mat * 255
        mat = mat.astype('uint8')
        uv = cv2.resize(uv,(2 * width, 2 * height))
        hr = np.concatenate((mat,uv),axis=2)
        rgb = cv2.cvtColor(hr,cv2.COLOR_YUV2RGB)


        # {do something with the frame here}
        writer.write(rgb)

        # check for 'q' key if pressed
        key = cv2.waitKey(1) & 0xFF
        if key == ord("q"):
            break

    # close output window
    cv2.destroyAllWindows()

    # safely close video stream
    stream.stop()

    writer.close()


**OUTPUT:**
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
16:51:46 ::    Helper     :: WARNING  :: Specified directory `/home/sawantkumar/rtsp_to_rtsp/rtsp:/localhost:8554` doesn't exists or valid.
16:51:46 ::   WriteGear   :: WARNING  :: `rtsp://localhost:8554/mystream` isn't a valid system path or directory. Skipped!
16:51:46 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.
16:51:46 ::   WriteGear   ::  DEBUG   :: Output Parameters: {'-f': 'rtsp', '-rtsp_transport': 'tcp'}
16:51:46 ::    Helper     ::  DEBUG   :: Final FFmpeg Path: ffmpeg
16:51:46 ::    Helper     ::  DEBUG   :: FFmpeg validity Test Passed!
16:51:46 ::    Helper     ::  DEBUG   :: Found valid FFmpeg Version: `b'4.2.7-0ubuntu0.1'` installed on this system
16:51:46 ::   WriteGear   ::  DEBUG   :: Found valid FFmpeg executable: `ffmpeg`.
16:51:46 ::   WriteGear   ::  DEBUG   :: Checking whether output_filename is a valid URL..
16:51:46 ::    Helper     ::  DEBUG   :: URL scheme `rtsp` is supported by FFmpeg.
16:51:46 ::   WriteGear   ::  DEBUG   :: URL:`rtsp://localhost:8554/mystream` is successfully configured for streaming.
16:51:46 ::   WriteGear   ::  DEBUG   :: Compression Mode with FFmpeg backend is configured properly.
1/1 [==============================] - 0s 486ms/step
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?eb9c8b2e-a8f0-45a3-9220-1235ddbbde91)
16:51:49 ::   WriteGear   ::  DEBUG   :: InputFrame => Height:960 Width:1280 Channels:3
16:51:49 ::   WriteGear   ::  DEBUG   :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 1280x960 -pix_fmt bgr24 -i - -f rtsp -rtsp_transport tcp -vcodec libx264 -crf 18 -preset fast rtsp://localhost:8554/mystream`

ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 737280 kb/s
    Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 1280x960, 737280 kb/s, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 0x558bf9d7a300] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x558bf9d7a300] profile High 4:4:4 Predictive, level 3.2, 4:4:4 8-bit
[libx264 @ 0x558bf9d7a300] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=18.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, rtsp, to 'rtsp://localhost:8554/mystream':
  Metadata:
    encoder         : Lavf58.29.100
...
    Metadata:
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1

**Comment by SawantMyelin** [comment]
1/1 [==============================] - 0s 369ms/step
1/1 [==============================] - 0s 357ms/step
1/1 [==============================] - 0s 362ms/step
frame=    4 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 354ms/step
1/1 [==============================] - 0s 348ms/step
frame=    6 fps=3.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 374ms/step
1/1 [==============================] - 0s 340ms/step
frame=    8 fps=3.1 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 346ms/step
1/1 [==============================] - 0s 359ms/step
frame=   10 fps=2.9 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 366ms/step
1/1 [==============================] - 0s 353ms/step
frame=   12 fps=2.8 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 416ms/step
1/1 [==============================] - 0s 362ms/step
frame=   14 fps=2.7 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 415ms/step
1/1 [==============================] - 0s 332ms/step
frame=   16 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 341ms/step
1/1 [==============================] - 0s 356ms/step
frame=   18 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 342ms/step
1/1 [==============================] - 0s 341ms/step
frame=   20 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 342ms/step
1/1 [==============================] - 0s 343ms/step
frame=   22 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 346ms/step
1/1 [==============================] - 0s 349ms/step
frame=   24 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 351ms/step
1/1 [==============================] - 0s 345ms/step
frame=   26 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 339ms/step
1/1 [==============================] - 0s 333ms/step
frame=   28 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 357ms/step
16:52:01 ::   WriteGear   ::  DEBUG   :: Terminating WriteGear Processes.
av_interleaved_write_frame(): Broken pipe0:00:00.00 bitrate=N/A speed=   0x    
frame=   29 fps=2.4 q=23.0 Lsize=N/A time=-00:00:00.07 bitrate=N/A speed=N/A    
video:125kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x558bf9d7a300] frame I:1     Avg QP:12.33  size:127140
[libx264 @ 0x558bf9d7a300] frame P:7     Avg QP:14.41  size: 11217
[libx264 @ 0x558bf9d7a300] frame B:21    Avg QP:16.84  size:  1265
[libx264 @ 0x558bf9d7a300] consecutive B-frames:  3.4%  0.0%  0.0% 96.6%
[libx264 @ 0x558bf9d7a300] mb I  I16..4: 16.0%  0.0% 84.0%
[libx264 @ 0x558bf9d7a300] mb P  I16..4:  1.9%  0.0%  1.5%  P16..4: 24.5%  6.4%  5.1%  0.0%  0.0%    skip:60.5%
[libx264 @ 0x558bf9d7a300] mb B  I16..4:  0.4%  0.0%  0.0%  B16..8:  5.8%  1.1%  0.0%  direct: 1.6%  skip:91.2%  L0:49.2% L1:49.3% BI: 1.5%
[libx264 @ 0x558bf9d7a300] coded y,u,v intra: 66.5% 31.0% 24.8% inter: 3.5% 2.4% 1.8%
[libx264 @ 0x558bf9d7a300] i16 v,h,dc,p: 33% 32% 20% 15%
[libx264 @ 0x558bf9d7a300] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 18% 12%  6% 14% 10%  8%  4%  5%
[libx264 @ 0x558bf9d7a300] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x558bf9d7a300] ref P L0: 70.6% 29.4%
[libx264 @ 0x558bf9d7a300] ref B L0: 78.7% 21.3%
[libx264 @ 0x558bf9d7a300] ref B L1: 94.5%  5.5%
[libx264 @ 0x558bf9d7a300] kb/s:1601.59
Conversion failed!

**Comment by SawantMyelin** [comment]
1/1 [==============================] - 0s 355ms/step
1/1 [==============================] - 0s 344ms/step
1/1 [==============================] - 0s 347ms/step
frame=    4 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 356ms/step
1/1 [==============================] - 0s 350ms/step
frame=    6 fps=3.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 349ms/step
1/1 [==============================] - 0s 347ms/step
frame=    8 fps=3.1 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 349ms/step
1/1 [==============================] - 0s 342ms/step
frame=   10 fps=3.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 350ms/step
1/1 [==============================] - 0s 338ms/step
frame=   12 fps=2.8 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 342ms/step
1/1 [==============================] - 0s 341ms/step
frame=   14 fps=2.8 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 347ms/step
1/1 [==============================] - 0s 344ms/step
frame=   16 fps=2.7 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 356ms/step
1/1 [==============================] - 0s 341ms/step
frame=   18 fps=2.7 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 345ms/step
1/1 [==============================] - 0s 346ms/step
frame=   20 fps=2.7 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 353ms/step
1/1 [==============================] - 0s 339ms/step
frame=   22 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 353ms/step
1/1 [==============================] - 0s 353ms/step
frame=   24 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 391ms/step
1/1 [==============================] - 0s 320ms/step
frame=   26 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 369ms/step
1/1 [==============================] - 0s 350ms/step
frame=   28 fps=2.6 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 328ms/step
1/1 [==============================] - 0s 326ms/step
frame=   30 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 313ms/step
1/1 [==============================] - 0s 308ms/step
frame=   32 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 326ms/step
1/1 [==============================] - 0s 321ms/step
frame=   34 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 336ms/step
1/1 [==============================] - 0s 334ms/step
frame=   36 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 351ms/step
1/1 [==============================] - 0s 321ms/step
frame=   38 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 365ms/step
1/1 [==============================] - 0s 374ms/step
frame=   40 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 363ms/step
1/1 [==============================] - 0s 348ms/step
frame=   42 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 357ms/step
1/1 [==============================] - 0s 319ms/step
frame=   44 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 336ms/step
1/1 [==============================] - 0s 363ms/step
frame=   46 fps=2.5 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
1/1 [==============================] - 0s 343ms/step
av_interleaved_write_frame(): Broken pipe
1/1 [==============================] - 0s 457ms/step
frame=   47 fps=2.3 q=23.0 Lsize=N/A time=-00:00:00.07 bitrate=N/A speed=N/A    
video:153kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x55f85748f300] frame I:1     Avg QP:18.34  size:156345
[libx264 @ 0x55f85748f300] frame P:42    Avg QP:18.79  size: 33947
[libx264 @ 0x55f85748f300] frame B:4     Avg QP:23.18  size:  9669
[libx264 @ 0x55f85748f300] consecutive B-frames: 87.2%  4.3%  0.0%  8.5%
[libx264 @ 0x55f85748f300] mb I  I16..4:  6.0%  0.0% 94.0%
[libx264 @ 0x55f85748f300] mb P  I16..4:  0.2%  0.0%  1.8%  P16..4: 36.9% 25.9% 14.0%  0.0%  0.0%    skip:21.2%
[libx264 @ 0x55f85748f300] mb B  I16..4:  0.0%  0.0%  0.1%  B16..8: 30.4%  7.5%  0.7%  direct:11.5%  skip:49.8%  L0:38.8% L1:52.3% BI: 8.9%
[libx264 @ 0x55f85748f300] coded y,u,v intra: 91.6% 31.5% 36.8% inter: 31.1% 3.7% 5.2%
[libx264 @ 0x55f85748f300] i16 v,h,dc,p: 23% 11% 20% 46%
[libx264 @ 0x55f85748f300] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 20% 15% 10%  8% 11% 10%  8%  8% 10%
[libx264 @ 0x55f85748f300] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x55f85748f300] ref P L0: 82.9% 17.1%
[libx264 @ 0x55f85748f300] ref B L0: 95.5%  4.5%
[libx264 @ 0x55f85748f300] ref B L1: 94.7%  5.3%
[libx264 @ 0x55f85748f300] kb/s:6897.03
Conversion failed!
18:41:39 ::   WriteGear   ::  ERROR   :: BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?20775522-7cea-41a0-8144-14c146286cbc)
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
File ~/anaconda3/envs/myenv3/lib/python3.10/site-packages/vidgear/gears/writegear.py:354, in WriteGear.write(self, frame, rgb_mode)
    353 try:
--> 354     self.__process.stdin.write(frame.tobytes())
    355 except (OSError, IOError):
    356     # log something is wrong!

BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/home/sawantkumar/rtsp_to_rtsp/rtsp_to_rtsp_stream.ipynb Cell 4 in <cell line: 68>()
    [105](vscode-notebook-cell:/home/sawantkumar/rtsp_to_rtsp/rtsp_to_rtsp_stream.ipynb#W2sZmlsZQ%3D%3D?line=104) rgb = cv2.cvtColor(hr,cv2.COLOR_YUV2RGB)
    [108](vscode-notebook-cell:/home/sawantkumar/rtsp_to_rtsp/rtsp_to_rtsp_stream.ipynb#W2sZmlsZQ%3D%3D?line=107) # {do something with the frame here}
--> [109](vscode-notebook-cell:/home/sawantkumar/rtsp_to_rtsp/rtsp_to_rtsp_stream.ipynb#W2sZmlsZQ%3D%3D?line=108) writer.write(rgb)
    [111](vscode-notebook-cell:/home/sawantkumar/rtsp_to_rtsp/rtsp_to_rtsp_stream.ipynb#W2sZmlsZQ%3D%3D?line=110) # check for 'q' key if pressed
    [112](vscode-notebook-cell:/home/sawantkumar/rtsp_to_rtsp/rtsp_to_rtsp_stream.ipynb#W2sZmlsZQ%3D%3D?line=111) key = cv2.waitKey(1) & 0xFF

File ~/anaconda3/envs/myenv3/lib/python3.10/site-packages/vidgear/gears/writegear.py:360, in WriteGear.write(self, frame, rgb_mode)
    355     except (OSError, IOError):
    356         # log something is wrong!
    357         logger.error(
    358             "BrokenPipeError caught, Wrong values passed to FFmpeg Pipe, Kindly Refer Docs!"
...
    362     # otherwise initiate OpenCV's VideoWriter Class
    363     if self.__initiate:
    364         # start VideoWriter Class process

ValueError:

**Comment by SawantMyelin** [comment]
Error always occurs after frame 46 . I have tried it several times, even using the cv2.videocapture to capture the frames but still, the issue persists

**Comment by abhiTronix** [comment]
> Error always occurs after frame 46 . I have tried it several times, even using the cv2.videocapture to capture the frames but still, the issue persists

@SawantMyelin Do you have RTSP server running at `rtsp://localhost:8554/mystream` address?

**Comment by abhiTronix** [comment]
> Yes , i do have a rtsp server running at that address, i created it using the simple-rtsp-server.

Then it looks like a corrupted frame. Can you verify testing branch as follows:

```sh
 # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout testing

  # install normally
  pip install .[core]

  # OR install with asyncio support
  pip install .[asyncio]
```

**Comment by abhiTronix** [comment]
Remember to renamed `output_filename` string parameter to `output` in your code.

**Comment by abhiTronix** [comment]
@SawantMyelin Ok this is the error: https://stackoverflow.com/a/30539963, you need to do this `pip install '.[core]'`

**Comment by SawantMyelin** [comment]
Thank you , I installed .[core]. What should i do next? Run my code again with this version of vidgear?

**Comment by abhiTronix** [comment]
> Run my code again with this version of vidgear?

@SawantMyelin Yes, see if you get any different error. I think corrupted colorspace frames are getting in.

**Comment by SawantMyelin** [comment]
I did check with the newer version of vidgear that is 0.3.0 and still it crashes exactly after 46 frames.

**Comment by abhiTronix** [comment]
@SawantMyelin Only way to debug it is to review frames in real time before writing, using `cv2.imshow` method. Checkout any vidgear examples for it.

**Comment by abhiTronix** [comment]
@SawantMyelin I'm closing this as I don't see any obvious reason why it is happening other than corrupted source. Try without data manipulation and see if works.
