### ISSUE TITLE
[Bug]: client.recv() is returning None in Linux after sometime if client & server is not connected.

### ISSUE THREAD

**Issue by ErSurajGupta** [abhiTronix/vidgear#337]
### Description

cap = cv.VideoCapture("rtsp://192.168.1.2:8080/out.h264")

frame sender
def sender():
    options = {"bidirectional_mode": True,'max_retries':100000}
    server = NetGear(receive_mode=False,**options)
    while True:
        server._NetGear__max_retries = 1000
        ret,frame = cap.read()
        
        additional_data = {'camera_id':'1'}
        if frame is not None: 
             server.send(frame,additional_data)

frame receiver
def frame_receiver():
    options = {"bidirectional_mode": True,'max_retries':10000}
    client = NetGear(receive_mode=True,**options)
    try:
        while True:
            try:
                client._NetGear__max_retries = 1000
                data,frame= client.recv()
                if frame is None:
                    continue
                    print(f"None Frame detected in frame collector")
                
                #decide where to put this frame
                if not int_q.full():
                    int_q.put((data,frame))

            except Exception as e:
                print(f"frame collection error due to {e}")
                
    except Exception as e:
        print(f"exception is due to {e}")

I am trying to send frame one python file to second python file.

it works fine in windows but when i run this in linux client.recv() function return error.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

I expect that connection should remain active whether they are sending data or not.

it should send data whenever any frame is produced.

### Actual behaviour

In Windows 11 its working fine but in linux client.recv() retuning None even if am not snding any frame and system becomes nonworking after that.

### Steps to reproduce

1. Go to Linux system.
2. Make 2 files sender.py and receiver.py
3. start sending frames from one file to other one.
4. after sometime stop  sending the frame.
5. it will show no response from the server.
6. wat for sometime then it will generate error

### Terminal log output

```shell
frame collection error due to cannot unpack Nonetype object
```

### VidGear Version

0.2.6

### Python version

3.7

### OpenCV version

4.6

### Operating System version

Ubuntu 20.04 LTS

**Comment by abhiTronix** [comment]
> I expect that connection should remain active whether they are sending data or not.

@ErSurajGupta Then, why don't you use `request_timeout` optional parameter and increase timeout? The API is working as expected, the client regularly checks if the server is alive, if it fails to respond on time, it exit by returning `None`.
