### ISSUE TITLE
[Proposal]: Please only print banner if I call/use vidgear, not at import

### ISSUE THREAD

**Issue by hughperkins** [abhiTronix/vidgear#338]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) and found nothing related to my idea.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and it doesn't mention anything about my idea.
- [X] To my best knowledge, my idea wouldn't break something for other users.

### Describe your Idea

Please only print banner if I call/use vidgear, not at import.

Currently I've moved the import to below an if guard
```
    if our_args.record:
        import vidgear.gears
```
... but lots of linters don't like this kind of construction.

I'm happy to have a banner showing, but would prefer it only to show when I'm actually using/calling the library, not simply at import, please.

Note that I have not read the issue guidelines, nor searched open and closed issues etc. I just ticked the boxes because it was mandated by this form. Please feel free to close this issue on that basis.

### Use Cases

Means I don't need to add a guard around the vidgear import, in order not to get a banner when I'm not using it.

**Comment by abhiTronix** [comment]
@hughperkins I think this issue is very thought upon when creating this banner, it was necessary because some user never mention vidgear version when filing for issue here. 

> Currently I've moved the import to below an if guard
> 
>     if our_args.record:
>         import vidgear.gears
> ... but lots of linters don't like this kind of construction.

Yes this is bad way to tackle it. I'll think other way to display it only once the Class/API is called. I'll notify you here when it is done.

**Comment by hughperkins** [comment]
Thank you!

**Comment by abhiTronix** [comment]
@hughperkins With PR #348, you can now completely turn off logging and moreover APIs with logging turned on (`logging=True`) will automatically log version once, thus serving both purposes. Kindly test it if you could by cloning and installing vidgear's `development` branch as follows:

```sh
# clone the repository and get inside
git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

# checkout the latest testing branch
git checkout development

# Install latest stable release with all Core dependencies
pip install .[core]
```

Then test if problem still presists. Goodluck!

**Comment by hughperkins** [comment]
Super! thank you :)
