### ISSUE TITLE
[Question]: Donot create/use templates(html files)

### ISSUE THREAD

**Issue by 4nuragk** [abhiTronix/vidgear#339]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

How do I set the parameter so that vidgear doesn't require the HTML files.

I just want to use the /video endpoint and disable automatic template creation.

### VidGear Version

0.2.6

### Python version

3.8

### Operating System version

Ubuntu 20.04

**Comment by abhiTronix** [comment]
@4nuragk Thanks, this feature hasn't been implemented yet but I'd love to implement this in both WebGear and WebGear_RTC.

**Comment by abhiTronix** [comment]
@4nuragk With commit https://github.com/abhiTronix/vidgear/commit/4edbfab311a081858508d10fef91f0055a91fb23, you can now completely disable Data-Files Auto-Generation WorkFlow in WebGear API using `skip_generate_webdata` boolean optional attribute. Kindly test it if you could by cloning and installing vidgear's `testing` branch as follows:

```sh
# clone the repository and get inside
git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

# checkout the latest testing branch
git checkout testing 

# Install latest stable release with all Core dependencies
pip install .[core]
```

Goodluck!
