### ISSUE TITLE
[Question]: Disable logger (Helper, WriteGear, etc)

### ISSUE THREAD

**Issue by albertfaromatics** [abhiTronix/vidgear#340]
### Issue guidelines

- [x] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

Is there any way to disable the logging messages that are printed on the screen?

Examples:
`12:09:04 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.6`
`12:11:38 ::    Helper     ::   WARNING   :: Specified directory ..... `

I'm running the code on a service on boot, and by default printing screen to a log, but all these messages pollute it a lot when loading gears, streaming, saving videos, etc.

Thanks

### VidGear Version

0.2.6

### Python version

3.9.2

### Operating System version

Debian 11 - aarch64

**Comment by abhiTronix** [comment]
> 12:09:04 :: Helper :: INFO :: Running VidGear Version: 0.2.6

This is by default and mentioned in #338

> 12:11:38 :: Helper :: WARNING :: Specified directory .....

This is important, otherwise you won't able to see why your code is not working. Warnings cannot be suppressed.

**Comment by albertfaromatics** [comment]
Thanks for your response. I'll then simply clean all logging code and problem solved.

Regards.
