### ISSUE TITLE
[Bug]: "Audio source [...] is not valid, Skipped!", for a file that should be valid

### ISSUE THREAD

**Issue by GuillaumeTong** [abhiTronix/vidgear#343]
### Description

I have a valid .wav file on disk, and am supplying the correct path to StreamGear, but it does not recognize it as valid.

I have gone down in debugging, and isolated the problematic piece of code here:
https://github.com/abhiTronix/vidgear/blob/6e4eaf6e8f29f4145afabf96d3fc30c8b81f69fc/vidgear/gears/helper.py#L656-L665

For my "problematic" file, here is the metadata's value:
``` python
In [3]: metadata
Out[3]: b"Guessed Channel Layout for Input Stream #0.0 : mono\r\nInput #0, wav, from 'C:\\Users\\guillaume\\PycharmProjects\\sandbox\\streaming_prototype\\tts-multi-lang.wav':\r\n  Metadata:\r\n    encoder         : Lavf58.76.100\r\n  Duration: 00:00:25.08, bitrate: 256 kb/s\r\n  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s\r\nAt least one output file must be specified\r\n"
```
As you may see, that metadata does contain a bitrate and a sample rate, which should be recognized.

However, the values of `audio_bitrate` and `audio_sample_rate` both end up being `[]`

It seems that looking for `fltp` is preventing `validate_audio` from actually finding these values.

If that `fltp` is truly a criteria for the validity of the audio, it would be nice to include a mention about this [here in the documentation](https://abhitronix.github.io/vidgear/latest/gears/streamgear/rtfm/usage/#usage-with-file-audio-input)

I would also appreciate help in figuring our an ffmpeg command to convert an input audio to the required format.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

The output stream should use the provided audio

### Actual behaviour

The output stream does not use the provided audio

### Steps to reproduce

1. Create a sample audio file, for e.g. with this command: `ffmpeg -f lavfi -i anoisesrc=d=20:c=pink:sample_rate=16000 -ar 16000 noise.wav`
2. Use any(?) input video file
3. Attempt to use StreamGear with those two

### Terminal log output

```shell
18:25:29 ::  StreamGear   :: WARNING  :: Audio source `[...]/noise.wav` is not valid, Skipped!
```

### Python Code

```python
from pathlib import Path

from vidgear.gears import StreamGear, CamGear


def main():
    test_video_path = "input.mp4"
    test_audio_path = "noise.wav"
    stream_destination = "output.m3u8"

    format_ = "hls" if Path(stream_destination).suffix == ".m3u8" else "dash"
    stream_params = {
        "-input_framerate": 25,
        "-livestream": True,
        "-audio": test_audio_path,
    }
    stream = CamGear(source=test_video_path).start()
    streamer = StreamGear(output=stream_destination, format=format_, logging=True, **stream_params)

    while True:
        frame = stream.read()
        if frame is None:
            break
        streamer.stream(frame)
    stream.stop()
    streamer.terminate()


if __name__ == '__main__':
    main()
```

### VidGear Version

0.2.6

### Python version

3.9

### OpenCV version

4.4.0.46

### Operating System version

Microsoft Windows 10 Home, Version 10.0.19044 Build 19044

**Comment by GuillaumeTong** [comment]
I have found a working workaround for now, using ffmpeg to convert the original audio into a `fltp` `.mp3`, priort to feeding it into StreamGear:
`ffmpeg -i noise.wav -acodec libmp3lame -sample_fmt fltp noise.mp3`

I would still appreciate some clarification in the documentation if the `fltp` sample_fmt is really necessary. To my knowledge, since StreamGear uses `ffmpeg` anyways, it should be able to handle the re-encoding of many possible input audio formats into the correct one in the output stream directly.

**Comment by abhiTronix** [comment]
@GuillaumeTong With PR #350, this issue must be resolved. Kindly test it if you could by cloning and installing vidgear's `development` branch as follows:

```sh
# clone the repository and get inside
git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

# checkout the latest development branch
git checkout development

# Install latest stable release with all Core dependencies
pip install .[core]
```

Then test if problem still persists or not. Goodluck!

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/9047d91176b4909a636e39ab61de2ec393b223da**
