### ISSUE TITLE
[Bug]: CamGear.read() blocks unnecessarily.

### ISSUE THREAD

**Issue by linkoid** [abhiTronix/vidgear#344]
### Description

When `THREADED_QUEUE_MODE` is enabled `CamGear.read()` will block for an excessive duration (default is 5 min) when attempting to read past the end of a stream.

### Issue Checklist

- [x] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

`CamGear.read()` will return `None` immediately when the end of the stream has been reached.

### Actual behaviour

`CamGear.read()` will hang for `THREAD_TIMEOUT` before returning `None`

### Steps to reproduce

1. Read a video file with `THREADED_QUEUE_MODE` enabled (it is enabled by default)
2. Call `CamGear.read()` as quickly as possible

### VidGear Version

0.2.6

### Python version

3.8.10

### OpenCV version

4.6.0

### Operating System version

Windows 11

### Any other Relevant Information?

`CamGear.read()` will always hang if it is called again after the last frame has been returned because `self.__queue.get()` blocks until the queue is not empty, or until `self.__thread_timeout`
https://github.com/abhiTronix/vidgear/blob/6e4eaf6e8f29f4145afabf96d3fc30c8b81f69fc/vidgear/gears/camgear.py#L515-L516
Checking if the queue is empty and the stream has terminated partially solves the issue.
```py
        while self.__threaded_queue_mode:
            if self.__queue.empty() and self.__terminate.is_set():
                return None
            return self.__queue.get(timeout=self.__thread_timeout)
```
However, this now becomes a race condition. Take the scenario where `CamGear.read()` is called while the queue is empty and there are no frames left in the stream, but the producers have not yet terminated. The consumer will continue to block after the producers terminate because it has already passed the guard-clause and is now blocking at `self.__queue.get()`.
The `self.__queue.get()` will need to be re-implemented inside of `CamGear.read()` so the guard-clause can be moved inside the blocking-loop of [`Queue.get()`](https://github.com/python/cpython/blob/main/Lib/queue.py#L154-L183).

**Comment by abhiTronix** [comment]
When THREADED_QUEUE_MODE is enabled CamGear.read() will block for an excessive duration (default is 5 min) when attempting to read past the end of a stream.

@linkoid That's a typo in comments, there's no 5mins timeout. It blocks thread when your source is not responding. Check you source not Camgear, if it is blocking set `THREAD_TIMEOUT` value in its optional parameter.

**Comment by linkoid** [comment]
This script is able to reliably reproduce the issue on my device. The videos files I ran it with are commonly used in research. If it does not block on your device as-is, increasing `progress_interval` will increase the chances of it blocking.

If the consumer makes `read()` calls fast enough, the thread is blocked. If `print("Producing ending")` is added to the end of [`CamGear.__update()`](https://github.com/abhiTronix/vidgear/blob/master/vidgear/gears/camgear.py#L438-L506) it can be seen that the producer closes the stream, but the consumer continues to be blocked.

```py
# import required libraries
import cv2
from vidgear.gears import CamGear
from tqdm import tqdm, trange

def test(source, progress_interval=0.1):
    """
    Test for blocking race-condition

    Parameters:
        source (based on input): The video source that is passed to CamGear for the test.
        progress_interval (float): The minimum time that must pass before an I/O operation can be performed by the progress bar.

    Schrödinger's Cat
        Performing I/O ops each iteration slows down the main thread too much
        for a race-condition to block, so `progress_interval` can't be decreased too much.
    """
    tqdm.write(f"Running test({repr(source)})")

    # open any valid video stream(for e.g `myvideo.avi` file)
    camgear = CamGear(source=source).start()
    length = int(camgear.stream.get(cv2.CAP_PROP_FRAME_COUNT))

    # create the progress bar
    t = trange(length+1, mininterval=progress_interval, miniters=1)

    # loop over
    while True:

        # read frames from stream
        frame = camgear.read()
        t.update()

        # check for frame if Nonetype
        if frame is None:
            tqdm.write("Reached end-of-stream")
            break


    # safely close video stream
    camgear.stop()
    t.close()

    tqdm.write(f"Completed test({repr(source)})")

if __name__ == '__main__':
    test("videos/news.mp4")
    test("videos/ice.mp4")
    test("videos/big_buck_bunny_scene.mp4")
    tqdm.write("Finished!")

```

**Comment by abhiTronix** [comment]
@linkoid Yes blocking there is on purpose. If input is slower and output is faster, then frame skipping will happen, the consumer will consume all frames from queue immediately and thread will exit since it assumes input is already over, and you will get fewer frames than original. This problem is already discussed in issue https://github.com/abhiTronix/vidgear/issues/20, Since input frames from video is blocked by IO, as you cannot decode faster than what pace underline API is decoding(OpenCV VideoCapture in our case), you can only just access frame faster when it is available, that's what CamGear is doing currently.

**Comment by abhiTronix** [comment]
Anyways, I'm depreciating CamGear soon in favor of more accurate, fast and agile FFmpeg based decoding library called [deffcode](https://github.com/abhiTronix/deffocode) in issue #148, So fixing bugs on depreciated CamGear API is not feasible anymore.

**Comment by abhiTronix** [comment]
@linkoid OK I checked this and might have resolved this in the latest commit. Can you test your scripts again?

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/9f17025abd0bd8fd4ba840fab70af463ae63bf68**
