### ISSUE TITLE
[Question]: High CPU usage when streaming locally using Webgear

### ISSUE THREAD

**Issue by 4nuragk** [abhiTronix/vidgear#345]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

I am currently streaming the output of my Object Detection frames to Webgear. 

When I am accessing the stream from a different device in the network, the CPU usage in the host device is normal. But when I stream in the host device, the CPU usage goes up drastically(+50-60%). 

How do I stream on the host system and get the same usage as streaming on other devices in the network?

### VidGear Version

0.2.6

### Python version

3.8

### Operating System version

Ubuntu 20.04

**Comment by abhiTronix** [comment]
> But when I stream in the host device, the CPU usage goes up drastically(+50-60%)

That's because of your browser trying to use same resources as your python application. Try different browsers with low overhead and no extensions installed to lower CPU usage.
