### ISSUE TITLE
[Question]: Running as ROS Subscriber node

### ISSUE THREAD

**Issue by vigneshwarvenkat** [abhiTronix/vidgear#353]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

I want to use this package to stabilise the raw raspi camera feed coming in before processing it further myself. For that, I want to implement this python package on ROS Noetic as a subscriber node. When I try to add this package to my CMakeLists.txt, I get the following error.
**
![image](https://user-images.githubusercontent.com/83450776/216236806-1a425087-541b-4650-9b85-0f578bd8ff18.png)
**

When I try to catkin_make, the error says that it cannot find the package config file for our vidgear package. This is how we have written the package name in our CMakeLists.txt.

![image](https://user-images.githubusercontent.com/83450776/216237845-54bbf1ec-d577-417b-9646-7aa8b6217158.png)

What is the proper way to import this package in my CMakeLists.txt? Is it even possible to implement this on ROS?

### Terminal log output(Optional)

```shell
-- +++ processing catkin package: 'orb_slam3_ros_wrapper'
-- ==> add_subdirectory(orb_slam3_ros_wrapper)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find vidgear (missing: vidgear_DIR)
-- Could not find the required component 'vidgear'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "vidgear" with any
  of the following names:

    vidgearConfig.cmake
    vidgear-config.cmake

  Add the installation prefix of "vidgear" to CMAKE_PREFIX_PATH or set
  "vidgear_DIR" to a directory containing one of the above files.  If
  "vidgear" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  orb_slam3_ros_wrapper/CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/capstone/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/capstone/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:1510: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
```

### VidGear Version

0.3.0

### Python version

3.8.10

### Operating System version

Linux Ubuntu 20.04

**Comment by abhiTronix** [comment]
Can't you use `cv_bridge` : https://abhitronix.github.io/vidgear/latest/help/videogear_ex/#using-videogear-with-rosrobot-operating-system?
