### ISSUE TITLE
[Question]: Installation guid on Jetson Nano

### ISSUE THREAD

**Issue by jet-c-21** [abhiTronix/vidgear#354]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

when I try to use the following command, I am failed at building ```PyAV```
```shell
python3 -m pip install -U vidgear[asyncio]
```

And I find some resource indicated that the latest version of PyAV is not supported ffmpeg < 4.x. However the Jetson Nano ffmpeg is 3.6.

Can I ask for some install instructions?

### VidGear Version

latest

### Python version

3.6.9

### Operating System version

Ubuntu 18.04 (L4T 32.5.1, Linux Kernel 4.9)

**Comment by abhiTronix** [comment]
> And I find some resource indicated that the latest version of PyAV is not supported ffmpeg < 4.x.

@jet-c-21 Okay if this the case, then you can do bare-minimal install first and then install individual dependencies according to API in use. And also it is well-documented in vidgear's documentation: https://abhitronix.github.io/vidgear/latest/installation/pip_install/#installation

![image](https://user-images.githubusercontent.com/34266896/220074188-147f5bae-d120-4124-a405-482fc3be46d3.png)

**Comment by abhiTronix** [comment]
For PyAV, just install the lower working version.
