### ISSUE TITLE
[Question]: How to set rtsp output resolution?

### ISSUE THREAD

**Issue by BlackSazha** [abhiTronix/vidgear#355]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

Hello everyone, I re-read everything, but I still don’t understand how to set the permission for the rtsp stream, I need the stream to be not in full resolution, imshow opening on full screen

### VidGear Version

latest

### Python version

3.9

### Operating System version

rockylinux 9.1

**Comment by abhiTronix** [comment]
@BlackSazha Kindly provide code you're using for your application or provide hyperlink to example code you followed. Also, elaborate your setup, where you're generating Rtsp stream and where you're viewing your output.

**Comment by abhiTronix** [comment]
> I just need to change the size and/or resolution of the window/stream

It's simple. There's a [`reducer`](https://abhitronix.github.io/vidgear/latest/bonus/reference/helper/#vidgear.gears.helper.reducer--reducer) helper method that you can use to reduce frame size to desired resolution at runtime. For example:

```py
from vidgear.gears.helper import reducer

frame = reducer(frame, percentage=30, interpolation=cv2.INTER_AREA)  # reduce frame by 30%
```
