### ISSUE TITLE
[Docs]: Update the chunk size parameter in docs

### ISSUE THREAD

**Issue by themagicalmammal** [abhiTronix/vidgear#359]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

Cannot find chunk size for hls format? I tried  -seg_duration but that doesn't seem to change the chunk size. I am trying to get it to 2.

### VidGear Version

latest

### Python version

3.10

### Operating System version

Ubuntu 22.04

**Comment by themagicalmammal** [comment]
Found it -

`"-hls_init_time": 2, "-hls_time": 2,`

setting one of them doesn't fix it, for some reason have to set both of them. Please put this in the docs.

**Comment by abhiTronix** [comment]
**@themagicalmammal  This issue has been fixed in commit: https://github.com/abhiTronix/vidgear/commit/612dee010a79e6c425d13237bd184694c8359d4e, thanks for reporting.**
