### ISSUE TITLE
[Bug]: frame_size_reduction does not allow value of 0

### ISSUE THREAD

**Issue by jarodhanko-crafco** [abhiTronix/vidgear#360]
### Description

Docs say that frame_size_reduction on WebGear_RTC must be 0-90. If frame_size_reduction is set to 0 using a custom_stream, application will not stream video. No errors are raised in python or in the web console. See sample code below to reproduce (generates random frames with a timestamp). 

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

Setting frame_size_reduction to 0 should stream uncompressed frames

### Actual behaviour

Application does not stream video. Nothing is logged, so I'm not sure what the error is.

### Steps to reproduce

1. Run python code below. Frames are generated programmatically.

### Terminal log output

```shell
18:32:53 ::  WebGear_RTC  :: CRITICAL :: Enabled live broadcasting for Peer connection(s).
18:32:53 :: Helper_Async  ::  DEBUG   :: Found valid WebGear data-files successfully.
18:32:53 ::  WebGear_RTC  ::  DEBUG   :: `/home/crafco-admin/.vidgear/webgear_rtc` is the default location for saving WebGear_RTC data-files.
18:32:53 ::    Helper     ::   INFO   :: Running VidGear Version: 0.3.0
18:32:53 ::  WebGear_RTC  :: CRITICAL :: Using custom stream for its Default Internal Video-Server.
18:32:53 ::  WebGear_RTC  ::  DEBUG   :: Setting params:: Size Reduction:0% and emulating infinite frames
18:32:53 ::  WebGear_RTC  ::  DEBUG   :: Running Starlette application.
INFO:     Started server process [115814]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     192.168.0.104:53713 - "POST /close_connection HTTP/1.1" 200 OK
INFO:     192.168.0.104:53713 - "GET / HTTP/1.1" 200 OK
18:32:55 ::  WebGear_RTC  ::  DEBUG   :: Initiating Video Streaming.
18:32:55 ::  WebGear_RTC  ::  DEBUG   :: Launching Internal RTC Video-Server
18:32:55 ::  WebGear_RTC  ::   INFO   :: Created WebRTC Peer Connection.
INFO:     192.168.0.104:53713 - "POST /offer HTTP/1.1" 200 OK
18:32:56 ::  WebGear_RTC  ::  DEBUG   :: ICE connection state is checking
18:32:56 ::  WebGear_RTC  ::  DEBUG   :: ICE connection state is completed
18:32:56 ::  WebGear_RTC  ::  DEBUG   :: Setting timestamps
18:32:57 :: Helper_Async  ::  DEBUG   :: Adding text: No Input
```

### Python Code(Optional)

```python
import time
import datetime
import cv2
import numpy as np

from vidgear.gears.asyncio import WebGear_RTC
import uvicorn

def time_frame(size=(480, 640, 1)):
    frame = np.random.randint(0, 255, size=size, dtype=np.uint8)
    # get current time
    now = datetime.datetime.now()
    current_time = now.strftime("%H:%M:%S.%f")

    # put current time text in the image
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(frame, current_time, (200, 240), font, 1, 255, 2, cv2.LINE_AA)
    return frame

frame_rate = 30


class Custom_Stream_Class:
    def __init__(self) -> None:
        self.start_time = None

    def read(self):
        if self.start_time is None:
            self.start_time = time.time()
        elapsed_time = time.time()
        # if (elapsed_time - self.start_time) > (1/frame_rate):
        self.start_time += 1/frame_rate
        if (elapsed_time - self.start_time) > 5/frame_rate:
            print(elapsed_time - self.start_time)
        return time_frame((1080, 1920, 1))

    def stop(self):
        return


opts = {
    "custom_stream": Custom_Stream_Class(),
    "framerate": frame_rate, #removing this does not help
    "enable_live_broadcast": True, # removing this does not help
    "enable_infinite_frames": True, # removing this does not help
    'time_delay': 1, # removing this does not help
    'frame_size_reduction': 0 #setting to 1 or greater works
}
webgear_rtc = WebGear_RTC(logging=True, **opts)
# # run this app on Uvicorn server at address http://localhost:8000/
uvicorn.run(webgear_rtc(), host='0.0.0.0', port=8000)

# # close app safely
webgear_rtc.shutdown()
```

### VidGear Version

0.3.0

### Python version

3.10.6

### OpenCV version

4.7.0

### Operating System version

Ubuntu 22.04.2 LTS

**Comment by abhiTronix** [comment]
@jarodhanko-crafco Okay there was a bug in [PyAV](https://github.com/PyAV-Org/PyAV/tree/main) backend library that got exposed because of your code. 

### Bug

The PyAV's VideoFrame.from_ndarray expects grayscale images to be of shape `(height, width)` and not `(height, width,1)`, like you trying in your code.

### Why it worked with  `frame_size_reduction` parameter defined(or greater than `0`)?
If defined, vidgear it uses OpenCV functions to manipulate frame size and yield `(height, width)` shaped frames supported by PyAV's VideoFrame.from_ndarray.

### Solution
The possible solution is to just drop third dimension if detected. And I'm going to implement that only. For now, you code will work if shape is `(1080, 1920)` and not `(1080, 1920, 1)`.

**Comment by abhiTronix** [comment]
**@jarodhanko-crafco This issue has been resolved in commit https://github.com/abhiTronix/vidgear/commit/41c9e996001bdaf47e3d47f22ed212e28dedb003.**
