### ISSUE TITLE
[Question]: Change default video path in WebGear

### ISSUE THREAD

**Issue by AliSalehian** [abhiTronix/vidgear#362]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

By default, the path route for video in the WebGear broadcasting API is set to /video. How can I change it to something else, like /video2? 
I tried to iterate over all the routes generated by the constructor of WebGear and find the route with the /video path to change it. However, it doesn't work. Even after changing it to /video2, this route gives me a 404 error, while the /video path still works. Any ideas?
I believe this feature could be added as an argument to the WebGear constructor because I can see that the /video path is added to the routing table in it.

### Python Code(Optional)

```python
import uvicorn
from vidgear.gears.asyncio import WebGear


class WebRtcServer:
    def __init__(self,
                  media_source: str,
                  route: str,
                  webGearLogging: bool = False,
                  frame_size_reduction: int = 40,
                  jpeg_compression_quality: int = 90,
                  jpeg_compression_fastdct: bool = False,
                  jpeg_compression_fastupsample: bool = False,
                  host: str = "0.0.0.0",
                  port: int = 8000) -> None:
        webGearOptions = { 
            "frame_size_reduction": frame_size_reduction,
            "jpeg_compression_quality": jpeg_compression_quality,
            "jpeg_compression_fastdct": jpeg_compression_fastdct,
            "jpeg_compression_fastupsample": jpeg_compression_fastupsample
            }
        web = WebGear(source=media_source, logging=webGearLogging, **webGearOptions)
        for i in range(len(web.routes)):
            if web.routes[i].path == "/video":
                web.routes[i].path = route
        print("routes:", web.routes)
        uvicorn.run(web(), host=host, port=port)
        web.shutdown()
```

### VidGear Version

0.3.0

### Python version

3.8.10

### Operating System version

Linux Ubuntu 20.04.6 LTS focal

**Comment by abhiTronix** [comment]
@AliSalehian Thank you for raising this issue. Sure I'll look into it, and if it is safe to implement, I'll add it to next milestone.

**Comment by abhiTronix** [comment]
**@AliSalehian The support for custom endpoint path has been added in commit https://github.com/abhiTronix/vidgear/commit/41c9e996001bdaf47e3d47f22ed212e28dedb003 and will be available in next release. 🎉**
