### ISSUE TITLE
[Question]: Fetch Multiple Video from Youtube

### ISSUE THREAD

**Issue by AlifRizza** [abhiTronix/vidgear#368]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

Hello, I've been using your VidGear library for a web application project where we fetch and process YouTube videos for object detection tasks. The UI is similar to Google Meet where multiple videos are displayed at once. We've hit a snag though. When we add six or more videos, the response time drastically slows down and we experience lag, with new videos taking up to 6-10 minutes to load and each frame drops to just 9-12 FPS. I'm reaching out to understand more about VidGear's resource consumption - is fetching multiple videos at once particularly resource-heavy? And is there a cap on the number of videos VidGear can handle simultaneously?

### VidGear Version

0.3.0

### Python version

3.8

### Operating System version

Windows 11

**Comment by abhiTronix** [comment]
@AlifRizza This is because of curse of [Global Interpreter Lock](https://realpython.com/python-gil/) when you use threading in python. Because you're opening multiple threads for same resource with CamGear, the performance will take certainly take toll, because of race condition between those thread..
