### ISSUE TITLE
[Proposal] Can NetGear Client receive input from multiple Servers?

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [abhiTronix/vidgear#37]
[Enhancement] NetGear Client can receive inpunt from multipule Server and show them into a Grid View

## Detailed Description
Same concept is here https://www.pyimagesearch.com/2019/04/15/live-video-streaming-over-network-with-opencv-and-imagezmq/
Biside frame, NetGear Server can send other information, eg: Frame type, Camera Name... some thing like that: server.send(frame, dict(msg_type=2, context='camera continue frame')}) and NetGear Client can receive data like this: frame, extra_data = client.recv()

**Comment by abhiTronix** [comment]
Hello @xamarindevelopervietnam,

Thank you for bringing this proposal up, It will be a great addition to VidGear. I've added this enhancement proposal to next milestone and in the next few days, I'll push PR related to it. So stay tuned.

### Current Difficulties 
* Firstly, Vidgear currently does not support multiple server configuration as there is no direct access to the server message in the `rec()` method.
* Secondly VidGear configuration only supports blocking mode that either uses a `REQ/REP` or `PAIR/PAIR` zmq socket, in which either end would freeze until the other end is connected & start running for added synchronization. But this configuration is non-ideal for live-streaming as synchronization adds to latency in this mode.

### Proposed Solution
- [ ] Implement a new feature that supports **dynamic multiple server configurations at the receiver's end** that can handle any number of servers automatically in NetGear API
- [ ] **Add new Non-Blocking mode `PUB/SUB` zmq socket** in which the publishing side will continue to send frames across regardless of the state of the subscriber i.e. ideal for live-streaming in NetGear
- [ ] Fixed related bugs
- [ ] Update Docs

**Comment by xamarindevelopervietnam** [comment]
That's great @abhiTronix! I already have some proposals here and and hope it can help Vidgear better and better!

**Comment by abhiTronix** [comment]
> That's great @abhiTronix! I already have some proposals here and hope it can help Vidgear better and better!

Yes that a great idea, let me know if you have other proposals for Vidgear too!

**Comment by abhiTronix** [comment]
**Successfully Resolved & Merged in commit: https://github.com/abhiTronix/vidgear/commit/48c6a69d46e8b02683e4760c0e9488f58dfc2f47**
