### ISSUE TITLE
[Bug]: CamGear - Error when loading first segment , while taking picture from youtube streaming

### ISSUE THREAD

**Issue by TarasDysiuk** [abhiTronix/vidgear#373]
### Description

Hi All, I using python library CamGear for download video and revive error

    def GetImageFromYoutube(url=INPUT_URL,output_file=OUTPUT_FILENAME):
    #  Youtube streaming 
    try:
        stream = CamGear(source=url, stream_mode =True,  time_delay=1, logging=True).start()
        frame = stream.read()
        cv2.imwrite(output_file, frame)
        if FileIsImage(OUTPUT_FILENAME)==False:
            assert True,"Wrong file format"
    except Exception as ex:
        print("Error", ex)
        print("YouTube cam download error")
        return False, ex
    else:
        print("YouTube cam download successfully")
        return True, ""

GetImageFromYoutube('https://www.youtube.com/watch?v=PJR_aGTEcgs')

and after execution i have

    09:28:12 ::    Helper     ::   INFO   :: Running VidGear Version: 0.3.0
09:28:12 ::    Helper     :: WARNING  :: GStreamer not found!
09:28:12 ::    Helper     ::  DEBUG   :: Selecting `best` resolution for streams.
09:28:12 ::    CamGear    ::   INFO   :: Verifying Streaming URL using yt-dlp backend. Please wait...
09:28:17 ::    CamGear    ::   INFO   :: [Backend] :: Streaming URL is fully supported. Available Streams are: [144p, 240p, 360p, 480p, 720p, 1080p, best, worst]
09:28:17 ::    CamGear    :: WARNING  :: Livestream URL detected. It is advised to use GStreamer backend(`cv2.CAP_GSTREAMER`) with it.
09:28:17 ::    CamGear    ::  DEBUG   :: Using `best` resolution for streaming.
09:28:17 ::    CamGear    ::  DEBUG   :: YouTube source ID: `PJR_aGTEcgs`, Title: `YPI Headquarters Live - Dublin, NH 2023-08-31 09:28`, Quality: `best`
09:28:17 ::    CamGear    ::  DEBUG   :: Enabling Threaded Queue Mode for the current video source!
[hls @ 00f3de80] Error when loading first segment 'https://rr3---sn-x8xgxnu05-8poe.googlevideo.com/videoplayback/id/PJR_aGTEcgs.6/itag/96/source/yt_live_broadcast/expire/1693484906/ei/CjPwZPCiB6ek0u8Pl42NgAQ/ip/178.74.226.70/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr3---sn-x8xgxnu05-8poe.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/UWF9f4DY-pRKuECRRNtfOlePmqAGNdhdDkhH1PU3Nw/vprv/1/playlist_type/DVR/initcwndbps/1527500/mh/Qp/mm/44/mn/sn-x8xgxnu05-8poe/ms/lva/mv/m/mvi/3/pl/20/keepalive/yes/fexp/24007246,51000023/beids/24350017/mt/1693462834/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAO9YWbx4cxJ6TdPd-LK43AwHh4j_ytmUN3qB2aVtkxYwAiA8gbQxbvj8BtZvsUFr72GusZag5W03UxwaGtov306Yww%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhAN0ZzdnrjOs6rfBS--SPoZdSpRIB6CenzkSniZkTVW16AiEAtk9ERReDud8mhbhwNWmA9qp0TCsl-UtNq_yrZon0lgo%3D/playlist/index.m3u8/sq/3977707/goap/clen%3D81851%3Blmt%3D1693458905928707/govp/clen%3D532581%3Blmt%3D1693458905928705/dur/5.000/file/seg.ts'
[tls @ 0a16e680] Failed to send close message
[tls @ 00f3e840] Failed to send close message
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1gnnrwcf\opencv\modules\videoio\src\cap.cpp (162) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1gnnrwcf\opencv\modules\videoio\src\cap_images.cpp:235: error: (-5:Bad argument) CAP_IMAGES: error, expected '0?[1-9][du]' pattern, got: https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1693484906/ei/CjPwZPCiB6ek0u8Pl42NgAQ/ip/178.74.226.70/id/PJR_aGTEcgs.6/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr3---sn-x8xgxnu05-8poe.googlevideo.com/playlist_duration/30/manifest_duration/30/spc/UWF9f4DY-pRKuECRRNtfOlePmqAGNdhdDkhH1PU3Nw/vprv/1/playlist_type/DVR/initcwndbps/1527500/mh/Qp/mm/44/mn/sn-x8xgxnu05-8poe/ms/lva/mv/m/mvi/3/pl/20/dover/11/pacing/0/keepalive/yes/fexp/24007246,51000023/beids/24350017/mt/1693462834/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AOq0QJ8wRQIhAO9YWbx4cxJ6TdPd-LK43AwHh4j_ytmUN3qB2aVtkxYwAiA8gbQxbvj8BtZvsUFr72GusZag5W03UxwaGtov306Yww%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhAN0ZzdnrjOs6rfBS--SPoZdSpRIB6CenzkSniZkTVW16AiEAtk9ERReDud8mhbhwNWmA9qp0TCsl-UtNq_yrZon0lgo%3D/playlist/index.m3u8 in function 'cv::icvExtractPattern'

Error [CamGear:ERROR] :: Source is invalid, CamGear failed to initialize stream on this source!

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

works fine and the picture download

### Actual behaviour

The source is invalid, CamGear failed to initialize stream on this source 

### Steps to reproduce

run script

### VidGear Version

0.3.0

### Python version

3.7.2

### OpenCV version

4.5.3

### Operating System version

windows

**Comment by abhiTronix** [comment]
@TarasDysiuk Did you used GSTREAMER backend? Both docs and logs clearly says:  

> 09:28:17 :: CamGear :: WARNING :: Livestream URL detected. It is advised to use GStreamer backend(cv2.CAP_GSTREAMER) with it.
