### ISSUE TITLE
[Proposal]: Add type annotations to the code or add stub files

### ISSUE THREAD

**Issue by simon-liebehenschel** [abhiTronix/vidgear#376]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) and found nothing related to my idea.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and it doesn't mention anything about my idea.
- [X] To my best knowledge, my idea wouldn't break something for other users.

### Describe your Idea

[PEP 484 – Type Hints](https://peps.python.org/pep-0484/)

[Stub files](https://mypy.readthedocs.io/en/stable/stubs.html)

### Use Cases

To simplify integration into existing projects that have type annotations.

### Any other Relevant Information?

Not sure about my availability (whether I will be able to contribute in the near future), but at least I can review a pull request if anyone will submit one.

**Comment by abhiTronix** [comment]
@AIGeneratedUsername Yeah, I would love to have this for vidgear. Type annotations enhance code clarity, facilitate type checking, and maintain consistency within the codebase, ultimately improving development efficiency and code quality.

**Comment by abhiTronix** [comment]
**@simon-liebehenschel This issue is successfully fixed and merged in commit: https://github.com/abhiTronix/vidgear/commit/31550b648025b5fef493c11797a196f237acbdc7**
