### ISSUE TITLE
Remove duplicate code to import MSS

### ISSUE THREAD

**Issue by BoboTiG** [abhiTronix/vidgear#38]
## Detailed Description

The code to import the MSS module is duplicated. You first try to import OS specific code, and if no OS was good, you still do `from mss import mss`.
But the current code is a duplicate from the `mss.mss()` factory, which already handle OS specific imports for you :)

The current code will simply double the checks and the result would be the same in any cases (when the OS is not handled).

The patch would be quite simple:
```diff
-			import platform			
-			if platform.system() == 'Linux':
-				from mss.linux import MSS as mss
-			elif platform.system() == 'Windows':
-				from mss.windows import MSS as mss
-			elif platform.system() == 'Darwin':
-				from mss.darwin import MSS as mss
-			else:
-				from mss import mss
+			from mss import mss
```

Do you are interested in a PR?

BTW I am the MSS author, glad to see the module in use there :+1: 

### Your Environment

* VidGear version: 0.1.5
* Branch: all
* Python version: all
* pip version: all
* Operating System and version: all

**Comment by abhiTronix** [comment]
Hey @BoboTiG, Thanks for the great `mss` library and point this fault out. I thought it will be safe to implement my own wrapper around your system specific imports, while going through the mss docs. I should have checked the source-code too. Thanks again, I'll merge this update as soon as I can.

**Comment by abhiTronix** [comment]
@BoboTiG Aren't these lines in `mss` docs redundant?

![2019-07-26 13_30_36-Usage — Python MSS latest documentation](https://user-images.githubusercontent.com/34266896/61955255-3516e380-afd8-11e9-8a45-b4ed8fb0ed83.png)

As `mss` automatically detects the right import according to your system OS?

**Comment by BoboTiG** [comment]
You are right. I thought it was a good thing to let users choose a specific import. I will remove that part from the documentation ;)

**Comment by abhiTronix** [comment]
Successfully resolved in https://github.com/abhiTronix/vidgear/commit/bad5d0c07d486b2a0a7b6801d21b9361b3189f63
