### ISSUE TITLE
Putting a client IP into the Server code?

### ISSUE THREAD

**Issue by mrazadal** [abhiTronix/vidgear#382]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

For those used to the idea that a "server" provides their address to a client, then you should recheck your preconceptions! Please read the [Netgear instructions](https://abhitronix.github.io/vidgear/latest/gears/netgear/usage/#using-netgear-with-variable-parameters) carefully, and you will note that it is the client device that defines the IP that is provided to the server config. If you get this the wrong way (using the server IP on the client), then you will get a zmq.error.ZMQError error. Make sure it is the client's IP shared across the two systems.

Can anyone elaborate on the above paragraph?

I have the following setup: 1 server with a camera and 2 clients are trying to access it. Considering the above paragraph, how is it possible that the server is running all the time and waiting for the clients to connect, or in other words, how the clients can find the server streaming video? The server and clients are connected to the same router.

### VidGear Version

0.3.2

### Python version

3.8

### Operating System version

Windows 11

**Comment by abhiTronix** [comment]
> For those used to the idea that a "server" provides their address to a client, then you should recheck your preconceptions! Please read the [Netgear instructions](https://abhitronix.github.io/vidgear/latest/gears/netgear/usage/#using-netgear-with-variable-parameters) carefully, and you will note that it is the client device that defines the IP that is provided to the server config. If you get this the wrong way (using the server IP on the client), then you will get a zmq.error.ZMQError error. Make sure it is the client's IP shared across the two systems.

@mrazadal, I agree, this is somewhat unconventional when compared to what we typically encounter in our daily experiences. Actually, The term "Server" associated with machine that sends frames, while "Receiver" is associated with the one receiving those frames, but this works opposite when ZMQ server-client is considered. Don't worry; it's not a significant issue. You can easily switch roles by simply changing variable names in your Python script.

> I have the following setup: 1 server with a camera and 2 clients are trying to access it. Considering the above paragraph, how is it possible that the server is running all the time and waiting for the clients to connect, or in other words, how the clients can find the server streaming video? The server and clients are connected to the same router.

@mrazadal If you went through docs carefully, I assume, you must be aware with advanced multi-clients mode:  https://abhitronix.github.io/vidgear/latest/gears/netgear/advanced/multi_client/, also for any quick questions like this, please refrain from opening an issue, as you can reach us on [Gitter](https://gitter.im/vidgear/community) community channel. Hope this helps :)
