### ISSUE TITLE
[Bug]: no sound on output video with bare minimum code on google colab

### ISSUE THREAD

**Issue by sugizo** [abhiTronix/vidgear#387]
### Description

no sound on output video with bare minimum code on google colab

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

have sound on output video

### Actual behaviour

no sound on output video

### Steps to reproduce

```
!wget -c http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
pip install -U vidgear pyscreenshot uvicorn starlette simplejpeg aiortc
from vidgear.gears import CamGear, WriteGear
import cv2
import IPython
stream = CamGear(source = 'BigBuckBunny.mp4', logging = True).start()

output = "minimum.mp4"
writer = WriteGear(output = output, compression_mode = True, logging = True)

while True:
    frame = stream.read()

    if frame is None:
        break

    writer.write(frame)

    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

stream.stop()

writer.close()

IPython.display.Video(output, embed = True)
```

### Terminal log output

```shell
15:30:39 ::    Helper     ::   INFO   :: Running VidGear Version: 0.3.2
15:30:39 ::    CamGear    ::  DEBUG   :: Enabling Threaded Queue Mode for the current video source!
15:30:39 ::   WriteGear   ::  DEBUG   :: Output Parameters: `{}`
15:30:39 ::   WriteGear   ::  DEBUG   :: Compression Mode is enabled therefore checking for valid FFmpeg executable.
15:30:39 ::   WriteGear   :: WARNING  :: Optional `-disable_ffmpeg_window` flag is only available on Windows OS with `logging=False`. Discarding!
15:30:39 ::    Helper     ::  DEBUG   :: Final FFmpeg Path: ffmpeg
15:30:40 ::    Helper     ::  DEBUG   :: FFmpeg validity Test Passed!
15:30:40 ::    Helper     ::  DEBUG   :: Found valid FFmpeg Version: `b'4.4.2-0ubuntu0.22.04.1'` installed on this system
15:30:40 ::   WriteGear   ::  DEBUG   :: Found valid FFmpeg executable: `ffmpeg`.
15:30:40 ::   WriteGear   ::  DEBUG   :: Compression Mode with FFmpeg backend is configured properly.
15:30:40 ::   WriteGear   ::  DEBUG   :: InputFrame => Height:720 Width:1280 Channels:3 Datatype:uint8
15:30:40 ::   WriteGear   ::  DEBUG   :: Executing FFmpeg command: `ffmpeg -y -f rawvideo -vcodec rawvideo -s 1280x720 -pix_fmt bgr24 -i - -vcodec libx264 -crf 18 -preset fast /content/minimum.mp4`
```

### Python Code(Optional)

```python
from vidgear.gears import CamGear, WriteGear
import cv2
import IPython
stream = CamGear(source = 'BigBuckBunny.mp4', logging = True).start()

output = "minimum.mp4"
writer = WriteGear(output = output, compression_mode = True, logging = True)

while True:
    frame = stream.read()

    if frame is None:
        break

    writer.write(frame)

    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

stream.stop()

writer.close()

IPython.display.Video(output, embed = True)
```

### VidGear Version

0.3.2

### Python version

3.10.12

### OpenCV version

4.8.0

### Operating System version

ubuntu jammy 

### Any other Relevant Information?

google colab environment

**Comment by sugizo** [comment]
tested with 
`output_params = {"-acodec": "copy"}`
and
`output_params = {"-c:a": "copy"}`

also have same result (no sound on output video, while the source video is have a sound)

suspect the problem is on function
`writer.write() `

because the only thing work 
when have a sound on output video is 
by using function
`writer.execute_ffmpeg_cmd() `

**code no sound on output video**
```
from vidgear.gears import CamGear, WriteGear
import cv2
import IPython

stream = CamGear(source = 'BigBuckBunny.mp4', logging = True).start()

output_params = {"-acodec": "copy"}

output = "cv2.mp4"
writer = WriteGear(output = output, compression_mode = True, logging = True, **output_params)

while True:
    frame = stream.read()

    if frame is None:
        break

    writer.write(frame)

    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

stream.stop()

writer.close()

IPython.display.Video(output, embed = True)
```

best regards

**Comment by sugizo** [comment]
to get the sound
must use `writer.execute_ffmpeg_cmd()`

**Comment by abhiTronix** [comment]
> to get the sound
> must use writer.execute_ffmpeg_cmd()
> 


@sugizo Wrong, you didn't read docs properly. Here are docs links to add sound:

- https://abhitronix.github.io/vidgear/v0.3.1-stable/gears/writegear/compression/usage/#using-compression-mode-with-live-audio-input
- https://abhitronix.github.io/vidgear/v0.3.1-stable/help/writegear_ex/#using-writegears-compression-mode-to-add-external-audio-file-input-to-video-frames
- And also: https://abhitronix.github.io/vidgear/v0.3.1-stable/gears/writegear/compression/advanced/cciw/#using-writegear-to-merge-audio-with-video
