### ISSUE TITLE
[Question]: how to stream frames from opencv capture already in use?

### ISSUE THREAD

**Issue by netpbcl** [abhiTronix/vidgear#389]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

I, Hello, I need to know how to transmit the opencv frames that are already being used. I have the following code: I want to transmit the image that is being generated in "im1", with webgear_rtc (I suppose). Note: I am a novice programmer.

Thank you

### Python Code(Optional)

```python
from ultralytics import YOLO
from ultralytics.solutions import object_counter
import cv2

model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Define line points
line_points = [(20, 400), (1080, 400)]

# Video writer
video_writer = cv2.VideoWriter("object_counting_output.avi",
                       cv2.VideoWriter_fourcc(*'mp4v'),
                       fps,
                       (w, h))

# Init Object Counter
counter = object_counter.ObjectCounter()
counter.set_args(view_img=True,
                 reg_pts=line_points,
                 classes_names=model.names,
                 draw_tracks=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False)

    im1 = counter.start_counting(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
```

### VidGear Version

0.3.0

### Python version

3.11

### Operating System version

windows 11

**Comment by abhiTronix** [comment]
> I, Hello, I need to know how to transmit the opencv frames that are already being used. I have the following code: I want to transmit the image that is being generated in "im1", with webgear_rtc (I suppose). Note: I am a novice programmer.

Just follow this example: https://abhitronix.github.io/vidgear/v0.3.2-stable/gears/webgear_rtc/advanced/#using-webgear_rtc-with-a-custom-sourceopencv
