### ISSUE TITLE
Exception in thread NetGear, zmq.error.Again: Resource temporarily unavailable

### ISSUE THREAD

**Issue by sourabCV** [abhiTronix/vidgear#390]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

In my code, I used Netgear for video transfer in the cloud. On that code, I received a NetGear thread error in the long run.

### Terminal log output(Optional)

```shell
Exception in thread NetGear:
Traceback (most recent call last):
  File "C:\Users\SchneiderElectric\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\SchneiderElectric\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run   
    self._target(*self._args, **self._kwargs)
  File "C:\DefectScanner\venv3\Lib\site-packages\vidgear\gears\netgear.py", line 972, in __recv_handler
    msg_json = self.__msg_socket.recv_json(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DefectScanner\venv3\Lib\site-packages\zmq\sugar\socket.py", line 941, in recv_json
    msg = self.recv(flags)
          ^^^^^^^^^^^^^^^^
  File "zmq\backend\cython\socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
  File "zmq\backend\cython\socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq\backend\cython\socket.pyx", line 199, in zmq.backend.cython.socket._recv_copy
  File "zmq\backend\cython\socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
  File "zmq\backend\cython\checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable
```

### Python Code(Optional)

```python
from vidgear.gears import NetGear

options = {"max_retries":2,"request_timeout":5,"flag":1,"copy": False, "track": False}
client = NetGear(receive_mode=True, address="0.0.0.0", port="12345",protocol="tcp",pattern=1,**options,)

frame = client.recv()
```

### VidGear Version

0.3.2

### Python version

3.11.6

### Operating System version

windows10

### Any other Relevant Information?

I dont want to use pattern 2 and how can I solve this error  or how can I catch this error in a try, exception block pls suggest

**Comment by sourabCV** [comment]
any solution?

**Comment by abhiTronix** [comment]
> I received a NetGear thread error in the long run.

Meaning your connection is unstable. And connection is breaking, so you have to re-establish connection with (`pattern=1`) `zmq.REQ/zmq.REP`

> any solution?

Yes, it's simple, just use [pattern=2](https://abhitronix.github.io/vidgear/v0.3.3-dev/gears/netgear/params/#pattern) in your script, which is [zmq.PUB/zmq.SUB](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html) (ZMQ Publish/Subscribe Pattern) with NetGear API. In this pattern, both Server and Client end works independently and messages are published without the knowledge of what or if any subscriber of that knowledge exists. No single publisher overwhelms the subscriber. The messages from both publishers are interleaved.

**Comment by abhiTronix** [comment]
More knowledge about this error:
ZMQ Python wrappers raise `zmq.error.Again` if the underlying C API returns `EAGAIN`. You could follow [zmq_recv](http://api.zeromq.org/4-2:zmq-recv) documentation, which states:
- EAGAIN: Non-blocking mode was requested and the message cannot be sent at the moment.

@sourabCV Also, Try removing these flags: `"flag":1,"copy": False, "track": False`

**Comment by abhiTronix** [comment]
I'll remove these parameters from docs.

**Comment by sourabCV** [comment]
Thanks for your response 

Today i removed that flags and all, now waiting for 48 hours to check this worked or not 

pattern=2 also used one time but that also generate a different error  after this error confermation i will show you pattern 2 error

**Comment by sourabCV** [comment]
After removing the flag it's working. Thank you for your support.

**Comment by abhiTronix** [comment]
**This issue is fixed in commit https://github.com/abhiTronix/vidgear/commit/e533553214b1b931dbf211679abd56b2acfba215**
