### ISSUE TITLE
How to use nvdec/nvenc

### ISSUE THREAD

**Issue by johnnynunez** [abhiTronix/vidgear#395]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

I am trying to make a yolo detector using mp4 video or real time camera. I am trying to speed up my pipeline because the fps of the model is much higher than the video and the fps marked. How can I use hardware e.g. nvenc and nvenc to encode and decode the video?
I have opencv and ffmpeg with cuda. The device is a jetson agx orin

### VidGear Version

0.3.2

### Python version

3.11

### Operating System version

Ubuntu 22.04

**Comment by abhiTronix** [comment]
> I am trying to make a yolo detector using mp4 video or real time camera. I am trying to speed up my pipeline because the fps of the model is much higher than the video and the fps marked. How can I use hardware e.g. nvenc and nvenc to encode and decode the video?
> I have opencv and ffmpeg with cuda. The device is a jetson agx orin

@johnnynunez Don't use OpenCV for video IO, but FFmpeg directly which supports both nvenc and nvenc to encode and decode the video. For this purpose, **You could use my [deffcode](https://github.com/abhiTronix/deffcode) library instead which will be integrated soon in https://github.com/abhiTronix/vidgear/issues/148.** The complete HW transcoding example is given in this docs:  https://abhitronix.github.io/deffcode/latest/recipes/advanced/transcode-hw-acceleration/#hardware-accelerated-video-transcoding

Goodluck!

**Comment by johnnynunez** [comment]
> > I am trying to make a yolo detector using mp4 video or real time camera. I am trying to speed up my pipeline because the fps of the model is much higher than the video and the fps marked. How can I use hardware e.g. nvenc and nvenc to encode and decode the video?
> > I have opencv and ffmpeg with cuda. The device is a jetson agx orin
> 
> @johnnynunez Don't use OpenCV for video IO, but FFmpeg directly which supports both nvenc and nvenc to encode and decode the video. For this purpose, **You could use my [deffcode](https://github.com/abhiTronix/deffcode) library instead which will be integrated soon in #148.** The complete HW transcoding example is given in this docs: https://abhitronix.github.io/deffcode/latest/recipes/advanced/transcode-hw-acceleration/#hardware-accelerated-video-transcoding
> 
> Goodluck!

but Does it have threaded-queue-mode too?? https://abhitronix.github.io/vidgear/v0.3.2-stable/bonus/TQM/#threaded-queue-mode

**Comment by abhiTronix** [comment]
You don't need multi-threading here.

**Comment by johnnynunez** [comment]
> You don't need multi-threading here.

and deffcode uses queue? Or only decoding?

**Comment by abhiTronix** [comment]
> and deffcode uses queue? Or only decoding?

@johnnynunez No queue, just decoding. You could learn more about it here: https://abhitronix.github.io/deffcode/latest/recipes/advanced/decode-hw-acceleration/#hardware-accelerated-video-decoding

**Comment by johnnynunez** [comment]
> > and deffcode uses queue? Or only decoding?
> 
> @johnnynunez No queue, just decoding. You could learn more about it here: https://abhitronix.github.io/deffcode/latest/recipes/advanced/decode-hw-acceleration/#hardware-accelerated-video-decoding

Yeah it is working for me
