### ISSUE TITLE
WriteGear Bare-Minimum example (Non-Compression) not working

### ISSUE THREAD

**Issue by iflyingboots** [abhiTronix/vidgear#40]
## Description
1. I followed the demo here: https://github.com/abhiTronix/vidgear/wiki/Non-Compression-Mode:-OpenCV#1-writegear-bare-minimum-examplenon-compression-mode

2. Run the code

3. The following error showed:
```
Compression Mode is disabled, Activating OpenCV In-built Writer!
InputFrame => Height:360 Width:640 Channels:1
FILE_PATH: /******/Output.mp4, FOURCC = 1196444237, FPS = 30.0, WIDTH = 640, HEIGHT = 360, BACKEND =
OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Warning: RGBA and 16-bit grayscale video frames are not supported by OpenCV yet, switch to `compression_mode` to use them!
Traceback (most recent call last):
  File "cam_demo.py", line 31, in <module>
    writer.write(gray)
  File "/Users/*****/lib/python3.7/site-packages/vidgear/gears/writegear.py", line 221, in write
    raise ValueError('All frames in a video should have same size')
ValueError: All frames in a video should have same size
```

### Acknowledgment

- [x] A brief but descriptive Title of your issue
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).
- [x] I have read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md).

### Environment

* VidGear version: 0.1.5
* Branch:  PyPi
* Python version: 3.7.3
* pip version: 19.1.1
* Operating System and version: macOS 10.14.3

### Expected Behavior

Write frame to file.

### Actual Behavior

Frames in different sizes.

### Possible Fix

WriteGear specify the output frame size?

### Steps to reproduce

(Write your steps here:)

See description.

**Comment by abhiTronix** [comment]
> I followed the demo here: https://github.com/abhiTronix/vidgear/wiki/Non-Compression-Mode:-OpenCV#1-writegear-bare-minimum-examplenon-compression-mode
> 
> Run the code
> 
> The following error showed:
> 
> Compression Mode is disabled, Activating OpenCV In-built Writer!
> InputFrame => Height:360 Width:640 Channels:1
> FILE_PATH: /******/Output.mp4, FOURCC = 1196444237, FPS = 30.0, WIDTH = 640, HEIGHT = 360, BACKEND =
> OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
> OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
> Warning: RGBA and 16-bit grayscale video frames are not supported by OpenCV yet, switch to `compression_mode` to use them!
> Traceback (most recent call last):
>   File "cam_demo.py", line 31, in <module>
>     writer.write(gray)
>   File "/Users/*****/lib/python3.7/site-packages/vidgear/gears/writegear.py", line 221, in write
>     raise ValueError('All frames in a video should have same size')
> ValueError: All frames in a video should have same size

### My Insight 

@iflyingboots  **This error arises because for different size (width/height) or different number of channels(dimensions) of input frames which is either due to incorrect code you are using in your application or the input video stream have incorrect number of channels.**. 
The code you said https://github.com/abhiTronix/vidgear/wiki/Non-Compression-Mode:-OpenCV#1-writegear-bare-minimum-examplenon-compression-mode is working absolutely fine at my machine and [all CLI test are passing](https://travis-ci.org/abhiTronix/vidgear/jobs/564276031#L1997) too without any error whatsoever. 

### Troubleshooting

@iflyingboots  **Kindly post the code of "cam_demo.py" you are using. Secondly if you are using a video file as input source then share the video url here.**

**Comment by abhiTronix** [comment]
**Closed. Kindly provide necessary information related to issue for further troubleshooting.**
