### ISSUE TITLE
[Question]: How to use our project as RTSP Server based on local usb camera？

### ISSUE THREAD

**Issue by wynshiter** [abhiTronix/vidgear#405]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

How to use our project as RTSP Server based on local usb camera？
There is a USB camera on my Windows server, and I want to convert the images it collects into RTSP or other webRTC and publish them. I saw an example of webRTC, but I couldn't find the RTSP example. I hope you can guide me

### VidGear Version

latest

### Python version

3.10

### Operating System version

windows10

**Comment by abhiTronix** [comment]
@wynshiter here it is: https://abhitronix.github.io/vidgear/latest/help/writegear_ex/#using-writegears-compression-mode-for-rtsprtp-live-streaming

**Comment by wynshiter** [comment]
thanks for the guide

```python
# import required libraries
import cv2
from vidgear.gears import CamGear
from vidgear.gears import WriteGear

# open any valid video stream(for e.g `foo.mp4` file)
stream = CamGear(source=0).start()

# define required FFmpeg parameters for your writer
output_params = {"-f": "rtsp", "-rtsp_transport": "tcp"}

# Define writer with defined parameters and RTSP address
# [WARNING] Change your RTSP address `rtsp://localhost:8554/mystream` with yours!

writer = WriteGear(
    output="localhost:8554",logging=True,custom_ffmpeg=r"D:/code/c++/myyolo/streaming/ffmpeg",**output_params
)

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # write frame to writer
    writer.write(frame)

# safely close video stream
stream.stop()

# safely close writer
writer.close()

```
this code may cause bug , when i change output to `rtsp://localhost:8554/mystream`, i think custom_ffmpeg=r"D:/code/c++/myyolo/streaming/ffmpeg" may cause the problem
