### ISSUE TITLE
[Bug]: Stabilization not good on linux environment

### ISSUE THREAD

**Issue by ronfromhp** [abhiTronix/vidgear#416]
### Description

Video gets even more unstable after stabilizing it on linux, while the same stabilized video looks fine on windows

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

i expected the stabilized video coming out like this on linux, which is what it does on windows

https://github.com/user-attachments/assets/8b20bb81-3f66-40d1-9ae6-591fac188940

### Actual behaviour

the actual stabilized video looks like this 

https://github.com/user-attachments/assets/0d60b6e4-04e1-48d8-a246-28484a986c8a

### Steps to reproduce

I used the below python code to process the files

### Python Code(Optional)

```python
from vidgear.gears.stabilizer import Stabilizer
import cv2
import time
import logging

logger = logging.getLogger(__name__)
logger.setLevel(level=3)
stab = Stabilizer(border_size=10, crop_n_zoom=True, logging=True)

def stabilize_video(input_path, output_path):
    start_time = time.time()
    stream = cv2.VideoCapture(input_path)
    
    # Get video properties
    fps = int(stream.get(cv2.CAP_PROP_FPS))
    width = int(stream.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(stream.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))
    
    while True:
        # read frames from stream
        (grabbed, frame) = stream.read()
        
        if not grabbed:
            break
        # send current frame to stabilizer for processing
        stabilized_frame = stab.stabilize(frame)

        # wait for stabilizer which still be initializing
        if stabilized_frame is None:
            continue
        
        out.write(stabilized_frame)

    # clear stabilizer resources
    stab.clean()

    # safely close video stream
    stream.release()
    out.release()
    logger.info(f"Stabilization completed in {time.time() - start_time} seconds.")
    return True
```

### VidGear Version

0.3.3

### Python version

3.11.9

### OpenCV version

opencv-python-headless-4.8.0.74

### Operating System version

wsl Ubuntu-22.04

**Comment by abhiTronix** [comment]
@ronfromhp This is weird. There are platform-specific changes in the Stabilizer API that I know of. I'll test it on my system and let you know. This issue mostly arises from a small error in code you write in a script, so if you could double-check, that would be great.

**Comment by ronfromhp** [comment]
I've double checked it and it shows no error on the logs or in the output, only issue is that the quality of the stabilization is worse on the Ubuntu enviornment

**Comment by abhiTronix** [comment]
@ronfromhp  This error is not reproducible on any Linux distro:
- Tested on Linux Mint
- Tested on Ubuntu (separate machine)
- Tested on Ubuntu 22.04 WSL (as per your environment)
- Tested on Raspberry Pi
All tests worked perfectly. 

Closing this issue as it is not reproducible.

**Comment by abhiTronix** [comment]
Try to use different version of OpenCV it might possible something broken there.

**Comment by ronfromhp** [comment]
Sorry, forgot to update you on this bug for a long time, actually i made a mistake while specifying the platform, the bug only exists on this debian docker image which im using like this

```
# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.11
ARG DEBIAN_VERSION=bullseye

FROM public.ecr.aws/docker/library/python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION} AS base

WORKDIR /code

ARG TARGETPLATFORM
RUN echo "Building for $TARGETPLATFORM"```

within that i install this version of opencv: opencv-python-headless==4.8.0.74
the bug can be recreated with this configuration
