### ISSUE TITLE
[Question]: How to hide logs

### ISSUE THREAD

**Issue by juniorcines** [abhiTronix/vidgear#422]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

Hi, I'm integrating node js + python.

I use python with StreamGear to convert video, so in nodejs how is the logs returned by python being read?

It's difficult for me since StreamGear is giving a lot of logs.

I already have: logging=False

but it still doesn't work.

### VidGear Version

0.3.3

### Python version

3.12.2

### Operating System version

Ubuntu 20

**Comment by abhiTronix** [comment]
@juniorcines What logs? Could you give an example?

**Comment by abhiTronix** [comment]
Closing this for missing information. Feel free to re-open this once you have the all the required evidences. Thanks.
