### ISSUE TITLE
[Bug]: Unable to determine Video-Bitrate for the stream `{'-resolution': '1280x720', '-framerate': '23.976023976023978'}`. Skipped!

### ISSUE THREAD

**Issue by juniorcines** [abhiTronix/vidgear#423]
### Description

Unable to determine Video-Bitrate for the stream `{'-resolution': '1280x720', '-framerate': '23.976023976023978'}`. Skipped!

Hi, I'm getting this error.

For example, if I do it for multiple qualities, if any of them I get the error that it does not add it, and also if I set the video_bitrate it also causes some videos not to convert.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Expected behaviour

?

### Actual behaviour

?

### Steps to reproduce

stream_params = 
    {"-streams": 
        [
        {"-resolution": "1920x1080", "-video_bitrate": "4000k"}, # Stream1: 1920x1080 at 4000kbs bitrate
        {"-resolution": "1280x720", "-framerate": 30}, # Stream2: 1280x720 at 30fps
        {"-resolution": "640x360", "-framerate": 60.0},  # Stream3: 640x360 at 60fps 
        ]
    }

### Python Code(Optional)

```python
stream_params = 
    {"-streams": 
        [
        {"-resolution": "1920x1080", "-video_bitrate": "4000k"}, # Stream1: 1920x1080 at 4000kbs bitrate
        {"-resolution": "1280x720", "-framerate": 30}, # Stream2: 1280x720 at 30fps
        {"-resolution": "640x360", "-framerate": 60.0},  # Stream3: 640x360 at 60fps 
        ]
    }
```

### VidGear Version

0.2.6

### Python version

3.7

### OpenCV version

lastest

### Operating System version

Ubuntu 20

**Comment by juniorcines** [comment]
![image](https://github.com/user-attachments/assets/c2d20e46-240f-46cd-ba38-13493851b901)

When I want to make multi quality, this appears and it avoids creating the 1280x720.

I'm using an mkv and I also tried with an mp4, and the video dimension is 1920, 1080

Also, if I set the video_bitrate manually, it causes problems and does not convert the videos.

**Comment by juniorcines** [comment]
![image](https://github.com/user-attachments/assets/abcf55e5-70ec-465c-883b-cd3405ab0f2f)

Here it would be if I configure the video_bitrate, when it avoids converting to multiple quality by adding 1280x720

**Comment by juniorcines** [comment]
I hope they can fix this problem.

Since it is becoming impossible to create multiple qualities.

My only solution was to create my own quality list, and use single source to convert it to the quality I want and then create the playlist.m3u8

**Comment by abhiTronix** [comment]
> ![image](https://private-user-images.githubusercontent.com/2522721/375576366-c2d20e46-240f-46cd-ba38-13493851b901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTg5ODgsIm5iZiI6MTcyOTM5ODY4OCwicGF0aCI6Ii8yNTIyNzIxLzM3NTU3NjM2Ni1jMmQyMGU0Ni0yNDBmLTQ2Y2QtYmEzOC0xMzQ5Mzg1MWI5MDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMDQzMTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhjZjM2ODVkNDliN2U5YjliZTBiYzFlZmMyMzdhZjYxZGY0MDBjZTFhNmVlMGJmYzBlYjU3OGY4ODY3Mzk2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Hp915WLBQ-1Hr1IqPffE9P-7G4kVV8zxCLvmzCKsZNY)
> 
> When I want to make multi quality, this appears and it avoids creating the 1280x720.
> 
> I'm using an mkv and I also tried with an mp4, and the video dimension is 1920, 1080
> 
> Also, if I set the video_bitrate manually, it causes problems and does not convert the videos.

@juniorcines Here you're just providing just resolution `1280x720` and not the framerate or video bitrate. That's why it didn't worked.

**Comment by abhiTronix** [comment]
> ![image](https://private-user-images.githubusercontent.com/2522721/375576817-abcf55e5-70ec-465c-883b-cd3405ab0f2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjA3NzgsIm5iZiI6MTcyOTQyMDQ3OCwicGF0aCI6Ii8yNTIyNzIxLzM3NTU3NjgxNy1hYmNmNTVlNS03MGVjLTQ2NWMtODgzYi1jZDM0MDVhYjBmMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTAzNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMwZjViM2I1ZjFjNjkwMGJiY2M5MmU1ZDkxOWZlOWFmZjVmYTc0MWRiOTY0Zjc2YzExMDlhZTlhYTJlMjdiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eQa6SgN28SFZNa_NmOzjohAHb-g1R27ua8ZQRwXUUBQ)
> 
> Here it would be if I configure the video_bitrate, when it avoids converting to multiple quality by adding 1280x720

@juniorcines `5000k` is really high, try instead fps such as `"-framerate": 30.0`

**Comment by abhiTronix** [comment]
Closing this for missing information. Please feel free to re-open this if required.
