### ISSUE TITLE
[Question]: How do i directly get the encoded frames???

### ISSUE THREAD

**Issue by Praveenstein** [abhiTronix/vidgear#426]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

I am able to use vidgear, setup to read frames from usb camera, use ffmpeg, and encode to h264 format, i don't want to write it to a mp4 file or something, i just want the encoded frames as they come, to be in my local variable, i will use that to stream directly.

### VidGear Version

0.3.3

### Python version

3.8

### Operating System version

windows

**Comment by abhiTronix** [comment]
I am able to use vidgear, setup to read frames from usb camera, use ffmpeg, and encode to h264 format, i don't want to write it to a mp4 file or something, i just want the encoded frames as they come, to be in my local variable, i will use that to stream directly.

@Praveenstein Just use my another library [**DeFFcode**](https://abhitronix.github.io/deffcode/latest/) that is made for this only. Let me know if you have any other questions!
