### ISSUE TITLE
Multi-camera frame refresh issue

### ISSUE THREAD

**Issue by lrichard52** [abhiTronix/vidgear#43]
## Description

I have four USB cameras connected to an RPI4. The while loop captures a fresh frame from each camera each time it loops. The issue is - 3 of 4 cameras always capture a fresh frame. Sometimes the fourth camera does for a few frames and then it stops. I have no idea what's causing this issue. 

### Acknowledgment

- [x] A brief but descriptive Title of your issue
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).
- [x] I have read the [Contributing Guidelines](https://github.com/abhiTronix/vidgear/blob/master/contributing.md).

### Environment

* VidGear version: 0.14.0
* Branch: 
* Python version: 3.7
* pip version: 0.18.1
* Operating System and version: Raspbian Buster

### Expected Behavior

All four cameras should capture a fresh frame each loop
### Actual Behavior

three of four cameras capture a fresh frame
### Possible Fix

I know a lot of work-arounds, but no idea on a fix
### Steps to reproduce

(Write your steps here:)

You'd likely need an RPI4 and these same ELP USB cameras. The odd thing is sometimes the fourth camera works for the first few frames and then it stops. Also, I've placed markers throughout the loop to make sure the variable for which the frame data is named is cleared each loop - yet somehow the python script is presenting the same image over and over.

**Comment by lrichard52** [comment]
[https://github.com/lrichard52/opencv_python/blob/master/troubleshoot_main_beta_camgear_720all.py](url)

Here's a link to the code - it's a mess, but functions.

**Comment by abhiTronix** [comment]
Hey @lrichard52, **Are you new to python programming?** 

I'm sorry to tell you but there are numerous problems with this code that you just shared, Everything from top to bottom is inappropriately implemented. **You're not even using my VidGear Library in your code(only just importing it) but rather calling various OpenCV functions again and again unnecessarily.** I did'nt know how you managed to make this code even work at your end.

### My Advice
Your code needs to be implemented completely from scratch with proper formatting again to make work properly. But first I will advice you to go through following blogsites throughly and first learn how OpenCV actually works(_with examples_):
- [**PyImageSearch.com**](https://www.pyimagesearch.com/) is the best resource for learning OpenCV and its Python implementation. Adrian Rosebrock provides many practical OpenCV techniques with tutorials, code examples, blogs and books at PyImageSearch.com.  I also learned a LOT about computer vision methods and techniques when I started to Computer Vision. Highly recommended.
- [**learnopencv.com**](https://www.learnopencv.com)  Maintained by OpenCV CEO Satya Mallick. This blog is for programmers, hackers, engineers, scientists, students and self-starters who are interested in Computer Vision and Machine Learning. It is for those creative people who have the itch to learn something new, and build something useful; who love tinkering and getting their hands dirty; who take pride in their work, and are craftsmen at heart; who believe in sharpening their tools and improving their craft every single day!
- There's also the official [**OpenCV Tutorials**](http://docs.opencv.org/doc/tutorials/tutorials.html), provided by the OpenCV folks themselves.

Finally when your done, go through [VidGear's Wiki Documentation](https://github.com/abhiTronix/vidgear/wiki) to see how VidGear works. Goodluck!
