### ISSUE TITLE
[Proposal] Can NetGear Client/Server can send/receive data with custom certificates?

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [abhiTronix/vidgear#46]
## Detailed Description

I think someone in the middle can capture the frame that Server sends to the client without security mechanisms. Can NetGear Client/Server can send/receive data with custom certificates? 

### Context

This proposal is to add Secure the connection between Servers and Client with custom certificates. This gives us strong encryption on data, and (as far as we know) unbreakable authentication. Stonehouse is the minimum you would use over public networks and assures clients that they are speaking to an authentic server while allowing any client to connect. **More information can be found in these links:**
https://github.com/zeromq/pyzmq/blob/master/examples/security/stonehouse.py
https://github.com/zeromq/pyzmq/blob/master/examples/security/generate_certificates.py

### Your Environment

* VidGear version: latest
* Branch: PyPi 
* Python version: all
* pip version: latest
* Operating System and version: not applicable

### Any Other Important Information

Not available

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam Kindly briefly explain the context/use of this feature and why it is necessary? along with your proposal.

**Comment by xamarindevelopervietnam** [comment]
I think some one in the middle can capture the frame that Server send to client without security mechanisms. I'm not python developer so I can't take over the task.

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam _**I'm editing your proposal this time only but next time may be marked as INVALID. Kindly use and fill proper template for your proposal next time.**_ Following a template is compulsory to make it comfortable for others to easily understand the issue/context and so that they can make a contribution to this library easily.

**Comment by xamarindevelopervietnam** [comment]
thanks @abhiTronix

**Comment by xamarindevelopervietnam** [comment]
my suggestion: we give path to Yaml file and Server and Client can read configurations from Yaml file. Yaml file contain path to certificates.

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam  Good Idea! can be implemented. Do you have a source/example of such a YAML file or related information? Also, Are you're suggesting to store encrypted keys/certificates to this file?

**Comment by xamarindevelopervietnam** [comment]
I have an great example here: https://github.com/jeffbass/imagenode. I mean Yaml file contain path to certificates, Netgear can read Yaml file and get the path to keys/cetificates. Did you get my idea?

**Comment by abhiTronix** [comment]
> I have an great example here: https://github.com/jeffbass/imagenode. I mean Yaml file contain path to certificates, Netgear can read Yaml file and get the path to keys/cetificates. Did you get my idea?

We can directly provide a certificate paths to NetGear API through a list/dict, So why using YAML file here?

**Comment by xamarindevelopervietnam** [comment]
eg. We can setup NetGear with out change from the code, we only need to change Yaml file content and restart system without change any line of code.

**Comment by abhiTronix** [comment]
> eg. We can setup NetGear with out change from the code, we only need to change Yaml file content and restart system without change any line of code.

Good point. So we need VidGear's own YAML file to store paths, that can be done. Thanks for this info.

**Comment by xamarindevelopervietnam** [comment]
I think here https://github.com/zeromq/pyzmq/blob/master/examples/security/stonehouse.py
https://github.com/zeromq/pyzmq/blob/master/examples/security/generate_certificates.py @abhiTronix

**Comment by abhiTronix** [comment]
Ohk we have to generate these certificates at runtime. Thank you, I'll inform you when this feature will be added. I'll open a PR for that in upcoming days. Stay tuned.

**Comment by xamarindevelopervietnam** [comment]
We can create cers at runtime or we can create a utility and run it from command line.
On 26 Aug 2019, 9:56 AM +0700, Abhishek Thakur <notifications@github.com>, wrote:

Ohk we have to generate these certificates at runtime. Thank you, I'll inform you when this feature will be added. I'll open a PR for that in upcoming days. Stay tuned.

**Comment by abhiTronix** [comment]
> We can create cers at runtime or we can create a utility and run it from command line.

Creating certificates at runtime is easier to use for everyone, especially for newcomers to python programming.

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam I'm dropping the idea of creating YAML file to store paths in favor of using only a particular vidgear directory (for e.g. `.vidgear`) dedicated to saving auth certificates.

**Comment by abhiTronix** [comment]
@xamarindevelopervietnam Kindly refer to #52 to test the PR.

**Comment by abhiTronix** [comment]
**Successfully Resolved & Merged in commit: https://github.com/abhiTronix/vidgear/commit/6120a29c5f8edbd0e3dfc833ea4567f3fb1ae587**
