### ISSUE TITLE
in multithreading，appear Core dump error

### ISSUE THREAD

**Issue by mujinbao** [abhiTronix/vidgear#49]
I created a thread pool，Write each frame of video in a thread，appear "core dumped" error， please help

**Comment by mujinbao** [comment]
@abhiTronix

**Comment by abhiTronix** [comment]
@mujinbao This is a incomplete issue and missing basic information to understand it properly. **Kindly reformat your issue and provide proper Source-Code and other relevant information related to your issue, Otherwise, This issue will be marked invalid and will be closed**

**Comment by mujinbao** [comment]
@abhiTronix  I'm so sorry，this is my code：

`
# create thread pool
pool = ThreadPoolExecutor(max_workers=1500)
# create video out
output_params = {"-vcodec": "libx264", "-input_framerate": "25", "-crf":28, "-preset":"ultrafast", "-tune":"zerolatency"}
out = WriteGear(output_filename=os.path.join(current_path, 'video', 'video.mp4'),
                    compression_mode=True,
                    **output_params)
camera = cv2.VideoCapture(0)
while camera.isOpened():
    ret, frame = camera.read()
    
    pool.submit(out_frame, frame, out) # the function code is  "out.write(frame) " and other  )

    # do something....
`

In this way, the video is written in multi-threaded, and “Segmentation fault (core dumped) ” appears. 
This is not always the case, and I suddenly found two times, I would like to ask if it is related to ffmpeg or other thread security settings.

**Comment by abhiTronix** [comment]
@mujinbao **Can you explain what it is the necessity of using Thread pool here? What are the performance advantages you're getting from this?** Since, VidGear itself self-optimize the OpenCV & FFmpeg's I/O processes, and there is no need of creating an additional layer of a thread pool, that may result in undesired behaviour as in your case. 

**Reason for the Error:** The VidGear's FFmpeg pipeline relies on `subprocess` python module to communicates with FFmpeg binaries. As speed of writing is dependent on speed of processing time of this Pipeline, therefore You cannot increase speed up the process more than the execution speed of Pipeline itself, thereby as the result see this segmentation fault at the output, as threadpool workers are working too much faster than capacity of FFmpeg Pipeline that can't handle it.

**Instead of using the threaded pool with OpenCV, I'll advice you must try powerful & threaded VidGear API's such as CamGear with WriteGear API. Both work out of the box on any high to lower-end systems. Here's an example to use them:**

```python
# import libraries
from vidgear.gears import CamGear
from vidgear.gears import WriteGear
import cv2

output_params = {"-vcodec":"libx264", "-crf": 0, "-preset": "fast"} #define (Codec,CRF,preset) FFmpeg tweak parameters for writer


stream = CamGear(source=0).start() #Open live webcam video stream on first index(i.e. 0) device

writer = WriteGear(output_filename = 'Output.mp4', compression_mode = True, logging = True, **output_params) #Define writer with output filename 'Output.mp4' 

# infinite loop
while True:
	
	frame = stream.read()
	# read frames

	# check if frame is None
	if frame is None:
		#if True break the infinite loop
		break
	


	# do something with frame here


	# write a modified frame to writer
        writer.write(frame) 
       
        # Show output window
	cv2.imshow("Output Frame", frame)

	key = cv2.waitKey(1) & 0xFF
	# check for 'q' key-press
	if key == ord("q"):
		#if 'q' key-pressed break out
		break

cv2.destroyAllWindows()
# close output window

# safely close video stream
stream.stop()
# safely close writer
writer.close()
```

**Comment by abhiTronix** [comment]
**Closed. Feel free to reopen if you encounter further problems or Kindly provide complete GDB debug backtrace of your crashed program and full error log from your terminal for further investigation.**

**Comment by mujinbao** [comment]
@abhiTronix 
I got GDB information. 


![core_01](https://user-images.githubusercontent.com/42856783/64103521-06451780-cda5-11e9-8e1a-03750642a402.png)
![core_02](https://user-images.githubusercontent.com/42856783/64103531-09400800-cda5-11e9-81a5-767976dc1597.png)

**Allow me to explain this function code:** 
According to the needs of Party A, I need to create four video output objects to save the original image and the image after deep learning recognition, and video formats require both AVI and mp4. 
As the latency requirement was minimized, I had to use thread pool to optimize processing speed.
Therefore, in the "write_video" function, the same image is written twice, and then the image is detected by in-depth learning. The new image after detection is also written twice. This code also happens "core dump".

I don't understand why there was no problem saving only AVI format before，from the GDB information, it seems that the address of this object has changed, and then there is a pointer error.

But segment errors (core dumps) do not occur very often, and they occur only twice or three times a day.

Please help me. Thank you very much.

**Comment by mujinbao** [comment]
#49

**Comment by abhiTronix** [comment]
@mujinbao **Try putting breakpoints after each line, you can also clone this library and put breakpoints and print commands to see at which line or at which input value this error is happening.** It is very hard to debug this error just by seeing as this is happening within threads, so we can't tell what is the actual cause or you can share the entire code for debugging. So my advise is to ***Try your code without using any threading at all, to see the actual error is. There may be a wrong input value or corrupt data which is resulting in this error/crash.***
