### ISSUE TITLE
How to read lenght of file in frame and how to jump to specific frame

### ISSUE THREAD

**Issue by TomasTrnkaPLC** [abhiTronix/vidgear#53]
Hi. 
I want to use vidgear with for webcam and also the file loading.
For webcam or youtube run everything well problem is when I load the video.
My program is based on frame position so I use code like this:

 video_pos =int(cap.get(cv2.CAP_PROP_POS_FRAMES))

but I get error
AttributeError: 'CamGear' object has no attribute 'get' how I can fix it?

Some question is how I can jump to specific frame.

Thanks for the answer

### Acknowledgment

- [x] A brief but descriptive Title of your issue.
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Your Environment

* VidGear version:
* Branch: 
* Python version:
* pip version:
* Operating System and version:

**Comment by TomasTrnkaPLC** [comment]
I want to use vidgear with for webcam and also the file loading.
For webcam or youtube run everything well problem is when I load the video.
My program is based on frame position so I use code like this:

video_pos =int(cap.get(cv2.CAP_PROP_POS_FRAMES))

but I get error
AttributeError: 'CamGear' object has no attribute 'get' how I can fix it?

Some question is how I can jump to specific frame.

Thanks for the answer

**Comment by abhiTronix** [comment]
> My program is based on frame position so I use code like this:
> 
> video_pos =int(cap.get(cv2.CAP_PROP_POS_FRAMES))
> 
> but I get error
> AttributeError: 'CamGear' object has no attribute 'get' how I can fix it?
> 
> Some question is how I can jump to specific frame.


@TomasTrnkaPLC This is not a bug or issue with vidgear, **you can easily access frame position with vidgear as follows:**
```python
from vidgear.gears import CamGear
import cv2

cap =  CamGear(source='test.mp4').start()
video_pos =int(cap.stream.get(cv2.CAP_PROP_POS_FRAMES))
```
**:warning: But it is not advisable nor it is guaranteed that it will work and here are some reasons for this conclusion:**

### Why it is not advisable to use VidGear for jumping/seeking specific frame?
VidGear provides a high-level Threaded wrapper around OpenCV's  API that targets only specific methods and classes related to Video Processing. **It is possible to access other methods too but not advisable with VidGear as it uses _Threads and Queue structure for capturing frame_, which can result in undesired effects with those methods.** Therefore you should refrain yourself from using frame jumping/seeking in VidGear but rather use OpenCV directly for this purpose.

### Why it is not advisable to use Frame Jumping/Seeking  in OpenCV at all?
OpenCV is still in beta stage, with many bugs that remain unsolved. The `VideoCapture::set (CAP_PROP_POS_FRAMES, frameNumber)` method itself is not exact or reliable in OpenCV and can lead to wrong frame seeking at any instance. **You can see this famous issue in OpenCV github repository related to this bug: https://github.com/opencv/opencv/issues/9053 which is still unsolved.**

**Here is the [comment](https://github.com/opencv/opencv/issues/9053#issuecomment-346439490) from [Alexander Alekhin](https://github.com/alalek)(Lead developer at OpenCV):**

> OpenCV highly uses FFmpeg (in case of FFmpeg backend).
> But FFmpeg itself doesn't work well with seeking on non "key" frames. There are many workarounds, but they are not very reliable. Sometimes seeking code works, sometimes doesn't.
> If your have worked FFmpeg's code with accurate seeking, then we could try to integrate it into OpenCV.

**_Hence, Kindly refrain from using Frame Jumping/Seeking with OpenCV at all. Hope this helps good luck._**

**Comment by TomasTrnkaPLC** [comment]
Thanks for the reply.
That is a nice example. I already implement and definitely I move from cv
to your solution. Really soon you get a new "example" how is
implement VidGear in app :)
I have one more question
 when I try run = cap.stream.set(cv2.CAP_PROP_POS_FRAMES,trackbarValue) I
get reply True but stream never jump there. I talking about the jump when
is file loaded.
And one more thing. write.gear run really well. I just use an example and
on Windows 7 64bit is everything ok but, on Windows 10 scripts only create
an empty .mp4 file and never record anything. Why?
I does receive any error everything looks fine the only mp4 is empty.

Thanks

**Comment by abhiTronix** [comment]
> I have one more question
>  when I try run = cap.stream.set(cv2.CAP_PROP_POS_FRAMES,trackbarValue) I
> get reply True but stream never jump there. I talking about the jump when
> is file loaded.

@TomasTrnkaPLC I already told you that **OpenCV is still buggy and cannot reliably seek/jump frame due to a inherit bug. You can see this issue in OpenCV Github repository related to this bug: opencv/opencv#9053 which is still unsolved.** 

> on Windows 10 scripts only create
> an empty .mp4 file and never record anything. Why?

**@TomasTrnkaPLC Wrong, I tested all my VidGear scripts on Windows 10 x64 machine, There must a problem at your end. Kindly paste the terminal log here for further debugging the error which is causing this.**

**Comment by TomasTrnkaPLC** [comment]
Thanks for the reply.
1. Jump to the frame. Yes, you are right but I use the latest version
OpenCV 4 and jump is without the problem.
2. Thanks for the tip I forgot about that.

**Comment by TomasTrnkaPLC** [comment]
1. Jump to Frame
OK, I made some test and now I not sure if I do something wrong.
This is a code
if (trackbar_new  == True):

                cap.stream.set(cv2.CAP_PROP_POS_FRAMES,trackbarValue)

                print('I try to jump')
                video_pos = int(cap.stream.get(cv2.CAP_PROP_POS_FRAMES))
                globals().update(current_video_position = video_pos)


if I do this then nothing happens. Funny is video_pos be updated correctly
but the video continues without any effect.

If I do this so stop-cap before. (I cannot figure out how to only "pause
streaming"). Then I jump to position how I want but video be stoped and
don't want to continue.
if (trackbar_new  == True):
                cap.stop() #TO DO How to pause????
                cap.stream.set(cv2.CAP_PROP_POS_FRAMES,trackbarValue)
                cap.start()
                print('I try to jump')
                video_pos = int(cap.stream.get(cv2.CAP_PROP_POS_FRAMES))
                globals().update(current_video_position = video_pos)

Thanks for your time.
