### ISSUE TITLE
Video didn't write when packaging the program with PyInstaller

### ISSUE THREAD

**Issue by Seraphli** [abhiTronix/vidgear#54]
I use PyInstaller to package my app. I create one file, windowed application. And I use the path function written by myself.
https://github.com/Seraphli/TestField/blob/master/Examples/logging_and_tqdm/util.py#L4-L43
I create a config file in subfolder `config` and that is fine.
I then pass the absolute path to WriteGear and it creates the video file. But after closing the WriteGear, the video file has 0kb size. Seems the video is not written into it.
```
# import libraries
from vidgear.gears import ScreenGear
from vidgear.gears import WriteGear
import cv2
import time

options = {'top': 40, 'left': 0, 'width': 100,
           'height': 100}  # define dimensions of screen w.r.t to given monitor to be captured

output_params = {"-vcodec": "libx264", "-crf": 0,
                 "-preset": "fast"}  # define (Codec,CRF,preset) FFmpeg tweak parameters for writer

stream = ScreenGear(monitor=1,
                    logging=True).start()  # Open Live Screencast on current monitor

writer = WriteGear(output_filename='Output.mp4', compression_mode=True,
                   logging=True,
                   **output_params)  # Define writer with output filename 'Output.mp4'

# infinite loop
while True:

    frame = stream.read()
    # read frames

    # check if frame is None
    if frame is None:
        # if True break the infinite loop
        break

    # {do something with frame here}
    # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # write a modified frame to writer
    writer.write(frame)

    # Show output window
    cv2.imshow("Output Frame", frame)

    key = cv2.waitKey(1) & 0xFF
    # check for 'q' key-press
    if key == ord("q"):
        # if 'q' key-pressed break out
        break

    # delay of about  0.1 seconds
time.sleep(0.1)

cv2.destroyAllWindows()
# close output window

stream.stop()
# safely close video stream
writer.close()
# safely close writer
```
I create a one file app for this small demo.
https://drive.google.com/file/d/1Wgd4bm9bzK079TL73XfEuwGxsZpLcExt/view?usp=sharing

**Comment by abhiTronix** [comment]
Do you have a log or terminal log? and how you are managing the FFmpeg backend? Are you providing FFmpeg prebuilt package with your app?

**Comment by abhiTronix** [comment]
@Seraphli Judging from you app, it is obvious that you are not running WriteGear in compression mode and Hence FFmpeg binaries are not necessary. So coming back to your problem, the empty output error  might be related to OpenCV's CODEC. Kindly try changing your output video extension to `.avi` instead of `.mp4` and revert the results.

**Comment by Seraphli** [comment]
The script is running fine before being packed. So after packed, I have to set the custom ffmpeg path, right? I thought it would find the right place. ffmpeg has been downloaded before, by vidgear.

**Comment by Seraphli** [comment]
It is using ffmpeg because the app is just a packed version of the code I posted.

**Comment by abhiTronix** [comment]
> The script is running fine before being packed. So after packed, I have to set the custom ffmpeg path, right?

@Seraphli That is not a right thing to do as different windows machines may not have common path to the custom FFmpeg binary and will end up in broken application. Using non-compression mode(`compression=False`) i.e OpenCV builtin writer is more suitable in this case.


> I thought it would find the right place. ffmpeg has been downloaded before, by vidgear.

I don't think Pyinstaller environment is letting the vidgear to auto-download/auto-install ffmpeg binaries on host machine as it starts immediately without downloading the appropriate binary. Therefore kindly switch off compression mode and try non-compression mode instead.

> It is using ffmpeg because the app is just a packed version of the code I posted.

Wrong. When writegear fails to download custom FFmpeg binaries on windows, it automatically switch backs to non-compression mode which uses OpenCV's builtin Writer Class instead.

**Comment by Seraphli** [comment]
I find out that the packed version has no problem on Ubuntu, but it has the problem on Windows. It will take some time to trace the problem.

**Comment by abhiTronix** [comment]
> I find out that the packed version has no problem on Ubuntu, but it has the problem on Windows. It will take some time to trace the problem.

@Seraphli That's because Ubuntu provides system wide FFmpeg binaries and therefore vidgear find no problem identifying it. Clearly this problem is related to your configurations not vidgear API itself.

**Comment by abhiTronix** [comment]
Closed. Feel free to reopen if something related to vidgear API doesn't works. Goodluck

**Comment by abhiTronix** [comment]
Closed. Feel free to reopen if something related to vidgear API doesn't works. Goodluck

**Comment by Seraphli** [comment]
I use compression=False when packing the program. But the issue still exists.
So the reason is not what you explained.
I tried to pack the program without ``--windowed``, and there is no bug.

**Comment by abhiTronix** [comment]
> I tried to pack the program without --windowed, and there is no bug.

@Seraphli Nice Find. Thank you for sharing. **Here's some insight for others:**

---
`-w, --windowed, --noconsole` :  _Windows and Mac OS X: do not provide a console window for standard i/o. On Mac OS X this also triggers building an OS X .app bundle. This option is ignored in *NIX systems._

---

**Comment by Seraphli** [comment]
That's not solved. I want to pack an app that doesn't pop up a console when running. So missing `--windowed` will result in a window application coming with a console. That's not the way I want.

**Comment by abhiTronix** [comment]
> That's not solved.

As you stated, it's not vidgear related bug that's why it is marked solved. Otherwise it will be marked invalid.

> I want to pack an app that doesn't pop up a console when running. So missing --windowed will result in a window application coming with a console. That's not the way I want.

Open this issue on Pyinstaller forum, they can guide you properly, as I never used Pyinstaller before. Goodluck.
