### ISSUE TITLE
how to get rtsp frame as tcp(not opencv's defoult udp)

### ISSUE THREAD

**Issue by abcdehc** [abhiTronix/vidgear#56]

**Comment by abhiTronix** [comment]
@abcdehc _This makes no sense at all. Kindly clarify what are you trying to achieve?, What gear this related to?, give related context/description/example-code,  furthermore share a screenshot if available._ **Otherwise, this issue will be marked invalid and thereby closed.**

**Comment by abhiTronix** [comment]
**Closed. Kindly provide necessary information/evidence related to issue for further troubleshooting.**
