### ISSUE TITLE
More Example For CamGear Options

### ISSUE THREAD

**Issue by samoelLuck** [abhiTronix/vidgear#58]
please make more Example For 
Options Like
options = {'THREADED_QUEUE_MODE': False , ......... ....... }

**Comment by abhiTronix** [comment]
@samoelLuck Did you checked [CamGear Wiki Doc](https://github.com/abhiTronix/vidgear/wiki/CamGea)? **The CamGear's Option flag example can be found here: https://github.com/abhiTronix/vidgear/wiki/CamGear#2-camgear-api-with-variable-properties**

**Comment by abhiTronix** [comment]
**Closed. Kindly elaborate your issue for further investigation and follow proper template for filing issue next time.**
