### ISSUE TITLE
How to set framerate with ScreenGear

### ISSUE THREAD

**Issue by FrancescoRossi1987** [abhiTronix/vidgear#59]
## Question
I would like to set the frame rate with which the ScreenGear module acquires the frames from my monitor.
How can I do it?

### Other details:
If I grab a small frame, I will have very slow down video effect (i.e. I record for 10 seconds but the writed video is 1 minute), since it is able to grab many fps and put them with the fixed fps of the WriteGear module (e.g. 25).

On the other hand, If I grab a large frame (e.g. my whole 4k monitor), I will have a very fast video effect (i.e. I record for 30 seconds but the writed video is 5 seconds), since it is able to grab few fps because of the large images.

How can I manage this?

**Comment by abhiTronix** [comment]
@FrancescoRossi1987 I think you need constant framerate on WriteGear side and not at ScreenGear. And you can achieve this easily by setting **[`-input_framerate`](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#2-supported-encoders-and-parameters) parameter of WriteGear API in [compression mode](https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg). Here's the complete example to achieve this: https://github.com/abhiTronix/vidgear/wiki/Compression-Mode:-FFmpeg#3-writegearcompression-mode-control-framerate**

**Comment by abhiTronix** [comment]
**@FrancescoRossi1987 Closing this issue and marked solved. Feel free to reopen if this solution doesn't work for you.**

**Comment by FrancescoRossi1987** [comment]
@abhiTronix Please try this code. 

```
# IMPORT  
from vidgear.gears import ScreenGear
from vidgear.gears import WriteGear
import cv2

# SHOW WINDOW
cv2.namedWindow('Output_Frame',cv2.WINDOW_NORMAL)

# SCREEN
options = {'top': 300, 'left': 300, 'width': 300, 'height': 200} 
stream = ScreenGear(monitor=1, logging=True, **options).start()

# WRITE
output_params = {"-input_framerate":25}
writer = WriteGear(output_filename = 'video_Screen2Write_example.mp4', logging = True, **output_params) 

# MAIN LOOP
while True: 
	
    # read frame from Screen
    frame = stream.read()
    if frame is None:
        break

    # show frame in window
    cv2.imshow("Output_Frame", frame)
    writer.write(frame)

    # if 'q' then EXIT
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break


# CLOSE ALL
cv2.destroyAllWindows()
stream.stop()
writer.close()

```

After running for 30 seconds press "q" to stop. Then go to the saved file video, look at its Properties-> Duration. It will be much more than 30 seconds, with Framerate = 25.
(In fact during the writing process I see the speed>1.0x and the fps>25)

I suppose that  the reason is  that my writer is faster  than 25 fps, so it is able to screen at  higher framerate, generating a longer output video.
