### ISSUE TITLE
How to recover from picamera I/O operation on closed file?

### ISSUE THREAD

**Issue by Jamesits** [abhiTronix/vidgear#61]
## Question

Sometimes when fetching frames from PiGear in an infinite loop, my program would encounter this async exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/vidgear/gears/pigear.py", line 158, in update
    for stream in self.stream:
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/camera.py", line 1889, in capture_continuous
    if not encoder.wait(self.CAPTURE_TIMEOUT):
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 395, in wait
    self.stop()
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 419, in stop
    self._close_output()
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 349, in _close_output
    mo.close_stream(output, opened)
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/mmalobj.py", line 428, in close_stream
    stream.flush()
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/array.py", line 237, in flush
    super(PiRGBArray, self).flush()
ValueError: I/O operation on closed file.
```

If it happens, there seems no obvious way for the caller program to know about it, and there is no instruction on how to recover from this exception. Is there any way to detect or recover from this situation?

### Acknowledgment

- [x] A brief but descriptive Title of your issue.
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Your Environment

* VidGear version: 0.1.5
* Branch: PyPi
* Python version: 3.7.3
* pip version: 18.1 
* Operating System and version: Raspbian Buster

**Comment by abhiTronix** [comment]
@Jamesits Is your camera connected properly?, and Did you encounter any pattern when this error occurs or what causes this error?

### Bug Insights

> ValueError: I/O operation on closed file.

Means PiCamera API shuts down/freezes Camera Module pipeline prematurely due to an unknown Internal error while PiGear API doesn't know if it does. So when PiGear API tries to grab another frame from pipeline this error shows up. This is a bug within the [Picamera library](https://github.com/waveform80/picamera) which PiGear API provides a wrapper for.

### Possible Cause:
I think this freezing problem is with the latest Kernel as you're using with Raspbian Buster as seen this [Issue](https://github.com/waveform80/picamera/issues/574). Do you have any old Raspbian Stretch OS memory card laying around or can you downgrade to Raspbian Stretch to see if this bug still persists with the old kernel/OS? If this Bug is related to kernel then we have to raise this issue on PiCamera repo to get a fix for the new kernel as soon as possible.

**Comment by Jamesits** [comment]
Thanks for your quick reply. I mainly observed it when other parts of the program used up all the virtual memory space. (Raspbian is a 32-bit distribution; Raspberry Pi 4 has a 4GiB memory option, so it is very easy to achieve this.) I admit this is an edge case; still I'd appreciate it if there is an easy way for PiGear to raise the exception to the caller function.

**Comment by Jamesits** [comment]
In my use case, it is easy for me to tell the part of the program utilizing too much memory (a circular recording buffer) to back off, so if I can catch this exception I can either try to restart everything in-process or simply quit and let the supervisor respawn the process. I agree it is generally better to just close the process. Either way, it is better than having a zombie loop running without knowing the camera has already dead.

**Comment by abhiTronix** [comment]
@Jamesits **Kindly install the #62 PR as follows:**
```sh
git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout development
sudo pip3 install .
cd
```
**and test if it works as you expected or not? and then revert here. Good luck!**

**Comment by Jamesits** [comment]
My test camera module is currently not at my side. Please allow some time.

**Comment by abhiTronix** [comment]
@Jamesits Sure no problem, take your time.

**Comment by abhiTronix** [comment]
**@Jamesits I'm merging the PR now, Kindly share your results when you're ready. Goodluck!**

**Comment by Jamesits** [comment]
Sorry for the delay, my testing module had some time en route.

The updated code now throws another exception:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/vidgear/gears/pigear.py", line 167, in update
    stream = next(self.stream)
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/camera.py", line 1889, in capture_continuous
    if not encoder.wait(self.CAPTURE_TIMEOUT):
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 395, in wait
    self.stop()
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 419, in stop
    self._close_output()
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 349, in _close_output
    mo.close_stream(output, opened)
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/mmalobj.py", line 428, in close_stream
    stream.flush()
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/array.py", line 237, in flush
    super(PiRGBArray, self).flush()
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/vidgear/gears/pigear.py", line 172, in update
    raise RuntimeError('[ERROR]: Camera Module API failure occured!')
RuntimeError: [ERROR]: Camera Module API failure occured!
```

But it is still not possible for the caller procedure to get this exception since it is happening in another thread. There seems to be no straightforward way to raise an exception in a thread and catch it in another thread in Python. (See: https://stackoverflow.com/questions/2829329/catch-a-threads-exception-in-the-caller-thread-in-python ) So I think the better way is to implement some sort of signaling (see the StackOverflow link) to pass the exception into the main thread and re-raise it when the caller calls `stream.read()`. 

Another finding during my test: if you pull out the camera module's cable, PiCamera module will not generate any exceptions; instead it will return an all-black frame. So maybe eating up all the memory is the only way to trigger this.

Here is a small program to reproduce this problem: (only tested on RPi4 4GB version; on low memory models you might need to set a lower `memory_eating_arg` (like `10**4`). 

```python
#!/usr/bin/env python3
from vidgear.gears import PiGear
import psutil
import os
import sys

stream_options = {"hflip": True, "exposure_mode": "auto", "iso": 800, "exposure_compensation": 15, "awb_mode": "horizon", "sensor_mode": 0} # define tweak parameters
framerate = 15
record_w = 720
record_h = 416

def main():
    counter = 0
    memory_eater = []
    memory_eating_arg = 10**5 # make this smaller if you cannot trigger the camera module exception
    stream = PiGear(resolution=(record_w, record_h), framerate=framerate, time_delay=2, logging = True, **stream_options).start()

    while True:
        try:
            frame = stream.read()
            # check if frame is None
            if frame is None:
                # if True skip this
                print("Got null frame")
                continue

            # eat some memory
            memory_eater.append(' ' * memory_eating_arg)

            counter += 1
            if counter % 100 == 0:
                print(f"CPU: {psutil.cpu_percent()}% MEM: {psutil.virtual_memory()[2]}% WORKING_SET: {psutil.Process(os.getpid()).memory_info()[0]/1073741824}GiB")

        except MemoryError:
            print("Main thread OOM")
            memory_eating_arg = int(memory_eating_arg / 10)
            if memory_eating_arg < 100:
                sys.exit(0)

main()
```

**Comment by abhiTronix** [comment]
> But it is still not possible for the caller procedure to get this exception since it is happening in another thread.

Hello @Jamesits, **Good point. After going through the helpful link you provided, I think we can implement this workaround.** Unfortunately, the previous PR is already been merged and therefore I'm going to implement this in upcoming PR in next few days. Till then please stay tuned and test it asap when ready, so that I can made necessary tweaks as required.

> PiCamera module will not generate any exceptions; instead it will return an all-black frame. So maybe eating up all the memory is the only way to trigger this.

@Jamesits **I thinking of a simple filter(_i knew quite a few_) that checks if a certain number of frames are black, then raise an exception and exit out to save memory, We can ask user to set that threshold. What's your thought about it?**

**Comment by abhiTronix** [comment]
Hey @Jamesits, Thanks for your patience, Kindly reinstall the updated PR as follows:

```sh
git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout development
sudo pip3 install .
cd
```

and **test ASAP if it works as you expected or not?** and then revert here. Good luck!

**Comment by abhiTronix** [comment]
@Jamesits **I'm hoping you to test this PR as soon as possible as it will be going to be merge by tomorrow.**

**Comment by Jamesits** [comment]
Sorry for being late, I'm experiencing multiple device failures at my homelab. The current development version looks good to me. It now correctly forwards the exception to the caller thread. 

Thank you for the quick response!

```
CPU: 25.6% MEM: 81.7% WORKING_SET: 2.7753067016601562GiB
Traceback (most recent call last):
  File "test_oom.py", line 41, in <module>
    main()
  File "test_oom.py", line 21, in main
    frame = stream.read()
  File "/usr/local/lib/python3.7/dist-packages/vidgear/gears/pigear.py", line 283, in read
    raise RuntimeError(error_msg).with_traceback(self.exceptions[2])
  File "/usr/local/lib/python3.7/dist-packages/vidgear/gears/pigear.py", line 216, in update
    stream = next(self.stream)
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/camera.py", line 1889, in capture_continuous
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 395, in wait
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 419, in stop
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/encoders.py", line 349, in _close_output
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/mmalobj.py", line 428, in close_stream
  File "/usr/local/lib/python3.7/dist-packages/picamera-1.13-py3.7.egg/picamera/array.py", line 237, in flush
RuntimeError: [ERROR]: Camera Module API failure occured: I/O operation on closed file.
```

**Comment by abhiTronix** [comment]
Thanks for the valuable input. **But I'm curious that did you tried pulling cable out when running?**

**Comment by abhiTronix** [comment]
@Jamesits Thanks for the valuable input. **But I'm curious that did you tried pulling Camera cable out when running your script?**

**Comment by Jamesits** [comment]
Ah, forgot that. When I pull the cable out, it is giving the following exception:

```
[WARNING]: Camera Module Disconnected!
Traceback (most recent call last):
  File "/home/pi/.local/bin/videotwister", line 11, in <module>
    load_entry_point('videotwister==1.0.0', 'console_scripts', 'videotwister')()
  File "/home/pi/.local/lib/python3.7/site-packages/videotwister-1.0.0-py3.7.egg/videotwister/pygear_main.py", line 49, in main
  File "/usr/local/lib/python3.7/dist-packages/vidgear-0.1.6.dev0-py3.7.egg/vidgear/gears/pigear.py", line 277, in read
SystemError: [ERROR]: Hardware failure occurred, Kindly reconnect Camera Module and restart your Pi!
```

This looks good.

**Comment by abhiTronix** [comment]
@Jamesits Thanks for the quick response, this is a great addition to vidgear. I'll merge it by tomorrow. Hope this helped you.

**Comment by Jamesits** [comment]
Much thanks to you!

BTW, you don't really need to restart the Pi to recover from a cable disconnection; simply connect it back and restart capturing will just work.

**Comment by abhiTronix** [comment]
> BTW, you don't really need to restart the Pi to recover from a cable disconnection; simply connect it back and restart capturing will just work.

Yes, (Just) to be on safer side ;)

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit: https://github.com/abhiTronix/vidgear/commit/0ea05238aeb32a582bb25c02651415fc82cb4ea7**
