### ISSUE TITLE
The output video is slower than the input

### ISSUE THREAD

**Issue by serbanc94** [abhiTronix/vidgear#68]
Hi,

I don't know if I'm the only one experiencing this, but the output video after framewise processing using OpenCV is slower than the input video.

Basically the workflow is this:

1. Read frame from stream;
2. Apply OpenCV functions over it
3. Write the frame back using Writer.

In my case, an one minute video(4K 60FPS) ends up having 2 minutes and a half.

**Comment by abhiTronix** [comment]
@serbanc94 Slow processing can depend upon a lot factors but it doesn't effect length of video.
 Kindly share the following information:

* vidgear version you're using and the Gears/APIs your're dealing with(for e.g CamGear/WriteGear etc.) in your code.
* Python code you're using and the respective log (set `logging = True`) from terminal. 
* what's the framerate of final 2min video, also share the video itself along with input video if possible.

**_Also, kindly fill the issue template properly before opening an issue._**

**Comment by abhiTronix** [comment]
**Closed. Kindly provide necessary information/evidence related to issue for further troubleshooting.**
