### ISSUE TITLE
Set VideoGear's decoder.

### ISSUE THREAD

**Issue by serbanc94** [abhiTronix/vidgear#69]
Is there any way to set the video decoder for the VideoGear class? I've been looking through docs but not so many details found. 
I would like to use the GPU in order to decode the video, in order to speed up the process a little.

**Comment by abhiTronix** [comment]
> I would like to use the GPU in order to decode the video, in order to speed up the process a little.

**OpenCV don't support GPU decoding in python yet and therefore there's no way of doing this in vidgear.** OpenCV does supports Nvidia GPUs for speeding up DNN's computation modules which can used if you compile OpenCV with CUDA support, follow [this article](https://www.pyimagesearch.com/2016/07/11/compiling-opencv-with-cuda-support/) for more information.

_But wait there's a Hack, `export OPENCV_FFMPEG_CAPTURE_OPTIONS="video_codec|h264_cuvid"` environment variable which works for some people but decrease performance for others and more information can be found in this issue: https://github.com/opencv/opencv/issues/11220_
