### ISSUE TITLE
How do i use Vidgear for stabilizing series of images?

### ISSUE THREAD

**Issue by rithvikrthampy** [abhiTronix/vidgear#74]
### Acknowledgment

- [ ] A brief but descriptive Title of your issue.
- [ ] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [ ] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [ ] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Your Environment

* VidGear version:
* Branch: 
* Python version:
* pip version:
* Operating System and version:

**Comment by abhiTronix** [comment]
It's easy, just Convert those images to video using WriteGear API(in compression mode) and then use VideoGear API to stablize that video.

**_Also, remember to fill the template properly before raising an issue here next time. See [wiki](https://github.com/abhiTronix/vidgear/wiki/reporting-issue#reporting-an-issue) for more info._**

**Comment by rithvikrthampy** [comment]
each frames are taken in real time. i need to process each frame after stabilization so if i process the frames after converting it to a video there will be a huge delay

**Comment by abhiTronix** [comment]
@rithvikrthampy Did you saw [
Real-time Video Stabilization Wiki](https://github.com/abhiTronix/vidgear/wiki/Real-time-Video-Stabilization#real-time-video-stabilization)? You can use https://github.com/abhiTronix/vidgear/wiki/Real-time-Video-Stabilization#2-using-stabilizer-class-directly-with-opencv example code for achieving realtime stabilization on webcam.
