### ISSUE TITLE
Vapoursynth script support

### ISSUE THREAD

**Issue by mratsim** [abhiTronix/vidgear#86]
Avisynth and Vapoursynth are frameservers with a plugin system that allows very flexible per-frame manipulation of videos for various purposes:

See: http://avisynth.nl/index.php/External_filters
- 3 Restoration Filters
  - 3.1 Anti-aliasing
  - 3.2 Chroma correction
  - 3.3 Debanding
  - 3.4 Deblocking
  - 3.5 Dehaloing
  - 3.6 Deringing & Mosquito Noise
  - 3.7 Deinterlacing
  - 3.8 Duplicate Frame Detectors
  - 3.9 Fieldblending and Frameblending removal
  - 3.10 Film Damage correction
  - 3.11 Frequency Interference removal
  - 3.12 IVTC & Decimation
  - 3.13 Ghost Removal
  - 3.14 Logo Removal
  - 3.15 Luma Equalization
  - 3.16 Rainbow & Dot Crawl Removal
  - 3.17 Stabilization

- 4 Denoisers
  - 4.1 Spatial Denoisers
  - 4.2 Temporal Denoisers
  - 4.3 Spatio-Temporal Denoisers

- 5 Adjustment Filters
  - 5.1 Averaging/Layering/Masking
  - 5.2 Blurring
  - 5.3 Borders and Cropping
  - 5.4 Colourspace Conversion
  - 5.5 Effects
  - 5.6 Field Order
  - 5.7 Frame Rate Conversion
  - 5.8 Frame Replacement/Range Processing
  - 5.9 Levels and Chroma
  - 5.10 Line Darkening
  - 5.11 Resizers
  - 5.12 Sharpeners
  - 5.13 Rotation/Shear/Skew/Perspective
  - 5.14 Subtitling
  - 5.15 Transitions

- 6 Other Filters
  -  6.1 Debugging/Diagnostic Filters
  -  6.2 Edge Detection
  -  6.3 Export Filters
  -  6.4 Import Filters
  -  6.5 Meta-Filters
  -  6.6 Multipurpose Filters
  -  6.7 Scene Change Detection
  -  6.8 Support filters
  -  6.9 Deepcolor Filters
  -  6.10 3D Filters
  -  6.11 Libraries

Those filters can then be combined in an user script for specific purposes (improving compressibility, dealing with Inverse Telecine or interlacing, deshaking, denoising, supersampling, improving videos from old cameras or VHS, removing the "edge enhancement" that is common place in some DVDs).

Avisynth is Windows-only and development has stalled but Vapoursynth its spiritual successor (and a pun about Avisynth being vaporware) is written in Python and most of the community has ported important Avisynth plugins to it: https://github.com/vapoursynth/vapoursynth.

Example wrappers in other languages: 
- C++: https://github.com/sekrit-twc/vsxx,
- Rust: https://github.com/YaLTeR/vapoursynth-rs

Note that mencoder and x264 both can be build with avisynth/vapoursynth input support.

For example a non-trivial Vapoursynth script to deal with the following compression artifacts:
- Ringing
- Staircase noise
- Blockiness

https://github.com/IFeelBloated/Oyster

Community forum for both: http://forum.doom9.org/forumdisplay.php?s=1862ef90a6538ce2f8e5e3fb4e8e7ba1&f=67

Supporting Vapoursynth as a backend would bring VidGear a lot of additional video processing capabilities that are unmatched by just OpenCV and FFMpeg. Furthermore all the in-depth knowledge that has been accumulated in the past 20 years in the video encoding community could be reused in VidGear.

**Comment by abhiTronix** [comment]
> Avisynth and Vapoursynth are frameservers with a plugin system that allows very flexible per-frame manipulation of videos for various purposes:
See: http://avisynth.nl/index.php/External_filters
Those filters can then be combined in an user script for specific purposes (improving compressibility, dealing with Inverse Telecine or interlacing, deshaking, denoising, supersampling, improving videos from old cameras or VHS, removing the "edge enhancement" that is common place in some DVDs).

**@mratsim Wow, this is huge. Thanks for the Nicely elaborated & detailed insight.**


> For example a non-trivial Vapoursynth script to deal with the following compression artifacts:
    Ringing
    Staircase noise
    Blockiness
https://github.com/IFeelBloated/Oyster

**I mean wow, those results are awesome in the given repository link. _But, Does these processes will also work for memory-constrained devices? Also, are we able to put out real-time performance with vapoursynth library?_**

> Example wrappers in other languages:
> C++: https://github.com/sekrit-twc/vsxx,
> Rust: https://github.com/YaLTeR/vapoursynth-rs
> Community forum for both: http://forum.doom9.org/forumdisplay.php?s=1862ef90a6538ce2f8e5e3fb4e8e7ba1&f=67

**Awesome, this will be helpful. _But, Is there's any python wrapper already implemented somewhere else? tho any additional related python reference/examples would be amazing if possible._**

> Avisynth is Windows-only and development has stalled but Vapoursynth its spiritual successor (and a pun about Avisynth being vaporware) is written in Python and most of the community has ported important Avisynth plugins to it: https://github.com/vapoursynth/vapoursynth. 
> Supporting Vapoursynth as a backend would bring VidGear a lot of additional video processing capabilities that are unmatched by just OpenCV and FFMpeg.

**Thanks for sharing this info. An initial glance into Vapoursynth library documentation, I think implementing it as a backend for vidgear is definitely possible, but with numerous challenges ahead. For now, I'm adding this feature to the next milestone and already have started working on it. Luckily, If everything went easy, I'll post an update or roll out PR related to this enhancement in upcoming days. Kindly stay tuned.**

**Comment by mratsim** [comment]
Vapoursynth is Python ;), AFAIK everything needed is here: https://github.com/vapoursynth/vapoursynth/tree/master/src/cython

**Comment by abhiTronix** [comment]
> Vapoursynth is Python

@mratsim yeah i knew that. The primary reason i asked for a existing python API wrapper was to see how to handle vapoursynth installation of mutliple OSes through python directly. Because looking through its [documentation](http://vapoursynth.com/doc/installation.html#installation-via-pip-pypi), the pypi installation seems to install python API only which is useless without main library. Also, what we can see from issue section of this library is that many people are having trouble building this library on their machines. Btw, Do we have any static builds available for vapoursynth library?

> In terms of performance, it depends on the plugins, those with GPU backend like https://github.com/pinterf/FFT3dGPU are really fast. Those implemented in C or Assembly depend on the implementation and the heaviness of the computation, and those implemented in Python are slow for obvious reasons ;).For example FFT3d (https://github.com/Klimax/FFT3DFilter/blob/master/FFT3DFilter.cpp) was notoriously slow back in 2004 when it was released but since then fftw had numerous SIMD (including ARM Neon) and multithreading improvement and now processors have decent L1 and L2 cache which makes it much easier for software to use optimize for.

Thanks for this valuable information. I'll add it to the wiki docs later when this enhancement is merged.

**Comment by mratsim** [comment]
Unfortunately I use Linux (and Arch) as my main machine to have sane shared library management, so I never explored that options.

A quick Google search brought me to: https://github.com/DeadSix27/python_cross_compile_script/issues/61 and https://forum.doom9.org/showthread.php?s=34450361102aeecbca2d2d545978f7ba&p=1840806#post1840806 and looking into the repo there is a static build commit: https://github.com/vapoursynth/vapoursynth/commit/519b61dba35a5c83cb1dba89d7ec2f2eef41e398

**Comment by abhiTronix** [comment]
> A quick Google search brought me to: DeadSix27/python_cross_compile_script#61 and https://forum.doom9.org/showthread.php?s=34450361102aeecbca2d2d545978f7ba&p=1840806#post1840806 and looking into the repo there is a static build commit: vapoursynth/vapoursynth@519b61d

Thanks. I'm thinking of building pre-compiled binaries for each platform and then auto-set them up inside vidgear, as a newbie won't be able to compile it properly.

**Comment by abhiTronix** [comment]
@mratsim the  [vapoursyth's SIL Open Font License 1.1 license](https://github.com/vapoursynth/vapoursynth/blob/master/ofl.txt) that emphasis `"Same license "` condition and [other restrictions](http://scripts.sil.org/cms/scripts/page.php?id=ofl-faq_web&site_id=nrsi#eefa6a5e), and [non-maintained VapourSynth packages for Linux environments](https://github.com/vapoursynth/vapoursynth/issues/455), plus slow development in recent year are some major roadblocks for adopting this library for vidgear. On top of everything, a very simple task of installing this library is too tedious, buggy and thereby non-ideal with easy-to-use vidgear library, where our goal is to simplify things. In contrast, there are many examples such as ZMQ and FFmpeg itself, that provide easy, straightforward installation of their binaries on every platform.  I think we should wait for the vapoursyth project to mature further and finally fix these problems, and then we can plan of adding this feature into vidgear.

**Comment by mratsim** [comment]
I understand the packaging reasons.

Regarding SIL I think there is a misunderstanding though, the SIL Open Font license is a font license, not a code license and it only applies to the terminus font that is shipped here: https://github.com/vapoursynth/vapoursynth/blob/9e193706ca13a2f7efbb0c612e148628f2c86601/src/core/ter-116n.h
Terminus is also a quite popular font that is available as a package in many distros.
SIL is a big as Apache or GPL in the open-source font world.

**Comment by abhiTronix** [comment]
> the SIL Open Font license is a font license, not a code license and it only applies to the terminus font

@mratsim Is source-code license something else? Is it due to Terminus font, they have to adopt this license as a whole? If that's the case then they should have gone with **Dual licensing**. Tho' the real turn off point was there's no true effort being made by project devs in providing easy access to these binaries to the users. No doubt vapoursyth is awesome at what it does, but right now if you need this library, you've to compile everything from scratch yourself that's not ideal for most of the people. Moreover, the issue count is really huge on that library and every next issue is related to failing to compile it properly.
