### ISSUE TITLE
[Proposal]  Starlette Real-time video streaming with vidgear

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#87]
### [Starlette](https://github.com/encode/starlette) 
Starlette is a lightweight ASGI framework/toolkit, which is ideal for building high-performance asyncio services. It is very simple and intuitive. It's designed to be easily extensible and has modular components. Starlette is currently the fastest Python framework tested. Only surpassed by Uvicorn, which is not a framework, but a server.

### Context

For a long time, vidgear lacks the ability to stream video to web browsers. Our goal through this proposal is to test whether it is possible to stream video frames over Starlette in real-time and if possible, then implement this feature with vidgear multithreaded API.

### Your Environment

* VidGear version: 0.1.7
* Branch:  Testing
* Python version: 3.0+
* pip version: all
* Operating System and version: all

### Any Other Important Information

https://www.starlette.io/

**Comment by akx** [comment]
For a streaming application like this, you may want to consider an async framework like [Starlette](https://www.starlette.io/) instead of Flask.

**Comment by abhiTronix** [comment]
> Performance
> Independent TechEmpower benchmarks show Starlette applications running under Uvicorn as one of the fastest Python frameworks available. (*)

@akx Thanks a lot for suggesting this awesome library. Realtime Performance is what I'm looking forward to for this proposal and I think Starlette has great potential to do so. Tho' I will test both Flask and Starlette and benchmark them myself on my machines. New Ideas like this are very helpful in the development of vidgear, So keep them coming!

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/d57f01eeb879b1a1783f8842d8099322b3c9f168**
