### ISSUE TITLE
Is Writegear support multi thread mode?

### ISSUE THREAD

**Issue by km23630** [abhiTronix/vidgear#96]
### Acknowledgment

- [x] A brief but descriptive Title of your issue.
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Context

I want improve my video write speed.
Is Writegear support multi thread mode?
please let me know. thanks!

**Comment by abhiTronix** [comment]
> I want improve my video write speed.

You cannot speed up writing as it depends upon your physical hardware speed on with your python script is running. However, You can optimize the performance by [compiling FFmpeg with GPU support](https://stackoverflow.com/a/44518572/10158117) and using that in WriteGear.

>  Is Writegear support multi thread mode?

Nope, As it is not desirable as we cannot speed up writing beyond the physical limits of your system as it will result in side-effect like [race-condition](https://searchstorage.techtarget.com/definition/race-condition).
