### ISSUE TITLE
In my case WriteGear is slower than cv2.videowriter.

### ISSUE THREAD

**Issue by km23630** [abhiTronix/vidgear#97]
## Question
I'm trying to use WriteGear to speed up frame writes.
but In my case WriteGear is slower than cv2.videowriter.
WriteGear is 1.5 times slower than cv.videowrite.
Why is this happening?

### Acknowledgment

- [x] A brief but descriptive Title of your issue.
- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [x] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Your Environment

* VidGear version: 0.1.6-dev
* Branch: 
* Python version: 3.6.9
* pip version: 
* Operating System and version: ubuntu 18.04

### Optional

my benchmarks

```
Timer unit: 1e-06 s

cv2
Line #      Hits         Time  Per Hit   % Time  Line Contents
    132       303    3012795.0   9943.2      6.1                  out.write(out_image)

write gear
Line #      Hits         Time  Per Hit   % Time  Line Contents
    140       303    4668383.0  15407.2      8.4                  out.write(out_image)
```

**Comment by abhiTronix** [comment]
@km23630 kindly refrain from opening multiple issues of same kind and instead make your comment under previous one.

> WriteGear is 1.5 times slower than cv.videowrite.
>my benchmarks
>Timer unit: 1e-06 s
cv2
Line #      Hits         Time  Per Hit   % Time  Line Contents
    132       303    3012795.0   9943.2      6.1                  out.write(out_image)
write gear
Line #      Hits         Time  Per Hit   % Time  Line Contents
    140       303    4668383.0  15407.2      8.4                  out.write(out_image) 

What mode are you using in WriteGear? Kindly share your complete benchmark source code here.

**Comment by km23630** [comment]
it was my code problem.
Sorry for wasting your time.
thaks :)
